#pragma once

#include <cstddef>

namespace ghostrigger::phase15::ghostrigger_diagnostics {

using PythonFunctionDescriptorJson = const char* (*)();

struct PythonFunctionDescriptorEntry {
    const char* python_file;
    const char* qualname;
    const char* function_type;
    PythonFunctionDescriptorJson descriptor_json;
};

const char* src_core_diagnostics_diagnostics_set_sentinel_dir_line_44_8ae827ec_descriptor_json();
const char* src_core_diagnostics_diagnostics_log_mdl_header_line_55_555985b6_descriptor_json();
const char* src_core_diagnostics_diagnostics_validate_mdl_preconditions_line_141_b19c0b38_descriptor_json();
const char* src_core_diagnostics_diagnostics_load_timer_line_184_838b14f5_descriptor_json();
const char* src_core_diagnostics_diagnostics_log_model_summary_line_210_51f13b57_descriptor_json();
const char* src_core_diagnostics_diagnostics_log_model_anomalies_line_260_d81498cb_descriptor_json();
const char* src_core_diagnostics_diagnostics_log_render_error_line_355_8784dfa8_descriptor_json();
const char* src_core_diagnostics_diagnostics_check_main_thread_line_390_c935d866_descriptor_json();
const char* src_core_diagnostics_diagnostics_log_thread_violation_line_406_d1d6f04c_descriptor_json();
const char* src_core_diagnostics_diagnostics_log_texture_resolution_line_424_15424580_descriptor_json();
const char* src_core_diagnostics_diagnostics_log_crash_report_line_456_4d715750_descriptor_json();
const char* src_core_diagnostics_diagnostics_write_crash_sentinel_line_517_62a85bcd_descriptor_json();
const char* src_core_diagnostics_diagnostics_run_model_diagnostics_line_545_133f9b6e_descriptor_json();
const char* src_core_diagnostics_diagnostics_log_session_start_line_678_715dbbf7_descriptor_json();
const char* src_core_diagnostics_diagnostics_report_old_sentinels_line_717_8dd23cec_descriptor_json();
const char* src_core_diagnostics_module_reference_safety_module_from_input_line_119_8faf9ef8_descriptor_json();
const char* src_core_diagnostics_module_reference_safety_normalise_resref_line_123_5bfdaeb7_descriptor_json();
const char* src_core_diagnostics_module_reference_safety_normalise_restype_line_132_5c829799_descriptor_json();
const char* src_core_diagnostics_module_reference_safety_record_key_line_136_d01ddfdd_descriptor_json();
const char* src_core_diagnostics_module_reference_safety_resources_from_input_line_149_50bc7de0_descriptor_json();
const char* src_core_diagnostics_module_reference_safety_available_index_line_162_9dfee9c1_descriptor_json();
const char* src_core_diagnostics_module_reference_safety_git_raw_line_196_a688d5a0_descriptor_json();
const char* src_core_diagnostics_module_reference_safety_core_raw_line_203_6ab0a473_descriptor_json();
const char* src_core_diagnostics_module_reference_safety_raw_list_line_213_a7111a0b_descriptor_json();
const char* src_core_diagnostics_module_reference_safety_script_field_line_221_fa440c9a_descriptor_json();
const char* src_core_diagnostics_module_reference_safety_dialog_field_line_226_58535f64_descriptor_json();
const char* src_core_diagnostics_module_reference_safety_iter_script_dialog_refs_line_230_de4ac179_descriptor_json();
const char* src_core_diagnostics_module_reference_safety_collect_module_references_line_260_b7f6bfe1_descriptor_json();
const char* src_core_diagnostics_module_reference_safety_has_reference_line_291_462c6d98_descriptor_json();
const char* src_core_diagnostics_module_reference_safety_issue_for_missing_line_309_e4fe892b_descriptor_json();
const char* src_core_diagnostics_module_reference_safety_validate_module_references_line_344_44437eb2_descriptor_json();
const char* src_core_diagnostics_validation_service_validate_scene_line_462_4978dd75_descriptor_json();

const PythonFunctionDescriptorEntry* modulefunctions_descriptors(std::size_t& count);

} // namespace ghostrigger::phase15::ghostrigger_diagnostics
