#pragma once

#include <cstddef>

namespace ghostrigger::graphics::renderer::shared::contracts {

#ifndef GHOSTRIGGER_RENDERER_CONTRACTS_NATIVE_FUNCTION_IMPLEMENTATION_DEFINED
#define GHOSTRIGGER_RENDERER_CONTRACTS_NATIVE_FUNCTION_IMPLEMENTATION_DEFINED
struct NativeFunctionImplementation {
    const char* project;
    const char* native_namespace;
    const char* python_file;
    const char* qualname;
    const char* callable_type;
    const char* implementation_status;
    bool native_first;
    bool python_runtime_required;
    bool python_fallback_allowed;
    const char* contract_json;
};
#endif // GHOSTRIGGER_RENDERER_CONTRACTS_NATIVE_FUNCTION_IMPLEMENTATION_DEFINED

const NativeFunctionImplementation& vbo_builder_line_20_92b405a6_native();
const NativeFunctionImplementation& iter_mesh_render_data_line_28_ef5528d1_native();
const NativeFunctionImplementation& extract_node_arrays_line_33_a10d76a2_native();
const NativeFunctionImplementation& getattr_line_38_e5b7d284_native();
const NativeFunctionImplementation& dir_line_46_405f5132_native();
const NativeFunctionImplementation& renderer_for_backend_line_26_97b0c440_native();
const NativeFunctionImplementation& dedupe_line_39_889a5836_native();
const NativeFunctionImplementation& render_kwargs_for_line_47_c3c86eb3_native();
const NativeFunctionImplementation& fallback_order_line_63_da1d0371_native();
const NativeFunctionImplementation& renderer_capabilities_snapshot_line_93_70d11e0e_native();
const NativeFunctionImplementation& create_viewport_renderer_line_353_9176ad1d_native();
const NativeFunctionImplementation& iter_mesh_render_data_line_65_fa47e988_native();
const NativeFunctionImplementation& model_nodes_line_211_661ae3a2_native();
const NativeFunctionImplementation& node_is_renderable_mesh_line_225_e3ba8c3b_native();
const NativeFunctionImplementation& extract_node_arrays_line_239_41751f47_native();
const NativeFunctionImplementation& skinned_lbs_vbo_cache_key_line_326_3546a59b_native();
const NativeFunctionImplementation& static_vbo_cache_key_line_346_d5eafd23_native();
const NativeFunctionImplementation& get_skinned_lbs_vbo_cache_line_362_d6f98c35_native();
const NativeFunctionImplementation& set_skinned_lbs_vbo_cache_line_374_25580cd0_native();
const NativeFunctionImplementation& smooth_render_normals_line_383_3400ba22_native();
const NativeFunctionImplementation& coerce_normal_array_line_440_fec0c1af_native();
const NativeFunctionImplementation& area_weighted_normal_accum_line_460_c1f111bb_native();
const NativeFunctionImplementation& normalize_rows_line_487_a0d58bc1_native();
const NativeFunctionImplementation& extract_skinning_line_507_5c8210f3_native();
const NativeFunctionImplementation& bas_attachment_palette_model_for_node_line_552_e008b162_native();
const NativeFunctionImplementation& mesh_model_matrix_for_node_line_579_7a36d755_native();
const NativeFunctionImplementation& bas_attachment_subtree_nodes_line_590_c7e0370e_native();
const NativeFunctionImplementation& texture_image_to_rgba8_line_604_dba24dc9_native();
const NativeFunctionImplementation& node_uv_array_line_627_f48a4217_native();
const NativeFunctionImplementation& material_data_line_652_f91a8721_native();
const NativeFunctionImplementation& texture_data_line_718_f11f351f_native();
const NativeFunctionImplementation& node_has_lightmap_line_739_ec27445f_native();
const NativeFunctionImplementation& alpha_mode_line_751_5b17aae8_native();
const NativeFunctionImplementation& blend_mode_line_770_7ad06fd8_native();
const NativeFunctionImplementation& sprite_alpha_source_line_788_1fbd6397_native();
const NativeFunctionImplementation& sprite_glow_line_800_fffe5bfb_native();
const NativeFunctionImplementation& is_saber_hilt_line_813_8bbed6e1_native();
const NativeFunctionImplementation& has_sprite_material_override_line_823_ce0579b4_native();
const NativeFunctionImplementation& node_world_transform_line_832_8a0acaf4_native();
const NativeFunctionImplementation& node_world_matrix_line_855_b56aeb9c_native();
const NativeFunctionImplementation& bas_attachment_root_for_node_line_881_fc1375c3_native();
const NativeFunctionImplementation& bas_attachment_effective_pose_for_node_line_892_2964cc0a_native();
const NativeFunctionImplementation& bas_attachment_socket_node_line_952_c843adcc_native();
const NativeFunctionImplementation& bas_attachment_world_transform_line_975_5e5d0edc_native();
const NativeFunctionImplementation& bas_attachment_pose_mode_for_root_line_1037_ad40b926_native();
const NativeFunctionImplementation& bas_attachment_pose_applies_to_root_line_1056_fda3d3ac_native();
const NativeFunctionImplementation& bas_head_attachment_has_inherited_pose_tracks_line_1060_58a53a90_native();
const NativeFunctionImplementation& bas_inherited_head_pose_node_allowed_line_1086_36e30abb_native();
const NativeFunctionImplementation& bas_head_attachment_local_pose_node_allowed_name_line_1091_0259f1df_native();
const NativeFunctionImplementation& pose_node_for_transform_line_1106_d54c4f76_native();
const NativeFunctionImplementation& bas_attachment_local_transform_line_1124_852c5d58_native();
const NativeFunctionImplementation& animated_node_world_transform_line_1166_122268f5_native();
const NativeFunctionImplementation& material_color_line_1252_3c10f578_native();
const NativeFunctionImplementation& node_revision_line_1263_37f8d7bd_native();
const NativeFunctionImplementation& clamp01_line_1271_5850941f_native();
const NativeFunctionImplementation& clean_tex_name_line_1275_04a02cb4_native();
const NativeFunctionImplementation& normalize_renderer_backend_line_66_6420bbbf_native();
const NativeFunctionImplementation& supported_renderer_backend_line_73_e099ca56_native();
const NativeFunctionImplementation& renderer_backend_label_line_80_7ea56790_native();
const NativeFunctionImplementation& safe_bool_line_10_5d610f71_native();
const NativeFunctionImplementation& safe_int_line_24_8e8fd9ce_native();
const NativeFunctionImplementation& safe_float_line_31_75f11871_native();

const NativeFunctionImplementation* modulefunctions_native_functions(std::size_t& count);

} // namespace ghostrigger::graphics::renderer::shared::contracts
