#pragma once

#include <cstddef>

namespace ghostrigger::tools::workflow::nodeskeletonbrowser {

#ifndef GHOSTRIGGER_TOOLS_NODESSKELETONBROWSER_NATIVE_FUNCTION_IMPLEMENTATION_DEFINED
#define GHOSTRIGGER_TOOLS_NODESSKELETONBROWSER_NATIVE_FUNCTION_IMPLEMENTATION_DEFINED
struct NativeFunctionImplementation {
    const char* project;
    const char* native_namespace;
    const char* python_file;
    const char* qualname;
    const char* callable_type;
    const char* implementation_status;
    bool native_first;
    bool python_runtime_required;
    bool python_fallback_allowed;
    const char* contract_json;
};
#endif // GHOSTRIGGER_TOOLS_NODESSKELETONBROWSER_NATIVE_FUNCTION_IMPLEMENTATION_DEFINED

const NativeFunctionImplementation& animationengine_construct_line_679_36026f04_native();
const NativeFunctionImplementation& animationengine_play_line_734_85485cbd_native();
const NativeFunctionImplementation& animationengine_stop_line_797_cd03bac7_native();
const NativeFunctionImplementation& animationengine_pause_line_800_74638f7c_native();
const NativeFunctionImplementation& animationengine_seek_line_803_a855105b_native();
const NativeFunctionImplementation& animationengine_advance_line_815_ae43d7fd_native();
const NativeFunctionImplementation& animationengine_evaluate_line_861_f5a5a2c1_native();
const NativeFunctionImplementation& animationengine_eval_node_line_963_edfea505_native();
const NativeFunctionImplementation& animationengine_find_anim_line_1116_9f512ba1_native();
const NativeFunctionImplementation& animationengine_is_usecomp_model_line_1164_a8ce9b0a_native();
const NativeFunctionImplementation& animationengine_get_usecomp_bone_names_line_1174_5534755e_native();
const NativeFunctionImplementation& animationengine_merge_usecomp_from_line_1181_08d3da28_native();
const NativeFunctionImplementation& animationengine_build_bone_remap_line_1217_a9323214_native();
const NativeFunctionImplementation& animationengine_retarget_usecomp_line_1228_3c8fd9a7_native();
const NativeFunctionImplementation& animationengine_list_animations_line_1274_c5f887bf_native();
const NativeFunctionImplementation& animationengine_list_all_animations_line_1304_bc82e3bc_native();
const NativeFunctionImplementation& animationengine_get_animation_fps_estimate_line_1367_f1664e1a_native();
const NativeFunctionImplementation& animationengine_get_recommended_playback_fps_line_1399_075adeea_native();
const NativeFunctionImplementation& animationengine_export_animation_json_line_1411_cbe8ca12_native();
const NativeFunctionImplementation& animationengine_export_animation_bvh_line_1457_515700ee_native();
const NativeFunctionImplementation& animationengine_export_all_animations_line_1622_40d76844_native();
const NativeFunctionImplementation& animationengine_import_animation_json_line_1641_a21c8be8_native();
const NativeFunctionImplementation& animationengine_get_pose_line_1687_136732a2_native();
const NativeFunctionImplementation& animationengine_get_fired_events_line_1692_6bd576e2_native();
const NativeFunctionImplementation& animationengine_is_blending_line_1702_6a055dac_native();
const NativeFunctionImplementation& animationengine_blend_fraction_line_1706_a7648f0d_native();
const NativeFunctionImplementation& animationengine_add_animation_line_1710_244667dd_native();
const NativeFunctionImplementation& animationengine_remove_animation_line_1721_e299ef06_native();
const NativeFunctionImplementation& danglysimulator_construct_line_1957_66484ba7_native();
const NativeFunctionImplementation& danglysimulator_build_edges_line_1980_acaf3f46_native();
const NativeFunctionImplementation& danglysimulator_reset_line_1999_5dc77bfa_native();
const NativeFunctionImplementation& danglysimulator_step_line_2005_511d26fe_native();
const NativeFunctionImplementation& animstatemachine_construct_line_2262_f07eb2b0_native();
const NativeFunctionImplementation& animstatemachine_add_state_line_2275_e42676b0_native();
const NativeFunctionImplementation& animstatemachine_remove_state_line_2282_2e142ed7_native();
const NativeFunctionImplementation& animstatemachine_add_transition_line_2289_ddf5b5f7_native();
const NativeFunctionImplementation& animstatemachine_set_constructial_line_2306_5473e95b_native();
const NativeFunctionImplementation& animstatemachine_start_line_2315_0f6f1b28_native();
const NativeFunctionImplementation& animstatemachine_stop_line_2331_57035370_native();
const NativeFunctionImplementation& animstatemachine_reset_line_2335_eaec43f7_native();
const NativeFunctionImplementation& animstatemachine_request_transition_line_2345_dbf18193_native();
const NativeFunctionImplementation& animstatemachine_advance_line_2378_a9c4e2a3_native();
const NativeFunctionImplementation& animstatemachine_history_line_2465_92aa4536_native();
const NativeFunctionImplementation& animstatemachine_get_state_line_2469_8d19a795_native();
const NativeFunctionImplementation& animstatemachine_enter_state_line_2475_fa77fc5f_native();
const NativeFunctionImplementation& animstatemachine_eval_transitions_line_2512_2b388559_native();
const NativeFunctionImplementation& animationlibrary_construct_line_104_3c2041eb_native();
const NativeFunctionImplementation& animationlibrary_scan_line_116_87ece461_native();
const NativeFunctionImplementation& animationlibrary_do_scan_line_153_cc8683e3_native();
const NativeFunctionImplementation& animationlibrary_search_line_213_b882aee8_native();
const NativeFunctionImplementation& animationlibrary_get_model_animations_line_235_aea9f0ed_native();
const NativeFunctionImplementation& animationlibrary_get_all_model_names_line_240_6e4fdb41_native();
const NativeFunctionImplementation& animationlibrary_get_all_anim_names_line_245_9a5d4e20_native();
const NativeFunctionImplementation& animationlibrary_get_engine_line_250_18151a62_native();
const NativeFunctionImplementation& fbxanimationexporter_export_line_458_32acfc7e_native();
const NativeFunctionImplementation& fbxanimationexporter_export_baked_line_493_c12a4541_native();
const NativeFunctionImplementation& fbxanimationexporter_export_all_line_520_05a74834_native();
const NativeFunctionImplementation& fbxanimationexporter_export_all_baked_line_535_214d3a11_native();
const NativeFunctionImplementation& fbxanimationexporter_export_library_entry_line_560_e5acf569_native();
const NativeFunctionImplementation& fbxanimationexporter_write_fbx_line_580_f5e716d6_native();
const NativeFunctionImplementation& fbxanimationexporter_write_fbx_baked_line_943_0cbbd504_native();
const NativeFunctionImplementation& matrixpaletteuploader_construct_line_368_03652906_native();
const NativeFunctionImplementation& matrixpaletteuploader_build_inverse_bind_pose_line_406_24fc3700_native();
const NativeFunctionImplementation& matrixpaletteuploader_set_bind_pose_from_anim_line_576_a8a8082a_native();
const NativeFunctionImplementation& matrixpaletteuploader_world_pose_matrix_line_684_f52b1f4a_native();
const NativeFunctionImplementation& matrixpaletteuploader_resolve_skin_formula_for_skin_node_line_837_7a38e77e_native();
const NativeFunctionImplementation& matrixpaletteuploader_compute_skin_node_palette_line_890_d87fece7_native();
const NativeFunctionImplementation& matrixpaletteuploader_compute_palette_line_1085_47b41050_native();
const NativeFunctionImplementation& matrixpaletteuploader_as_numpy_array_line_1224_b6f5b275_native();
const NativeFunctionImplementation& matrixpaletteuploader_as_flat_bytes_line_1242_e97500b6_native();
const NativeFunctionImplementation& matrixpaletteuploader_upload_to_ssbo_line_1263_dc04d082_native();
const NativeFunctionImplementation& matrixpaletteuploader_release_line_1291_f96e0c10_native();
const NativeFunctionImplementation& matrixpaletteuploader_bone_index_line_1310_4f3fdd1f_native();
const NativeFunctionImplementation& tbncomputer_compute_line_1399_5f8e235c_native();
const NativeFunctionImplementation& tbncomputer_compute_numpy_line_1530_7adacde8_native();
const NativeFunctionImplementation& nodetreedelegate_sizehint_line_36_321339bf_native();
const NativeFunctionImplementation& qtskeletonpanel_construct_line_49_3f30a7ea_native();
const NativeFunctionImplementation& qtskeletonpanel_build_line_56_2cc74a34_native();
const NativeFunctionImplementation& qtskeletonpanel_load_model_line_134_597d915e_native();
const NativeFunctionImplementation& qtskeletonpanel_insert_node_iterative_line_148_371423c3_native();
const NativeFunctionImplementation& qtskeletonpanel_make_node_item_line_161_9558626b_native();
const NativeFunctionImplementation& qtskeletonpanel_on_selection_changed_line_185_5fc33db3_native();
const NativeFunctionImplementation& qtskeletonpanel_filter_line_196_f26c6c5b_native();
const NativeFunctionImplementation& qtskeletonpanel_tree_expand_all_line_205_6a30d8cf_native();
const NativeFunctionImplementation& qtskeletonpanel_tree_collapse_to_roots_line_209_bea2c7bc_native();
const NativeFunctionImplementation& qtskeletonpanel_select_all_nodes_line_214_5a069b61_native();
const NativeFunctionImplementation& qtskeletonpanel_clear_selection_line_217_aaf409ae_native();
const NativeFunctionImplementation& qtskeletonpanel_select_node_line_220_845e2623_native();
const NativeFunctionImplementation& qtskeletonpanel_get_selected_nodes_line_236_c781cadc_native();
const NativeFunctionImplementation& qtskeletonpanel_filter_item_line_239_a09305c8_native();
const NativeFunctionImplementation& qtskeletonpanel_resize_columns_to_content_line_254_467c81ac_native();
const NativeFunctionImplementation& qtskeletonpanel_node_role_line_258_9d3fa882_native();
const NativeFunctionImplementation& qtskeletonpanel_mesh_label_line_261_9aa4955c_native();
const NativeFunctionImplementation& qtskeletonpanel_attachment_count_line_270_d098351f_native();
const NativeFunctionImplementation& qtskeletonpanel_node_tooltip_line_279_e969e11a_native();
const NativeFunctionImplementation& qtskeletonpanel_icon_for_role_line_293_071d25ba_native();
const NativeFunctionImplementation& qtskeletonpanel_draw_node_icon_line_310_483abfe4_native();

const NativeFunctionImplementation* instancemethods_native_functions(std::size_t& count);

} // namespace ghostrigger::tools::workflow::nodeskeletonbrowser
