#pragma once

#include <cstddef>

namespace ghostrigger::domain::core::validation {

#ifndef GHOSTRIGGER_VALIDATION_NATIVE_FUNCTION_IMPLEMENTATION_DEFINED
#define GHOSTRIGGER_VALIDATION_NATIVE_FUNCTION_IMPLEMENTATION_DEFINED
struct NativeFunctionImplementation {
    const char* project;
    const char* native_namespace;
    const char* python_file;
    const char* qualname;
    const char* callable_type;
    const char* implementation_status;
    bool native_first;
    bool python_runtime_required;
    bool python_fallback_allowed;
    const char* contract_json;
};
#endif // GHOSTRIGGER_VALIDATION_NATIVE_FUNCTION_IMPLEMENTATION_DEFINED

const NativeFunctionImplementation& validate_raw_animation_footprint_line_112_d02544a1_native();
const NativeFunctionImplementation& u32_line_240_9c1f39d4_native();
const NativeFunctionImplementation& u16_line_246_32ef73da_native();
const NativeFunctionImplementation& read_c_string_line_252_70542a6a_native();
const NativeFunctionImplementation& read_name_table_line_261_319df6aa_native();
const NativeFunctionImplementation& find_animation_offset_line_277_fede4b45_native();
const NativeFunctionImplementation& controller_label_line_300_aa0bf618_native();
const NativeFunctionImplementation& is_position_controller_line_307_84fb2300_native();
const NativeFunctionImplementation& is_orientation_controller_line_311_d9027126_native();
const NativeFunctionImplementation& fconstructe_values_line_318_06233d23_native();
const NativeFunctionImplementation& validate_controller_line_325_c7a61bae_native();
const NativeFunctionImplementation& validate_animation_block_against_model_line_418_d4b136ec_native();
const NativeFunctionImplementation& quaternion_angular_difference_degrees_line_63_92f73317_native();
const NativeFunctionImplementation& verify_written_animation_override_roundtrip_line_76_318c9c65_native();
const NativeFunctionImplementation& find_animation_line_130_12fbd0b1_native();
const NativeFunctionImplementation& normalize_quat_line_138_2994c8e9_native();
const NativeFunctionImplementation& controller_key_line_147_c50532d9_native();
const NativeFunctionImplementation& node_map_line_151_563be9b6_native();
const NativeFunctionImplementation& controller_map_line_159_e5f1b7ef_native();
const NativeFunctionImplementation& float_close_line_163_0859f19c_native();
const NativeFunctionImplementation& vec_close_line_167_098a7e79_native();
const NativeFunctionImplementation& compare_model_structure_line_171_eba98c26_native();
const NativeFunctionImplementation& compare_animation_metadata_line_233_a74f45de_native();
const NativeFunctionImplementation& compare_animation_controllers_line_252_d8f70927_native();
const NativeFunctionImplementation& compare_controller_line_278_6c69b449_native();
const NativeFunctionImplementation& sample_times_for_line_333_9e070fef_native();
const NativeFunctionImplementation& compare_evaluated_poses_line_342_285e4bb6_native();
const NativeFunctionImplementation& compare_transform_line_375_754b7f6d_native();
const NativeFunctionImplementation& compare_mdx_bytes_if_available_line_399_31fd81d8_native();
const NativeFunctionImplementation& project_validation_report_to_bus_report_line_20_d4cdca85_native();
const NativeFunctionImplementation& retarget_preview_audit_to_validation_report_line_46_c51f3b56_native();
const NativeFunctionImplementation& retarget_issue_line_144_31e94c29_native();
const NativeFunctionImplementation& extract_node_time_line_167_29df66fc_native();
const NativeFunctionImplementation& severity_line_193_ac792e26_native();
const NativeFunctionImplementation& severity_rank_line_172_cf55f224_native();
const NativeFunctionImplementation& make_issue_id_line_176_478d669f_native();
const NativeFunctionImplementation& merge_validation_reports_line_192_fa145f4a_native();
const NativeFunctionImplementation& validation_navigation_target_to_dict_line_208_f74af269_native();
const NativeFunctionImplementation& validation_navigation_target_from_dict_line_225_915859c1_native();
const NativeFunctionImplementation& validation_issue_to_dict_line_242_c1f14dc8_native();
const NativeFunctionImplementation& validation_issue_from_dict_line_259_57b8bb16_native();
const NativeFunctionImplementation& validation_report_to_dict_line_276_f73c3382_native();
const NativeFunctionImplementation& validation_report_from_dict_line_286_b5b290cf_native();
const NativeFunctionImplementation& dedupe_issues_line_296_6bd3cc48_native();
const NativeFunctionImplementation& coerce_severity_line_308_9efc1219_native();
const NativeFunctionImplementation& coerce_subsystem_line_314_0d1ea778_native();
const NativeFunctionImplementation& ensure_json_serializable_line_320_4c17f302_native();

const NativeFunctionImplementation* modulefunctions_native_functions(std::size_t& count);

} // namespace ghostrigger::domain::core::validation
