#pragma once

#include <cstddef>

namespace ghostrigger::phase15::ghostrigger_gui_integration {

using PythonFunctionDescriptorJson = const char* (*)();

struct PythonFunctionDescriptorEntry {
    const char* python_file;
    const char* qualname;
    const char* function_type;
    PythonFunctionDescriptorJson descriptor_json;
};

const char* src_gui_assets_qt_matrix_background_qtmatrixengine_init_line_60_0dc28f9c_descriptor_json();
const char* src_gui_assets_qt_matrix_background_qtmatrixengine_start_line_66_25622b25_descriptor_json();
const char* src_gui_assets_qt_matrix_background_qtmatrixengine_stop_line_70_e3c2b852_descriptor_json();
const char* src_gui_assets_qt_matrix_background_qtmatrixpanel_init_line_77_e400e60c_descriptor_json();
const char* src_gui_assets_qt_matrix_background_qtmatrixpanel_apply_ghost_theme_line_105_45c2f152_descriptor_json();
const char* src_gui_assets_qt_matrix_background_qtmatrixpanel_set_matrix_config_line_119_63d4965d_descriptor_json();
const char* src_gui_assets_qt_matrix_background_qtmatrixpanel_crop_rect_line_160_263c6742_descriptor_json();
const char* src_gui_assets_qt_matrix_background_qtmatrixpanel_resizeevent_line_170_ff69dedc_descriptor_json();
const char* src_gui_assets_qt_matrix_background_qtmatrixpanel_paintevent_line_182_4e44a4b6_descriptor_json();
const char* src_gui_assets_qt_matrix_background_qtmatrixpanel_advance_line_217_33000fa3_descriptor_json();
const char* src_gui_assets_qt_matrix_background_qtmatrixlabel_init_line_234_987d214d_descriptor_json();
const char* src_gui_assets_qt_matrix_background_qtmatrixlabel_apply_ghost_theme_line_238_e467f9fe_descriptor_json();
const char* src_gui_assets_qt_theme_qtoverflowscrollarea_init_line_23_83c656a7_descriptor_json();
const char* src_gui_assets_qt_theme_qtoverflowscrollarea_setwidget_line_32_3c3140ee_descriptor_json();
const char* src_gui_assets_qt_theme_qtoverflowscrollarea_resizeevent_line_36_05cd02c4_descriptor_json();
const char* src_gui_assets_qt_theme_qtoverflowscrollarea_sync_content_width_line_40_9fbec4af_descriptor_json();
const char* src_gui_assets_qt_theme_qtflowlayout_init_line_54_8627f45a_descriptor_json();
const char* src_gui_assets_qt_theme_qtflowlayout_additem_line_70_a817afc1_descriptor_json();
const char* src_gui_assets_qt_theme_qtflowlayout_setspacing_line_73_5e14d2e5_descriptor_json();
const char* src_gui_assets_qt_theme_qtflowlayout_count_line_78_39dbd8ed_descriptor_json();
const char* src_gui_assets_qt_theme_qtflowlayout_itemat_line_81_e6cd0652_descriptor_json();
const char* src_gui_assets_qt_theme_qtflowlayout_takeat_line_84_ec994623_descriptor_json();
const char* src_gui_assets_qt_theme_qtflowlayout_expandingdirections_line_89_a124d406_descriptor_json();
const char* src_gui_assets_qt_theme_qtflowlayout_hasheightforwidth_line_92_63efc361_descriptor_json();
const char* src_gui_assets_qt_theme_qtflowlayout_heightforwidth_line_95_326d1524_descriptor_json();
const char* src_gui_assets_qt_theme_qtflowlayout_setgeometry_line_98_8a7e840d_descriptor_json();
const char* src_gui_assets_qt_theme_qtflowlayout_sizehint_line_102_9f166a20_descriptor_json();
const char* src_gui_assets_qt_theme_qtflowlayout_minimumsize_line_105_e27816b7_descriptor_json();
const char* src_gui_assets_qt_theme_qtflowlayout_do_layout_line_113_5ce904ee_descriptor_json();
const char* src_gui_integration_editor_services_editorintegrationeventbus_init_line_56_39b5d149_descriptor_json();
const char* src_gui_integration_editor_services_editorintegrationeventbus_record_tool_action_line_65_23d5b024_descriptor_json();
const char* src_gui_integration_editor_services_editorintegrationeventbus_record_scene_update_line_70_f7ecd415_descriptor_json();
const char* src_gui_integration_editor_services_editorintegrationeventbus_record_cache_invalidation_line_81_8a0007eb_descriptor_json();
const char* src_gui_integration_editor_services_editorintegrationeventbus_record_redraw_line_85_43c35f9d_descriptor_json();
const char* src_gui_integration_editor_services_editorintegrationeventbus_warn_unsupported_line_89_9083e319_descriptor_json();
const char* src_gui_integration_editor_services_activeviewportservice_init_line_96_b750c90a_descriptor_json();
const char* src_gui_integration_editor_services_activeviewportservice_get_active_viewport_line_109_dbb2cda8_descriptor_json();
const char* src_gui_integration_editor_services_activeviewportservice_get_active_renderer_line_114_6962af86_descriptor_json();
const char* src_gui_integration_editor_services_activeviewportservice_get_active_renderer_backend_line_120_0d438fbb_descriptor_json();
const char* src_gui_integration_editor_services_activeviewportservice_get_display_options_line_134_3bebbb5f_descriptor_json();
const char* src_gui_integration_editor_services_activeviewportservice_request_redraw_line_138_9c331d19_descriptor_json();
const char* src_gui_integration_editor_services_activeviewportservice_get_camera_line_148_f59bb637_descriptor_json();
const char* src_gui_integration_editor_services_activeviewportservice_get_scene_line_152_84771390_descriptor_json();
const char* src_gui_integration_editor_services_activeviewportservice_get_selection_line_161_a717c3b0_descriptor_json();
const char* src_gui_integration_editor_services_rendererservice_init_line_175_dac1ed29_descriptor_json();
const char* src_gui_integration_editor_services_rendererservice_get_capabilities_line_185_0cbcccfa_descriptor_json();
const char* src_gui_integration_editor_services_rendererservice_get_diagnostics_line_200_311e9e22_descriptor_json();
const char* src_gui_integration_editor_services_rendererservice_supports_line_218_321f224f_descriptor_json();
const char* src_gui_integration_editor_services_rendererservice_request_mode_line_225_b11fb619_descriptor_json();
const char* src_gui_integration_editor_services_rendererservice_request_surface_refresh_line_236_4ed18016_descriptor_json();
const char* src_gui_integration_editor_services_rendererservice_request_resource_invalidation_line_242_5e844a58_descriptor_json();
const char* src_gui_integration_editor_services_rendererservice_fallback_capabilities_line_263_574398db_descriptor_json();
const char* src_gui_integration_editor_services_selectionservice_init_line_330_af4d5f8d_descriptor_json();
const char* src_gui_integration_editor_services_selectionservice_current_line_335_92376805_descriptor_json();
const char* src_gui_integration_editor_services_selectionservice_select_node_line_338_6fc945c9_descriptor_json();
const char* src_gui_integration_editor_services_selectionservice_select_meshes_line_345_8b8613bd_descriptor_json();
const char* src_gui_integration_editor_services_sceneservice_init_line_354_7545edb7_descriptor_json();
const char* src_gui_integration_editor_services_sceneservice_get_scene_line_359_fc34c885_descriptor_json();
const char* src_gui_integration_editor_services_diagnosticsservice_init_line_380_3a6fb0c8_descriptor_json();
const char* src_gui_integration_editor_services_diagnosticsservice_snapshot_line_396_dd0427ea_descriptor_json();
const char* src_gui_integration_tool_integration_registry_toolintegrationregistry_register_line_36_e6dad00e_descriptor_json();
const char* src_gui_integration_tool_integration_registry_toolintegrationregistry_get_line_39_afc5f053_descriptor_json();
const char* src_gui_integration_tool_integration_registry_toolintegrationregistry_all_tools_line_42_99154aac_descriptor_json();
const char* src_gui_integration_tool_integration_registry_toolintegrationregistry_compatibility_rows_line_45_ed790c26_descriptor_json();
const char* src_gui_qt_lib_aliasloader_init_line_224_ab29ba54_descriptor_json();
const char* src_gui_qt_lib_aliasloader_create_module_line_227_f2e967e8_descriptor_json();
const char* src_gui_qt_lib_aliasloader_exec_module_line_230_98e3e840_descriptor_json();
const char* src_gui_qt_lib_aliasfinder_find_spec_line_242_05e98a6c_descriptor_json();
const char* src_gui_qt_lib_lazymodule_init_line_257_c7722d35_descriptor_json();
const char* src_gui_qt_lib_lazymodule_load_line_262_9d56a695_descriptor_json();
const char* src_gui_qt_lib_lazymodule_getattr_line_272_406585d8_descriptor_json();
const char* src_gui_qt_lib_lazymodule_dir_line_275_23687304_descriptor_json();

const PythonFunctionDescriptorEntry* instancemethods_descriptors(std::size_t& count);

} // namespace ghostrigger::phase15::ghostrigger_gui_integration
