#pragma once

#include <cstddef>

namespace ghostrigger::phase15::ghostrigger_modules {

using PythonFunctionDescriptorJson = const char* (*)();

struct PythonFunctionDescriptorEntry {
    const char* python_file;
    const char* qualname;
    const char* function_type;
    PythonFunctionDescriptorJson descriptor_json;
};

const char* src_core_modules_module_blueprint_service_moduleblueprintservice_add_blueprint_line_9_f5f95e66_descriptor_json();
const char* src_core_modules_module_blueprint_service_moduleblueprintservice_remove_blueprint_line_19_59b2d59f_descriptor_json();
const char* src_core_modules_module_blueprint_service_moduleblueprintservice_send_to_gmodular_line_27_da3ed39e_descriptor_json();
const char* src_core_modules_module_builder_service_modulebuilderservice_build_preview_line_27_46432696_descriptor_json();
const char* src_core_modules_module_editor_controller_moduleeditorcontroller_init_line_20_faa00848_descriptor_json();
const char* src_core_modules_module_editor_controller_moduleeditorcontroller_new_project_line_36_b71c5a6d_descriptor_json();
const char* src_core_modules_module_editor_controller_moduleeditorcontroller_open_project_line_42_7279d7c3_descriptor_json();
const char* src_core_modules_module_editor_controller_moduleeditorcontroller_save_project_line_48_aea1fd89_descriptor_json();
const char* src_core_modules_module_editor_controller_moduleeditorcontroller_add_module_line_52_d952bc6a_descriptor_json();
const char* src_core_modules_module_editor_controller_moduleeditorcontroller_remove_selected_line_59_7edb7680_descriptor_json();
const char* src_core_modules_module_editor_controller_moduleeditorcontroller_duplicate_selected_line_70_7481ff4c_descriptor_json();
const char* src_core_modules_module_editor_controller_moduleeditorcontroller_load_lyt_line_78_388a097e_descriptor_json();
const char* src_core_modules_module_editor_controller_moduleeditorcontroller_load_wok_line_81_8997f2be_descriptor_json();
const char* src_core_modules_module_editor_controller_moduleeditorcontroller_validate_line_88_55995243_descriptor_json();
const char* src_core_modules_module_editor_controller_moduleeditorcontroller_build_preview_line_91_67d5afd0_descriptor_json();
const char* src_core_modules_module_editor_controller_moduleeditorcontroller_export_fbx_line_94_5b2994a6_descriptor_json();
const char* src_core_modules_module_editor_controller_moduleeditorcontroller_add_blueprint_line_97_7493cace_descriptor_json();
const char* src_core_modules_module_editor_controller_moduleeditorcontroller_import_library_asset_line_102_f52ba369_descriptor_json();
const char* src_core_modules_module_editor_controller_moduleeditorcontroller_record_port_line_180_8f64f619_descriptor_json();
const char* src_core_modules_module_editor_model_moduleeditormodel_set_project_line_32_93014ec6_descriptor_json();
const char* src_core_modules_module_editor_model_moduleeditormodel_select_line_39_8d782e55_descriptor_json();
const char* src_core_modules_module_editor_model_moduleeditormodel_log_line_46_8da612bc_descriptor_json();
const char* src_core_modules_module_format_lytlayout_to_text_line_149_422dfda2_descriptor_json();
const char* src_core_modules_module_format_lytlayout_write_line_168_5f928624_descriptor_json();
const char* src_core_modules_module_format_visdata_to_text_line_202_de38d244_descriptor_json();
const char* src_core_modules_module_format_visdata_write_line_210_42731897_descriptor_json();
const char* src_core_modules_module_format_visdata_add_full_visibility_line_213_48ef1b03_descriptor_json();
const char* src_core_modules_module_format_gitdata_summary_line_442_dd8b7bc0_descriptor_json();
const char* src_core_modules_module_format_wokdata_parse_line_621_9ee3c9b8_descriptor_json();
const char* src_core_modules_module_format_wokdata_walkable_face_count_line_665_6aa16ccc_descriptor_json();
const char* src_core_modules_module_format_wokdata_non_walk_face_count_line_668_57746993_descriptor_json();
const char* src_core_modules_module_format_wokdata_boundary_edges_line_671_25ce5b99_descriptor_json();
const char* src_core_modules_module_format_wokdata_summary_line_693_d1146c6a_descriptor_json();
const char* src_core_modules_module_format_wokdata_set_face_surface_line_700_e6ead2c4_descriptor_json();
const char* src_core_modules_module_format_wokdata_bulk_replace_surface_line_708_a418fb94_descriptor_json();
const char* src_core_modules_module_format_wokdata_surface_distribution_line_717_c9dec993_descriptor_json();
const char* src_core_modules_module_format_wokdata_face_at_point_line_724_31aacffd_descriptor_json();
const char* src_core_modules_module_format_wokdata_to_bytes_line_749_02c688dd_descriptor_json();
const char* src_core_modules_module_format_wokdata_write_binary_line_809_ff1ad723_descriptor_json();
const char* src_core_modules_module_format_walkmeshwallgenerator_init_line_835_f43e667e_descriptor_json();
const char* src_core_modules_module_format_walkmeshwallgenerator_generate_line_839_6abef998_descriptor_json();
const char* src_core_modules_module_format_walkmeshwallgenerator_write_ascii_wok_line_897_fb2168e4_descriptor_json();
const char* src_core_modules_module_format_kotormodule_summary_line_997_9e595455_descriptor_json();
const char* src_core_modules_module_layout_service_modulelayoutservice_load_lyt_file_line_30_c75720d9_descriptor_json();
const char* src_core_modules_module_layout_service_modulelayoutservice_import_lyt_line_46_da486f7b_descriptor_json();
const char* src_core_modules_module_layout_service_modulelayoutservice_save_lyt_text_line_76_9618621c_descriptor_json();
const char* src_core_modules_module_loader_loadresult_summary_line_102_8da7e8eb_descriptor_json();
const char* src_core_modules_module_loader_modellookup_init_line_133_94106c1f_descriptor_json();
const char* src_core_modules_module_loader_modellookup_load_model_line_136_f72d50ac_descriptor_json();
const char* src_core_modules_module_loader_modellookup_has_model_line_156_bde75990_descriptor_json();
const char* src_core_modules_module_loader_moduleloader_init_line_193_8a9f17bd_descriptor_json();
const char* src_core_modules_module_loader_moduleloader_load_from_directory_line_203_d676b6a3_descriptor_json();
const char* src_core_modules_module_loader_moduleloader_load_from_kotor_module_line_232_1354e708_descriptor_json();
const char* src_core_modules_module_loader_moduleloader_load_from_lyt_text_line_244_673c0fd8_descriptor_json();
const char* src_core_modules_module_loader_moduleloader_build_scene_line_289_75738a27_descriptor_json();
const char* src_core_modules_module_loader_moduleloader_load_git_objects_line_391_42e0aba2_descriptor_json();
const char* src_core_modules_module_porter_service_moduleporterservice_record_port_decision_line_21_74489126_descriptor_json();
const char* src_core_modules_module_save_pipeline_modulesavemanifest_to_dict_line_183_83c7eedc_descriptor_json();
const char* src_core_modules_module_walkmesh_service_modulewalkmeshservice_load_wok_file_line_32_38fdd2f8_descriptor_json();
const char* src_core_modules_module_walkmesh_service_modulewalkmeshservice_paint_face_line_43_40915eef_descriptor_json();
const char* src_core_modules_module_walkmesh_service_modulewalkmeshservice_validate_line_46_3ce44231_descriptor_json();
const char* src_core_modules_module_walkmesh_service_modulewalkmeshservice_generate_walls_line_49_96936d64_descriptor_json();
const char* src_core_modules_module_walkmesh_service_modulewalkmeshservice_save_wok_line_53_83adc8d1_descriptor_json();

const PythonFunctionDescriptorEntry* instancemethods_descriptors(std::size_t& count);

} // namespace ghostrigger::phase15::ghostrigger_modules
