#pragma once

#include <cstddef>

namespace ghostrigger::modules {

#ifndef GHOSTRIGGER_MODULES_NATIVE_FUNCTION_IMPLEMENTATION_DEFINED
#define GHOSTRIGGER_MODULES_NATIVE_FUNCTION_IMPLEMENTATION_DEFINED
struct NativeFunctionImplementation {
    const char* project;
    const char* native_namespace;
    const char* python_file;
    const char* qualname;
    const char* callable_type;
    const char* implementation_status;
    bool native_first;
    bool python_runtime_required;
    bool python_fallback_allowed;
    const char* contract_json;
};
#endif // GHOSTRIGGER_MODULES_NATIVE_FUNCTION_IMPLEMENTATION_DEFINED

const NativeFunctionImplementation& moduleblueprintservice_add_blueprint_line_9_f5f95e66_native();
const NativeFunctionImplementation& moduleblueprintservice_remove_blueprint_line_19_59b2d59f_native();
const NativeFunctionImplementation& moduleblueprintservice_send_to_gmodular_line_27_da3ed39e_native();
const NativeFunctionImplementation& modulebuilderservice_build_preview_line_27_46432696_native();
const NativeFunctionImplementation& moduleeditorcontroller_construct_line_20_faa00848_native();
const NativeFunctionImplementation& moduleeditorcontroller_new_project_line_36_b71c5a6d_native();
const NativeFunctionImplementation& moduleeditorcontroller_open_project_line_42_7279d7c3_native();
const NativeFunctionImplementation& moduleeditorcontroller_save_project_line_48_aea1fd89_native();
const NativeFunctionImplementation& moduleeditorcontroller_add_module_line_52_d952bc6a_native();
const NativeFunctionImplementation& moduleeditorcontroller_remove_selected_line_59_7edb7680_native();
const NativeFunctionImplementation& moduleeditorcontroller_duplicate_selected_line_70_7481ff4c_native();
const NativeFunctionImplementation& moduleeditorcontroller_load_lyt_line_78_388a097e_native();
const NativeFunctionImplementation& moduleeditorcontroller_load_wok_line_81_8997f2be_native();
const NativeFunctionImplementation& moduleeditorcontroller_validate_line_88_55995243_native();
const NativeFunctionImplementation& moduleeditorcontroller_build_preview_line_91_67d5afd0_native();
const NativeFunctionImplementation& moduleeditorcontroller_export_fbx_line_94_5b2994a6_native();
const NativeFunctionImplementation& moduleeditorcontroller_add_blueprint_line_97_7493cace_native();
const NativeFunctionImplementation& moduleeditorcontroller_import_library_asset_line_102_f52ba369_native();
const NativeFunctionImplementation& moduleeditorcontroller_record_port_line_180_8f64f619_native();
const NativeFunctionImplementation& moduleeditormodel_set_project_line_32_93014ec6_native();
const NativeFunctionImplementation& moduleeditormodel_select_line_39_8d782e55_native();
const NativeFunctionImplementation& moduleeditormodel_log_line_46_8da612bc_native();
const NativeFunctionImplementation& lytlayout_to_text_line_149_422dfda2_native();
const NativeFunctionImplementation& lytlayout_write_line_168_5f928624_native();
const NativeFunctionImplementation& visdata_to_text_line_202_de38d244_native();
const NativeFunctionImplementation& visdata_write_line_210_42731897_native();
const NativeFunctionImplementation& visdata_add_full_visibility_line_213_48ef1b03_native();
const NativeFunctionImplementation& gitdata_summary_line_442_dd8b7bc0_native();
const NativeFunctionImplementation& wokdata_parse_line_621_9ee3c9b8_native();
const NativeFunctionImplementation& wokdata_walkable_face_count_line_665_6aa16ccc_native();
const NativeFunctionImplementation& wokdata_non_walk_face_count_line_668_57746993_native();
const NativeFunctionImplementation& wokdata_boundary_edges_line_671_25ce5b99_native();
const NativeFunctionImplementation& wokdata_summary_line_693_d1146c6a_native();
const NativeFunctionImplementation& wokdata_set_face_surface_line_700_e6ead2c4_native();
const NativeFunctionImplementation& wokdata_bulk_replace_surface_line_708_a418fb94_native();
const NativeFunctionImplementation& wokdata_surface_distribution_line_717_c9dec993_native();
const NativeFunctionImplementation& wokdata_face_at_point_line_724_31aacffd_native();
const NativeFunctionImplementation& wokdata_to_bytes_line_749_02c688dd_native();
const NativeFunctionImplementation& wokdata_write_binary_line_809_ff1ad723_native();
const NativeFunctionImplementation& walkmeshwallgenerator_construct_line_835_f43e667e_native();
const NativeFunctionImplementation& walkmeshwallgenerator_generate_line_839_6abef998_native();
const NativeFunctionImplementation& walkmeshwallgenerator_write_ascii_wok_line_897_fb2168e4_native();
const NativeFunctionImplementation& kotormodule_summary_line_997_9e595455_native();
const NativeFunctionImplementation& modulelayoutservice_load_lyt_file_line_30_c75720d9_native();
const NativeFunctionImplementation& modulelayoutservice_import_lyt_line_46_da486f7b_native();
const NativeFunctionImplementation& modulelayoutservice_save_lyt_text_line_76_9618621c_native();
const NativeFunctionImplementation& loadresult_summary_line_102_8da7e8eb_native();
const NativeFunctionImplementation& modellookup_construct_line_133_94106c1f_native();
const NativeFunctionImplementation& modellookup_load_model_line_136_f72d50ac_native();
const NativeFunctionImplementation& modellookup_has_model_line_156_bde75990_native();
const NativeFunctionImplementation& moduleloader_construct_line_193_8a9f17bd_native();
const NativeFunctionImplementation& moduleloader_load_from_directory_line_203_d676b6a3_native();
const NativeFunctionImplementation& moduleloader_load_from_kotor_module_line_232_1354e708_native();
const NativeFunctionImplementation& moduleloader_load_from_lyt_text_line_244_673c0fd8_native();
const NativeFunctionImplementation& moduleloader_build_scene_line_289_75738a27_native();
const NativeFunctionImplementation& moduleloader_load_git_objects_line_391_42e0aba2_native();
const NativeFunctionImplementation& moduleporterservice_record_port_decision_line_21_74489126_native();
const NativeFunctionImplementation& modulesavemanifest_to_dict_line_183_83c7eedc_native();
const NativeFunctionImplementation& modulewalkmeshservice_load_wok_file_line_32_38fdd2f8_native();
const NativeFunctionImplementation& modulewalkmeshservice_paint_face_line_43_40915eef_native();
const NativeFunctionImplementation& modulewalkmeshservice_validate_line_46_3ce44231_native();
const NativeFunctionImplementation& modulewalkmeshservice_generate_walls_line_49_96936d64_native();
const NativeFunctionImplementation& modulewalkmeshservice_save_wok_line_53_83adc8d1_native();

const NativeFunctionImplementation* instancemethods_native_functions(std::size_t& count);

} // namespace ghostrigger::modules
