#pragma once

#include <cstddef>

namespace ghostrigger::phase15::ghostrigger_tools_contentbrowser {

using PythonFunctionDescriptorJson = const char* (*)();

struct PythonFunctionDescriptorEntry {
    const char* python_file;
    const char* qualname;
    const char* function_type;
    PythonFunctionDescriptorJson descriptor_json;
};

const char* src_core_resources_game_resource_provider_coerce_resource_query_line_167_aa2b5698_descriptor_json();
const char* src_core_resources_game_resource_provider_restype_to_extension_line_435_d168dbf6_descriptor_json();
const char* src_core_resources_game_resource_provider_records_from_install_line_442_29a1399c_descriptor_json();
const char* src_core_resources_game_resource_provider_override_records_line_460_fa1405f7_descriptor_json();
const char* src_core_resources_game_resource_provider_erf_records_line_484_f262248d_descriptor_json();
const char* src_core_resources_game_resource_provider_bif_records_line_522_923b63b9_descriptor_json();
const char* src_core_resources_game_resource_provider_record_line_553_2745da10_descriptor_json();
const char* src_core_resources_game_resource_provider_record_matches_line_585_f4a92796_descriptor_json();
const char* src_core_resources_game_resource_provider_sort_records_line_602_cf3d7f84_descriptor_json();
const char* src_core_resources_game_resource_provider_dedupe_records_line_616_788f2d14_descriptor_json();
const char* src_core_resources_game_resource_provider_shadow_warnings_line_628_0fd0c506_descriptor_json();
const char* src_core_resources_game_resource_provider_missing_message_line_639_8fea0f4d_descriptor_json();
const char* src_core_resources_game_resource_provider_safe_path_size_line_645_ca4cce06_descriptor_json();
const char* src_core_resources_game_resource_provider_clean_text_line_654_ba113744_descriptor_json();
const char* src_core_resources_game_resource_provider_clean_restype_line_663_96e19284_descriptor_json();
const char* src_core_resources_game_resource_provider_clean_game_line_672_dc0cf339_descriptor_json();
const char* src_core_resources_game_resource_provider_manager_game_name_line_684_d824b250_descriptor_json();
const char* src_core_resources_game_resource_provider_manager_install_line_688_f11c7825_descriptor_json();
const char* src_core_resources_game_resource_provider_resource_manager_type_id_line_696_88dd7962_descriptor_json();
const char* src_core_resources_game_resource_provider_resource_manager_restype_line_706_feb4e7a7_descriptor_json();
const char* src_core_resources_game_resource_provider_known_resource_type_ids_line_715_dd065008_descriptor_json();
const char* src_gui_panels_qt_content_browser_panel_display_name_from_library_row_line_118_5539bae8_descriptor_json();
const char* src_gui_panels_qt_content_browser_panel_encoded_display_name_line_140_1ee739f0_descriptor_json();
const char* src_gui_panels_qt_content_browser_panel_player_display_name_line_199_41174031_descriptor_json();
const char* src_gui_panels_qt_content_browser_panel_party_display_name_line_219_ceed43bb_descriptor_json();
const char* src_gui_panels_qt_content_browser_panel_npc_display_name_line_240_75e1c40f_descriptor_json();
const char* src_gui_panels_qt_content_browser_panel_droid_display_name_line_273_d3645255_descriptor_json();
const char* src_gui_panels_qt_content_browser_panel_species_gender_display_name_line_284_37d95e21_descriptor_json();
const char* src_gui_panels_qt_content_browser_panel_party_variant_line_313_b078fc58_descriptor_json();
const char* src_gui_panels_qt_content_browser_panel_letter_or_number_variant_line_325_a22744e6_descriptor_json();
const char* src_gui_panels_qt_content_browser_panel_npc_variant_line_340_d2228373_descriptor_json();
const char* src_gui_panels_qt_content_browser_panel_with_variant_line_354_ccb0f27d_descriptor_json();
const char* src_gui_panels_qt_content_browser_panel_humanize_asset_name_line_364_1bad8caf_descriptor_json();
const char* src_gui_panels_qt_content_browser_panel_descriptor_from_library_row_line_417_7b1074c1_descriptor_json();
const char* src_gui_panels_qt_content_browser_panel_descriptor_from_animation_entry_line_473_6a4ce035_descriptor_json();
const char* src_gui_panels_qt_library_panel_looks_like_minigame_line_706_52da16d2_descriptor_json();
const char* src_gui_panels_qt_library_panel_category_sort_key_line_710_cf24a25a_descriptor_json();
const char* src_gui_panels_qt_library_panel_looks_like_party_member_line_717_ca92f23e_descriptor_json();
const char* src_gui_panels_qt_library_panel_looks_like_droid_line_721_3657b726_descriptor_json();
const char* src_gui_panels_qt_library_panel_looks_like_gui_or_menu_model_line_725_412b3e69_descriptor_json();
const char* src_gui_panels_qt_library_panel_looks_like_module_geometry_line_735_13bfdb98_descriptor_json();
const char* src_gui_panels_qt_library_panel_looks_like_module_minigame_piece_line_741_1acc9e03_descriptor_json();
const char* src_gui_panels_qt_library_panel_infer_model_category_line_745_cd03150d_descriptor_json();
const char* src_gui_panels_qt_library_panel_stripped_resource_token_line_885_e5cdb09e_descriptor_json();
const char* src_gui_panels_qt_library_panel_metadata_int_line_893_e73882a8_descriptor_json();
const char* src_gui_panels_qt_library_panel_subcategory_from_item_metadata_line_901_d8c23b50_descriptor_json();
const char* src_gui_panels_qt_library_panel_category_from_item_metadata_line_934_5068412a_descriptor_json();
const char* src_gui_panels_qt_library_panel_subcategory_from_door_metadata_line_941_d6219d40_descriptor_json();
const char* src_gui_panels_qt_library_panel_player_character_metadata_line_958_9d32c1ff_descriptor_json();
const char* src_gui_panels_qt_library_panel_party_member_metadata_line_997_c1c247a8_descriptor_json();
const char* src_gui_panels_qt_library_panel_commoner_metadata_line_1027_339c9395_descriptor_json();
const char* src_gui_panels_qt_library_panel_npc_metadata_line_1040_f6daba89_descriptor_json();
const char* src_gui_panels_qt_library_panel_droid_metadata_line_1138_6da28921_descriptor_json();
const char* src_gui_panels_qt_library_panel_creature_metadata_line_1155_2d01bbbd_descriptor_json();
const char* src_gui_panels_qt_library_panel_supermodel_metadata_line_1204_dd432d41_descriptor_json();
const char* src_gui_panels_qt_library_panel_turret_metadata_line_1217_e34f11de_descriptor_json();
const char* src_gui_panels_qt_library_panel_engine_item_metadata_line_1230_e7999c9e_descriptor_json();
const char* src_gui_panels_qt_library_panel_environment_metadata_line_1247_6cdb985e_descriptor_json();
const char* src_gui_panels_qt_library_panel_gui_metadata_line_1264_b7c2e2dc_descriptor_json();
const char* src_gui_panels_qt_library_panel_hologram_metadata_line_1289_221875cb_descriptor_json();
const char* src_gui_panels_qt_library_panel_level_asset_metadata_line_1304_9da927bf_descriptor_json();
const char* src_gui_panels_qt_library_panel_minigame_metadata_line_1327_d5293595_descriptor_json();
const char* src_gui_panels_qt_library_panel_menu_metadata_line_1342_fee6079d_descriptor_json();
const char* src_gui_panels_qt_library_panel_visual_fx_metadata_line_1351_eb94436c_descriptor_json();
const char* src_gui_panels_qt_library_panel_visual_metadata_line_1374_70b5a553_descriptor_json();
const char* src_gui_panels_qt_library_panel_planet_metadata_line_1397_319cabb3_descriptor_json();
const char* src_gui_panels_qt_library_panel_misc_model_metadata_line_1404_2cde7b2b_descriptor_json();
const char* src_gui_panels_qt_library_panel_stunt_metadata_line_1419_f3ad83c5_descriptor_json();
const char* src_gui_panels_qt_library_panel_infer_model_subcategory_line_1434_335a1205_descriptor_json();
const char* src_gui_panels_qt_library_panel_subcategory_sort_key_line_1645_e1868f2d_descriptor_json();
const char* src_gui_panels_qt_library_panel_content_browser_metadata_for_resref_line_1653_82928a38_descriptor_json();
const char* src_gui_panels_qt_library_panel_module_info_for_row_line_1729_04499754_descriptor_json();
const char* src_gui_panels_qt_library_panel_as_gff_dict_line_1738_67b9acc7_descriptor_json();
const char* src_gui_panels_qt_library_panel_template_field_text_line_1750_9ffe08e3_descriptor_json();
const char* src_gui_panels_qt_library_panel_template_model_candidates_line_1755_f89306d9_descriptor_json();
const char* src_gui_panels_qt_library_panel_door_model_candidates_line_1786_1b78da41_descriptor_json();
const char* src_gui_panels_qt_library_panel_template_metadata_index_for_game_line_1810_9ecd4628_descriptor_json();
const char* src_gui_panels_qt_library_panel_enrich_library_rows_with_resource_metadata_line_1893_d76cdcd1_descriptor_json();
const char* src_gui_panels_qt_library_panel_enrich_library_rows_line_1910_e1a3e5ac_descriptor_json();
const char* src_resources_game_detector_detect_kotor_dirs_line_59_58c316ed_descriptor_json();
const char* src_resources_game_detector_save_config_line_140_715b3b16_descriptor_json();
const char* src_resources_game_detector_load_config_line_159_231807ce_descriptor_json();
const char* src_resources_game_detector_list_all_candidates_line_172_cfdbd573_descriptor_json();
const char* src_resources_game_detector_is_kotor_dir_line_212_41b67c1f_descriptor_json();
const char* src_resources_game_detector_steam_library_paths_line_260_6ffd514b_descriptor_json();
const char* src_resources_game_detector_steam_candidates_line_324_c5aaa94d_descriptor_json();
const char* src_resources_game_detector_gog_candidates_line_369_7c4b8b65_descriptor_json();
const char* src_resources_game_detector_default_candidates_line_422_4e4dc2c4_descriptor_json();
const char* src_resources_game_detector_unique_paths_line_468_37e6a31e_descriptor_json();
const char* src_resources_game_detector_windows_drive_roots_line_484_9fabc71e_descriptor_json();
const char* src_resources_game_detector_registry_path_values_line_500_c1d5de92_descriptor_json();
const char* src_resources_game_detector_windows_registry_steam_roots_line_520_b845a039_descriptor_json();
const char* src_resources_game_detector_windows_registry_kotor_candidates_line_539_84aa7014_descriptor_json();
const char* src_resources_game_detector_windows_uninstall_kotor_candidates_line_568_2f969042_descriptor_json();
const char* src_resources_game_library_res_ext_line_125_0163fdc4_descriptor_json();
const char* src_resources_game_library_res_name_line_130_c437aa6c_descriptor_json();

const PythonFunctionDescriptorEntry* modulefunctions_descriptors(std::size_t& count);

} // namespace ghostrigger::phase15::ghostrigger_tools_contentbrowser
