#pragma once

#include <cstddef>

namespace ghostrigger::tools::contentbrowser {

#ifndef GHOSTRIGGER_TOOLS_CONTENTBROWSER_NATIVE_FUNCTION_IMPLEMENTATION_DEFINED
#define GHOSTRIGGER_TOOLS_CONTENTBROWSER_NATIVE_FUNCTION_IMPLEMENTATION_DEFINED
struct NativeFunctionImplementation {
    const char* project;
    const char* native_namespace;
    const char* python_file;
    const char* qualname;
    const char* callable_type;
    const char* implementation_status;
    bool native_first;
    bool python_runtime_required;
    bool python_fallback_allowed;
    const char* contract_json;
};
#endif // GHOSTRIGGER_TOOLS_CONTENTBROWSER_NATIVE_FUNCTION_IMPLEMENTATION_DEFINED

const NativeFunctionImplementation& coerce_resource_query_line_167_aa2b5698_native();
const NativeFunctionImplementation& restype_to_extension_line_435_d168dbf6_native();
const NativeFunctionImplementation& records_from_install_line_442_29a1399c_native();
const NativeFunctionImplementation& override_records_line_460_fa1405f7_native();
const NativeFunctionImplementation& erf_records_line_484_f262248d_native();
const NativeFunctionImplementation& bif_records_line_522_923b63b9_native();
const NativeFunctionImplementation& record_line_553_2745da10_native();
const NativeFunctionImplementation& record_matches_line_585_f4a92796_native();
const NativeFunctionImplementation& sort_records_line_602_cf3d7f84_native();
const NativeFunctionImplementation& dedupe_records_line_616_788f2d14_native();
const NativeFunctionImplementation& shadow_warnings_line_628_0fd0c506_native();
const NativeFunctionImplementation& missing_message_line_639_8fea0f4d_native();
const NativeFunctionImplementation& safe_path_size_line_645_ca4cce06_native();
const NativeFunctionImplementation& clean_text_line_654_ba113744_native();
const NativeFunctionImplementation& clean_restype_line_663_96e19284_native();
const NativeFunctionImplementation& clean_game_line_672_dc0cf339_native();
const NativeFunctionImplementation& manager_game_name_line_684_d824b250_native();
const NativeFunctionImplementation& manager_install_line_688_f11c7825_native();
const NativeFunctionImplementation& resource_manager_type_id_line_696_88dd7962_native();
const NativeFunctionImplementation& resource_manager_restype_line_706_feb4e7a7_native();
const NativeFunctionImplementation& known_resource_type_ids_line_715_dd065008_native();
const NativeFunctionImplementation& display_name_from_library_row_line_118_5539bae8_native();
const NativeFunctionImplementation& encoded_display_name_line_140_1ee739f0_native();
const NativeFunctionImplementation& player_display_name_line_199_41174031_native();
const NativeFunctionImplementation& party_display_name_line_219_ceed43bb_native();
const NativeFunctionImplementation& npc_display_name_line_240_75e1c40f_native();
const NativeFunctionImplementation& droid_display_name_line_273_d3645255_native();
const NativeFunctionImplementation& species_gender_display_name_line_284_37d95e21_native();
const NativeFunctionImplementation& party_variant_line_313_b078fc58_native();
const NativeFunctionImplementation& letter_or_number_variant_line_325_a22744e6_native();
const NativeFunctionImplementation& npc_variant_line_340_d2228373_native();
const NativeFunctionImplementation& with_variant_line_354_ccb0f27d_native();
const NativeFunctionImplementation& humanize_asset_name_line_364_1bad8caf_native();
const NativeFunctionImplementation& descriptor_from_library_row_line_417_7b1074c1_native();
const NativeFunctionImplementation& descriptor_from_animation_entry_line_473_6a4ce035_native();
const NativeFunctionImplementation& looks_like_minigame_line_706_52da16d2_native();
const NativeFunctionImplementation& category_sort_key_line_710_cf24a25a_native();
const NativeFunctionImplementation& looks_like_party_member_line_717_ca92f23e_native();
const NativeFunctionImplementation& looks_like_droid_line_721_3657b726_native();
const NativeFunctionImplementation& looks_like_gui_or_menu_model_line_725_412b3e69_native();
const NativeFunctionImplementation& looks_like_module_geometry_line_735_13bfdb98_native();
const NativeFunctionImplementation& looks_like_module_minigame_piece_line_741_1acc9e03_native();
const NativeFunctionImplementation& infer_model_category_line_745_cd03150d_native();
const NativeFunctionImplementation& stripped_resource_token_line_885_e5cdb09e_native();
const NativeFunctionImplementation& metadata_int_line_893_e73882a8_native();
const NativeFunctionImplementation& subcategory_from_item_metadata_line_901_d8c23b50_native();
const NativeFunctionImplementation& category_from_item_metadata_line_934_5068412a_native();
const NativeFunctionImplementation& subcategory_from_door_metadata_line_941_d6219d40_native();
const NativeFunctionImplementation& player_character_metadata_line_958_9d32c1ff_native();
const NativeFunctionImplementation& party_member_metadata_line_997_c1c247a8_native();
const NativeFunctionImplementation& commoner_metadata_line_1027_339c9395_native();
const NativeFunctionImplementation& npc_metadata_line_1040_f6daba89_native();
const NativeFunctionImplementation& droid_metadata_line_1138_6da28921_native();
const NativeFunctionImplementation& creature_metadata_line_1155_2d01bbbd_native();
const NativeFunctionImplementation& supermodel_metadata_line_1204_dd432d41_native();
const NativeFunctionImplementation& turret_metadata_line_1217_e34f11de_native();
const NativeFunctionImplementation& engine_item_metadata_line_1230_e7999c9e_native();
const NativeFunctionImplementation& environment_metadata_line_1247_6cdb985e_native();
const NativeFunctionImplementation& gui_metadata_line_1264_b7c2e2dc_native();
const NativeFunctionImplementation& hologram_metadata_line_1289_221875cb_native();
const NativeFunctionImplementation& level_asset_metadata_line_1304_9da927bf_native();
const NativeFunctionImplementation& minigame_metadata_line_1327_d5293595_native();
const NativeFunctionImplementation& menu_metadata_line_1342_fee6079d_native();
const NativeFunctionImplementation& visual_fx_metadata_line_1351_eb94436c_native();
const NativeFunctionImplementation& visual_metadata_line_1374_70b5a553_native();
const NativeFunctionImplementation& planet_metadata_line_1397_319cabb3_native();
const NativeFunctionImplementation& misc_model_metadata_line_1404_2cde7b2b_native();
const NativeFunctionImplementation& stunt_metadata_line_1419_f3ad83c5_native();
const NativeFunctionImplementation& infer_model_subcategory_line_1434_335a1205_native();
const NativeFunctionImplementation& subcategory_sort_key_line_1645_e1868f2d_native();
const NativeFunctionImplementation& content_browser_metadata_for_resref_line_1653_82928a38_native();
const NativeFunctionImplementation& module_info_for_row_line_1729_04499754_native();
const NativeFunctionImplementation& as_gff_dict_line_1738_67b9acc7_native();
const NativeFunctionImplementation& template_field_text_line_1750_9ffe08e3_native();
const NativeFunctionImplementation& template_model_candidates_line_1755_f89306d9_native();
const NativeFunctionImplementation& door_model_candidates_line_1786_1b78da41_native();
const NativeFunctionImplementation& template_metadata_index_for_game_line_1810_9ecd4628_native();
const NativeFunctionImplementation& enrich_library_rows_with_resource_metadata_line_1893_d76cdcd1_native();
const NativeFunctionImplementation& enrich_library_rows_line_1910_e1a3e5ac_native();
const NativeFunctionImplementation& detect_kotor_dirs_line_59_58c316ed_native();
const NativeFunctionImplementation& save_config_line_140_715b3b16_native();
const NativeFunctionImplementation& load_config_line_159_231807ce_native();
const NativeFunctionImplementation& list_all_candidates_line_172_cfdbd573_native();
const NativeFunctionImplementation& is_kotor_dir_line_212_41b67c1f_native();
const NativeFunctionImplementation& steam_library_paths_line_260_6ffd514b_native();
const NativeFunctionImplementation& steam_candidates_line_324_c5aaa94d_native();
const NativeFunctionImplementation& gog_candidates_line_369_7c4b8b65_native();
const NativeFunctionImplementation& default_candidates_line_422_4e4dc2c4_native();
const NativeFunctionImplementation& unique_paths_line_468_37e6a31e_native();
const NativeFunctionImplementation& windows_drive_roots_line_484_9fabc71e_native();
const NativeFunctionImplementation& registry_path_values_line_500_c1d5de92_native();
const NativeFunctionImplementation& windows_registry_steam_roots_line_520_b845a039_native();
const NativeFunctionImplementation& windows_registry_kotor_candidates_line_539_84aa7014_native();
const NativeFunctionImplementation& windows_uninstall_kotor_candidates_line_568_2f969042_native();
const NativeFunctionImplementation& res_ext_line_125_0163fdc4_native();
const NativeFunctionImplementation& res_name_line_130_c437aa6c_native();

const NativeFunctionImplementation* modulefunctions_native_functions(std::size_t& count);

} // namespace ghostrigger::tools::contentbrowser
