#pragma once

#include <cstddef>

namespace ghostrigger::phase15::ghostrigger_native_nativecore_diagnostics {

using PythonFunctionDescriptorJson = const char* (*)();

struct PythonFunctionDescriptorEntry {
    const char* python_file;
    const char* qualname;
    const char* function_type;
    PythonFunctionDescriptorJson descriptor_json;
};

const char* src_adapters_rendering_gpu_diagnostics_exports_getattr_line_139_8e4ea95a_descriptor_json();
const char* src_adapters_rendering_gpu_diagnostics_exports_dir_line_148_2084c3bf_descriptor_json();
const char* src_core_diagnostics_diagnostics_set_sentinel_dir_line_44_8ae827ec_descriptor_json();
const char* src_core_diagnostics_diagnostics_log_mdl_header_line_55_555985b6_descriptor_json();
const char* src_core_diagnostics_diagnostics_validate_mdl_preconditions_line_141_b19c0b38_descriptor_json();
const char* src_core_diagnostics_diagnostics_load_timer_line_184_838b14f5_descriptor_json();
const char* src_core_diagnostics_diagnostics_log_model_summary_line_210_51f13b57_descriptor_json();
const char* src_core_diagnostics_diagnostics_log_model_anomalies_line_260_d81498cb_descriptor_json();
const char* src_core_diagnostics_diagnostics_log_render_error_line_355_8784dfa8_descriptor_json();
const char* src_core_diagnostics_diagnostics_check_main_thread_line_390_c935d866_descriptor_json();
const char* src_core_diagnostics_diagnostics_log_thread_violation_line_406_d1d6f04c_descriptor_json();
const char* src_core_diagnostics_diagnostics_log_texture_resolution_line_424_15424580_descriptor_json();
const char* src_core_diagnostics_diagnostics_log_crash_report_line_456_4d715750_descriptor_json();
const char* src_core_diagnostics_diagnostics_write_crash_sentinel_line_517_62a85bcd_descriptor_json();
const char* src_core_diagnostics_diagnostics_run_model_diagnostics_line_545_133f9b6e_descriptor_json();
const char* src_core_diagnostics_diagnostics_log_session_start_line_678_715dbbf7_descriptor_json();
const char* src_core_diagnostics_diagnostics_report_old_sentinels_line_717_8dd23cec_descriptor_json();
const char* src_core_diagnostics_module_reference_safety_module_from_input_line_119_8faf9ef8_descriptor_json();
const char* src_core_diagnostics_module_reference_safety_normalise_resref_line_123_5bfdaeb7_descriptor_json();
const char* src_core_diagnostics_module_reference_safety_normalise_restype_line_132_5c829799_descriptor_json();
const char* src_core_diagnostics_module_reference_safety_record_key_line_136_d01ddfdd_descriptor_json();
const char* src_core_diagnostics_module_reference_safety_resources_from_input_line_149_50bc7de0_descriptor_json();
const char* src_core_diagnostics_module_reference_safety_available_index_line_162_9dfee9c1_descriptor_json();
const char* src_core_diagnostics_module_reference_safety_git_raw_line_196_a688d5a0_descriptor_json();
const char* src_core_diagnostics_module_reference_safety_core_raw_line_203_6ab0a473_descriptor_json();
const char* src_core_diagnostics_module_reference_safety_raw_list_line_213_a7111a0b_descriptor_json();
const char* src_core_diagnostics_module_reference_safety_script_field_line_221_fa440c9a_descriptor_json();
const char* src_core_diagnostics_module_reference_safety_dialog_field_line_226_58535f64_descriptor_json();
const char* src_core_diagnostics_module_reference_safety_iter_script_dialog_refs_line_230_de4ac179_descriptor_json();
const char* src_core_diagnostics_module_reference_safety_collect_module_references_line_260_b7f6bfe1_descriptor_json();
const char* src_core_diagnostics_module_reference_safety_has_reference_line_291_462c6d98_descriptor_json();
const char* src_core_diagnostics_module_reference_safety_issue_for_missing_line_309_e4fe892b_descriptor_json();
const char* src_core_diagnostics_module_reference_safety_validate_module_references_line_344_44437eb2_descriptor_json();
const char* src_core_diagnostics_validation_service_validate_scene_line_462_4978dd75_descriptor_json();
const char* src_core_rendering_gpu_diagnostics_config_path_from_env_line_19_14f3c397_descriptor_json();
const char* src_core_rendering_gpu_diagnostics_config_int_env_clamped_line_23_d561e4b4_descriptor_json();
const char* src_core_rendering_gpu_diagnostics_config_gl_state_trace_path_line_31_dc7a1b70_descriptor_json();
const char* src_core_rendering_gpu_diagnostics_config_lm_data_dump_path_line_35_42ca528c_descriptor_json();
const char* src_core_rendering_gpu_diagnostics_config_skin_dump_path_line_39_fe55d8b8_descriptor_json();
const char* src_core_rendering_gpu_diagnostics_config_debug_visualize_mode_line_43_5b215ffd_descriptor_json();
const char* src_core_rendering_gpu_diagnostics_config_lm_composite_mode_line_47_d363b831_descriptor_json();
const char* src_core_rendering_gpu_diagnostics_records_jsonable_gl_value_line_34_1ede079b_descriptor_json();
const char* src_core_rendering_gpu_diagnostics_records_safe_gl_attr_line_46_f3c09db3_descriptor_json();
const char* src_core_rendering_gpu_diagnostics_records_uniform_trace_value_line_53_a664db23_descriptor_json();
const char* src_core_rendering_gpu_diagnostics_records_build_gl_state_trace_record_line_63_661c5f41_descriptor_json();
const char* src_core_rendering_gpu_diagnostics_records_append_gl_state_trace_line_124_86a67054_descriptor_json();
const char* src_core_rendering_gpu_diagnostics_records_first_uv_pairs_line_135_da46e2f2_descriptor_json();
const char* src_core_rendering_gpu_diagnostics_records_first_vbo_uv_pairs_line_145_8a1604a1_descriptor_json();
const char* src_core_rendering_gpu_diagnostics_records_texture_content_stats_line_155_f01bae93_descriptor_json();
const char* src_core_rendering_gpu_diagnostics_records_lightmap_role_info_line_209_0ccec99b_descriptor_json();
const char* src_core_rendering_gpu_diagnostics_records_build_lm_data_dump_record_line_248_50e702ce_descriptor_json();
const char* src_core_rendering_gpu_diagnostics_records_append_jsonl_record_line_295_860d61fe_descriptor_json();
const char* src_core_rendering_gpu_diagnostics_records_matrix4_json_line_306_ba4cf4dd_descriptor_json();
const char* src_core_rendering_gpu_diagnostics_records_matrix4_inverse_json_line_315_0b488bbd_descriptor_json();
const char* src_core_rendering_gpu_diagnostics_records_matrix4_mul_json_line_324_613234fd_descriptor_json();
const char* src_core_rendering_gpu_diagnostics_records_matrix4_det_value_line_333_10bbe3a5_descriptor_json();
const char* src_core_rendering_gpu_diagnostics_records_uploaded_palette_array_from_uploader_line_342_fddf1b89_descriptor_json();
const char* src_core_rendering_gpu_diagnostics_records_homogeneous_position_json_line_358_ac991133_descriptor_json();
const char* src_core_rendering_gpu_diagnostics_records_first_divergence_stage_line_369_c7da1b20_descriptor_json();
const char* src_core_rendering_gpu_diagnostics_records_matrix_max_abs_delta_line_383_59f01372_descriptor_json();
const char* src_core_rendering_gpu_diagnostics_records_matrix_translation_norm_line_394_e64780c0_descriptor_json();
const char* src_core_rendering_gpu_diagnostics_records_matrix_rotation_only_line_407_b4c89a01_descriptor_json();
const char* src_core_rendering_gpu_diagnostics_records_qbone_inverse_bind_json_line_423_dc625269_descriptor_json();
const char* src_core_rendering_gpu_diagnostics_records_qbone_direct_bind_json_line_452_87c34f93_descriptor_json();
const char* src_core_rendering_gpu_diagnostics_records_qbone_matrix_np_line_465_e2e68a5e_descriptor_json();
const char* src_core_rendering_gpu_diagnostics_records_node_world_matrix_for_pose_np_line_485_d8054911_descriptor_json();
const char* src_core_rendering_gpu_diagnostics_records_node_pose_chain_records_line_513_2a4aab68_descriptor_json();
const char* src_core_rendering_gpu_diagnostics_records_quat_xyzw_to_mat4_np_line_534_d9a3b5ee_descriptor_json();
const char* src_core_rendering_gpu_diagnostics_records_xoreos_first_frame_orientation_matrix_line_557_fce39b4e_descriptor_json();
const char* src_core_rendering_gpu_diagnostics_records_skin_3g_matrix_for_formula_line_618_9cc7f336_descriptor_json();
const char* src_core_rendering_gpu_diagnostics_records_skin_3g_role_for_bone_line_666_95ed8883_descriptor_json();
const char* src_core_rendering_gpu_diagnostics_records_skin_3g_role_priority_line_679_301987b6_descriptor_json();
const char* src_core_rendering_gpu_diagnostics_records_select_skin_3g_probe_vertices_line_704_12e70976_descriptor_json();
const char* src_core_rendering_gpu_diagnostics_records_skin_bind_equivalence_record_line_732_e3864866_descriptor_json();
const char* src_core_rendering_gpu_diagnostics_records_skin_3g_candidate_records_line_765_95075d52_descriptor_json();
const char* src_core_rendering_gpu_diagnostics_records_skin_live_slot_records_line_1233_88a63431_descriptor_json();
const char* src_core_rendering_gpu_diagnostics_records_build_skin_dump_record_line_1336_1e8ff3a1_descriptor_json();
const char* src_core_rendering_gpu_diagnostics_records_pose_node_transform_line_1669_c2989b35_descriptor_json();
const char* src_core_rendering_gpu_diagnostics_records_select_skin_probe_vertex_line_1687_bc6f7e2f_descriptor_json();
const char* src_core_rendering_gpu_diagnostics_records_node_parent_chain_names_line_1703_3065b3a0_descriptor_json();
const char* src_core_rendering_gpu_diagnostics_records_node_uses_single_tile_atlas_line_1712_7c035216_descriptor_json();
const char* src_core_rendering_gpu_diagnostics_records_should_auto_clamp_diffuse_line_1731_1c306c28_descriptor_json();

const PythonFunctionDescriptorEntry* modulefunctions_descriptors(std::size_t& count);

} // namespace ghostrigger::phase15::ghostrigger_native_nativecore_diagnostics
