#pragma once

#include <cstddef>

namespace ghostrigger::core::tools::pivotcontrols {

#ifndef GHOSTRIGGER_TOOLS_PIVOTCONTROLS_NATIVE_FUNCTION_IMPLEMENTATION_DEFINED
#define GHOSTRIGGER_TOOLS_PIVOTCONTROLS_NATIVE_FUNCTION_IMPLEMENTATION_DEFINED
struct NativeFunctionImplementation {
    const char* project;
    const char* native_namespace;
    const char* python_file;
    const char* qualname;
    const char* callable_type;
    const char* implementation_status;
    bool native_first;
    bool python_runtime_required;
    bool python_fallback_allowed;
    const char* contract_json;
};
#endif // GHOSTRIGGER_TOOLS_PIVOTCONTROLS_NATIVE_FUNCTION_IMPLEMENTATION_DEFINED

const NativeFunctionImplementation& transformcontroller_construct_line_39_50939a96_native();
const NativeFunctionImplementation& transformcontroller_snapshot_line_60_9f1c704a_native();
const NativeFunctionImplementation& transformcontroller_set_position_snap_line_86_cf91bb6b_native();
const NativeFunctionImplementation& transformcontroller_begin_drag_line_93_d91f3ce1_native();
const NativeFunctionImplementation& transformcontroller_drag_line_115_b61c076a_native();
const NativeFunctionImplementation& transformcontroller_apply_translate_line_127_0fbf0075_native();
const NativeFunctionImplementation& transformcontroller_apply_view_translate_line_181_aa686c4b_native();
const NativeFunctionImplementation& transformcontroller_apply_rotate_line_225_fb3c1c0d_native();
const NativeFunctionImplementation& transformcontroller_apply_scale_line_253_d0840c2f_native();
const NativeFunctionImplementation& transformcontroller_cancel_line_329_299df350_native();
const NativeFunctionImplementation& transformcontroller_end_drag_line_335_6d85d24f_native();
const NativeFunctionImplementation& transformcontroller_restore_line_342_1b53854f_native();
const NativeFunctionImplementation& transformcontroller_invalidate_line_364_e38981a7_native();
const NativeFunctionImplementation& transformcontroller_apply_light_scale_line_368_4d83d6d5_native();
const NativeFunctionImplementation& transformcontroller_apply_camera_scale_line_392_81775637_native();
const NativeFunctionImplementation& transformgizmo_construct_line_14_a9df9afb_native();
const NativeFunctionImplementation& transformgizmo_set_selected_object_line_35_2fe16a2b_native();
const NativeFunctionImplementation& transformgizmo_set_selected_objects_line_39_5056a6e3_native();
const NativeFunctionImplementation& transformgizmo_clear_selection_line_44_709ea6a0_native();
const NativeFunctionImplementation& transformgizmo_cycle_mode_line_52_647d8f31_native();
const NativeFunctionImplementation& transformgizmo_set_mode_line_58_6aa46899_native();
const NativeFunctionImplementation& transformgizmo_update_from_selection_line_62_608ad04e_native();
const NativeFunctionImplementation& transformgizmo_update_from_object_transform_line_98_58d66d54_native();
const NativeFunctionImplementation& transformgizmo_get_gizmo_origin_world_line_101_b1909cb5_native();
const NativeFunctionImplementation& transformgizmo_get_gizmo_orientation_matrix_line_105_0820e329_native();
const NativeFunctionImplementation& transformgizmo_get_gizmo_scale_for_camera_line_112_7e491cf8_native();
const NativeFunctionImplementation& transformgizmo_begin_drag_line_115_f58a8495_native();
const NativeFunctionImplementation& transformgizmo_drag_line_130_26d16200_native();
const NativeFunctionImplementation& transformgizmo_end_drag_line_134_8582966a_native();
const NativeFunctionImplementation& transformgizmo_cancel_drag_line_140_ae2279af_native();
const NativeFunctionImplementation& transformgizmo_draw_line_145_df47d660_native();
const NativeFunctionImplementation& transformgizmo_build_render_data_line_153_8ddf70d2_native();
const NativeFunctionImplementation& transformgizmo_hit_test_line_161_fcd24e7d_native();
const NativeFunctionImplementation& transformreferencecontroller_construct_line_98_fb543c88_native();
const NativeFunctionImplementation& transformreferencecontroller_set_axis_mode_line_103_2955bef9_native();
const NativeFunctionImplementation& transformreferencecontroller_get_axis_mode_line_109_3e8b0906_native();
const NativeFunctionImplementation& transformreferencecontroller_get_transform_basis_line_112_787c9f27_native();
const NativeFunctionImplementation& transformreferencecontroller_get_gizmo_orientation_line_132_f1e2319a_native();
const NativeFunctionImplementation& transformreferencecontroller_resolve_pick_reference_line_135_9bf0d575_native();
const NativeFunctionImplementation& transformreferencecontroller_clear_pick_reference_line_139_515a9c4c_native();
const NativeFunctionImplementation& transformreferencecontroller_picked_reference_line_142_ad668aad_native();
const NativeFunctionImplementation& transformreferencecontroller_set_working_basis_line_145_a5b720a0_native();
const NativeFunctionImplementation& transformreferencecontroller_object_basis_line_148_d7d6708d_native();
const NativeFunctionImplementation& transformreferencecontroller_reference_is_deleted_line_159_633805a7_native();
const NativeFunctionImplementation& adjustpivotpanel_construct_line_16_5db61efa_native();
const NativeFunctionImplementation& adjustpivotpanel_build_line_27_9f7fe03b_native();
const NativeFunctionImplementation& adjustpivotpanel_tool_button_line_82_e8423a9e_native();
const NativeFunctionImplementation& adjustpivotpanel_emit_pivot_mode_if_checked_line_95_1fe9e28a_native();
const NativeFunctionImplementation& adjustpivotpanel_set_pivot_mode_line_99_8f28a351_native();
const NativeFunctionImplementation& adjustpivotpanel_set_selection_state_line_106_fc4f1042_native();
const NativeFunctionImplementation& adjustpivotpanel_apply_ghost_theme_line_125_d6a3ef80_native();
const NativeFunctionImplementation& adjustpivotpanel_apply_ghost_layout_line_130_23e64942_native();
const NativeFunctionImplementation& axismodecontrol_construct_line_15_f6f7c143_native();
const NativeFunctionImplementation& axismodecontrol_build_line_20_97739904_native();
const NativeFunctionImplementation& axismodecontrol_axis_mode_line_35_0dc305b9_native();
const NativeFunctionImplementation& axismodecontrol_set_axis_mode_line_38_53f4b6b4_native();
const NativeFunctionImplementation& axismodecontrol_emit_mode_line_50_11daaee6_native();
const NativeFunctionImplementation& axismodecontrol_apply_ghost_theme_line_58_62a2fef0_native();
const NativeFunctionImplementation& axismodecontrol_apply_ghost_layout_line_72_9baa2461_native();

const NativeFunctionImplementation* instancemethods_native_functions(std::size_t& count);

} // namespace ghostrigger::core::tools::pivotcontrols
