#pragma once

#include <cstddef>

namespace ghostrigger::runtime::core::host::shared::descriptors {

#ifndef GHOSTRIGGER_RUNTIME_SHARED_DESCRIPTORS_NATIVE_FUNCTION_IMPLEMENTATION_DEFINED
#define GHOSTRIGGER_RUNTIME_SHARED_DESCRIPTORS_NATIVE_FUNCTION_IMPLEMENTATION_DEFINED
struct NativeFunctionImplementation {
    const char* project;
    const char* native_namespace;
    const char* python_file;
    const char* qualname;
    const char* callable_type;
    const char* implementation_status;
    bool native_first;
    bool python_runtime_required;
    bool python_fallback_allowed;
    const char* contract_json;
};
#endif // GHOSTRIGGER_RUNTIME_SHARED_DESCRIPTORS_NATIVE_FUNCTION_IMPLEMENTATION_DEFINED

const NativeFunctionImplementation& vbo_builder_line_20_92b405a6_native();
const NativeFunctionImplementation& iter_mesh_render_data_line_28_ef5528d1_native();
const NativeFunctionImplementation& extract_node_arrays_line_33_a10d76a2_native();
const NativeFunctionImplementation& getattr_line_38_e5b7d284_native();
const NativeFunctionImplementation& dir_line_46_405f5132_native();
const NativeFunctionImplementation& clean_optional_text_line_25_9d764858_native();
const NativeFunctionImplementation& iter_mesh_render_data_line_65_fa47e988_native();
const NativeFunctionImplementation& model_nodes_line_211_661ae3a2_native();
const NativeFunctionImplementation& node_is_renderable_mesh_line_225_e3ba8c3b_native();
const NativeFunctionImplementation& extract_node_arrays_line_239_41751f47_native();
const NativeFunctionImplementation& skinned_lbs_vbo_cache_key_line_326_3546a59b_native();
const NativeFunctionImplementation& static_vbo_cache_key_line_346_d5eafd23_native();
const NativeFunctionImplementation& get_skinned_lbs_vbo_cache_line_362_d6f98c35_native();
const NativeFunctionImplementation& set_skinned_lbs_vbo_cache_line_374_25580cd0_native();
const NativeFunctionImplementation& smooth_render_normals_line_383_3400ba22_native();
const NativeFunctionImplementation& coerce_normal_array_line_440_fec0c1af_native();
const NativeFunctionImplementation& area_weighted_normal_accum_line_460_c1f111bb_native();
const NativeFunctionImplementation& normalize_rows_line_487_a0d58bc1_native();
const NativeFunctionImplementation& extract_skinning_line_507_5c8210f3_native();
const NativeFunctionImplementation& bas_attachment_palette_model_for_node_line_552_e008b162_native();
const NativeFunctionImplementation& mesh_model_matrix_for_node_line_579_7a36d755_native();
const NativeFunctionImplementation& bas_attachment_subtree_nodes_line_590_c7e0370e_native();
const NativeFunctionImplementation& texture_image_to_rgba8_line_604_dba24dc9_native();
const NativeFunctionImplementation& node_uv_array_line_627_f48a4217_native();
const NativeFunctionImplementation& material_data_line_652_f91a8721_native();
const NativeFunctionImplementation& texture_data_line_718_f11f351f_native();
const NativeFunctionImplementation& node_has_lightmap_line_739_ec27445f_native();
const NativeFunctionImplementation& alpha_mode_line_751_5b17aae8_native();
const NativeFunctionImplementation& blend_mode_line_770_7ad06fd8_native();
const NativeFunctionImplementation& sprite_alpha_source_line_788_1fbd6397_native();
const NativeFunctionImplementation& sprite_glow_line_800_fffe5bfb_native();
const NativeFunctionImplementation& is_saber_hilt_line_813_8bbed6e1_native();
const NativeFunctionImplementation& has_sprite_material_override_line_823_ce0579b4_native();
const NativeFunctionImplementation& node_world_transform_line_832_8a0acaf4_native();
const NativeFunctionImplementation& node_world_matrix_line_855_b56aeb9c_native();
const NativeFunctionImplementation& bas_attachment_root_for_node_line_881_fc1375c3_native();
const NativeFunctionImplementation& bas_attachment_effective_pose_for_node_line_892_2964cc0a_native();
const NativeFunctionImplementation& bas_attachment_socket_node_line_952_c843adcc_native();
const NativeFunctionImplementation& bas_attachment_world_transform_line_975_5e5d0edc_native();
const NativeFunctionImplementation& bas_attachment_pose_mode_for_root_line_1037_ad40b926_native();
const NativeFunctionImplementation& bas_attachment_pose_applies_to_root_line_1056_fda3d3ac_native();
const NativeFunctionImplementation& bas_head_attachment_has_inherited_pose_tracks_line_1060_58a53a90_native();
const NativeFunctionImplementation& bas_inherited_head_pose_node_allowed_line_1086_36e30abb_native();
const NativeFunctionImplementation& bas_head_attachment_local_pose_node_allowed_name_line_1091_0259f1df_native();
const NativeFunctionImplementation& pose_node_for_transform_line_1106_d54c4f76_native();
const NativeFunctionImplementation& bas_attachment_local_transform_line_1124_852c5d58_native();
const NativeFunctionImplementation& animated_node_world_transform_line_1166_122268f5_native();
const NativeFunctionImplementation& material_color_line_1252_3c10f578_native();
const NativeFunctionImplementation& node_revision_line_1263_37f8d7bd_native();
const NativeFunctionImplementation& clamp01_line_1271_5850941f_native();
const NativeFunctionImplementation& clean_tex_name_line_1275_04a02cb4_native();
const NativeFunctionImplementation& build_skeleton_render_data_line_80_8beff479_native();
const NativeFunctionImplementation& cached_world_position_resolver_line_177_96f3e227_native();
const NativeFunctionImplementation& extract_skinning_arrays_line_223_4676a091_native();
const NativeFunctionImplementation& cpu_skin_vbo_arrays_line_299_8baa9173_native();
const NativeFunctionImplementation& bas_attachment_root_local_skin_palette_line_375_3fcd25db_native();
const NativeFunctionImplementation& bas_attachment_source_local_root_matrix_line_400_6cd81f41_native();
const NativeFunctionImplementation& skin_palette_flat_bytes_line_434_c134d52b_native();
const NativeFunctionImplementation& cached_matrix_palette_uploader_line_455_58be21bd_native();
const NativeFunctionImplementation& skinning_palette_model_for_node_line_476_193696ae_native();
const NativeFunctionImplementation& matrix_palette_uploader_cache_key_line_489_d2f67a8f_native();
const NativeFunctionImplementation& cpu_skin_positions_line_522_a4e14052_native();
const NativeFunctionImplementation& normalize_weight_rows_line_568_82ae484d_native();
const NativeFunctionImplementation& model_nodes_line_580_f434f2db_native();
const NativeFunctionImplementation& is_bone_node_line_587_82644d7b_native();
const NativeFunctionImplementation& nearest_bone_ancestor_line_602_56a86531_native();
const NativeFunctionImplementation& node_world_position_line_616_f9fdec7f_native();
const NativeFunctionImplementation& animated_world_position_line_634_d88f7518_native();
const NativeFunctionImplementation& distance_line_671_272ee1dd_native();
const NativeFunctionImplementation& bone_colour_hint_line_677_18d8061f_native();
const NativeFunctionImplementation& skin_revision_line_687_806e2dee_native();
const NativeFunctionImplementation& root_model_from_node_line_699_94251bf8_native();
const NativeFunctionImplementation& vec3_line_10_91771333_native();

const NativeFunctionImplementation* modulefunctions_native_functions(std::size_t& count);

} // namespace ghostrigger::runtime::core::host::shared::descriptors
