#pragma once

#include <cstddef>

namespace ghostrigger::phase15::ghostrigger_runtime_shared_descriptors {

using PythonFunctionDescriptorJson = const char* (*)();

struct PythonFunctionDescriptorEntry {
    const char* python_file;
    const char* qualname;
    const char* function_type;
    PythonFunctionDescriptorJson descriptor_json;
};

const char* src_adapters_rendering_mesh_render_data_vbo_builder_line_20_92b405a6_descriptor_json();
const char* src_adapters_rendering_mesh_render_data_iter_mesh_render_data_line_28_ef5528d1_descriptor_json();
const char* src_adapters_rendering_mesh_render_data_extract_node_arrays_line_33_a10d76a2_descriptor_json();
const char* src_adapters_rendering_mesh_render_data_getattr_line_38_e5b7d284_descriptor_json();
const char* src_adapters_rendering_mesh_render_data_dir_line_46_405f5132_descriptor_json();
const char* src_core_project_resource_address_clean_optional_text_line_25_9d764858_descriptor_json();
const char* src_core_rendering_mesh_render_data_iter_mesh_render_data_line_65_fa47e988_descriptor_json();
const char* src_core_rendering_mesh_render_data_model_nodes_line_211_661ae3a2_descriptor_json();
const char* src_core_rendering_mesh_render_data_node_is_renderable_mesh_line_225_e3ba8c3b_descriptor_json();
const char* src_core_rendering_mesh_render_data_extract_node_arrays_line_239_41751f47_descriptor_json();
const char* src_core_rendering_mesh_render_data_skinned_lbs_vbo_cache_key_line_326_3546a59b_descriptor_json();
const char* src_core_rendering_mesh_render_data_static_vbo_cache_key_line_346_d5eafd23_descriptor_json();
const char* src_core_rendering_mesh_render_data_get_skinned_lbs_vbo_cache_line_362_d6f98c35_descriptor_json();
const char* src_core_rendering_mesh_render_data_set_skinned_lbs_vbo_cache_line_374_25580cd0_descriptor_json();
const char* src_core_rendering_mesh_render_data_smooth_render_normals_line_383_3400ba22_descriptor_json();
const char* src_core_rendering_mesh_render_data_coerce_normal_array_line_440_fec0c1af_descriptor_json();
const char* src_core_rendering_mesh_render_data_area_weighted_normal_accum_line_460_c1f111bb_descriptor_json();
const char* src_core_rendering_mesh_render_data_normalize_rows_line_487_a0d58bc1_descriptor_json();
const char* src_core_rendering_mesh_render_data_extract_skinning_line_507_5c8210f3_descriptor_json();
const char* src_core_rendering_mesh_render_data_bas_attachment_palette_model_for_node_line_552_e008b162_descriptor_json();
const char* src_core_rendering_mesh_render_data_mesh_model_matrix_for_node_line_579_7a36d755_descriptor_json();
const char* src_core_rendering_mesh_render_data_bas_attachment_subtree_nodes_line_590_c7e0370e_descriptor_json();
const char* src_core_rendering_mesh_render_data_texture_image_to_rgba8_line_604_dba24dc9_descriptor_json();
const char* src_core_rendering_mesh_render_data_node_uv_array_line_627_f48a4217_descriptor_json();
const char* src_core_rendering_mesh_render_data_material_data_line_652_f91a8721_descriptor_json();
const char* src_core_rendering_mesh_render_data_texture_data_line_718_f11f351f_descriptor_json();
const char* src_core_rendering_mesh_render_data_node_has_lightmap_line_739_ec27445f_descriptor_json();
const char* src_core_rendering_mesh_render_data_alpha_mode_line_751_5b17aae8_descriptor_json();
const char* src_core_rendering_mesh_render_data_blend_mode_line_770_7ad06fd8_descriptor_json();
const char* src_core_rendering_mesh_render_data_sprite_alpha_source_line_788_1fbd6397_descriptor_json();
const char* src_core_rendering_mesh_render_data_sprite_glow_line_800_fffe5bfb_descriptor_json();
const char* src_core_rendering_mesh_render_data_is_saber_hilt_line_813_8bbed6e1_descriptor_json();
const char* src_core_rendering_mesh_render_data_has_sprite_material_override_line_823_ce0579b4_descriptor_json();
const char* src_core_rendering_mesh_render_data_node_world_transform_line_832_8a0acaf4_descriptor_json();
const char* src_core_rendering_mesh_render_data_node_world_matrix_line_855_b56aeb9c_descriptor_json();
const char* src_core_rendering_mesh_render_data_bas_attachment_root_for_node_line_881_fc1375c3_descriptor_json();
const char* src_core_rendering_mesh_render_data_bas_attachment_effective_pose_for_node_line_892_2964cc0a_descriptor_json();
const char* src_core_rendering_mesh_render_data_bas_attachment_socket_node_line_952_c843adcc_descriptor_json();
const char* src_core_rendering_mesh_render_data_bas_attachment_world_transform_line_975_5e5d0edc_descriptor_json();
const char* src_core_rendering_mesh_render_data_bas_attachment_pose_mode_for_root_line_1037_ad40b926_descriptor_json();
const char* src_core_rendering_mesh_render_data_bas_attachment_pose_applies_to_root_line_1056_fda3d3ac_descriptor_json();
const char* src_core_rendering_mesh_render_data_bas_head_attachment_has_inherited_pose_tracks_line_1060_58a53a90_descriptor_json();
const char* src_core_rendering_mesh_render_data_bas_inherited_head_pose_node_allowed_line_1086_36e30abb_descriptor_json();
const char* src_core_rendering_mesh_render_data_bas_head_attachment_local_pose_node_allowed_name_line_1091_0259f1df_descriptor_json();
const char* src_core_rendering_mesh_render_data_pose_node_for_transform_line_1106_d54c4f76_descriptor_json();
const char* src_core_rendering_mesh_render_data_bas_attachment_local_transform_line_1124_852c5d58_descriptor_json();
const char* src_core_rendering_mesh_render_data_animated_node_world_transform_line_1166_122268f5_descriptor_json();
const char* src_core_rendering_mesh_render_data_material_color_line_1252_3c10f578_descriptor_json();
const char* src_core_rendering_mesh_render_data_node_revision_line_1263_37f8d7bd_descriptor_json();
const char* src_core_rendering_mesh_render_data_clamp01_line_1271_5850941f_descriptor_json();
const char* src_core_rendering_mesh_render_data_clean_tex_name_line_1275_04a02cb4_descriptor_json();
const char* src_core_rendering_skeleton_render_data_build_skeleton_render_data_line_80_8beff479_descriptor_json();
const char* src_core_rendering_skeleton_render_data_cached_world_position_resolver_line_177_96f3e227_descriptor_json();
const char* src_core_rendering_skeleton_render_data_extract_skinning_arrays_line_223_4676a091_descriptor_json();
const char* src_core_rendering_skeleton_render_data_cpu_skin_vbo_arrays_line_299_8baa9173_descriptor_json();
const char* src_core_rendering_skeleton_render_data_bas_attachment_root_local_skin_palette_line_375_3fcd25db_descriptor_json();
const char* src_core_rendering_skeleton_render_data_bas_attachment_source_local_root_matrix_line_400_6cd81f41_descriptor_json();
const char* src_core_rendering_skeleton_render_data_skin_palette_flat_bytes_line_434_c134d52b_descriptor_json();
const char* src_core_rendering_skeleton_render_data_cached_matrix_palette_uploader_line_455_58be21bd_descriptor_json();
const char* src_core_rendering_skeleton_render_data_skinning_palette_model_for_node_line_476_193696ae_descriptor_json();
const char* src_core_rendering_skeleton_render_data_matrix_palette_uploader_cache_key_line_489_d2f67a8f_descriptor_json();
const char* src_core_rendering_skeleton_render_data_cpu_skin_positions_line_522_a4e14052_descriptor_json();
const char* src_core_rendering_skeleton_render_data_normalize_weight_rows_line_568_82ae484d_descriptor_json();
const char* src_core_rendering_skeleton_render_data_model_nodes_line_580_f434f2db_descriptor_json();
const char* src_core_rendering_skeleton_render_data_is_bone_node_line_587_82644d7b_descriptor_json();
const char* src_core_rendering_skeleton_render_data_nearest_bone_ancestor_line_602_56a86531_descriptor_json();
const char* src_core_rendering_skeleton_render_data_node_world_position_line_616_f9fdec7f_descriptor_json();
const char* src_core_rendering_skeleton_render_data_animated_world_position_line_634_d88f7518_descriptor_json();
const char* src_core_rendering_skeleton_render_data_distance_line_671_272ee1dd_descriptor_json();
const char* src_core_rendering_skeleton_render_data_bone_colour_hint_line_677_18d8061f_descriptor_json();
const char* src_core_rendering_skeleton_render_data_skin_revision_line_687_806e2dee_descriptor_json();
const char* src_core_rendering_skeleton_render_data_root_model_from_node_line_699_94251bf8_descriptor_json();
const char* src_core_scene_scene_object_vec3_line_10_91771333_descriptor_json();

const PythonFunctionDescriptorEntry* modulefunctions_descriptors(std::size_t& count);

} // namespace ghostrigger::phase15::ghostrigger_runtime_shared_descriptors
