#pragma once

#include <cstddef>

namespace ghostrigger::phase15::ghostrigger_windows_mainwindow {

using PythonFunctionDescriptorJson = const char* (*)();

struct PythonFunctionDescriptorEntry {
    const char* python_file;
    const char* qualname;
    const char* function_type;
    PythonFunctionDescriptorJson descriptor_json;
};

const char* src_gui_windows_application_core_application_core_lib_make_package_line_116_3b225a79_descriptor_json();
const char* src_gui_windows_application_core_application_core_lib_register_alias_line_123_cfe75bc1_descriptor_json();
const char* src_gui_windows_application_core_application_core_lib_register_group_line_133_69d31992_descriptor_json();
const char* src_gui_windows_application_core_functions_app_runner_run_qt_application_line_17_22c2bb63_descriptor_json();
const char* src_gui_windows_application_core_functions_geometry_bounds_from_points_line_12_0f5b3342_descriptor_json();
const char* src_gui_windows_application_core_functions_geometry_bounds_center_line_28_529ac354_descriptor_json();
const char* src_gui_windows_application_core_functions_geometry_bounds_overlap_xy_line_35_0875c0d3_descriptor_json();
const char* src_gui_windows_application_core_functions_geometry_walkmesh_reference_bounds_line_43_cb8ce1d1_descriptor_json();
const char* src_gui_windows_application_core_functions_geometry_walkmesh_overlay_offset_for_model_line_70_a715a3f3_descriptor_json();
const char* src_gui_windows_application_core_functions_geometry_walkmesh_overlay_node_from_wok_line_99_9a392cbb_descriptor_json();
const char* src_gui_windows_application_core_functions_geometry_prebuild_gpu_mesh_data_for_model_line_125_ad6175f6_descriptor_json();
const char* src_gui_windows_application_core_functions_qt_helpers_wgpu_backend_type_line_25_b08cfaf1_descriptor_json();
const char* src_gui_windows_application_core_functions_qt_helpers_wgpu_backend_restart_required_line_28_f31e2dd1_descriptor_json();
const char* src_gui_windows_application_core_functions_qt_helpers_primary_screen_available_geometry_line_36_e708b4ac_descriptor_json();
const char* src_gui_windows_application_core_functions_qt_helpers_qt_object_alive_line_45_c0bd40f8_descriptor_json();
const char* src_gui_windows_application_core_functions_splash_theme_lighten_hex_line_15_c934fdb4_descriptor_json();
const char* src_gui_windows_application_core_functions_splash_theme_darken_hex_line_20_90dbbcf7_descriptor_json();
const char* src_gui_windows_application_core_functions_splash_theme_surface_fill_line_25_99123150_descriptor_json();
const char* src_gui_windows_application_core_functions_splash_theme_palette_hex_line_38_0315949c_descriptor_json();
const char* src_gui_windows_application_core_functions_splash_theme_native_splash_palette_colors_line_41_783cc396_descriptor_json();
const char* src_gui_windows_application_core_functions_startup_library_index_game_libraries_sync_line_19_429b5955_descriptor_json();
const char* src_gui_windows_application_core_functions_startup_library_scan_library_rows_sync_line_37_e39110c2_descriptor_json();
const char* src_gui_windows_application_core_functions_startup_library_read_settings_file_line_40_73ac53bf_descriptor_json();
const char* src_gui_windows_application_core_functions_startup_library_write_settings_file_line_47_78408892_descriptor_json();
const char* src_gui_windows_application_core_functions_startup_library_build_prelaunch_library_input_line_52_6d0bd1d7_descriptor_json();
const char* src_gui_windows_application_core_functions_startup_library_collect_prewindow_startup_diagnostics_line_121_7f35bd93_descriptor_json();
const char* src_gui_windows_application_core_shared_workers_load_resource_model_from_game_resources_line_122_42a051a5_descriptor_json();
const char* src_gui_windows_progress_toast_lighten_hex_line_15_805afa9c_descriptor_json();
const char* src_gui_windows_progress_toast_darken_hex_line_22_1be83d41_descriptor_json();
const char* src_gui_windows_progress_toast_surface_fill_line_29_c3e65dcb_descriptor_json();
const char* src_gui_windows_qt_main_window_index_game_libraries_sync_line_194_8f2842f7_descriptor_json();
const char* src_gui_windows_qt_main_window_scan_library_rows_sync_line_198_49b27f21_descriptor_json();
const char* src_gui_windows_qt_main_window_build_prelaunch_library_input_line_203_1a4d4d40_descriptor_json();
const char* src_gui_windows_qt_main_window_run_line_1039_f822e3ed_descriptor_json();

const PythonFunctionDescriptorEntry* modulefunctions_descriptors(std::size_t& count);

} // namespace ghostrigger::phase15::ghostrigger_windows_mainwindow
