#pragma once

#include <cstddef>

namespace ghostrigger::phase15::ghostrigger_windows_mainwindow {

using PythonFunctionDescriptorJson = const char* (*)();

struct PythonFunctionDescriptorEntry {
    const char* python_file;
    const char* qualname;
    const char* function_type;
    PythonFunctionDescriptorJson descriptor_json;
};

const char* src_gui_windows_application_core_functions_app_runner_run_qt_application_update_prelaunch_status_line_41_09d9114c_descriptor_json();
const char* src_gui_windows_application_core_functions_startup_library_build_prelaunch_library_input_status_line_72_860c2c41_descriptor_json();
const char* src_gui_windows_application_core_shared_animation_workflow_animationworkflowmixin_build_baked_animation_samples_for_node_line_501_8b43e701_descriptor_json();
const char* src_gui_windows_application_core_shared_resource_loading_resourceloadingmixin_load_resource_model_on_ui_thread_progress_line_363_96d5503d_descriptor_json();
const char* src_gui_windows_application_core_shared_resource_loading_resourceloadingmixin_select_module_mesh_by_name_from_ipc_node_source_line_1121_698f5300_descriptor_json();
const char* src_gui_windows_application_core_shared_resource_loading_resourceloadingmixin_select_module_mesh_by_name_from_ipc_matches_line_1142_da92884e_descriptor_json();
const char* src_gui_windows_application_core_shared_workers_load_resource_model_from_game_resources_report_line_136_692e3227_descriptor_json();
const char* src_gui_windows_qt_main_window_qtghostriggermainwindow_start_ipc_server_load_model_by_resref_line_397_c62e134d_descriptor_json();
const char* src_gui_windows_qt_main_window_qtghostriggermainwindow_start_ipc_server_open_mdl_line_400_8b333042_descriptor_json();
const char* src_gui_windows_qt_main_window_qtghostriggermainwindow_start_ipc_server_new_scene_line_404_1168f12d_descriptor_json();
const char* src_gui_windows_qt_main_window_qtghostriggermainwindow_start_ipc_server_open_scene_line_410_1bf177eb_descriptor_json();
const char* src_gui_windows_qt_main_window_qtghostriggermainwindow_start_ipc_server_save_scene_line_413_58071066_descriptor_json();
const char* src_gui_windows_qt_main_window_qtghostriggermainwindow_start_ipc_server_create_scene_camera_line_416_a014d193_descriptor_json();
const char* src_gui_windows_qt_main_window_qtghostriggermainwindow_start_ipc_server_create_scene_light_line_419_c3bcb978_descriptor_json();
const char* src_gui_windows_qt_main_window_qtghostriggermainwindow_start_ipc_server_select_scene_object_line_422_bd3c099b_descriptor_json();
const char* src_gui_windows_qt_main_window_qtghostriggermainwindow_start_ipc_server_set_scene_object_visibility_line_425_5c46246b_descriptor_json();
const char* src_gui_windows_qt_main_window_qtghostriggermainwindow_start_ipc_server_scene_object_command_line_428_92549420_descriptor_json();
const char* src_gui_windows_qt_main_window_qtghostriggermainwindow_start_ipc_server_scene_object_properties_line_436_241380b2_descriptor_json();
const char* src_gui_windows_qt_main_window_qtghostriggermainwindow_start_ipc_server_open_blueprint_resource_line_440_778e458c_descriptor_json();
const char* src_gui_windows_qt_main_window_qtghostriggermainwindow_start_ipc_server_open_blueprint_resource_open_line_441_d76617c9_descriptor_json();
const char* src_gui_windows_qt_main_window_qtghostriggermainwindow_start_ipc_server_refresh_viewport_line_447_37479c8b_descriptor_json();
const char* src_gui_windows_qt_main_window_qtghostriggermainwindow_start_ipc_server_show_panel_line_450_32bf0e6f_descriptor_json();
const char* src_gui_windows_qt_main_window_qtghostriggermainwindow_start_ipc_server_open_tool_line_453_fa7b9ad7_descriptor_json();
const char* src_gui_windows_qt_main_window_qtghostriggermainwindow_start_ipc_server_viewport_command_line_514_35d5c393_descriptor_json();
const char* src_gui_windows_qt_main_window_qtghostriggermainwindow_start_ipc_server_appearance_line_518_4acf4d59_descriptor_json();
const char* src_gui_windows_qt_main_window_qtghostriggermainwindow_start_ipc_server_animation_command_line_521_8d75e544_descriptor_json();
const char* src_gui_windows_qt_main_window_qtghostriggermainwindow_start_ipc_server_get_state_line_530_eb548f7b_descriptor_json();
const char* src_gui_windows_qt_main_window_qtghostriggermainwindow_start_ipc_server_library_search_line_533_25df7a9e_descriptor_json();
const char* src_gui_windows_qt_main_window_qtghostriggermainwindow_start_ipc_server_library_select_line_537_f24e33a8_descriptor_json();
const char* src_gui_windows_qt_main_window_qtghostriggermainwindow_start_ipc_server_resource_search_line_541_9c44ae03_descriptor_json();
const char* src_gui_windows_qt_main_window_qtghostriggermainwindow_start_ipc_server_resource_select_line_545_64d6e5d0_descriptor_json();
const char* src_gui_windows_qt_main_window_qtghostriggermainwindow_start_ipc_server_select_module_mesh_line_549_3b2d1152_descriptor_json();
const char* src_gui_windows_qt_main_window_qtghostriggermainwindow_start_ipc_server_set_renderer_backend_line_552_80fcf41d_descriptor_json();
const char* src_gui_windows_qt_main_window_qtghostriggermainwindow_start_ipc_server_set_dummy_helpers_line_562_6b2f1651_descriptor_json();
const char* src_gui_windows_qt_main_window_qtghostriggermainwindow_start_ipc_server_set_light_helpers_line_567_7b4bbfb5_descriptor_json();
const char* src_gui_windows_qt_main_window_qtghostriggermainwindow_start_ipc_server_select_helper_line_577_78b5594a_descriptor_json();
const char* src_gui_windows_qt_main_window_qtghostriggermainwindow_start_ipc_server_capture_viewport_line_600_460700de_descriptor_json();

const PythonFunctionDescriptorEntry* nestedfunctions_descriptors(std::size_t& count);

} // namespace ghostrigger::phase15::ghostrigger_windows_mainwindow
