#pragma once

#include <cstddef>

namespace ghostrigger::phase15::ghostrigger_windows_mainwindow {

using PythonFunctionDescriptorJson = const char* (*)();

struct PythonFunctionDescriptorEntry {
    const char* python_file;
    const char* qualname;
    const char* function_type;
    PythonFunctionDescriptorJson descriptor_json;
};

const char* src_gui_windows_application_core_shared_animation_workflow_animationworkflowmixin_is_head_animation_slot_line_278_daa495fc_descriptor_json();
const char* src_gui_windows_application_core_shared_resource_loading_resourceloadingmixin_module_group_anchor_lyt_position_line_634_d4352bba_descriptor_json();
const char* src_gui_windows_application_core_shared_resource_loading_resourceloadingmixin_runtime_model_child_count_line_727_2f2b8208_descriptor_json();
const char* src_gui_windows_application_core_shared_resource_loading_resourceloadingmixin_model_bounds_center_line_738_b02c98be_descriptor_json();
const char* src_gui_windows_application_core_shared_resource_loading_resourceloadingmixin_supports_animation_retarget_target_line_946_75ffa719_descriptor_json();
const char* src_gui_windows_application_core_shared_resource_loading_resourceloadingmixin_derive_wok_resrefs_line_971_d2ba6539_descriptor_json();
const char* src_gui_windows_application_core_shared_scene_workflow_sceneworkflowmixin_sprite_node_key_line_629_f8d350f8_descriptor_json();
const char* src_gui_windows_application_core_shared_scene_workflow_sceneworkflowmixin_sprite_material_payload_line_637_e3e1dbdd_descriptor_json();
const char* src_gui_windows_application_core_shared_scene_workflow_sceneworkflowmixin_apply_sprite_material_payload_line_655_f8a0ee48_descriptor_json();
const char* src_gui_windows_application_core_shared_scene_workflow_sceneworkflowmixin_sprite_node_has_explicit_override_line_677_a4437a56_descriptor_json();
const char* src_gui_windows_application_core_shared_window_chrome_windowchromemixin_height_for_wrapping_widget_line_693_2983b020_descriptor_json();

const PythonFunctionDescriptorEntry* staticmethods_descriptors(std::size_t& count);

} // namespace ghostrigger::phase15::ghostrigger_windows_mainwindow
