"""Shared imports for renderer mixin modules."""

from __future__ import annotations

from .colors import (
    _AXIS_X,
    _AXIS_Y,
    _AXIS_Z,
    _BG,
    _BONE,
    _GRID,
    _SEL,
    _WIRE,
    _hex_to_rgb_tuple,
    _paste_lightmap_triangle,
    _paste_textured_triangle,
    _rgb_str_to_tuple,
)
from .dependencies import (
    DanglySimulator,
    Dict,
    GridMeasurement,
    Image,
    ImageDraw,
    ImageFont,
    Iterable,
    KOTOR_BASE_SKELETONS,
    KotorModel,
    List,
    ModelNode,
    NodeFlags,
    Optional,
    Tuple,
    UnitSystem,
    WalkmeshLoader,
    WalkmeshOverlay,
    _ACCEL_AVAILABLE,
    _ACCEL_TIER,
    _FACE_MESH_SUBSTRINGS,
    _INNER_GEO_SUBSTRINGS,
    _MatrixPaletteUploader,
    _NUMPY,
    _PIL,
    _SKIN_MAX_BONES,
    _TexArrayCache,
    _accel_depth_sort,
    _accel_flat_shade_frame,
    _accel_frustum_cull,
    _accel_proj_verts,
    _accel_rasterize_frame,
    _accel_shade_colors,
    _quat_conjugate,
    _quat_rotate,
    _time_mod,
    _warmup_jit,
    build_draw_list,
    is_animation_supermodel,
    log,
    logging,
    math,
    np,
    os,
    struct,
    threading,
)
from .diagnostics import _GR_VIEWPORT_PROBE, _GR_VIEWPORT_PROBE_SEEN, _gr_probe
from .rasterizer import _rasterize_triangle_textured
from .texture_cache import TextureCache
from src.core.camera.arcball_camera import ArcBallCamera
from src.core.graphics.tpc import (
    _decompress_dxt1_bytes,
    _decompress_dxt5_bytes,
    _ensure_bottom_up,
    _extract_txi_from_tpc,
    _extract_txi_from_tpc_legacy,
    _is_tpc_data,
    _is_tpc_file,
    _load_tpc_bytes,
    _load_tpc_bytes_legacy,
    _load_tpc_bytes_legacy_inner,
)
from src.core.graphics.txi import (
    _apply_txi_to_node,
    _compute_flipbook_uv,
    _extract_alpha_test_from_tpc,
    _parse_txi_string,
)
from src.math.frame_math import (
    _add,
    _clamp,
    _clean_tex_name,
    _compute_screen_size_ratio,
    _cross,
    _dot,
    _edge_has_seam_global,
    _float_to_sort_key,
    _lerp,
    _normalize,
    _struct,
    _sub,
    _uwrap_global,
    _vflip_nontiled,
    _vflip_tiled,
)

__all__ = tuple(name for name in globals() if not name.startswith('__'))
