#pragma once

#include <cstddef>

namespace ghostrigger::phase15::ghostrigger_tools_resourcebrowser {

using PythonFunctionDescriptorJson = const char* (*)();

struct PythonFunctionDescriptorEntry {
    const char* python_file;
    const char* qualname;
    const char* function_type;
    PythonFunctionDescriptorJson descriptor_json;
};

const char* src_core_assets_resource_manager_key_line_98_0520e2cf_descriptor_json();
const char* src_core_assets_resource_manager_texture_name_candidates_line_110_f1e75d5f_descriptor_json();
const char* src_core_assets_resource_manager_decode_texture_line_748_23e8416a_descriptor_json();
const char* src_core_assets_resource_manager_tpc_uncompressed_txi_line_877_211ae331_descriptor_json();
const char* src_core_assets_resource_manager_tpc_info_line_912_ce2f9944_descriptor_json();
const char* src_core_assets_resource_manager_is_tpc_line_943_3763289e_descriptor_json();
const char* src_core_assets_resource_manager_get_manager_line_1014_7b60640d_descriptor_json();
const char* src_core_assets_resource_manager_reset_manager_line_1024_a1b1addf_descriptor_json();
const char* src_core_assets_resource_manager_resolve_model_textures_line_1034_771e23a2_descriptor_json();
const char* src_core_assets_resource_manager_audit_model_textures_line_1149_37515999_descriptor_json();
const char* src_core_assets_resource_manager_identify_texture_source_line_1240_5185a261_descriptor_json();
const char* src_core_assets_resource_manager_parse_txi_for_alpha_line_1278_ef05cf3e_descriptor_json();
const char* src_core_assets_resource_manager_apply_alpha_fix_line_1313_55e1139e_descriptor_json();
const char* src_core_resources_game_resource_provider_coerce_resource_query_line_167_aa2b5698_descriptor_json();
const char* src_core_resources_game_resource_provider_restype_to_extension_line_435_d168dbf6_descriptor_json();
const char* src_core_resources_game_resource_provider_records_from_install_line_442_29a1399c_descriptor_json();
const char* src_core_resources_game_resource_provider_override_records_line_460_fa1405f7_descriptor_json();
const char* src_core_resources_game_resource_provider_erf_records_line_484_f262248d_descriptor_json();
const char* src_core_resources_game_resource_provider_bif_records_line_522_923b63b9_descriptor_json();
const char* src_core_resources_game_resource_provider_record_line_553_2745da10_descriptor_json();
const char* src_core_resources_game_resource_provider_record_matches_line_585_f4a92796_descriptor_json();
const char* src_core_resources_game_resource_provider_sort_records_line_602_cf3d7f84_descriptor_json();
const char* src_core_resources_game_resource_provider_dedupe_records_line_616_788f2d14_descriptor_json();
const char* src_core_resources_game_resource_provider_shadow_warnings_line_628_0fd0c506_descriptor_json();
const char* src_core_resources_game_resource_provider_missing_message_line_639_8fea0f4d_descriptor_json();
const char* src_core_resources_game_resource_provider_safe_path_size_line_645_ca4cce06_descriptor_json();
const char* src_core_resources_game_resource_provider_clean_text_line_654_ba113744_descriptor_json();
const char* src_core_resources_game_resource_provider_clean_restype_line_663_96e19284_descriptor_json();
const char* src_core_resources_game_resource_provider_clean_game_line_672_dc0cf339_descriptor_json();
const char* src_core_resources_game_resource_provider_manager_game_name_line_684_d824b250_descriptor_json();
const char* src_core_resources_game_resource_provider_manager_install_line_688_f11c7825_descriptor_json();
const char* src_core_resources_game_resource_provider_resource_manager_type_id_line_696_88dd7962_descriptor_json();
const char* src_core_resources_game_resource_provider_resource_manager_restype_line_706_feb4e7a7_descriptor_json();
const char* src_core_resources_game_resource_provider_known_resource_type_ids_line_715_dd065008_descriptor_json();
const char* src_gui_panels_qt_resource_browser_model_role_text_line_273_f07acd64_descriptor_json();
const char* src_gui_panels_qt_resource_browser_model_as_iter_line_282_aeff2e47_descriptor_json();
const char* src_resources_game_detector_detect_kotor_dirs_line_59_58c316ed_descriptor_json();
const char* src_resources_game_detector_save_config_line_140_715b3b16_descriptor_json();
const char* src_resources_game_detector_load_config_line_159_231807ce_descriptor_json();
const char* src_resources_game_detector_list_all_candidates_line_172_cfdbd573_descriptor_json();
const char* src_resources_game_detector_is_kotor_dir_line_212_41b67c1f_descriptor_json();
const char* src_resources_game_detector_steam_library_paths_line_260_6ffd514b_descriptor_json();
const char* src_resources_game_detector_steam_candidates_line_324_c5aaa94d_descriptor_json();
const char* src_resources_game_detector_gog_candidates_line_369_7c4b8b65_descriptor_json();
const char* src_resources_game_detector_default_candidates_line_422_4e4dc2c4_descriptor_json();
const char* src_resources_game_detector_unique_paths_line_468_37e6a31e_descriptor_json();
const char* src_resources_game_detector_windows_drive_roots_line_484_9fabc71e_descriptor_json();
const char* src_resources_game_detector_registry_path_values_line_500_c1d5de92_descriptor_json();
const char* src_resources_game_detector_windows_registry_steam_roots_line_520_b845a039_descriptor_json();
const char* src_resources_game_detector_windows_registry_kotor_candidates_line_539_84aa7014_descriptor_json();
const char* src_resources_game_detector_windows_uninstall_kotor_candidates_line_568_2f969042_descriptor_json();
const char* src_resources_game_library_res_ext_line_125_0163fdc4_descriptor_json();
const char* src_resources_game_library_res_name_line_130_c437aa6c_descriptor_json();

const PythonFunctionDescriptorEntry* modulefunctions_descriptors(std::size_t& count);

} // namespace ghostrigger::phase15::ghostrigger_tools_resourcebrowser
