#pragma once

#include <cstddef>

namespace ghostrigger::runtime::shared::resources {

#ifndef GHOSTRIGGER_RUNTIME_SHARED_RESOURCES_NATIVE_FUNCTION_IMPLEMENTATION_DEFINED
#define GHOSTRIGGER_RUNTIME_SHARED_RESOURCES_NATIVE_FUNCTION_IMPLEMENTATION_DEFINED
struct NativeFunctionImplementation {
    const char* project;
    const char* native_namespace;
    const char* python_file;
    const char* qualname;
    const char* callable_type;
    const char* implementation_status;
    bool native_first;
    bool python_runtime_required;
    bool python_fallback_allowed;
    const char* contract_json;
};
#endif // GHOSTRIGGER_RUNTIME_SHARED_RESOURCES_NATIVE_FUNCTION_IMPLEMENTATION_DEFINED

const NativeFunctionImplementation& overrideentry_construct_line_78_d0248e73_native();
const NativeFunctionImplementation& overridelayer_construct_line_92_9a4beb57_native();
const NativeFunctionImplementation& overridelayer_scan_line_129_98c9efb9_native();
const NativeFunctionImplementation& overridelayer_has_line_165_b86069d5_native();
const NativeFunctionImplementation& overridelayer_get_line_169_5add8090_native();
const NativeFunctionImplementation& overridelayer_get_path_line_185_c262cb88_native();
const NativeFunctionImplementation& overridelayer_list_by_ext_line_190_557b8098_native();
const NativeFunctionImplementation& overridelayer_list_all_line_195_6f822cf2_native();
const NativeFunctionImplementation& overridelayer_badge_line_199_113b22d1_native();
const NativeFunctionImplementation& overridelayer_summary_line_203_64178277_native();
const NativeFunctionImplementation& overridelayer_get_model_line_219_d4fef934_native();
const NativeFunctionImplementation& overridelayer_get_model_mdx_line_226_8f1870db_native();
const NativeFunctionImplementation& overridelayer_get_texture_line_230_13b13e91_native();
const NativeFunctionImplementation& overridelayer_send_to_override_line_240_93c46add_native();
const NativeFunctionImplementation& overridelayer_delete_override_line_257_e4330164_native();
const NativeFunctionImplementation& overridelayer_get_or_fallback_line_276_1beaa118_native();
const NativeFunctionImplementation& bifindex_construct_line_134_43bf71f9_native();
const NativeFunctionImplementation& bifindex_read_line_150_3f1c64f4_native();
const NativeFunctionImplementation& erfindex_construct_line_180_fe2d145b_native();
const NativeFunctionImplementation& erfindex_read_line_208_299ccda5_native();
const NativeFunctionImplementation& erfindex_list_type_line_221_cb623c1f_native();
const NativeFunctionImplementation& erfindex_has_line_225_abaf94e1_native();
const NativeFunctionImplementation& resourcemanager_construct_line_251_4264fa12_native();
const NativeFunctionImplementation& resourcemanager_set_k1_dir_line_258_b686e51c_native();
const NativeFunctionImplementation& resourcemanager_set_k2_dir_line_276_d65c3d5d_native();
const NativeFunctionImplementation& resourcemanager_get_k1_line_294_80cd1115_native();
const NativeFunctionImplementation& resourcemanager_get_k2_line_297_aaeabce7_native();
const NativeFunctionImplementation& resourcemanager_is_ready_line_300_9449e3fd_native();
const NativeFunctionImplementation& resourcemanager_get_line_306_4982196b_native();
const NativeFunctionImplementation& resourcemanager_get_mdl_line_326_182100bd_native();
const NativeFunctionImplementation& resourcemanager_get_mdx_line_329_4915e0d9_native();
const NativeFunctionImplementation& resourcemanager_get_texture_line_332_b30518be_native();
const NativeFunctionImplementation& resourcemanager_get_txi_line_343_2fc841d3_native();
const NativeFunctionImplementation& resourcemanager_list_models_line_356_0e391e12_native();
const NativeFunctionImplementation& resourcemanager_list_textures_line_370_98c3bec0_native();
const NativeFunctionImplementation& resourcemanager_has_textures_line_381_7f8f22c0_native();
const NativeFunctionImplementation& resourcemanager_load_model_line_408_ef643ebf_native();
const NativeFunctionImplementation& resourcemanager_load_texture_image_line_432_dda8e4c2_native();
const NativeFunctionImplementation& resourcemanager_game_dir_line_453_5dd3ce5c_native();
const NativeFunctionImplementation& resourcemanager_stats_line_458_9896ccfe_native();
const NativeFunctionImplementation& gameinstall_construct_line_488_92370a38_native();
const NativeFunctionImplementation& gameinstall_index_chitin_line_509_0a35adde_native();
const NativeFunctionImplementation& gameinstall_index_texture_packs_line_560_05e39cb9_native();
const NativeFunctionImplementation& gameinstall_index_modules_line_583_6fe3848d_native();
const NativeFunctionImplementation& gameinstall_load_override_line_600_75822fc1_native();
const NativeFunctionImplementation& gameinstall_get_line_624_969575a1_native();
const NativeFunctionImplementation& gameinstall_has_line_664_c6e0101b_native();
const NativeFunctionImplementation& gameinstall_list_resrefs_line_677_863540d1_native();
const NativeFunctionImplementation& gameinstall_find_file_line_697_7f712412_native();
const NativeFunctionImplementation& gameinstall_find_dir_line_711_d26a04be_native();
const NativeFunctionImplementation& gameinstall_find_file_ci_line_727_ef094f05_native();
const NativeFunctionImplementation& texturedecoder_decode_texture_line_27_e83bd02c_native();
const NativeFunctionImplementation& gameresourcequery_post_construct_line_76_8060f04c_native();
const NativeFunctionImplementation& gameresourcequery_to_address_line_84_27269e94_native();
const NativeFunctionImplementation& gameresourcerecord_post_construct_line_107_9a620728_native();
const NativeFunctionImplementation& gameresourceprovider_list_resources_line_154_13eb721d_native();
const NativeFunctionImplementation& gameresourceprovider_resolve_line_157_db6153cc_native();
const NativeFunctionImplementation& gameresourceprovider_read_bytes_line_160_7e0b3a1b_native();
const NativeFunctionImplementation& gameresourceprovider_exists_line_163_eda4619b_native();
const NativeFunctionImplementation& inmemorygameresourceprovider_construct_line_188_d08dcb62_native();
const NativeFunctionImplementation& inmemorygameresourceprovider_add_line_197_49d40e02_native();
const NativeFunctionImplementation& inmemorygameresourceprovider_list_resources_line_200_2ca86bab_native();
const NativeFunctionImplementation& inmemorygameresourceprovider_list_module_resources_line_205_a022d9b4_native();
const NativeFunctionImplementation& inmemorygameresourceprovider_resolve_line_208_c2b6a07f_native();
const NativeFunctionImplementation& inmemorygameresourceprovider_read_bytes_line_224_2e9321d1_native();
const NativeFunctionImplementation& inmemorygameresourceprovider_read_resource_line_227_8e539aeb_native();
const NativeFunctionImplementation& inmemorygameresourceprovider_exists_line_238_28740a54_native();
const NativeFunctionImplementation& localfileresourceprovider_list_resources_line_249_577bbf95_native();
const NativeFunctionImplementation& localfileresourceprovider_resolve_line_260_dfe7c954_native();
const NativeFunctionImplementation& localfileresourceprovider_read_bytes_line_270_15ed95e3_native();
const NativeFunctionImplementation& localfileresourceprovider_exists_line_273_262362a1_native();
const NativeFunctionImplementation& localfileresourceprovider_record_for_path_line_280_1e0a7666_native();
const NativeFunctionImplementation& compositegameresourceprovider_construct_line_302_f4c139f6_native();
const NativeFunctionImplementation& compositegameresourceprovider_list_resources_line_305_158702ab_native();
const NativeFunctionImplementation& compositegameresourceprovider_list_module_resources_line_311_b9fdbc05_native();
const NativeFunctionImplementation& compositegameresourceprovider_resolve_line_314_8dbf0540_native();
const NativeFunctionImplementation& compositegameresourceprovider_read_bytes_line_334_31527e38_native();
const NativeFunctionImplementation& compositegameresourceprovider_read_resource_line_337_b248788c_native();
const NativeFunctionImplementation& compositegameresourceprovider_exists_line_348_dd7a3867_native();
const NativeFunctionImplementation& resourcemanagergameresourceprovider_construct_line_360_145e2601_native();
const NativeFunctionImplementation& resourcemanagergameresourceprovider_list_resources_line_363_1abeed1b_native();
const NativeFunctionImplementation& resourcemanagergameresourceprovider_list_module_resources_line_374_3e04a171_native();
const NativeFunctionImplementation& resourcemanagergameresourceprovider_resolve_line_377_10f73bb5_native();
const NativeFunctionImplementation& resourcemanagergameresourceprovider_read_bytes_line_413_bd99e881_native();
const NativeFunctionImplementation& resourcemanagergameresourceprovider_read_resource_line_416_6be8f0b0_native();
const NativeFunctionImplementation& resourcemanagergameresourceprovider_exists_line_427_5ef4e963_native();
const NativeFunctionImplementation& resourceentry_read_line_186_03bea365_native();
const NativeFunctionImplementation& keybifreader_construct_line_205_cf570382_native();
const NativeFunctionImplementation& keybifreader_load_line_214_75fa6781_native();
const NativeFunctionImplementation& keybifreader_get_line_391_63f58f54_native();
const NativeFunctionImplementation& keybifreader_list_type_line_419_6f3477e8_native();
const NativeFunctionImplementation& keybifreader_list_all_types_line_441_fbf76cca_native();
const NativeFunctionImplementation& keybifreader_list_all_resources_line_445_55202d73_native();
const NativeFunctionImplementation& erfreader_construct_line_458_20e07f2c_native();
const NativeFunctionImplementation& erfreader_load_line_463_787a1e59_native();
const NativeFunctionImplementation& erfreader_load_v1_from_tables_line_501_00997c81_native();
const NativeFunctionImplementation& erfreader_load_v1_line_525_48cb5f73_native();
const NativeFunctionImplementation& erfreader_get_line_535_3e2e3feb_native();
const NativeFunctionImplementation& erfreader_list_type_line_538_73602c7a_native();
const NativeFunctionImplementation& erfreader_list_all_line_541_8c5287c8_native();
const NativeFunctionImplementation& gamelibrary_construct_line_674_79ae6ceb_native();
const NativeFunctionImplementation& gamelibrary_set_k1_dir_line_690_bc728836_native();
const NativeFunctionImplementation& gamelibrary_set_k2_dir_line_697_f18ba4c4_native();
const NativeFunctionImplementation& gamelibrary_scan_line_704_943f553e_native();
const NativeFunctionImplementation& gamelibrary_scan_game_line_861_11feb0eb_native();
const NativeFunctionImplementation& gamelibrary_read_mdl_metadata_line_1021_49fe64f9_native();
const NativeFunctionImplementation& gamelibrary_get_2da_line_1036_e392fe83_native();
const NativeFunctionImplementation& gamelibrary_get_2da_raw_line_1060_d6cd5828_native();
const NativeFunctionImplementation& gamelibrary_list_2da_names_line_1083_66e75be4_native();
const NativeFunctionImplementation& gamelibrary_list_resources_line_1093_d309a480_native();
const NativeFunctionImplementation& gamelibrary_get_resource_data_line_1100_da175a53_native();
const NativeFunctionImplementation& gamelibrary_search_line_1125_3a92a130_native();
const NativeFunctionImplementation& gamelibrary_list_models_by_class_line_1131_305675e6_native();
const NativeFunctionImplementation& gamelibrary_list_textures_line_1147_14298a13_native();
const NativeFunctionImplementation& gamelibrary_get_tlk_string_line_1153_e6a818a7_native();
const NativeFunctionImplementation& gamelibrary_get_texture_data_line_1180_0a58651f_native();
const NativeFunctionImplementation& gamelibrary_get_model_data_line_1331_84a35054_native();
const NativeFunctionImplementation& gamelibrary_extract_to_folder_line_1375_1f447f19_native();
const NativeFunctionImplementation& gamelibrary_scan_texture_names_line_1407_2c8a495d_native();
const NativeFunctionImplementation& gamelibrary_detect_texture_ext_line_1441_cab77586_native();

const NativeFunctionImplementation* instancemethods_native_functions(std::size_t& count);

} // namespace ghostrigger::runtime::shared::resources
