#pragma once

#include <cstddef>

namespace ghostrigger::phase15::ghostrigger_tools_pivotcontrols {

using PythonFunctionDescriptorJson = const char* (*)();

struct PythonFunctionDescriptorEntry {
    const char* python_file;
    const char* qualname;
    const char* function_type;
    PythonFunctionDescriptorJson descriptor_json;
};

const char* src_core_gizmo_transform_controller_transformcontroller_init_line_39_50939a96_descriptor_json();
const char* src_core_gizmo_transform_controller_transformcontroller_snapshot_line_60_9f1c704a_descriptor_json();
const char* src_core_gizmo_transform_controller_transformcontroller_set_position_snap_line_86_cf91bb6b_descriptor_json();
const char* src_core_gizmo_transform_controller_transformcontroller_begin_drag_line_93_d91f3ce1_descriptor_json();
const char* src_core_gizmo_transform_controller_transformcontroller_drag_line_115_b61c076a_descriptor_json();
const char* src_core_gizmo_transform_controller_transformcontroller_apply_translate_line_127_0fbf0075_descriptor_json();
const char* src_core_gizmo_transform_controller_transformcontroller_apply_view_translate_line_181_aa686c4b_descriptor_json();
const char* src_core_gizmo_transform_controller_transformcontroller_apply_rotate_line_225_fb3c1c0d_descriptor_json();
const char* src_core_gizmo_transform_controller_transformcontroller_apply_scale_line_253_d0840c2f_descriptor_json();
const char* src_core_gizmo_transform_controller_transformcontroller_cancel_line_329_299df350_descriptor_json();
const char* src_core_gizmo_transform_controller_transformcontroller_end_drag_line_335_6d85d24f_descriptor_json();
const char* src_core_gizmo_transform_controller_transformcontroller_restore_line_342_1b53854f_descriptor_json();
const char* src_core_gizmo_transform_controller_transformcontroller_invalidate_line_364_e38981a7_descriptor_json();
const char* src_core_gizmo_transform_controller_transformcontroller_apply_light_scale_line_368_4d83d6d5_descriptor_json();
const char* src_core_gizmo_transform_controller_transformcontroller_apply_camera_scale_line_392_81775637_descriptor_json();
const char* src_core_gizmo_transform_gizmo_transformgizmo_init_line_14_a9df9afb_descriptor_json();
const char* src_core_gizmo_transform_gizmo_transformgizmo_set_selected_object_line_35_2fe16a2b_descriptor_json();
const char* src_core_gizmo_transform_gizmo_transformgizmo_set_selected_objects_line_39_5056a6e3_descriptor_json();
const char* src_core_gizmo_transform_gizmo_transformgizmo_clear_selection_line_44_709ea6a0_descriptor_json();
const char* src_core_gizmo_transform_gizmo_transformgizmo_cycle_mode_line_52_647d8f31_descriptor_json();
const char* src_core_gizmo_transform_gizmo_transformgizmo_set_mode_line_58_6aa46899_descriptor_json();
const char* src_core_gizmo_transform_gizmo_transformgizmo_update_from_selection_line_62_608ad04e_descriptor_json();
const char* src_core_gizmo_transform_gizmo_transformgizmo_update_from_object_transform_line_98_58d66d54_descriptor_json();
const char* src_core_gizmo_transform_gizmo_transformgizmo_get_gizmo_origin_world_line_101_b1909cb5_descriptor_json();
const char* src_core_gizmo_transform_gizmo_transformgizmo_get_gizmo_orientation_matrix_line_105_0820e329_descriptor_json();
const char* src_core_gizmo_transform_gizmo_transformgizmo_get_gizmo_scale_for_camera_line_112_7e491cf8_descriptor_json();
const char* src_core_gizmo_transform_gizmo_transformgizmo_begin_drag_line_115_f58a8495_descriptor_json();
const char* src_core_gizmo_transform_gizmo_transformgizmo_drag_line_130_26d16200_descriptor_json();
const char* src_core_gizmo_transform_gizmo_transformgizmo_end_drag_line_134_8582966a_descriptor_json();
const char* src_core_gizmo_transform_gizmo_transformgizmo_cancel_drag_line_140_ae2279af_descriptor_json();
const char* src_core_gizmo_transform_gizmo_transformgizmo_draw_line_145_df47d660_descriptor_json();
const char* src_core_gizmo_transform_gizmo_transformgizmo_build_render_data_line_153_8ddf70d2_descriptor_json();
const char* src_core_gizmo_transform_gizmo_transformgizmo_hit_test_line_161_fcd24e7d_descriptor_json();
const char* src_core_scene_axis_mode_transformreferencecontroller_init_line_98_fb543c88_descriptor_json();
const char* src_core_scene_axis_mode_transformreferencecontroller_set_axis_mode_line_103_2955bef9_descriptor_json();
const char* src_core_scene_axis_mode_transformreferencecontroller_get_axis_mode_line_109_3e8b0906_descriptor_json();
const char* src_core_scene_axis_mode_transformreferencecontroller_get_transform_basis_line_112_787c9f27_descriptor_json();
const char* src_core_scene_axis_mode_transformreferencecontroller_get_gizmo_orientation_line_132_f1e2319a_descriptor_json();
const char* src_core_scene_axis_mode_transformreferencecontroller_resolve_pick_reference_line_135_9bf0d575_descriptor_json();
const char* src_core_scene_axis_mode_transformreferencecontroller_clear_pick_reference_line_139_515a9c4c_descriptor_json();
const char* src_core_scene_axis_mode_transformreferencecontroller_picked_reference_line_142_ad668aad_descriptor_json();
const char* src_core_scene_axis_mode_transformreferencecontroller_set_working_basis_line_145_a5b720a0_descriptor_json();
const char* src_core_scene_axis_mode_transformreferencecontroller_object_basis_line_148_d7d6708d_descriptor_json();
const char* src_core_scene_axis_mode_transformreferencecontroller_reference_is_deleted_line_159_633805a7_descriptor_json();
const char* src_gui_panels_adjust_pivot_panel_adjustpivotpanel_init_line_16_5db61efa_descriptor_json();
const char* src_gui_panels_adjust_pivot_panel_adjustpivotpanel_build_line_27_9f7fe03b_descriptor_json();
const char* src_gui_panels_adjust_pivot_panel_adjustpivotpanel_tool_button_line_82_e8423a9e_descriptor_json();
const char* src_gui_panels_adjust_pivot_panel_adjustpivotpanel_emit_pivot_mode_if_checked_line_95_1fe9e28a_descriptor_json();
const char* src_gui_panels_adjust_pivot_panel_adjustpivotpanel_set_pivot_mode_line_99_8f28a351_descriptor_json();
const char* src_gui_panels_adjust_pivot_panel_adjustpivotpanel_set_selection_state_line_106_fc4f1042_descriptor_json();
const char* src_gui_panels_adjust_pivot_panel_adjustpivotpanel_apply_ghost_theme_line_125_d6a3ef80_descriptor_json();
const char* src_gui_panels_adjust_pivot_panel_adjustpivotpanel_apply_ghost_layout_line_130_23e64942_descriptor_json();
const char* src_gui_panels_axis_mode_control_axismodecontrol_init_line_15_f6f7c143_descriptor_json();
const char* src_gui_panels_axis_mode_control_axismodecontrol_build_line_20_97739904_descriptor_json();
const char* src_gui_panels_axis_mode_control_axismodecontrol_axis_mode_line_35_0dc305b9_descriptor_json();
const char* src_gui_panels_axis_mode_control_axismodecontrol_set_axis_mode_line_38_53f4b6b4_descriptor_json();
const char* src_gui_panels_axis_mode_control_axismodecontrol_emit_mode_line_50_11daaee6_descriptor_json();
const char* src_gui_panels_axis_mode_control_axismodecontrol_apply_ghost_theme_line_58_62a2fef0_descriptor_json();
const char* src_gui_panels_axis_mode_control_axismodecontrol_apply_ghost_layout_line_72_9baa2461_descriptor_json();

const PythonFunctionDescriptorEntry* instancemethods_descriptors(std::size_t& count);

} // namespace ghostrigger::phase15::ghostrigger_tools_pivotcontrols
