#pragma once

#include <cstddef>

namespace ghostrigger::phase15::ghostrigger_kotormcp {

using PythonFunctionDescriptorJson = const char* (*)();

struct PythonFunctionDescriptorEntry {
    const char* python_file;
    const char* qualname;
    const char* function_type;
    PythonFunctionDescriptorJson descriptor_json;
};

const char* src_kotormcp_mcp_resources_list_resource_templates_line_42_cdaea7a6_descriptor_json();
const char* src_kotormcp_mcp_resources_list_resources_line_62_684c6865_descriptor_json();
const char* src_kotormcp_mcp_resources_read_resource_line_116_3752482a_descriptor_json();
const char* src_kotormcp_server_run_stdio_line_230_c0db7d2c_descriptor_json();
const char* src_kotormcp_server_run_sse_line_247_4b3aca42_descriptor_json();
const char* src_kotormcp_server_run_http_fallback_line_269_8d17548e_descriptor_json();
const char* src_kotormcp_tools_init_handle_tool_line_100_504c7571_descriptor_json();
const char* src_kotormcp_tools_archives_handle_list_archive_line_83_396ef7aa_descriptor_json();
const char* src_kotormcp_tools_archives_handle_extract_resource_line_140_874dca15_descriptor_json();
const char* src_kotormcp_tools_debug_materials_handle_list_materials_line_426_48903da5_descriptor_json();
const char* src_kotormcp_tools_debug_materials_handle_list_textures_line_436_4c434297_descriptor_json();
const char* src_kotormcp_tools_debug_materials_handle_get_material_info_line_461_77159ecc_descriptor_json();
const char* src_kotormcp_tools_debug_materials_handle_get_texture_binding_info_line_474_1889f913_descriptor_json();
const char* src_kotormcp_tools_debug_materials_handle_get_txi_info_line_496_da12a567_descriptor_json();
const char* src_kotormcp_tools_debug_materials_handle_get_uv_channel_info_line_507_d5069748_descriptor_json();
const char* src_kotormcp_tools_debug_materials_handle_get_supermodel_chain_line_528_553e2f72_descriptor_json();
const char* src_kotormcp_tools_debug_materials_handle_list_body_parts_line_552_b8662b9d_descriptor_json();
const char* src_kotormcp_tools_debug_materials_handle_get_missing_mesh_report_line_575_d076f5b5_descriptor_json();
const char* src_kotormcp_tools_debug_materials_handle_get_node_classification_audit_line_598_fdd06228_descriptor_json();
const char* src_kotormcp_tools_debug_materials_handle_get_vertex_space_audit_line_609_fe101de8_descriptor_json();
const char* src_kotormcp_tools_debug_materials_handle_get_render_filter_audit_line_623_84f11c91_descriptor_json();
const char* src_kotormcp_tools_debug_materials_handle_export_render_debug_bundle_line_652_ecd49ef2_descriptor_json();
const char* src_kotormcp_tools_debug_materials_handle_get_render_filter_results_line_687_a2e91d6c_descriptor_json();
const char* src_kotormcp_tools_debug_materials_handle_get_vbo_build_status_line_791_58eb699b_descriptor_json();
const char* src_kotormcp_tools_debug_materials_handle_get_k1_vs_k2_model_differences_line_873_7e40b64e_descriptor_json();
const char* src_kotormcp_tools_debug_skinning_handle_launch_app_line_1240_94d777ad_descriptor_json();
const char* src_kotormcp_tools_debug_skinning_handle_close_app_line_1246_ca0b74e2_descriptor_json();
const char* src_kotormcp_tools_debug_skinning_handle_get_runtime_status_line_1252_0647d5e9_descriptor_json();
const char* src_kotormcp_tools_debug_skinning_handle_set_game_library_path_line_1268_b859be8b_descriptor_json();
const char* src_kotormcp_tools_debug_skinning_handle_verify_game_library_line_1277_6321289f_descriptor_json();
const char* src_kotormcp_tools_debug_skinning_handle_load_model_line_1282_614ac619_descriptor_json();
const char* src_kotormcp_tools_debug_skinning_handle_get_loaded_asset_info_line_1291_af5e2570_descriptor_json();
const char* src_kotormcp_tools_debug_skinning_handle_list_animations_line_1296_c7fa1fc9_descriptor_json();
const char* src_kotormcp_tools_debug_skinning_handle_set_animation_line_1302_8777880c_descriptor_json();
const char* src_kotormcp_tools_debug_skinning_handle_set_animation_time_line_1308_35377fbd_descriptor_json();
const char* src_kotormcp_tools_debug_skinning_handle_set_bind_pose_line_1314_856d3b43_descriptor_json();
const char* src_kotormcp_tools_debug_skinning_handle_set_camera_preset_line_1319_efd65fb9_descriptor_json();
const char* src_kotormcp_tools_debug_skinning_handle_capture_viewport_line_1325_1d4254b5_descriptor_json();
const char* src_kotormcp_tools_debug_skinning_handle_capture_validation_set_line_1333_528a01bf_descriptor_json();
const char* src_kotormcp_tools_debug_skinning_handle_get_skinning_state_line_1340_f2c7cb2a_descriptor_json();
const char* src_kotormcp_tools_debug_skinning_handle_get_renderer_state_line_1345_32d74c4a_descriptor_json();
const char* src_kotormcp_tools_debug_skinning_handle_get_bone_hierarchy_line_1350_f79a9889_descriptor_json();
const char* src_kotormcp_tools_debug_skinning_handle_get_bone_map_line_1355_1789cee7_descriptor_json();
const char* src_kotormcp_tools_debug_skinning_handle_get_palette_remap_table_line_1361_d43c35c8_descriptor_json();
const char* src_kotormcp_tools_debug_skinning_handle_get_bind_pose_matrices_line_1366_deec72a6_descriptor_json();
const char* src_kotormcp_tools_debug_skinning_handle_get_animated_pose_matrices_line_1372_9a8d6813_descriptor_json();
const char* src_kotormcp_tools_debug_skinning_handle_get_uploaded_palette_line_1378_031c4407_descriptor_json();
const char* src_kotormcp_tools_debug_skinning_handle_sample_vertex_influences_line_1383_75691b30_descriptor_json();
const char* src_kotormcp_tools_debug_skinning_handle_compare_cpu_gpu_line_1391_e788372a_descriptor_json();
const char* src_kotormcp_tools_debug_skinning_handle_export_debug_bundle_line_1399_d92a6d05_descriptor_json();
const char* src_kotormcp_tools_decompile_handle_ping_line_295_582f3030_descriptor_json();
const char* src_kotormcp_tools_decompile_handle_binary_info_line_321_0b4945ff_descriptor_json();
const char* src_kotormcp_tools_decompile_handle_list_engine_funcs_line_336_dad995f0_descriptor_json();
const char* src_kotormcp_tools_decompile_handle_decompile_function_line_355_c5ea6802_descriptor_json();
const char* src_kotormcp_tools_decompile_handle_search_symbols_line_378_4c80073c_descriptor_json();
const char* src_kotormcp_tools_decompile_handle_search_engine_strings_line_398_01134b51_descriptor_json();
const char* src_kotormcp_tools_decompile_handle_get_references_line_418_f3b98d1e_descriptor_json();
const char* src_kotormcp_tools_decompile_handle_call_graph_line_439_7e475007_descriptor_json();
const char* src_kotormcp_tools_decompile_handle_data_flow_line_460_6838b4f0_descriptor_json();
const char* src_kotormcp_tools_decompile_handle_inspect_memory_line_484_5df5368a_descriptor_json();
const char* src_kotormcp_tools_decompile_handle_engine_script_line_506_c997f096_descriptor_json();
const char* src_kotormcp_tools_discovery_handle_list_resources_line_320_15e692d0_descriptor_json();
const char* src_kotormcp_tools_discovery_handle_describe_resource_line_366_dcd01d64_descriptor_json();
const char* src_kotormcp_tools_discovery_handle_find_resource_line_390_f7d238ef_descriptor_json();
const char* src_kotormcp_tools_discovery_handle_search_resources_line_422_3e248f66_descriptor_json();
const char* src_kotormcp_tools_gamedata_handle_journal_overview_line_111_d65c47dd_descriptor_json();
const char* src_kotormcp_tools_gamedata_handle_lookup_2da_line_147_5375ac9d_descriptor_json();
const char* src_kotormcp_tools_gamedata_handle_lookup_tlk_line_193_02219054_descriptor_json();
const char* src_kotormcp_tools_gffdata_handle_read_gff_line_119_a7efae7e_descriptor_json();
const char* src_kotormcp_tools_gffdata_handle_read_2da_line_143_0bdbc456_descriptor_json();
const char* src_kotormcp_tools_gffdata_handle_read_tlk_line_174_396fd010_descriptor_json();
const char* src_kotormcp_tools_ghostrigger_handle_open_model_line_369_41ab85b2_descriptor_json();
const char* src_kotormcp_tools_ghostrigger_handle_render_model_line_412_f26bb91b_descriptor_json();
const char* src_kotormcp_tools_ghostrigger_handle_model_info_line_562_e12cf595_descriptor_json();
const char* src_kotormcp_tools_ghostrigger_handle_list_game_models_line_601_7ad72b52_descriptor_json();
const char* src_kotormcp_tools_ghostrigger_handle_audit_line_633_10d92b66_descriptor_json();
const char* src_kotormcp_tools_ghostrigger_handle_export_model_for_unity_line_662_3becdfdb_descriptor_json();
const char* src_kotormcp_tools_ghostrigger_handle_validate_unity_import_line_715_4884f221_descriptor_json();
const char* src_kotormcp_tools_ghostrigger_handle_run_malak_unity_smoke_line_741_28e51919_descriptor_json();
const char* src_kotormcp_tools_installation_handle_detect_installations_line_53_89e51930_descriptor_json();
const char* src_kotormcp_tools_installation_handle_load_installation_line_78_d9e146a4_descriptor_json();
const char* src_kotormcp_tools_installation_handle_installation_info_line_91_ec438eb3_descriptor_json();
const char* src_kotormcp_tools_modules_handle_list_modules_line_74_47cc9f96_descriptor_json();
const char* src_kotormcp_tools_modules_handle_describe_module_line_87_8d1d62e0_descriptor_json();
const char* src_kotormcp_tools_modules_handle_module_resources_line_134_58d31ed8_descriptor_json();
const char* src_kotormcp_tools_quest_handle_get_quest_line_91_5bb2f18f_descriptor_json();
const char* src_kotormcp_tools_refs_handle_list_references_line_199_cbcb6e85_descriptor_json();
const char* src_kotormcp_tools_refs_handle_find_referrers_line_231_8ac0764a_descriptor_json();
const char* src_kotormcp_tools_refs_handle_find_strref_referrers_line_285_0afa8040_descriptor_json();
const char* src_kotormcp_tools_refs_handle_describe_dlg_line_373_9995d605_descriptor_json();
const char* src_kotormcp_tools_refs_handle_describe_jrl_line_399_5e6a8deb_descriptor_json();
const char* src_kotormcp_tools_refs_handle_describe_resource_refs_line_424_a1af7aee_descriptor_json();
const char* src_kotormcp_tools_resource_handle_get_resource_line_88_c3875331_descriptor_json();
const char* src_kotormcp_tools_retargeting_handle_get_retarget_skeleton_info_line_227_bc32b09a_descriptor_json();
const char* src_kotormcp_tools_retargeting_handle_build_retarget_map_line_281_15300a43_descriptor_json();
const char* src_kotormcp_tools_retargeting_handle_list_retarget_animations_line_324_35decdc0_descriptor_json();
const char* src_kotormcp_tools_retargeting_handle_export_unity_fbx_line_394_9436dbe7_descriptor_json();
const char* src_kotormcp_tools_walkmesh_handle_walkmesh_validation_diagram_line_66_33afbf8d_descriptor_json();

const PythonFunctionDescriptorEntry* asyncmodulefunctions_descriptors(std::size_t& count);

} // namespace ghostrigger::phase15::ghostrigger_kotormcp
