#pragma once

#include <cstddef>

namespace ghostrigger::kotormcp {

#ifndef GHOSTRIGGER_KOTORMCP_NATIVE_FUNCTION_IMPLEMENTATION_DEFINED
#define GHOSTRIGGER_KOTORMCP_NATIVE_FUNCTION_IMPLEMENTATION_DEFINED
struct NativeFunctionImplementation {
    const char* project;
    const char* native_namespace;
    const char* python_file;
    const char* qualname;
    const char* callable_type;
    const char* implementation_status;
    bool native_first;
    bool python_runtime_required;
    bool python_fallback_allowed;
    const char* contract_json;
};
#endif // GHOSTRIGGER_KOTORMCP_NATIVE_FUNCTION_IMPLEMENTATION_DEFINED

const NativeFunctionImplementation& installationadapter_construct_line_94_1e56aa0f_native();
const NativeFunctionImplementation& installationadapter_path_line_98_50c5e6b3_native();
const NativeFunctionImplementation& installationadapter_game_name_line_101_bc07fc35_native();
const NativeFunctionImplementation& installationadapter_module_names_line_104_eff90408_native();
const NativeFunctionImplementation& installationadapter_override_count_line_110_641ac79a_native();
const NativeFunctionImplementation& installationadapter_iter_resources_line_116_e7622d16_native();
const NativeFunctionImplementation& installationadapter_get_resource_line_180_907d9a8a_native();
const NativeFunctionImplementation& installationadapter_talktable_string_line_208_784a22df_native();
const NativeFunctionImplementation& installationadapter_to_entry_line_213_e4723b08_native();
const NativeFunctionImplementation& installationadapter_resolve_module_alias_line_227_4eb0d82b_native();
const NativeFunctionImplementation& pykotorregistryadapter_construct_line_276_24f609fe_native();
const NativeFunctionImplementation& pykotorregistryadapter_resolve_line_279_0c943b2b_native();
const NativeFunctionImplementation& pykotorregistryadapter_load_line_284_aac27773_native();
const NativeFunctionImplementation& pykotorregistryadapter_clear_line_309_d7c88b70_native();
const NativeFunctionImplementation& pykotorregistryadapter_iter_candidate_paths_line_312_a330f0eb_native();
const NativeFunctionImplementation& pykotorregistryadapter_default_paths_line_316_de4eb501_native();
const NativeFunctionImplementation& pykotorregistryadapter_default_path_keys_line_320_e0704278_native();
const NativeFunctionImplementation& pykotorregistryadapter_iter_candidates_line_323_2fc91981_native();
const NativeFunctionImplementation& filesystemmodellocator_construct_line_373_4891feee_native();
const NativeFunctionImplementation& filesystemmodellocator_locate_line_376_81717ed4_native();
const NativeFunctionImplementation& installationmodellocator_construct_line_417_2708521a_native();
const NativeFunctionImplementation& installationmodellocator_locate_line_420_1ab51ccb_native();
const NativeFunctionImplementation& compositemodellocator_construct_line_451_490284f5_native();
const NativeFunctionImplementation& compositemodellocator_locate_line_454_0eb44a61_native();
const NativeFunctionImplementation& mdlbinaryparseradapter_construct_line_476_d631bd07_native();
const NativeFunctionImplementation& mdlbinaryparseradapter_parse_line_479_e6e0405a_native();
const NativeFunctionImplementation& modelanalyzer_model_info_line_501_2b10b7a1_native();
const NativeFunctionImplementation& modelanalyzer_audit_line_532_063513fb_native();
const NativeFunctionImplementation& agentdecompileclient_construct_line_83_da8122bf_native();
const NativeFunctionImplementation& agentdecompileclient_base_headers_line_106_b0cadd0e_native();
const NativeFunctionImplementation& agentdecompileclient_post_line_130_67c1d4a8_native();
const NativeFunctionImplementation& agentdecompileclient_constructialize_line_152_994ab06c_native();
const NativeFunctionImplementation& agentdecompileclient_ensure_session_line_168_81c2b6a1_native();
const NativeFunctionImplementation& agentdecompileclient_call_tool_line_172_453a944b_native();
const NativeFunctionImplementation& agentdecompileclient_ping_line_198_aebceeb4_native();
const NativeFunctionImplementation& agentdecompileclient_resolve_program_path_line_213_dd5cebc1_native();
const NativeFunctionImplementation& agentdecompileclient_open_program_line_217_90d5ca4c_native();
const NativeFunctionImplementation& agentdecompileclient_get_program_info_line_241_e068feac_native();
const NativeFunctionImplementation& agentdecompileclient_list_functions_line_247_41b9272b_native();
const NativeFunctionImplementation& agentdecompileclient_decompile_function_line_258_12cd1626_native();
const NativeFunctionImplementation& agentdecompileclient_search_symbols_line_276_870063e5_native();
const NativeFunctionImplementation& agentdecompileclient_search_strings_line_287_946025d1_native();
const NativeFunctionImplementation& agentdecompileclient_search_everything_line_298_924bed39_native();
const NativeFunctionImplementation& agentdecompileclient_get_references_line_309_b2a72227_native();
const NativeFunctionImplementation& agentdecompileclient_get_call_graph_line_325_ecdbc240_native();
const NativeFunctionImplementation& agentdecompileclient_list_imports_line_341_c510ad74_native();
const NativeFunctionImplementation& agentdecompileclient_list_strings_line_347_4865723a_native();
const NativeFunctionImplementation& agentdecompileclient_analyze_data_flow_line_353_46a5b9c8_native();
const NativeFunctionImplementation& agentdecompileclient_inspect_memory_line_370_ac2c739e_native();
const NativeFunctionImplementation& agentdecompileclient_execute_script_line_388_e524e86f_native();
const NativeFunctionImplementation& installationport_path_line_83_1d08a33c_native();
const NativeFunctionImplementation& installationport_game_name_line_87_8f7b0b5a_native();
const NativeFunctionImplementation& installationport_module_names_line_91_3d123582_native();
const NativeFunctionImplementation& installationport_override_count_line_95_37d19622_native();
const NativeFunctionImplementation& installationport_iter_resources_line_99_53b59fa7_native();
const NativeFunctionImplementation& installationport_get_resource_line_107_39e4f0ed_native();
const NativeFunctionImplementation& installationport_talktable_string_line_116_9a21227d_native();
const NativeFunctionImplementation& modellocatorport_locate_line_129_5d28ce83_native();
const NativeFunctionImplementation& modelparserport_parse_line_152_64173e93_native();
const NativeFunctionImplementation& installationregistryport_resolve_line_166_bc00959c_native();
const NativeFunctionImplementation& installationregistryport_load_line_170_41c6c5c1_native();
const NativeFunctionImplementation& installationregistryport_clear_line_182_8a62a10d_native();
const NativeFunctionImplementation& basemodel_construct_line_18_80a9d1be_native();
const NativeFunctionImplementation& fallbackhttpserver_construct_line_83_39a608ae_native();
const NativeFunctionImplementation& installationsview_len_line_39_dc697427_native();
const NativeFunctionImplementation& installationsview_contains_line_42_3c0c1274_native();
const NativeFunctionImplementation& installationsview_iter_line_45_22974c53_native();
const NativeFunctionImplementation& installationsview_items_line_48_d9705276_native();
const NativeFunctionImplementation& installationsview_get_line_51_c500907d_native();
const NativeFunctionImplementation& installationsview_clear_line_54_f9b48a70_native();
const NativeFunctionImplementation& debugsession_construct_line_70_53c4b988_native();
const NativeFunctionImplementation& debugsession_launch_line_99_f124df09_native();
const NativeFunctionImplementation& debugsession_close_line_110_ea72c5b2_native();
const NativeFunctionImplementation& debugsession_set_game_path_line_126_1aedfe5d_native();
const NativeFunctionImplementation& debugsession_verify_game_line_146_ece39cb9_native();
const NativeFunctionImplementation& debugsession_parse_key_line_167_b05f3b7c_native();
const NativeFunctionImplementation& debugsession_extract_model_line_210_0511101f_native();
const NativeFunctionImplementation& debugsession_load_model_line_242_b9fb5a90_native();
const NativeFunctionImplementation& debugsession_get_asset_info_line_311_fa390fb4_native();
const NativeFunctionImplementation& debugsession_list_animations_line_345_94c2c3a2_native();
const NativeFunctionImplementation& debugsession_set_animation_line_366_c7cf1737_native();
const NativeFunctionImplementation& debugsession_set_animation_time_line_385_19da465d_native();
const NativeFunctionImplementation& debugsession_set_bind_pose_line_403_ce49f7c2_native();
const NativeFunctionImplementation& debugsession_set_camera_line_425_b4e4d8ee_native();
const NativeFunctionImplementation& debugsession_capture_viewport_line_435_1d304634_native();
const NativeFunctionImplementation& debugsession_capture_validation_set_line_497_313f01dc_native();
const NativeFunctionImplementation& debugsession_get_skinning_state_line_570_77612443_native();
const NativeFunctionImplementation& debugsession_get_renderer_state_line_588_156f4faf_native();
const NativeFunctionImplementation& debugsession_get_bone_hierarchy_line_601_96d7f5dd_native();
const NativeFunctionImplementation& debugsession_get_bone_map_for_mesh_line_629_6a24da6b_native();
const NativeFunctionImplementation& debugsession_get_palette_remap_table_line_657_4e2e8c9d_native();
const NativeFunctionImplementation& debugsession_get_bind_pose_matrices_line_686_0ca630c2_native();
const NativeFunctionImplementation& debugsession_get_animated_pose_matrices_line_714_0158f9ef_native();
const NativeFunctionImplementation& debugsession_get_uploaded_palette_line_748_30e4aa11_native();
const NativeFunctionImplementation& debugsession_sample_vertex_influences_line_770_07892202_native();
const NativeFunctionImplementation& debugsession_compare_cpu_gpu_skinning_line_828_f33f1dce_native();
const NativeFunctionImplementation& debugsession_export_debug_bundle_line_911_7212f87e_native();
const NativeFunctionImplementation& resourceentryproxy_construct_line_167_85a3273d_native();
const NativeFunctionImplementation& resourceentryproxy_resname_line_170_b0d363e0_native();
const NativeFunctionImplementation& resourceentryproxy_restype_line_173_cc31b08c_native();
const NativeFunctionImplementation& resourceentryproxy_size_line_176_908f8df8_native();
const NativeFunctionImplementation& resourceentryproxy_identifier_line_183_9df3d2ff_native();
const NativeFunctionImplementation& resourcetypeproxy_construct_line_188_faa73e11_native();
const NativeFunctionImplementation& resourcetypeproxy_eq_line_192_a006da78_native();
const NativeFunctionImplementation& resourcetypeproxy_hash_line_197_7610d004_native();
const NativeFunctionImplementation& services_construct_line_55_2c2865dd_native();

const NativeFunctionImplementation* instancemethods_native_functions(std::size_t& count);

} // namespace ghostrigger::kotormcp
