#pragma once

#include <cstddef>

namespace ghostrigger::phase15::ghostrigger_kotormcp {

using PythonFunctionDescriptorJson = const char* (*)();

struct PythonFunctionDescriptorEntry {
    const char* python_file;
    const char* qualname;
    const char* function_type;
    PythonFunctionDescriptorJson descriptor_json;
};

const char* src_kotormcp_adapters_installationadapter_init_line_94_1e56aa0f_descriptor_json();
const char* src_kotormcp_adapters_installationadapter_path_line_98_50c5e6b3_descriptor_json();
const char* src_kotormcp_adapters_installationadapter_game_name_line_101_bc07fc35_descriptor_json();
const char* src_kotormcp_adapters_installationadapter_module_names_line_104_eff90408_descriptor_json();
const char* src_kotormcp_adapters_installationadapter_override_count_line_110_641ac79a_descriptor_json();
const char* src_kotormcp_adapters_installationadapter_iter_resources_line_116_e7622d16_descriptor_json();
const char* src_kotormcp_adapters_installationadapter_get_resource_line_180_907d9a8a_descriptor_json();
const char* src_kotormcp_adapters_installationadapter_talktable_string_line_208_784a22df_descriptor_json();
const char* src_kotormcp_adapters_installationadapter_to_entry_line_213_e4723b08_descriptor_json();
const char* src_kotormcp_adapters_installationadapter_resolve_module_alias_line_227_4eb0d82b_descriptor_json();
const char* src_kotormcp_adapters_pykotorregistryadapter_init_line_276_24f609fe_descriptor_json();
const char* src_kotormcp_adapters_pykotorregistryadapter_resolve_line_279_0c943b2b_descriptor_json();
const char* src_kotormcp_adapters_pykotorregistryadapter_load_line_284_aac27773_descriptor_json();
const char* src_kotormcp_adapters_pykotorregistryadapter_clear_line_309_d7c88b70_descriptor_json();
const char* src_kotormcp_adapters_pykotorregistryadapter_iter_candidate_paths_line_312_a330f0eb_descriptor_json();
const char* src_kotormcp_adapters_pykotorregistryadapter_default_paths_line_316_de4eb501_descriptor_json();
const char* src_kotormcp_adapters_pykotorregistryadapter_default_path_keys_line_320_e0704278_descriptor_json();
const char* src_kotormcp_adapters_pykotorregistryadapter_iter_candidates_line_323_2fc91981_descriptor_json();
const char* src_kotormcp_adapters_filesystemmodellocator_init_line_373_4891feee_descriptor_json();
const char* src_kotormcp_adapters_filesystemmodellocator_locate_line_376_81717ed4_descriptor_json();
const char* src_kotormcp_adapters_installationmodellocator_init_line_417_2708521a_descriptor_json();
const char* src_kotormcp_adapters_installationmodellocator_locate_line_420_1ab51ccb_descriptor_json();
const char* src_kotormcp_adapters_compositemodellocator_init_line_451_490284f5_descriptor_json();
const char* src_kotormcp_adapters_compositemodellocator_locate_line_454_0eb44a61_descriptor_json();
const char* src_kotormcp_adapters_mdlbinaryparseradapter_init_line_476_d631bd07_descriptor_json();
const char* src_kotormcp_adapters_mdlbinaryparseradapter_parse_line_479_e6e0405a_descriptor_json();
const char* src_kotormcp_adapters_modelanalyzer_model_info_line_501_2b10b7a1_descriptor_json();
const char* src_kotormcp_adapters_modelanalyzer_audit_line_532_063513fb_descriptor_json();
const char* src_kotormcp_adapters_decompile_agentdecompileclient_init_line_83_da8122bf_descriptor_json();
const char* src_kotormcp_adapters_decompile_agentdecompileclient_base_headers_line_106_b0cadd0e_descriptor_json();
const char* src_kotormcp_adapters_decompile_agentdecompileclient_post_line_130_67c1d4a8_descriptor_json();
const char* src_kotormcp_adapters_decompile_agentdecompileclient_initialize_line_152_994ab06c_descriptor_json();
const char* src_kotormcp_adapters_decompile_agentdecompileclient_ensure_session_line_168_81c2b6a1_descriptor_json();
const char* src_kotormcp_adapters_decompile_agentdecompileclient_call_tool_line_172_453a944b_descriptor_json();
const char* src_kotormcp_adapters_decompile_agentdecompileclient_ping_line_198_aebceeb4_descriptor_json();
const char* src_kotormcp_adapters_decompile_agentdecompileclient_resolve_program_path_line_213_dd5cebc1_descriptor_json();
const char* src_kotormcp_adapters_decompile_agentdecompileclient_open_program_line_217_90d5ca4c_descriptor_json();
const char* src_kotormcp_adapters_decompile_agentdecompileclient_get_program_info_line_241_e068feac_descriptor_json();
const char* src_kotormcp_adapters_decompile_agentdecompileclient_list_functions_line_247_41b9272b_descriptor_json();
const char* src_kotormcp_adapters_decompile_agentdecompileclient_decompile_function_line_258_12cd1626_descriptor_json();
const char* src_kotormcp_adapters_decompile_agentdecompileclient_search_symbols_line_276_870063e5_descriptor_json();
const char* src_kotormcp_adapters_decompile_agentdecompileclient_search_strings_line_287_946025d1_descriptor_json();
const char* src_kotormcp_adapters_decompile_agentdecompileclient_search_everything_line_298_924bed39_descriptor_json();
const char* src_kotormcp_adapters_decompile_agentdecompileclient_get_references_line_309_b2a72227_descriptor_json();
const char* src_kotormcp_adapters_decompile_agentdecompileclient_get_call_graph_line_325_ecdbc240_descriptor_json();
const char* src_kotormcp_adapters_decompile_agentdecompileclient_list_imports_line_341_c510ad74_descriptor_json();
const char* src_kotormcp_adapters_decompile_agentdecompileclient_list_strings_line_347_4865723a_descriptor_json();
const char* src_kotormcp_adapters_decompile_agentdecompileclient_analyze_data_flow_line_353_46a5b9c8_descriptor_json();
const char* src_kotormcp_adapters_decompile_agentdecompileclient_inspect_memory_line_370_ac2c739e_descriptor_json();
const char* src_kotormcp_adapters_decompile_agentdecompileclient_execute_script_line_388_e524e86f_descriptor_json();
const char* src_kotormcp_ports_installationport_path_line_83_1d08a33c_descriptor_json();
const char* src_kotormcp_ports_installationport_game_name_line_87_8f7b0b5a_descriptor_json();
const char* src_kotormcp_ports_installationport_module_names_line_91_3d123582_descriptor_json();
const char* src_kotormcp_ports_installationport_override_count_line_95_37d19622_descriptor_json();
const char* src_kotormcp_ports_installationport_iter_resources_line_99_53b59fa7_descriptor_json();
const char* src_kotormcp_ports_installationport_get_resource_line_107_39e4f0ed_descriptor_json();
const char* src_kotormcp_ports_installationport_talktable_string_line_116_9a21227d_descriptor_json();
const char* src_kotormcp_ports_modellocatorport_locate_line_129_5d28ce83_descriptor_json();
const char* src_kotormcp_ports_modelparserport_parse_line_152_64173e93_descriptor_json();
const char* src_kotormcp_ports_installationregistryport_resolve_line_166_bc00959c_descriptor_json();
const char* src_kotormcp_ports_installationregistryport_load_line_170_41c6c5c1_descriptor_json();
const char* src_kotormcp_ports_installationregistryport_clear_line_182_8a62a10d_descriptor_json();
const char* src_kotormcp_schemas_init_basemodel_init_line_18_80a9d1be_descriptor_json();
const char* src_kotormcp_server_fallbackhttpserver_init_line_83_39a608ae_descriptor_json();
const char* src_kotormcp_state_installationsview_len_line_39_dc697427_descriptor_json();
const char* src_kotormcp_state_installationsview_contains_line_42_3c0c1274_descriptor_json();
const char* src_kotormcp_state_installationsview_iter_line_45_22974c53_descriptor_json();
const char* src_kotormcp_state_installationsview_items_line_48_d9705276_descriptor_json();
const char* src_kotormcp_state_installationsview_get_line_51_c500907d_descriptor_json();
const char* src_kotormcp_state_installationsview_clear_line_54_f9b48a70_descriptor_json();
const char* src_kotormcp_tools_debug_skinning_debugsession_init_line_70_53c4b988_descriptor_json();
const char* src_kotormcp_tools_debug_skinning_debugsession_launch_line_99_f124df09_descriptor_json();
const char* src_kotormcp_tools_debug_skinning_debugsession_close_line_110_ea72c5b2_descriptor_json();
const char* src_kotormcp_tools_debug_skinning_debugsession_set_game_path_line_126_1aedfe5d_descriptor_json();
const char* src_kotormcp_tools_debug_skinning_debugsession_verify_game_line_146_ece39cb9_descriptor_json();
const char* src_kotormcp_tools_debug_skinning_debugsession_parse_key_line_167_b05f3b7c_descriptor_json();
const char* src_kotormcp_tools_debug_skinning_debugsession_extract_model_line_210_0511101f_descriptor_json();
const char* src_kotormcp_tools_debug_skinning_debugsession_load_model_line_242_b9fb5a90_descriptor_json();
const char* src_kotormcp_tools_debug_skinning_debugsession_get_asset_info_line_311_fa390fb4_descriptor_json();
const char* src_kotormcp_tools_debug_skinning_debugsession_list_animations_line_345_94c2c3a2_descriptor_json();
const char* src_kotormcp_tools_debug_skinning_debugsession_set_animation_line_366_c7cf1737_descriptor_json();
const char* src_kotormcp_tools_debug_skinning_debugsession_set_animation_time_line_385_19da465d_descriptor_json();
const char* src_kotormcp_tools_debug_skinning_debugsession_set_bind_pose_line_403_ce49f7c2_descriptor_json();
const char* src_kotormcp_tools_debug_skinning_debugsession_set_camera_line_425_b4e4d8ee_descriptor_json();
const char* src_kotormcp_tools_debug_skinning_debugsession_capture_viewport_line_435_1d304634_descriptor_json();
const char* src_kotormcp_tools_debug_skinning_debugsession_capture_validation_set_line_497_313f01dc_descriptor_json();
const char* src_kotormcp_tools_debug_skinning_debugsession_get_skinning_state_line_570_77612443_descriptor_json();
const char* src_kotormcp_tools_debug_skinning_debugsession_get_renderer_state_line_588_156f4faf_descriptor_json();
const char* src_kotormcp_tools_debug_skinning_debugsession_get_bone_hierarchy_line_601_96d7f5dd_descriptor_json();
const char* src_kotormcp_tools_debug_skinning_debugsession_get_bone_map_for_mesh_line_629_6a24da6b_descriptor_json();
const char* src_kotormcp_tools_debug_skinning_debugsession_get_palette_remap_table_line_657_4e2e8c9d_descriptor_json();
const char* src_kotormcp_tools_debug_skinning_debugsession_get_bind_pose_matrices_line_686_0ca630c2_descriptor_json();
const char* src_kotormcp_tools_debug_skinning_debugsession_get_animated_pose_matrices_line_714_0158f9ef_descriptor_json();
const char* src_kotormcp_tools_debug_skinning_debugsession_get_uploaded_palette_line_748_30e4aa11_descriptor_json();
const char* src_kotormcp_tools_debug_skinning_debugsession_sample_vertex_influences_line_770_07892202_descriptor_json();
const char* src_kotormcp_tools_debug_skinning_debugsession_compare_cpu_gpu_skinning_line_828_f33f1dce_descriptor_json();
const char* src_kotormcp_tools_debug_skinning_debugsession_export_debug_bundle_line_911_7212f87e_descriptor_json();
const char* src_kotormcp_tools_discovery_resourceentryproxy_init_line_167_85a3273d_descriptor_json();
const char* src_kotormcp_tools_discovery_resourceentryproxy_resname_line_170_b0d363e0_descriptor_json();
const char* src_kotormcp_tools_discovery_resourceentryproxy_restype_line_173_cc31b08c_descriptor_json();
const char* src_kotormcp_tools_discovery_resourceentryproxy_size_line_176_908f8df8_descriptor_json();
const char* src_kotormcp_tools_discovery_resourceentryproxy_identifier_line_183_9df3d2ff_descriptor_json();
const char* src_kotormcp_tools_discovery_resourcetypeproxy_init_line_188_faa73e11_descriptor_json();
const char* src_kotormcp_tools_discovery_resourcetypeproxy_eq_line_192_a006da78_descriptor_json();
const char* src_kotormcp_tools_discovery_resourcetypeproxy_hash_line_197_7610d004_descriptor_json();
const char* src_kotormcp_tools_ghostrigger_services_init_line_55_2c2865dd_descriptor_json();

const PythonFunctionDescriptorEntry* instancemethods_descriptors(std::size_t& count);

} // namespace ghostrigger::phase15::ghostrigger_kotormcp
