#pragma once

#include <cstddef>

namespace ghostrigger::renderer::null {

#ifndef GHOSTRIGGER_RENDERER_NULL_NATIVE_FUNCTION_IMPLEMENTATION_DEFINED
#define GHOSTRIGGER_RENDERER_NULL_NATIVE_FUNCTION_IMPLEMENTATION_DEFINED
struct NativeFunctionImplementation {
    const char* project;
    const char* native_namespace;
    const char* python_file;
    const char* qualname;
    const char* callable_type;
    const char* implementation_status;
    bool native_first;
    bool python_runtime_required;
    bool python_fallback_allowed;
    const char* contract_json;
};
#endif // GHOSTRIGGER_RENDERER_NULL_NATIVE_FUNCTION_IMPLEMENTATION_DEFINED

const NativeFunctionImplementation& nulldiagnosticrenderer_construct_line_17_3112397b_native();
const NativeFunctionImplementation& nulldiagnosticrenderer_is_available_line_44_a49b1c0b_native();
const NativeFunctionImplementation& nulldiagnosticrenderer_get_capabilities_line_47_af72ee8c_native();
const NativeFunctionImplementation& nulldiagnosticrenderer_create_surface_widget_line_71_30f203b9_native();
const NativeFunctionImplementation& nulldiagnosticrenderer_render_line_82_83dce641_native();
const NativeFunctionImplementation& nulldiagnosticrenderer_set_theme_colors_line_102_8c1984df_native();
const NativeFunctionImplementation& nulldiagnosticrenderer_set_native_palette_colors_line_110_3f7f4308_native();
const NativeFunctionImplementation& nulldiagnosticrenderer_clear_caches_line_113_0e13aa47_native();
const NativeFunctionImplementation& nulldiagnosticrenderer_reset_framebuffers_line_116_94d7b5fa_native();
const NativeFunctionImplementation& nulldiagnosticrenderer_invalidate_node_line_119_06057d29_native();
const NativeFunctionImplementation& nulldiagnosticrenderer_invalidate_node_cache_line_122_e4567c21_native();
const NativeFunctionImplementation& nulldiagnosticrenderer_invalidate_all_line_125_33366afb_native();
const NativeFunctionImplementation& nulldiagnosticrenderer_get_diagnostics_line_128_0f247a15_native();
const NativeFunctionImplementation& renderercapabilities_to_dict_line_56_96c9be59_native();
const NativeFunctionImplementation& renderercapabilities_status_text_line_152_fec5213f_native();
const NativeFunctionImplementation& renderercapabilities_supports_display_mode_line_158_98c34e96_native();
const NativeFunctionImplementation& iviewportrenderer_is_available_line_16_d8d6e763_native();
const NativeFunctionImplementation& iviewportrenderer_get_capabilities_line_20_71760aee_native();
const NativeFunctionImplementation& iviewportrenderer_constructialize_line_23_3c747f18_native();
const NativeFunctionImplementation& iviewportrenderer_create_surface_widget_line_26_1ab290cd_native();
const NativeFunctionImplementation& iviewportrenderer_resize_line_29_a241a354_native();
const NativeFunctionImplementation& iviewportrenderer_render_line_33_528a49c1_native();
const NativeFunctionImplementation& iviewportrenderer_render_overlay_line_36_0ea321a6_native();
const NativeFunctionImplementation& iviewportrenderer_pick_line_39_e82673ef_native();
const NativeFunctionImplementation& iviewportrenderer_shutdown_line_42_ff2b66e5_native();
const NativeFunctionImplementation& iviewportrenderer_get_diagnostics_line_47_5c5843ca_native();
const NativeFunctionImplementation& iviewportrenderer_upload_mesh_line_57_1fd39e44_native();
const NativeFunctionImplementation& iviewportrenderer_upload_texture_line_60_26f8032d_native();
const NativeFunctionImplementation& iviewportrenderer_release_resource_line_63_107b6898_native();
const NativeFunctionImplementation& iviewportrenderer_invalidate_all_line_66_8f695e92_native();

const NativeFunctionImplementation* instancemethods_native_functions(std::size_t& count);

} // namespace ghostrigger::renderer::null
