#pragma once

#include <cstddef>

namespace ghostrigger::phase15::ghostrigger_renderer_null {

using PythonFunctionDescriptorJson = const char* (*)();

struct PythonFunctionDescriptorEntry {
    const char* python_file;
    const char* qualname;
    const char* function_type;
    PythonFunctionDescriptorJson descriptor_json;
};

const char* src_adapters_rendering_null_renderer_nulldiagnosticrenderer_init_line_17_3112397b_descriptor_json();
const char* src_adapters_rendering_null_renderer_nulldiagnosticrenderer_is_available_line_44_a49b1c0b_descriptor_json();
const char* src_adapters_rendering_null_renderer_nulldiagnosticrenderer_get_capabilities_line_47_af72ee8c_descriptor_json();
const char* src_adapters_rendering_null_renderer_nulldiagnosticrenderer_create_surface_widget_line_71_30f203b9_descriptor_json();
const char* src_adapters_rendering_null_renderer_nulldiagnosticrenderer_render_line_82_83dce641_descriptor_json();
const char* src_adapters_rendering_null_renderer_nulldiagnosticrenderer_set_theme_colors_line_102_8c1984df_descriptor_json();
const char* src_adapters_rendering_null_renderer_nulldiagnosticrenderer_set_native_palette_colors_line_110_3f7f4308_descriptor_json();
const char* src_adapters_rendering_null_renderer_nulldiagnosticrenderer_clear_caches_line_113_0e13aa47_descriptor_json();
const char* src_adapters_rendering_null_renderer_nulldiagnosticrenderer_reset_framebuffers_line_116_94d7b5fa_descriptor_json();
const char* src_adapters_rendering_null_renderer_nulldiagnosticrenderer_invalidate_node_line_119_06057d29_descriptor_json();
const char* src_adapters_rendering_null_renderer_nulldiagnosticrenderer_invalidate_node_cache_line_122_e4567c21_descriptor_json();
const char* src_adapters_rendering_null_renderer_nulldiagnosticrenderer_invalidate_all_line_125_33366afb_descriptor_json();
const char* src_adapters_rendering_null_renderer_nulldiagnosticrenderer_get_diagnostics_line_128_0f247a15_descriptor_json();
const char* src_core_rendering_renderer_capabilities_renderercapabilities_to_dict_line_56_96c9be59_descriptor_json();
const char* src_core_rendering_renderer_capabilities_renderercapabilities_status_text_line_152_fec5213f_descriptor_json();
const char* src_core_rendering_renderer_capabilities_renderercapabilities_supports_display_mode_line_158_98c34e96_descriptor_json();
const char* src_core_rendering_renderer_interface_iviewportrenderer_is_available_line_16_d8d6e763_descriptor_json();
const char* src_core_rendering_renderer_interface_iviewportrenderer_get_capabilities_line_20_71760aee_descriptor_json();
const char* src_core_rendering_renderer_interface_iviewportrenderer_initialize_line_23_3c747f18_descriptor_json();
const char* src_core_rendering_renderer_interface_iviewportrenderer_create_surface_widget_line_26_1ab290cd_descriptor_json();
const char* src_core_rendering_renderer_interface_iviewportrenderer_resize_line_29_a241a354_descriptor_json();
const char* src_core_rendering_renderer_interface_iviewportrenderer_render_line_33_528a49c1_descriptor_json();
const char* src_core_rendering_renderer_interface_iviewportrenderer_render_overlay_line_36_0ea321a6_descriptor_json();
const char* src_core_rendering_renderer_interface_iviewportrenderer_pick_line_39_e82673ef_descriptor_json();
const char* src_core_rendering_renderer_interface_iviewportrenderer_shutdown_line_42_ff2b66e5_descriptor_json();
const char* src_core_rendering_renderer_interface_iviewportrenderer_get_diagnostics_line_47_5c5843ca_descriptor_json();
const char* src_core_rendering_renderer_interface_iviewportrenderer_upload_mesh_line_57_1fd39e44_descriptor_json();
const char* src_core_rendering_renderer_interface_iviewportrenderer_upload_texture_line_60_26f8032d_descriptor_json();
const char* src_core_rendering_renderer_interface_iviewportrenderer_release_resource_line_63_107b6898_descriptor_json();
const char* src_core_rendering_renderer_interface_iviewportrenderer_invalidate_all_line_66_8f695e92_descriptor_json();

const PythonFunctionDescriptorEntry* instancemethods_descriptors(std::size_t& count);

} // namespace ghostrigger::phase15::ghostrigger_renderer_null
