#pragma once

#define IDR_SPLASH_LOGO 101
#define IDR_SPLASH_ICON_CHECK 201
#define IDR_SPLASH_ICON_DOCUMENT 202
#define IDR_SPLASH_ICON_GEAR 203
#define IDR_SPLASH_ICON_SPINNER 204
#define IDR_SPLASH_ICON_TERMINAL 205
#define IDR_SPLASH_ICON_TRASH 206
