"""GhostRigger suite-level project/session model."""

from .ghostrigger_project import (
    CURRENT_GHOSTRIGGER_PROJECT_SCHEMA_VERSION,
    GHOSTRIGGER_PROJECT_FILE_TYPE,
    CharacterJobRef,
    ExportCandidateRef,
    GameInstallRef,
    GhostRiggerProject,
    MapProjectRef,
    ModuleWorkspaceRef,
    ProjectAssetRef,
    RetargetJobRef,
    ScenarioPackageRef,
    ValidationSnapshotRef,
    load_ghostrigger_project,
    save_ghostrigger_project,
    stable_project_id,
    utc_now_iso,
)
from .project_validation import (
    KOTOR_RESREF_MAX_LEN,
    ProjectValidationIssue,
    ProjectValidationReport,
    validate_ghostrigger_project,
    validate_resource_address,
)
from .resource_address import ResourceAddress, SUPPORTED_RESOURCE_ADDRESS_SCHEMES
from .placeable_asset import (
    CURRENT_PLACEABLE_ASSET_SCHEMA_VERSION,
    PLACEABLE_ASSET_FILE_SUFFIX,
    PLACEABLE_ASSET_FILE_TYPE,
    PLACEABLE_CATEGORIES,
    PLACEABLE_SCRIPT_HOOKS,
    PlaceableAppearanceMappingEvidence,
    PlaceableAsset,
    PlaceableAssetValidation,
    PlaceableBaseTemplateEvidence,
    PlaceableGameplay,
    PlaceableResourceRefs,
    load_placeable_asset,
    save_placeable_asset,
    validate_placeable_asset,
)

__all__ = [
    "CURRENT_GHOSTRIGGER_PROJECT_SCHEMA_VERSION",
    "GHOSTRIGGER_PROJECT_FILE_TYPE",
    "KOTOR_RESREF_MAX_LEN",
    "SUPPORTED_RESOURCE_ADDRESS_SCHEMES",
    "CURRENT_PLACEABLE_ASSET_SCHEMA_VERSION",
    "PLACEABLE_ASSET_FILE_SUFFIX",
    "PLACEABLE_ASSET_FILE_TYPE",
    "PLACEABLE_CATEGORIES",
    "PLACEABLE_SCRIPT_HOOKS",
    "CharacterJobRef",
    "ExportCandidateRef",
    "GameInstallRef",
    "GhostRiggerProject",
    "MapProjectRef",
    "ModuleWorkspaceRef",
    "ProjectAssetRef",
    "ProjectValidationIssue",
    "ProjectValidationReport",
    "PlaceableAppearanceMappingEvidence",
    "PlaceableAsset",
    "PlaceableAssetValidation",
    "PlaceableBaseTemplateEvidence",
    "PlaceableGameplay",
    "PlaceableResourceRefs",
    "ResourceAddress",
    "RetargetJobRef",
    "ScenarioPackageRef",
    "ValidationSnapshotRef",
    "load_ghostrigger_project",
    "load_placeable_asset",
    "save_ghostrigger_project",
    "save_placeable_asset",
    "stable_project_id",
    "utc_now_iso",
    "validate_ghostrigger_project",
    "validate_resource_address",
    "validate_placeable_asset",
]
