#pragma once

#include <cstddef>

namespace ghostrigger::windows::leveleditor {

#ifndef GHOSTRIGGER_WINDOWS_LEVELEDITOR_NATIVE_FUNCTION_IMPLEMENTATION_DEFINED
#define GHOSTRIGGER_WINDOWS_LEVELEDITOR_NATIVE_FUNCTION_IMPLEMENTATION_DEFINED
struct NativeFunctionImplementation {
    const char* project;
    const char* native_namespace;
    const char* python_file;
    const char* qualname;
    const char* callable_type;
    const char* implementation_status;
    bool native_first;
    bool python_runtime_required;
    bool python_fallback_allowed;
    const char* contract_json;
};
#endif // GHOSTRIGGER_WINDOWS_LEVELEDITOR_NATIVE_FUNCTION_IMPLEMENTATION_DEFINED

const NativeFunctionImplementation& moduleeditorwindow_construct_line_31_be9ea805_native();
const NativeFunctionImplementation& moduleeditorwindow_build_actions_line_67_23578e5a_native();
const NativeFunctionImplementation& moduleeditorwindow_build_menus_line_90_c5bfb990_native();
const NativeFunctionImplementation& moduleeditorwindow_build_ui_line_130_599e81fe_native();
const NativeFunctionImplementation& moduleeditorwindow_connect_line_210_0fe403f5_native();
const NativeFunctionImplementation& moduleeditorwindow_new_kmap_line_249_f3194079_native();
const NativeFunctionImplementation& moduleeditorwindow_open_kmap_line_255_695784d8_native();
const NativeFunctionImplementation& moduleeditorwindow_save_kmap_line_267_a09bdc00_native();
const NativeFunctionImplementation& moduleeditorwindow_save_kmap_as_line_274_2fd899d1_native();
const NativeFunctionImplementation& moduleeditorwindow_import_module_line_283_d2f36914_native();
const NativeFunctionImplementation& moduleeditorwindow_set_library_rows_line_290_d324a329_native();
const NativeFunctionImplementation& moduleeditorwindow_set_renderer_settings_line_294_59128e76_native();
const NativeFunctionImplementation& moduleeditorwindow_import_selected_library_asset_line_300_f9fada76_native();
const NativeFunctionImplementation& moduleeditorwindow_import_library_asset_line_308_7f45bbd4_native();
const NativeFunctionImplementation& moduleeditorwindow_delete_selected_line_318_f52c1ded_native();
const NativeFunctionImplementation& moduleeditorwindow_duplicate_selected_line_322_5d9e773d_native();
const NativeFunctionImplementation& moduleeditorwindow_rename_selected_line_326_cff62055_native();
const NativeFunctionImplementation& moduleeditorwindow_validate_kmap_line_338_fa00022a_native();
const NativeFunctionImplementation& moduleeditorwindow_build_module_files_line_345_6e7827cc_native();
const NativeFunctionImplementation& moduleeditorwindow_export_fbx_line_356_82e013fe_native();
const NativeFunctionImplementation& moduleeditorwindow_open_output_folder_line_368_cdd3a925_native();
const NativeFunctionImplementation& moduleeditorwindow_select_item_line_374_9e8b5d5c_native();
const NativeFunctionImplementation& moduleeditorwindow_closeevent_line_381_529d54a9_native();
const NativeFunctionImplementation& moduleeditorwindow_toolbar_action_line_387_ce0a337a_native();
const NativeFunctionImplementation& moduleeditorwindow_handle_tab_action_line_403_3aa0a1d5_native();
const NativeFunctionImplementation& moduleeditorwindow_outliner_action_line_460_f242d253_native();
const NativeFunctionImplementation& moduleeditorwindow_set_transform_line_477_cbb03039_native();
const NativeFunctionImplementation& moduleeditorwindow_set_visibility_line_481_eb37a9f7_native();
const NativeFunctionImplementation& moduleeditorwindow_set_locked_line_485_6db92745_native();
const NativeFunctionImplementation& moduleeditorwindow_set_property_line_489_29ec5e9f_native();
const NativeFunctionImplementation& moduleeditorwindow_refresh_all_line_500_aa4f3b0f_native();
const NativeFunctionImplementation& moduleeditorwindow_log_line_510_eaf80985_native();
const NativeFunctionImplementation& moduleeditorwindow_confirm_discard_or_save_line_516_9bb8abbf_native();
const NativeFunctionImplementation& moduleeditorwindow_reset_layout_line_532_c7d33cd9_native();
const NativeFunctionImplementation& moduleeditorwindow_show_help_line_538_8328d231_native();
const NativeFunctionImplementation& moduleeditorwindow_set_navigation_profile_line_545_312769ed_native();
const NativeFunctionImplementation& moduleeditorwindow_apply_ghost_theme_line_548_884ad234_native();
const NativeFunctionImplementation& moduleeditorwindow_apply_native_theme_line_568_d2aa7db5_native();
const NativeFunctionImplementation& moduleeditorwindow_apply_ghost_layout_line_577_7c9b9905_native();
const NativeFunctionImplementation& qtblueprinteditorpanel_construct_line_14_f6423f87_native();
const NativeFunctionImplementation& qtblueprinteditorpanel_build_line_18_5afd08b6_native();
const NativeFunctionImplementation& qtblueprinteditorpanel_new_blueprint_line_46_7e173b95_native();
const NativeFunctionImplementation& qtblueprinteditorpanel_load_ipc_resource_payload_line_50_676e7700_native();
const NativeFunctionImplementation& qtblueprinteditorpanel_open_blueprint_line_78_bd1f29e6_native();
const NativeFunctionImplementation& qtblueprinteditorpanel_save_blueprint_line_94_0783f7d8_native();
const NativeFunctionImplementation& qtblueprinteditorwindow_construct_line_119_58f5d711_native();
const NativeFunctionImplementation& qtblueprinteditorwindow_new_blueprint_line_127_b62baf14_native();
const NativeFunctionImplementation& qtblueprinteditorwindow_open_blueprint_line_130_fd0d1e85_native();
const NativeFunctionImplementation& qtblueprinteditorwindow_save_blueprint_line_133_398be2ae_native();

const NativeFunctionImplementation* instancemethods_native_functions(std::size_t& count);

} // namespace ghostrigger::windows::leveleditor
