#pragma once

#include <cstddef>

namespace ghostrigger::phase15::ghostrigger_windows_leveleditor {

using PythonFunctionDescriptorJson = const char* (*)();

struct PythonFunctionDescriptorEntry {
    const char* python_file;
    const char* qualname;
    const char* function_type;
    PythonFunctionDescriptorJson descriptor_json;
};

const char* src_gui_windows_module_editor_window_moduleeditorwindow_init_line_31_be9ea805_descriptor_json();
const char* src_gui_windows_module_editor_window_moduleeditorwindow_build_actions_line_67_23578e5a_descriptor_json();
const char* src_gui_windows_module_editor_window_moduleeditorwindow_build_menus_line_90_c5bfb990_descriptor_json();
const char* src_gui_windows_module_editor_window_moduleeditorwindow_build_ui_line_130_599e81fe_descriptor_json();
const char* src_gui_windows_module_editor_window_moduleeditorwindow_connect_line_210_0fe403f5_descriptor_json();
const char* src_gui_windows_module_editor_window_moduleeditorwindow_new_kmap_line_249_f3194079_descriptor_json();
const char* src_gui_windows_module_editor_window_moduleeditorwindow_open_kmap_line_255_695784d8_descriptor_json();
const char* src_gui_windows_module_editor_window_moduleeditorwindow_save_kmap_line_267_a09bdc00_descriptor_json();
const char* src_gui_windows_module_editor_window_moduleeditorwindow_save_kmap_as_line_274_2fd899d1_descriptor_json();
const char* src_gui_windows_module_editor_window_moduleeditorwindow_import_module_line_283_d2f36914_descriptor_json();
const char* src_gui_windows_module_editor_window_moduleeditorwindow_set_library_rows_line_290_d324a329_descriptor_json();
const char* src_gui_windows_module_editor_window_moduleeditorwindow_set_renderer_settings_line_294_59128e76_descriptor_json();
const char* src_gui_windows_module_editor_window_moduleeditorwindow_import_selected_library_asset_line_300_f9fada76_descriptor_json();
const char* src_gui_windows_module_editor_window_moduleeditorwindow_import_library_asset_line_308_7f45bbd4_descriptor_json();
const char* src_gui_windows_module_editor_window_moduleeditorwindow_delete_selected_line_318_f52c1ded_descriptor_json();
const char* src_gui_windows_module_editor_window_moduleeditorwindow_duplicate_selected_line_322_5d9e773d_descriptor_json();
const char* src_gui_windows_module_editor_window_moduleeditorwindow_rename_selected_line_326_cff62055_descriptor_json();
const char* src_gui_windows_module_editor_window_moduleeditorwindow_validate_kmap_line_338_fa00022a_descriptor_json();
const char* src_gui_windows_module_editor_window_moduleeditorwindow_build_module_files_line_345_6e7827cc_descriptor_json();
const char* src_gui_windows_module_editor_window_moduleeditorwindow_export_fbx_line_356_82e013fe_descriptor_json();
const char* src_gui_windows_module_editor_window_moduleeditorwindow_open_output_folder_line_368_cdd3a925_descriptor_json();
const char* src_gui_windows_module_editor_window_moduleeditorwindow_select_item_line_374_9e8b5d5c_descriptor_json();
const char* src_gui_windows_module_editor_window_moduleeditorwindow_closeevent_line_381_529d54a9_descriptor_json();
const char* src_gui_windows_module_editor_window_moduleeditorwindow_toolbar_action_line_387_ce0a337a_descriptor_json();
const char* src_gui_windows_module_editor_window_moduleeditorwindow_handle_tab_action_line_403_3aa0a1d5_descriptor_json();
const char* src_gui_windows_module_editor_window_moduleeditorwindow_outliner_action_line_460_f242d253_descriptor_json();
const char* src_gui_windows_module_editor_window_moduleeditorwindow_set_transform_line_477_cbb03039_descriptor_json();
const char* src_gui_windows_module_editor_window_moduleeditorwindow_set_visibility_line_481_eb37a9f7_descriptor_json();
const char* src_gui_windows_module_editor_window_moduleeditorwindow_set_locked_line_485_6db92745_descriptor_json();
const char* src_gui_windows_module_editor_window_moduleeditorwindow_set_property_line_489_29ec5e9f_descriptor_json();
const char* src_gui_windows_module_editor_window_moduleeditorwindow_refresh_all_line_500_aa4f3b0f_descriptor_json();
const char* src_gui_windows_module_editor_window_moduleeditorwindow_log_line_510_eaf80985_descriptor_json();
const char* src_gui_windows_module_editor_window_moduleeditorwindow_confirm_discard_or_save_line_516_9bb8abbf_descriptor_json();
const char* src_gui_windows_module_editor_window_moduleeditorwindow_reset_layout_line_532_c7d33cd9_descriptor_json();
const char* src_gui_windows_module_editor_window_moduleeditorwindow_show_help_line_538_8328d231_descriptor_json();
const char* src_gui_windows_module_editor_window_moduleeditorwindow_set_navigation_profile_line_545_312769ed_descriptor_json();
const char* src_gui_windows_module_editor_window_moduleeditorwindow_apply_ghost_theme_line_548_884ad234_descriptor_json();
const char* src_gui_windows_module_editor_window_moduleeditorwindow_apply_native_theme_line_568_d2aa7db5_descriptor_json();
const char* src_gui_windows_module_editor_window_moduleeditorwindow_apply_ghost_layout_line_577_7c9b9905_descriptor_json();
const char* src_gui_windows_qt_blueprint_editor_qtblueprinteditorpanel_init_line_14_f6423f87_descriptor_json();
const char* src_gui_windows_qt_blueprint_editor_qtblueprinteditorpanel_build_line_18_5afd08b6_descriptor_json();
const char* src_gui_windows_qt_blueprint_editor_qtblueprinteditorpanel_new_blueprint_line_46_7e173b95_descriptor_json();
const char* src_gui_windows_qt_blueprint_editor_qtblueprinteditorpanel_load_ipc_resource_payload_line_50_676e7700_descriptor_json();
const char* src_gui_windows_qt_blueprint_editor_qtblueprinteditorpanel_open_blueprint_line_78_bd1f29e6_descriptor_json();
const char* src_gui_windows_qt_blueprint_editor_qtblueprinteditorpanel_save_blueprint_line_94_0783f7d8_descriptor_json();
const char* src_gui_windows_qt_blueprint_editor_qtblueprinteditorwindow_init_line_119_58f5d711_descriptor_json();
const char* src_gui_windows_qt_blueprint_editor_qtblueprinteditorwindow_new_blueprint_line_127_b62baf14_descriptor_json();
const char* src_gui_windows_qt_blueprint_editor_qtblueprinteditorwindow_open_blueprint_line_130_fd0d1e85_descriptor_json();
const char* src_gui_windows_qt_blueprint_editor_qtblueprinteditorwindow_save_blueprint_line_133_398be2ae_descriptor_json();

const PythonFunctionDescriptorEntry* instancemethods_descriptors(std::size_t& count);

} // namespace ghostrigger::phase15::ghostrigger_windows_leveleditor
