"""Focused contracts for Ghost Studio's embedded spatial profile bootstrap."""

from __future__ import annotations

import ast
import base64
import importlib.util
import os
from pathlib import Path
import re
import sys
from types import SimpleNamespace

import pytest


ROOT = Path(__file__).resolve().parents[1]
IPC_ROOT = (
    ROOT
    / "native"
    / "GhostRigger.Core.Automation"
    / "Python"
    / "src"
    / "ipc"
)
AUTH_MODULE = IPC_ROOT / "spatial_auth.py"
ANCHOR_MODULE = IPC_ROOT / "spatial_profile_anchor.py"
QT_MAIN_WINDOW = (
    ROOT
    / "native"
    / "GhostRigger.Core.GUI.Display"
    / "Python"
    / "src"
    / "gui"
    / "windows"
    / "qt_main_window.py"
)
PACKAGE_SID = (
    "S-1-15-2-1229027098-1376173174-3902671414-3221589281-"
    "1354859120-752965424-969501979"
)


def _auth_module():
    spec = importlib.util.spec_from_file_location(
        "ghoststudio_spatial_embedded_bootstrap_test_module",
        AUTH_MODULE,
    )
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


def _anchor(module, approval_id: str = "ab" * 32):
    return module.SpatialProfileAnchor(
        schema="ghoststudio-spatial-profile-anchor/v1",
        adapter_id="ghoststudio",
        approval_id=approval_id,
        transport="windows-named-pipe-v1",
        identity_derivation="approval-sha256-base64url-userenv-v1",
    )


def _qt_start_ipc_server_method(namespace: dict[str, object]):
    tree = ast.parse(QT_MAIN_WINDOW.read_text(encoding="utf-8"))
    window_class = next(
        node
        for node in tree.body
        if isinstance(node, ast.ClassDef)
        and node.name == "QtGhostRiggerMainWindow"
    )
    method = next(
        node
        for node in window_class.body
        if isinstance(node, ast.FunctionDef)
        and node.name == "_start_ipc_server"
    )
    module = ast.fix_missing_locations(
        ast.Module(body=[method], type_ignores=[])
    )
    exec(compile(module, str(QT_MAIN_WINDOW), "exec"), namespace)
    return namespace["_start_ipc_server"]


class _FakeWindow:
    def __init__(self) -> None:
        self._ipc_server = None
        self._scripter_compat_ipc_server = None
        self.messages: list[tuple[str, str]] = []

    def _log(self, message: str, level: str) -> None:
        self.messages.append((message, level))

    def __getattr__(self, _name: str):
        return lambda *_args, **_kwargs: {}


class _FakeIPCServer:
    instances: list["_FakeIPCServer"] = []
    fail_start_indexes: set[int] = set()

    def __init__(self, callbacks, **kwargs) -> None:
        self.callbacks = callbacks
        self.kwargs = kwargs
        self.index = len(self.instances)
        self.port = int(kwargs.get("port", 7001))
        self.start_calls = 0
        self.stop_calls = 0
        self.instances.append(self)

    def start(self) -> None:
        self.start_calls += 1
        if self.index in self.fail_start_indexes:
            raise RuntimeError("expected startup failure")

    def stop(self) -> None:
        self.stop_calls += 1


def _qt_start_namespace(spatial_bootstrap):
    _FakeIPCServer.instances = []
    _FakeIPCServer.fail_start_indexes = set()
    return {
        "GhostRiggerIPCServer": _FakeIPCServer,
        "_resolve_optional_spatial_bootstrap": lambda: spatial_bootstrap,
        "os": SimpleNamespace(
            environ={"GHOSTSTUDIO_SCRIPTER_IPC_PORT": "7002"}
        ),
        "log": SimpleNamespace(exception=lambda *_args, **_kwargs: None),
    }


def test_embedded_anchor_has_the_exact_generated_byte_contract() -> None:
    anchor = _auth_module().load_embedded_spatial_profile_anchor()
    assert re.fullmatch(r"[a-f0-9]{64}", anchor.approval_id)
    assert anchor.approval_id != "0" * 64
    expected = (
        '# Generated by MCPStudio; do not edit.\n'
        'SCHEMA = "ghoststudio-spatial-profile-anchor/v1"\n'
        'ADAPTER_ID = "ghoststudio"\n'
        f'APPROVAL_ID = "{anchor.approval_id}"\n'
        'TRANSPORT = "windows-named-pipe-v1"\n'
        'IDENTITY_DERIVATION = '
        '"approval-sha256-base64url-userenv-v1"\n'
    ).encode("utf-8")

    assert ANCHOR_MODULE.read_bytes() == expected


def test_embedded_anchor_loader_wraps_parse_failures_with_stable_code(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    module = _auth_module()

    class _FailingLoader:
        def exec_module(self, _module) -> None:
            raise SyntaxError("private parser detail")

    spec = SimpleNamespace(loader=_FailingLoader())
    monkeypatch.setattr(
        module.importlib.util,
        "spec_from_file_location",
        lambda *_args, **_kwargs: spec,
    )
    monkeypatch.setattr(
        module.importlib.util,
        "module_from_spec",
        lambda _spec: SimpleNamespace(),
    )

    with pytest.raises(module.SpatialAuthenticationError) as error:
        module.load_embedded_spatial_profile_anchor()

    assert error.value.code == "invalid-spatial-profile-anchor"


@pytest.mark.parametrize(
    ("field", "value"),
    [
        ("schema", "ghoststudio-spatial-profile-anchor/v2"),
        ("adapter_id", "other"),
        ("approval_id", "A" * 64),
        ("approval_id", "0" * 63),
        ("transport", "loopback-http"),
        ("identity_derivation", "other"),
    ],
)
def test_spatial_profile_anchor_rejects_noncanonical_values(
    field: str,
    value: str,
) -> None:
    module = _auth_module()
    values = {
        "schema": "ghoststudio-spatial-profile-anchor/v1",
        "adapter_id": "ghoststudio",
        "approval_id": "ab" * 32,
        "transport": "windows-named-pipe-v1",
        "identity_derivation": (
            "approval-sha256-base64url-userenv-v1"
        ),
    }
    values[field] = value

    with pytest.raises(module.SpatialAuthenticationError) as error:
        module.SpatialProfileAnchor(**values)

    assert error.value.code == "invalid-spatial-profile-anchor"


def test_windows_moniker_derivation_matches_mcpstudio_base64url_contract() -> None:
    module = _auth_module()
    approval_id = "0123456789abcdef" * 4
    encoded = base64.urlsafe_b64encode(
        bytes.fromhex(approval_id)
    ).decode("ascii").rstrip("=")

    moniker = module.derive_windows_spatial_profile_moniker(approval_id)

    assert moniker == f"GhostMCPStudio.{encoded}"
    assert len(encoded) == 43


def test_windows_profile_bootstrap_requires_fixed_packages_root_and_low_il(
    tmp_path: Path,
) -> None:
    module = _auth_module()
    anchor = _anchor(module)
    local_app_data = tmp_path / "Local"
    moniker = module.derive_windows_spatial_profile_moniker(
        anchor.approval_id
    )
    packages_root = local_app_data / "Packages"
    profile_root = packages_root / moniker / "AC"
    profile_root.mkdir(parents=True)
    audited: list[Path] = []

    bootstrap = module.resolve_windows_spatial_server_bootstrap(
        anchor,
        environ={"LOCALAPPDATA": str(local_app_data)},
        native_profile_resolver=lambda observed: (
            PACKAGE_SID,
            profile_root,
        )
        if observed == moniker
        else pytest.fail("unexpected moniker"),
        low_integrity_audit=audited.append,
    )

    assert bootstrap.anchor == anchor
    assert bootstrap.identity.moniker == moniker
    assert bootstrap.identity.package_sid == PACKAGE_SID
    assert bootstrap.identity.profile_root == profile_root
    assert bootstrap.session_path == (
        profile_root
        / "MCPStudioState"
        / "GhostStudioSpatial"
        / "ghoststudio-session.json"
    )
    assert audited == [profile_root]


def test_windows_profile_bootstrap_rejects_wrong_root_and_placeholder(
    tmp_path: Path,
) -> None:
    module = _auth_module()
    local_app_data = tmp_path / "Local"
    wrong_root = tmp_path / "Other" / "profile"
    wrong_root.mkdir(parents=True)

    with pytest.raises(module.SpatialAuthenticationError) as placeholder:
        module.resolve_windows_spatial_server_bootstrap(
            _anchor(module, "0" * 64),
            environ={"LOCALAPPDATA": str(local_app_data)},
            native_profile_resolver=lambda _moniker: (
                PACKAGE_SID,
                wrong_root,
            ),
            low_integrity_audit=lambda _path: None,
        )
    assert placeholder.value.code == "unapproved-spatial-profile"

    with pytest.raises(module.SpatialAuthenticationError) as wrong:
        module.resolve_windows_spatial_server_bootstrap(
            _anchor(module),
            environ={"LOCALAPPDATA": str(local_app_data)},
            native_profile_resolver=lambda _moniker: (
                PACKAGE_SID,
                wrong_root,
            ),
            low_integrity_audit=lambda _path: None,
        )
    assert wrong.value.code == "invalid-spatial-profile-root"


@pytest.mark.parametrize(
    "environment",
    [
        {"GHOSTSTUDIO_SPATIAL_TRANSPORT": "loopback-http"},
        {"ghoststudio_spatial_app_container_sid": "S-1-15-2-0-0-0-0-0-0-0"},
        {"GHOSTSTUDIO_SPATIAL_SESSION_PATH": "C:\\wrong\\session.json"},
        {"GHOSTSTUDIO_SPATIAL_URL": "http://127.0.0.1:7001"},
        {"ghoststudio_spatial_port": "7001"},
    ],
)
def test_spatial_bootstrap_rejects_conflicting_reserved_environment(
    tmp_path: Path,
    environment: dict[str, str],
) -> None:
    module = _auth_module()
    anchor = _anchor(module)
    moniker = module.derive_windows_spatial_profile_moniker(
        anchor.approval_id
    )
    profile_root = tmp_path / "Local" / "Packages" / moniker
    profile_root.mkdir(parents=True)
    bootstrap = module.SpatialServerBootstrap(
        anchor=anchor,
        identity=module.WindowsSpatialProfileIdentity(
            moniker=moniker,
            package_sid=PACKAGE_SID,
            profile_root=profile_root,
        ),
        session_path=(
            profile_root
            / "MCPStudioState"
            / "GhostStudioSpatial"
            / "ghoststudio-session.json"
        ),
    )

    with pytest.raises(module.SpatialAuthenticationError) as error:
        module.assert_spatial_bootstrap_environment(
            bootstrap,
            environment,
        )

    assert error.value.code == "conflicting-spatial-environment"


def test_spatial_bootstrap_allows_absent_or_exact_reserved_environment(
    tmp_path: Path,
) -> None:
    module = _auth_module()
    anchor = _anchor(module)
    moniker = module.derive_windows_spatial_profile_moniker(
        anchor.approval_id
    )
    profile_root = tmp_path / "Local" / "Packages" / moniker
    profile_root.mkdir(parents=True)
    session_path = (
        profile_root
        / "MCPStudioState"
        / "GhostStudioSpatial"
        / "ghoststudio-session.json"
    )
    bootstrap = module.SpatialServerBootstrap(
        anchor=anchor,
        identity=module.WindowsSpatialProfileIdentity(
            moniker=moniker,
            package_sid=PACKAGE_SID,
            profile_root=profile_root,
        ),
        session_path=session_path,
    )

    module.assert_spatial_bootstrap_environment(bootstrap, {})
    module.assert_spatial_bootstrap_environment(
        bootstrap,
        {
            module.SPATIAL_TRANSPORT_ENV: module.WINDOWS_SPATIAL_TRANSPORT,
            module.SPATIAL_APP_CONTAINER_SID_ENV: PACKAGE_SID,
            module.SPATIAL_SESSION_PATH_ENV: str(session_path),
        },
    )


def test_gui_spatial_startup_fails_closed_without_tearing_down_legacy_ipc(
) -> None:
    bootstrap = object()
    namespace = _qt_start_namespace(bootstrap)
    _FakeIPCServer.fail_start_indexes = {0}
    start_ipc_server = _qt_start_ipc_server_method(namespace)
    window = _FakeWindow()

    start_ipc_server(window)

    spatial_attempt, legacy_fallback, compatibility = (
        _FakeIPCServer.instances
    )
    assert spatial_attempt.kwargs["spatial_bootstrap"] is bootstrap
    assert spatial_attempt.stop_calls == 1
    assert legacy_fallback.kwargs["spatial_bootstrap"] is None
    assert "spatial_session_path" not in legacy_fallback.kwargs
    assert legacy_fallback.stop_calls == 0
    assert compatibility.kwargs["program_name"] == (
        "GhostStudio Scripting Suite"
    )
    assert compatibility.stop_calls == 0
    assert window._ipc_server is legacy_fallback
    assert window._scripter_compat_ipc_server is compatibility


def test_gui_ipc_startup_retries_only_the_missing_independent_server() -> None:
    namespace = _qt_start_namespace(None)
    start_ipc_server = _qt_start_ipc_server_method(namespace)
    window = _FakeWindow()
    existing_primary = SimpleNamespace(port=7001, stop_calls=0)
    window._ipc_server = existing_primary

    start_ipc_server(window)

    assert window._ipc_server is existing_primary
    assert len(_FakeIPCServer.instances) == 1
    assert _FakeIPCServer.instances[0].kwargs["program_name"] == (
        "GhostStudio Scripting Suite"
    )
    assert window._scripter_compat_ipc_server is _FakeIPCServer.instances[0]


def test_gui_compatibility_failure_never_stops_primary_server() -> None:
    namespace = _qt_start_namespace(None)
    _FakeIPCServer.fail_start_indexes = {1}
    start_ipc_server = _qt_start_ipc_server_method(namespace)
    window = _FakeWindow()

    start_ipc_server(window)

    primary, compatibility = _FakeIPCServer.instances
    assert window._ipc_server is primary
    assert primary.stop_calls == 0
    assert compatibility.stop_calls == 1
    assert window._scripter_compat_ipc_server is None
