#pragma once

#include <cstddef>

namespace ghostrigger::phase15::ghostrigger_tools_export {

using PythonFunctionDescriptorJson = const char* (*)();

struct PythonFunctionDescriptorEntry {
    const char* python_file;
    const char* qualname;
    const char* function_type;
    PythonFunctionDescriptorJson descriptor_json;
};

const char* src_core_characters_character_export_transaction_characterbuilderexporttransactionrequest_post_init_line_67_ccaeb70b_descriptor_json();
const char* src_core_export_export_job_exportoutputspec_post_init_line_42_572c8711_descriptor_json();
const char* src_core_export_export_job_exportjobrequest_post_init_line_58_a4f639c4_descriptor_json();
const char* src_core_export_export_job_exportjobcontext_staged_path_for_line_72_d38bfad0_descriptor_json();
const char* src_core_export_export_job_exportjobcontext_write_bytes_line_79_2cfeb88c_descriptor_json();
const char* src_core_export_export_job_exportjobcontext_write_text_line_84_11dd60e5_descriptor_json();
const char* src_core_export_gltf_importer_glbreader_init_line_112_3d02acfb_descriptor_json();
const char* src_core_export_gltf_importer_glbreader_parse_line_118_39e7a87b_descriptor_json();
const char* src_core_export_gltf_importer_gltfimporter_import_file_line_454_04f56e5d_descriptor_json();
const char* src_core_export_gltf_importer_gltfimporter_import_bytes_line_484_0dfa5942_descriptor_json();
const char* src_core_export_gltf_importer_gltfimporter_import_pygltflib_line_503_9e23c8ae_descriptor_json();
const char* src_core_export_gltf_importer_gltfimporter_process_pygltflib_line_509_a766ad53_descriptor_json();
const char* src_core_export_gltf_importer_gltfimporter_process_gltf_node_pygltflib_line_567_1a107059_descriptor_json();
const char* src_core_export_gltf_importer_gltfimporter_fill_mesh_node_pygltflib_line_616_f4e324fc_descriptor_json();
const char* src_core_export_gltf_importer_gltfimporter_import_animation_pygltflib_line_660_a7dc254b_descriptor_json();
const char* src_core_export_gltf_importer_gltfimporter_import_builtin_line_704_bff5f380_descriptor_json();
const char* src_core_export_gltf_importer_gltfimporter_import_builtin_bytes_line_709_6c712b8b_descriptor_json();
const char* src_core_export_gltf_importer_gltfimporter_process_gltf_node_builtin_line_763_7bd75ca4_descriptor_json();
const char* src_core_export_gltf_importer_gltfimporter_fill_mesh_node_builtin_line_817_519f9756_descriptor_json();
const char* src_core_export_gltf_importer_gltfimporter_import_animation_builtin_line_895_87b935ca_descriptor_json();
const char* src_core_export_gltf_importer_fbxfallbackimporter_import_file_line_968_b32feeab_descriptor_json();
const char* src_core_export_gltf_importer_fbxfallbackimporter_load_via_blender_line_1038_f92766d5_descriptor_json();
const char* src_gui_dialogs_qt_export_dialog_qtexportdialog_init_line_57_9d67266a_descriptor_json();
const char* src_gui_dialogs_qt_export_dialog_qtexportdialog_selected_formats_line_152_42d8002d_descriptor_json();
const char* src_gui_dialogs_qt_export_dialog_qtexportdialog_output_dir_line_160_2d0f5273_descriptor_json();
const char* src_gui_dialogs_qt_export_dialog_qtexportdialog_write_sidecar_line_164_b3d656b2_descriptor_json();
const char* src_gui_dialogs_qt_export_dialog_qtexportdialog_on_browse_clicked_line_171_1f8864a1_descriptor_json();
const char* src_gui_dialogs_qt_export_dialog_qtexportdialog_on_accept_line_181_42063f2a_descriptor_json();
const char* src_gui_panels_module_editor_export_panel_moduleexportpanel_init_line_11_fff12482_descriptor_json();

const PythonFunctionDescriptorEntry* instancemethods_descriptors(std::size_t& count);

} // namespace ghostrigger::phase15::ghostrigger_tools_export
