# Generated by MCPStudio; do not edit.
SCHEMA = "ghoststudio-spatial-profile-anchor/v1"
ADAPTER_ID = "ghoststudio"
APPROVAL_ID = "440724beebabaa1a5ec0ec0b725d13a2ca448c770a2e44f45127290da8542e86"
TRANSPORT = "windows-named-pipe-v1"
IDENTITY_DERIVATION = "approval-sha256-base64url-userenv-v1"
