#pragma once

#include <cstddef>

namespace ghostrigger::phase15::ghostrigger_tools_bodyattachmentsystem {

using PythonFunctionDescriptorJson = const char* (*)();

struct PythonFunctionDescriptorEntry {
    const char* python_file;
    const char* qualname;
    const char* function_type;
    PythonFunctionDescriptorJson descriptor_json;
};

const char* src_gui_panels_qt_body_attachment_panel_qtbodyattachmentpanel_init_line_83_f681e428_descriptor_json();
const char* src_gui_panels_qt_body_attachment_panel_qtbodyattachmentpanel_build_line_93_2522e5c1_descriptor_json();
const char* src_gui_panels_qt_body_attachment_panel_qtbodyattachmentpanel_selected_slot_line_162_7f212de1_descriptor_json();
const char* src_gui_panels_qt_body_attachment_panel_qtbodyattachmentpanel_selected_mode_line_165_7e7800b2_descriptor_json();
const char* src_gui_panels_qt_body_attachment_panel_qtbodyattachmentpanel_set_mode_line_168_0c3ee976_descriptor_json();
const char* src_gui_panels_qt_body_attachment_panel_qtbodyattachmentpanel_selected_model_resref_line_185_dd042b5d_descriptor_json();
const char* src_gui_panels_qt_body_attachment_panel_qtbodyattachmentpanel_set_selected_slot_line_191_f2c2de62_descriptor_json();
const char* src_gui_panels_qt_body_attachment_panel_qtbodyattachmentpanel_set_body_model_line_205_ceeed903_descriptor_json();
const char* src_gui_panels_qt_body_attachment_panel_qtbodyattachmentpanel_set_slot_model_line_210_c8d64d69_descriptor_json();
const char* src_gui_panels_qt_body_attachment_panel_qtbodyattachmentpanel_clear_slot_model_line_215_9d62b336_descriptor_json();
const char* src_gui_panels_qt_body_attachment_panel_qtbodyattachmentpanel_set_status_line_219_5dd31913_descriptor_json();
const char* src_gui_panels_qt_body_attachment_panel_qtbodyattachmentpanel_populate_model_combo_line_222_2186666a_descriptor_json();
const char* src_gui_panels_qt_body_attachment_panel_qtbodyattachmentpanel_emit_attach_line_231_cddba835_descriptor_json();
const char* src_gui_panels_qt_body_attachment_panel_qtbodyattachmentpanel_set_slot_text_line_238_da26a40d_descriptor_json();
const char* src_gui_panels_qt_body_attachment_panel_qtbodyattachmentpanel_refresh_layers_line_247_ae6a7c13_descriptor_json();
const char* src_gui_panels_qt_body_attachment_panel_qtbodyattachmentpanel_sync_selected_layer_line_273_b273ddea_descriptor_json();
const char* src_gui_panels_qt_body_attachment_panel_qtbodyattachmentpanel_handle_layer_selection_changed_line_287_932184ba_descriptor_json();
const char* src_gui_panels_qt_body_attachment_panel_qtbodyattachmentpanel_handle_mode_changed_line_295_c1f7e0ae_descriptor_json();
const char* src_gui_panels_qt_body_attachment_panel_qtbodyattachmentpanel_layer_rows_line_298_45a17258_descriptor_json();
const char* src_gui_windows_application_core_shared_bas_workflow_basworkflowmixin_handle_bas_mode_changed_line_30_463782ec_descriptor_json();
const char* src_gui_windows_application_core_shared_bas_workflow_basworkflowmixin_bas_mode_for_model_line_45_637e5673_descriptor_json();
const char* src_gui_windows_application_core_shared_bas_workflow_basworkflowmixin_handle_bas_attach_requested_line_52_b913d353_descriptor_json();
const char* src_gui_windows_application_core_shared_bas_workflow_basworkflowmixin_handle_bas_clear_requested_line_113_d2c28306_descriptor_json();
const char* src_gui_windows_application_core_shared_bas_workflow_basworkflowmixin_refresh_bas_animation_panel_after_layer_change_line_128_4f5f1e4b_descriptor_json();
const char* src_gui_windows_application_core_shared_bas_workflow_basworkflowmixin_load_bas_attachment_model_line_143_816e89a5_descriptor_json();
const char* src_gui_windows_application_core_shared_bas_workflow_basworkflowmixin_rebuild_bas_preview_line_156_0cf1b9d1_descriptor_json();
const char* src_gui_windows_application_core_shared_bas_workflow_basworkflowmixin_handle_bas_save_build_requested_line_189_eb9b7858_descriptor_json();
const char* src_gui_windows_application_core_shared_bas_workflow_basworkflowmixin_save_bas_model_recipe_line_216_1bfdd376_descriptor_json();
const char* src_gui_windows_application_core_shared_bas_workflow_basworkflowmixin_reset_bas_model_node_traversal_line_236_e55ba05c_descriptor_json();
const char* src_gui_windows_application_core_shared_bas_workflow_basworkflowmixin_attach_bas_item_to_preview_line_251_3842565e_descriptor_json();
const char* src_gui_windows_application_core_shared_bas_workflow_basworkflowmixin_bas_layer_transform_from_model_line_281_d639e093_descriptor_json();
const char* src_gui_windows_application_core_shared_bas_workflow_basworkflowmixin_apply_bas_layer_transform_line_295_c1f51d6a_descriptor_json();
const char* src_gui_windows_application_core_shared_bas_workflow_basworkflowmixin_prepare_bas_layer_root_line_314_fa1500b9_descriptor_json();
const char* src_gui_windows_application_core_shared_bas_workflow_basworkflowmixin_tag_bas_attachment_subtree_line_328_e5c46d12_descriptor_json();
const char* src_gui_windows_application_core_shared_bas_workflow_basworkflowmixin_find_model_node_line_344_a8e7b853_descriptor_json();
const char* src_gui_windows_application_core_shared_bas_workflow_basworkflowmixin_bas_socket_for_slot_line_355_b5dcdf49_descriptor_json();
const char* src_gui_windows_application_core_shared_bas_workflow_basworkflowmixin_bas_target_scene_object_line_358_4eeb7693_descriptor_json();
const char* src_gui_windows_application_core_shared_bas_workflow_basworkflowmixin_apply_bas_preview_to_viewport_line_384_50d3d7fb_descriptor_json();
const char* src_gui_windows_application_core_shared_bas_workflow_basworkflowmixin_sync_bas_body_animation_engine_line_427_2a6ea634_descriptor_json();
const char* src_gui_windows_application_core_shared_bas_workflow_basworkflowmixin_restore_bas_animation_pose_after_viewport_refresh_line_465_ee920908_descriptor_json();
const char* src_gui_windows_application_core_shared_bas_workflow_basworkflowmixin_request_bas_viewport_refresh_line_485_7bbd9071_descriptor_json();

const PythonFunctionDescriptorEntry* instancemethods_descriptors(std::size_t& count);

} // namespace ghostrigger::phase15::ghostrigger_tools_bodyattachmentsystem
