#pragma once

#include <cstddef>

namespace ghostrigger::phase15::ghostrigger_tools_bodyattachmentsystem {

using PythonFunctionDescriptorJson = const char* (*)();

struct PythonFunctionDescriptorEntry {
    const char* python_file;
    const char* qualname;
    const char* function_type;
    PythonFunctionDescriptorJson descriptor_json;
};

const char* src_core_characters_headless_body_workflow_ground_snapped_target_origin_mapped_line_2011_8a0fe80f_descriptor_json();
const char* src_core_characters_headless_body_workflow_apply_external_model_fit_adjustment_transform_point_line_2309_3b6f063d_descriptor_json();
const char* src_core_characters_headless_body_workflow_normalize_external_model_for_kotor_transform_point_line_2575_98ab7fce_descriptor_json();
const char* src_core_characters_headless_body_workflow_normalize_external_model_for_kotor_transform_direction_line_2579_9f227abd_descriptor_json();
const char* src_core_characters_headless_body_workflow_normalize_external_model_for_kotor_transform_node_position_line_2583_bf5207e2_descriptor_json();
const char* src_core_characters_headless_body_workflow_normalize_external_model_for_kotor_transform_point_line_2692_be866f18_descriptor_json();
const char* src_core_characters_headless_body_workflow_normalize_external_model_for_kotor_transform_direction_line_2700_d3af9a5d_descriptor_json();
const char* src_core_characters_headless_body_workflow_normalize_external_model_for_kotor_transform_node_position_line_2706_3aa6f982_descriptor_json();
const char* src_core_characters_headless_body_workflow_with_supermodel_resource_manager_resolvercontext_init_line_5113_fc886da7_descriptor_json();
const char* src_core_characters_headless_body_workflow_with_supermodel_resource_manager_resolvercontext_enter_line_5118_e5652f36_descriptor_json();
const char* src_core_characters_headless_body_workflow_with_supermodel_resource_manager_resolvercontext_exit_line_5131_fed9154f_descriptor_json();
const char* src_core_characters_headless_body_workflow_model_nodes_walk_line_5184_c22f7bba_descriptor_json();
const char* src_core_characters_headless_body_workflow_export_single_format_reload_exported_line_5841_aa70b842_descriptor_json();
const char* src_systems_bas_attachment_alignment_normalize_bas_transform_values_line_38_bdcb89bd_descriptor_json();
const char* src_systems_bas_model_recipe_normalize_bas_layer_transform_values_line_162_3ef7d12a_descriptor_json();

const PythonFunctionDescriptorEntry* nestedfunctions_descriptors(std::size_t& count);

} // namespace ghostrigger::phase15::ghostrigger_tools_bodyattachmentsystem
