#pragma once

#include <cstddef>

namespace ghostrigger::core::resources {

#ifndef GHOSTRIGGER_RESOURCES_NATIVE_FUNCTION_IMPLEMENTATION_DEFINED
#define GHOSTRIGGER_RESOURCES_NATIVE_FUNCTION_IMPLEMENTATION_DEFINED
struct NativeFunctionImplementation {
    const char* project;
    const char* native_namespace;
    const char* python_file;
    const char* qualname;
    const char* callable_type;
    const char* implementation_status;
    bool native_first;
    bool python_runtime_required;
    bool python_fallback_allowed;
    const char* contract_json;
};
#endif // GHOSTRIGGER_RESOURCES_NATIVE_FUNCTION_IMPLEMENTATION_DEFINED

const NativeFunctionImplementation& gameresourcequery_post_construct_line_76_8060f04c_native();
const NativeFunctionImplementation& gameresourcequery_to_address_line_84_27269e94_native();
const NativeFunctionImplementation& gameresourcerecord_post_construct_line_107_9a620728_native();
const NativeFunctionImplementation& gameresourceprovider_list_resources_line_154_13eb721d_native();
const NativeFunctionImplementation& gameresourceprovider_resolve_line_157_db6153cc_native();
const NativeFunctionImplementation& gameresourceprovider_read_bytes_line_160_7e0b3a1b_native();
const NativeFunctionImplementation& gameresourceprovider_exists_line_163_eda4619b_native();
const NativeFunctionImplementation& inmemorygameresourceprovider_construct_line_188_d08dcb62_native();
const NativeFunctionImplementation& inmemorygameresourceprovider_add_line_197_49d40e02_native();
const NativeFunctionImplementation& inmemorygameresourceprovider_list_resources_line_200_2ca86bab_native();
const NativeFunctionImplementation& inmemorygameresourceprovider_list_module_resources_line_205_a022d9b4_native();
const NativeFunctionImplementation& inmemorygameresourceprovider_resolve_line_208_c2b6a07f_native();
const NativeFunctionImplementation& inmemorygameresourceprovider_read_bytes_line_224_2e9321d1_native();
const NativeFunctionImplementation& inmemorygameresourceprovider_read_resource_line_227_8e539aeb_native();
const NativeFunctionImplementation& inmemorygameresourceprovider_exists_line_238_28740a54_native();
const NativeFunctionImplementation& localfileresourceprovider_list_resources_line_249_577bbf95_native();
const NativeFunctionImplementation& localfileresourceprovider_resolve_line_260_dfe7c954_native();
const NativeFunctionImplementation& localfileresourceprovider_read_bytes_line_270_15ed95e3_native();
const NativeFunctionImplementation& localfileresourceprovider_exists_line_273_262362a1_native();
const NativeFunctionImplementation& localfileresourceprovider_record_for_path_line_280_1e0a7666_native();
const NativeFunctionImplementation& compositegameresourceprovider_construct_line_302_f4c139f6_native();
const NativeFunctionImplementation& compositegameresourceprovider_list_resources_line_305_158702ab_native();
const NativeFunctionImplementation& compositegameresourceprovider_list_module_resources_line_311_b9fdbc05_native();
const NativeFunctionImplementation& compositegameresourceprovider_resolve_line_314_8dbf0540_native();
const NativeFunctionImplementation& compositegameresourceprovider_read_bytes_line_334_31527e38_native();
const NativeFunctionImplementation& compositegameresourceprovider_read_resource_line_337_b248788c_native();
const NativeFunctionImplementation& compositegameresourceprovider_exists_line_348_dd7a3867_native();
const NativeFunctionImplementation& resourcemanagergameresourceprovider_construct_line_360_145e2601_native();
const NativeFunctionImplementation& resourcemanagergameresourceprovider_list_resources_line_363_1abeed1b_native();
const NativeFunctionImplementation& resourcemanagergameresourceprovider_list_module_resources_line_374_3e04a171_native();
const NativeFunctionImplementation& resourcemanagergameresourceprovider_resolve_line_377_10f73bb5_native();
const NativeFunctionImplementation& resourcemanagergameresourceprovider_read_bytes_line_413_bd99e881_native();
const NativeFunctionImplementation& resourcemanagergameresourceprovider_read_resource_line_416_6be8f0b0_native();
const NativeFunctionImplementation& resourcemanagergameresourceprovider_exists_line_427_5ef4e963_native();

const NativeFunctionImplementation* instancemethods_native_functions(std::size_t& count);

} // namespace ghostrigger::core::resources
