#pragma once

#include <cstddef>

namespace ghostrigger::phase15::ghostrigger_io {

using PythonFunctionDescriptorJson = const char* (*)();

struct PythonFunctionDescriptorEntry {
    const char* python_file;
    const char* qualname;
    const char* function_type;
    PythonFunctionDescriptorJson descriptor_json;
};

const char* src_io_fbx_fbx_diagnostics_build_fbx_diagnostic_report_line_17_11aebfa4_descriptor_json();
const char* src_io_fbx_fbx_exporter_export_fbx_line_44_c8e1a250_descriptor_json();
const char* src_io_fbx_fbx_exporter_validate_output_path_line_82_82cddbaa_descriptor_json();
const char* src_io_fbx_fbx_exporter_create_sdk_scene_line_91_10c128b6_descriptor_json();
const char* src_io_fbx_fbx_exporter_configure_scene_line_105_b6389ebf_descriptor_json();
const char* src_io_fbx_fbx_exporter_add_payload_to_scene_line_128_fb55d6ef_descriptor_json();
const char* src_io_fbx_fbx_exporter_models_from_payload_line_142_698e116f_descriptor_json();
const char* src_io_fbx_fbx_exporter_copy_model_with_instance_transform_line_172_dc0162f9_descriptor_json();
const char* src_io_fbx_fbx_exporter_create_mesh_node_line_182_5ce9b1e0_descriptor_json();
const char* src_io_fbx_fbx_exporter_new_node_line_199_bd784fd4_descriptor_json();
const char* src_io_fbx_fbx_exporter_set_node_transform_line_204_c09a8d53_descriptor_json();
const char* src_io_fbx_fbx_exporter_choose_writer_format_line_216_0804c3f4_descriptor_json();
const char* src_io_fbx_fbx_exporter_set_io_bool_line_231_3587f7c5_descriptor_json();
const char* src_io_fbx_fbx_exporter_sdk_error_line_240_f743e51e_descriptor_json();
const char* src_io_fbx_fbx_exporter_destroy_line_249_ff344015_descriptor_json();
const char* src_io_fbx_fbx_importer_import_fbx_line_25_f871e4c8_descriptor_json();
const char* src_io_fbx_fbx_importer_validate_fbx_path_line_69_5ac44ef0_descriptor_json();
const char* src_io_fbx_fbx_importer_create_sdk_scene_line_78_e2b5c126_descriptor_json();
const char* src_io_fbx_fbx_importer_triangulate_scene_if_possible_line_92_84755a48_descriptor_json();
const char* src_io_fbx_fbx_importer_scene_to_model_line_103_750d64be_descriptor_json();
const char* src_io_fbx_fbx_importer_convert_node_recursive_line_130_0a8cdcfc_descriptor_json();
const char* src_io_fbx_fbx_importer_safe_node_name_line_148_18ccf31b_descriptor_json();
const char* src_io_fbx_fbx_importer_apply_local_transform_line_157_229199d9_descriptor_json();
const char* src_io_fbx_fbx_importer_is_mesh_attribute_line_169_fc6a1c9e_descriptor_json();
const char* src_io_fbx_fbx_importer_count_skeleton_nodes_line_187_434f0484_descriptor_json();
const char* src_io_fbx_fbx_importer_sdk_error_line_203_4ec44863_descriptor_json();
const char* src_io_fbx_fbx_importer_destroy_line_212_3a6705e2_descriptor_json();
const char* src_io_fbx_fbx_scene_adapter_sdk_class_line_46_29991def_descriptor_json();
const char* src_io_fbx_fbx_scene_adapter_triple_from_fbx_line_51_0b2f928f_descriptor_json();
const char* src_io_fbx_fbx_scene_adapter_name_line_58_2feeb152_descriptor_json();
const char* src_io_fbx_fbx_scene_adapter_clean_name_line_66_88239ce4_descriptor_json();
const char* src_io_fbx_fbx_scene_adapter_euler_degrees_to_quat_xyz_line_71_594df07a_descriptor_json();
const char* src_io_fbx_fbx_scene_adapter_quat_xyzw_to_euler_degrees_line_83_157fe9df_descriptor_json();
const char* src_io_fbx_fbx_scene_adapter_fbx_matrix_to_gr_matrix_line_96_8e665a63_descriptor_json();
const char* src_io_fbx_fbx_scene_adapter_gr_transform_to_fbx_matrix_line_104_893aa93b_descriptor_json();
const char* src_io_fbx_fbx_scene_adapter_fbx_material_to_gr_material_line_120_7b61e66b_descriptor_json();
const char* src_io_fbx_fbx_scene_adapter_fbx_mesh_to_gr_mesh_line_140_2ebe32fe_descriptor_json();
const char* src_io_fbx_fbx_scene_adapter_polygon_material_index_line_225_1272b42f_descriptor_json();
const char* src_io_fbx_fbx_scene_adapter_gr_material_to_fbx_material_line_241_12a86f4a_descriptor_json();
const char* src_io_fbx_fbx_scene_adapter_gr_mesh_to_fbx_mesh_line_272_02cbe32f_descriptor_json();
const char* src_io_fbx_fbx_scene_adapter_iter_renderable_mesh_nodes_line_315_fe26c4aa_descriptor_json();
const char* src_io_fbx_fbx_scene_adapter_count_bone_like_nodes_line_323_2c989b58_descriptor_json();
const char* src_io_fbx_fbx_sdk_loader_import_optional_module_line_30_35fb0ecc_descriptor_json();
const char* src_io_fbx_fbx_sdk_loader_get_fbx_modules_line_37_6143f4fb_descriptor_json();
const char* src_io_fbx_fbx_sdk_loader_configure_fbx_sdk_paths_line_48_cac58998_descriptor_json();
const char* src_io_fbx_fbx_sdk_loader_is_fbx_sdk_available_line_59_fe40de6e_descriptor_json();
const char* src_io_fbx_fbx_sdk_loader_get_fbx_sdk_status_line_64_c20dd245_descriptor_json();
const char* src_io_fbx_fbx_sdk_loader_detect_sdk_version_line_93_18d673d3_descriptor_json();
const char* src_io_fbx_fbx_sdk_paths_normalize_fbx_sdk_settings_line_46_5e24f92c_descriptor_json();
const char* src_io_fbx_fbx_sdk_paths_configured_sdk_paths_line_54_32f15dc4_descriptor_json();
const char* src_io_fbx_fbx_sdk_paths_apply_configured_sdk_paths_line_76_21c90f8a_descriptor_json();
const char* src_io_fbx_fbx_sdk_paths_temporary_sys_path_line_87_4323835c_descriptor_json();
const char* src_io_fbx_fbx_sdk_paths_get_python_runtime_info_line_98_decb3ae1_descriptor_json();
const char* src_io_fbx_fbx_sdk_paths_test_fbx_sdk_configuration_line_122_2e1efdc2_descriptor_json();
const char* src_io_fbx_fbx_sdk_paths_likely_sdk_files_line_167_de5458c8_descriptor_json();
const char* src_io_fbx_fbx_sdk_paths_load_fbx_settings_from_file_line_188_04266fb0_descriptor_json();
const char* src_io_fbx_fbx_sdk_paths_site_packages_line_196_c596da0a_descriptor_json();
const char* src_io_fbx_fbx_sdk_paths_recommended_fix_line_208_0de9a1f8_descriptor_json();
const char* src_io_fbx_fbx_sdk_setup_compatibility_guidance_line_27_6a1b5460_descriptor_json();
const char* src_io_fbx_fbx_sdk_setup_open_autodesk_fbx_download_page_line_56_616ad088_descriptor_json();
const char* src_io_fbx_fbx_sdk_setup_save_successful_configuration_line_62_30e9954d_descriptor_json();
const char* src_io_fbx_fbx_sdk_setup_validate_and_prepare_line_83_5329b90a_descriptor_json();

const PythonFunctionDescriptorEntry* modulefunctions_descriptors(std::size_t& count);

} // namespace ghostrigger::phase15::ghostrigger_io
