#pragma once

#include <cstddef>

namespace ghostrigger::phase15::ghostrigger_validation {

using PythonFunctionDescriptorJson = const char* (*)();

struct PythonFunctionDescriptorEntry {
    const char* python_file;
    const char* qualname;
    const char* function_type;
    PythonFunctionDescriptorJson descriptor_json;
};

const char* src_core_validation_animation_block_validator_animationvalidationreport_add_error_line_44_579fec1b_descriptor_json();
const char* src_core_validation_animation_block_validator_animationvalidationreport_raise_for_errors_line_62_d5d018af_descriptor_json();
const char* src_core_validation_animation_block_validator_rawanimationfootprintreport_add_error_line_103_7d83d5ae_descriptor_json();
const char* src_core_validation_animation_roundtrip_validator_animationroundtripreport_add_error_line_41_81ef342f_descriptor_json();
const char* src_core_validation_animation_roundtrip_validator_animationroundtripreport_add_warning_line_45_e7835240_descriptor_json();
const char* src_core_validation_animation_roundtrip_validator_animationroundtripreport_raise_for_errors_line_48_6b7aba91_descriptor_json();
const char* src_core_validation_capture_specs_viewportcapturespec_post_init_line_41_b935d8fe_descriptor_json();
const char* src_core_validation_capture_specs_viewportvalidationresult_to_dict_line_91_9bff6744_descriptor_json();
const char* src_core_validation_validation_bus_validationnavigationtarget_post_init_line_53_a50f7298_descriptor_json();
const char* src_core_validation_validation_bus_validationissue_post_init_line_70_c7a7d6bb_descriptor_json();
const char* src_core_validation_validation_bus_validationreport_by_severity_line_96_fbbc013b_descriptor_json();
const char* src_core_validation_validation_bus_validationreport_by_subsystem_line_100_5f82b91c_descriptor_json();
const char* src_core_validation_validation_bus_validationreport_add_line_104_0f66274b_descriptor_json();
const char* src_core_validation_validation_bus_validationbus_init_line_111_33bd54c1_descriptor_json();
const char* src_core_validation_validation_bus_validationbus_publish_line_115_a13983cd_descriptor_json();
const char* src_core_validation_validation_bus_validationbus_clear_line_126_38ee04bd_descriptor_json();
const char* src_core_validation_validation_bus_validationbus_snapshot_line_146_f4f08ed3_descriptor_json();
const char* src_core_validation_validation_bus_validationbus_issues_line_149_14aea9ba_descriptor_json();
const char* src_core_validation_validation_bus_validationbus_has_blocking_line_152_7a17f5f2_descriptor_json();
const char* src_core_validation_validation_bus_validationbus_subscribe_line_155_fc8162cd_descriptor_json();
const char* src_core_validation_validation_bus_validationbus_notify_line_166_230e5af8_descriptor_json();
const char* src_core_validation_viewport_validator_viewportvalidator_init_line_42_8a1ebaba_descriptor_json();
const char* src_core_validation_viewport_validator_viewportvalidator_compute_sha256_line_48_b6e16108_descriptor_json();
const char* src_core_validation_viewport_validator_viewportvalidator_load_mdl_line_77_3c344e38_descriptor_json();
const char* src_core_validation_viewport_validator_viewportvalidator_configure_fixture_supermodels_line_112_3a72701f_descriptor_json();
const char* src_core_validation_viewport_validator_viewportvalidator_init_renderer_line_133_633da9eb_descriptor_json();
const char* src_core_validation_viewport_validator_viewportvalidator_init_animation_engine_line_140_51342a43_descriptor_json();
const char* src_core_validation_viewport_validator_viewportvalidator_available_animation_names_line_146_43cf9ba7_descriptor_json();
const char* src_core_validation_viewport_validator_viewportvalidator_set_animation_pose_line_153_47092ef2_descriptor_json();
const char* src_core_validation_viewport_validator_viewportvalidator_camera_angles_line_187_edf2a2c6_descriptor_json();
const char* src_core_validation_viewport_validator_viewportvalidator_capture_filename_line_190_5e0520c7_descriptor_json();
const char* src_core_validation_viewport_validator_viewportvalidator_capture_frame_line_200_12a2e033_descriptor_json();
const char* src_core_validation_viewport_validator_viewportvalidator_extract_bone_positions_line_255_9fe391ae_descriptor_json();
const char* src_core_validation_viewport_validator_viewportvalidator_compute_ssim_line_294_474bdda2_descriptor_json();
const char* src_core_validation_viewport_validator_viewportvalidator_reference_path_line_320_9ea5687b_descriptor_json();
const char* src_core_validation_viewport_validator_viewportvalidator_validate_mdl_line_337_c4398153_descriptor_json();
const char* src_core_validation_viewport_validator_viewportvalidator_calibrate_against_ingame_line_435_d73d17fe_descriptor_json();

const PythonFunctionDescriptorEntry* instancemethods_descriptors(std::size_t& count);

} // namespace ghostrigger::phase15::ghostrigger_validation
