#pragma once

#include <cstddef>

namespace ghostrigger::phase15::ghostrigger_validation {

using PythonFunctionDescriptorJson = const char* (*)();

struct PythonFunctionDescriptorEntry {
    const char* python_file;
    const char* qualname;
    const char* function_type;
    PythonFunctionDescriptorJson descriptor_json;
};

const char* src_core_validation_animation_block_validator_validate_raw_animation_footprint_line_112_d02544a1_descriptor_json();
const char* src_core_validation_animation_block_validator_u32_line_240_9c1f39d4_descriptor_json();
const char* src_core_validation_animation_block_validator_u16_line_246_32ef73da_descriptor_json();
const char* src_core_validation_animation_block_validator_read_c_string_line_252_70542a6a_descriptor_json();
const char* src_core_validation_animation_block_validator_read_name_table_line_261_319df6aa_descriptor_json();
const char* src_core_validation_animation_block_validator_find_animation_offset_line_277_fede4b45_descriptor_json();
const char* src_core_validation_animation_block_validator_controller_label_line_300_aa0bf618_descriptor_json();
const char* src_core_validation_animation_block_validator_is_position_controller_line_307_84fb2300_descriptor_json();
const char* src_core_validation_animation_block_validator_is_orientation_controller_line_311_d9027126_descriptor_json();
const char* src_core_validation_animation_block_validator_finite_values_line_318_06233d23_descriptor_json();
const char* src_core_validation_animation_block_validator_validate_controller_line_325_c7a61bae_descriptor_json();
const char* src_core_validation_animation_block_validator_validate_animation_block_against_model_line_418_d4b136ec_descriptor_json();
const char* src_core_validation_animation_roundtrip_validator_quaternion_angular_difference_degrees_line_63_92f73317_descriptor_json();
const char* src_core_validation_animation_roundtrip_validator_verify_written_animation_override_roundtrip_line_76_318c9c65_descriptor_json();
const char* src_core_validation_animation_roundtrip_validator_find_animation_line_130_12fbd0b1_descriptor_json();
const char* src_core_validation_animation_roundtrip_validator_normalize_quat_line_138_2994c8e9_descriptor_json();
const char* src_core_validation_animation_roundtrip_validator_controller_key_line_147_c50532d9_descriptor_json();
const char* src_core_validation_animation_roundtrip_validator_node_map_line_151_563be9b6_descriptor_json();
const char* src_core_validation_animation_roundtrip_validator_controller_map_line_159_e5f1b7ef_descriptor_json();
const char* src_core_validation_animation_roundtrip_validator_float_close_line_163_0859f19c_descriptor_json();
const char* src_core_validation_animation_roundtrip_validator_vec_close_line_167_098a7e79_descriptor_json();
const char* src_core_validation_animation_roundtrip_validator_compare_model_structure_line_171_eba98c26_descriptor_json();
const char* src_core_validation_animation_roundtrip_validator_compare_animation_metadata_line_233_a74f45de_descriptor_json();
const char* src_core_validation_animation_roundtrip_validator_compare_animation_controllers_line_252_d8f70927_descriptor_json();
const char* src_core_validation_animation_roundtrip_validator_compare_controller_line_278_6c69b449_descriptor_json();
const char* src_core_validation_animation_roundtrip_validator_sample_times_for_line_333_9e070fef_descriptor_json();
const char* src_core_validation_animation_roundtrip_validator_compare_evaluated_poses_line_342_285e4bb6_descriptor_json();
const char* src_core_validation_animation_roundtrip_validator_compare_transform_line_375_754b7f6d_descriptor_json();
const char* src_core_validation_animation_roundtrip_validator_compare_mdx_bytes_if_available_line_399_31fd81d8_descriptor_json();
const char* src_core_validation_validation_adapters_project_validation_report_to_bus_report_line_20_d4cdca85_descriptor_json();
const char* src_core_validation_validation_adapters_retarget_preview_audit_to_validation_report_line_46_c51f3b56_descriptor_json();
const char* src_core_validation_validation_adapters_retarget_issue_line_144_31e94c29_descriptor_json();
const char* src_core_validation_validation_adapters_extract_node_time_line_167_29df66fc_descriptor_json();
const char* src_core_validation_validation_adapters_severity_line_193_ac792e26_descriptor_json();
const char* src_core_validation_validation_bus_severity_rank_line_172_cf55f224_descriptor_json();
const char* src_core_validation_validation_bus_make_issue_id_line_176_478d669f_descriptor_json();
const char* src_core_validation_validation_bus_merge_validation_reports_line_192_fa145f4a_descriptor_json();
const char* src_core_validation_validation_bus_validation_navigation_target_to_dict_line_208_f74af269_descriptor_json();
const char* src_core_validation_validation_bus_validation_navigation_target_from_dict_line_225_915859c1_descriptor_json();
const char* src_core_validation_validation_bus_validation_issue_to_dict_line_242_c1f14dc8_descriptor_json();
const char* src_core_validation_validation_bus_validation_issue_from_dict_line_259_57b8bb16_descriptor_json();
const char* src_core_validation_validation_bus_validation_report_to_dict_line_276_f73c3382_descriptor_json();
const char* src_core_validation_validation_bus_validation_report_from_dict_line_286_b5b290cf_descriptor_json();
const char* src_core_validation_validation_bus_dedupe_issues_line_296_6bd3cc48_descriptor_json();
const char* src_core_validation_validation_bus_coerce_severity_line_308_9efc1219_descriptor_json();
const char* src_core_validation_validation_bus_coerce_subsystem_line_314_0d1ea778_descriptor_json();
const char* src_core_validation_validation_bus_ensure_json_serializable_line_320_4c17f302_descriptor_json();

const PythonFunctionDescriptorEntry* modulefunctions_descriptors(std::size_t& count);

} // namespace ghostrigger::phase15::ghostrigger_validation
