#pragma once

#include <cstddef>

namespace ghostrigger::native::nativecore::math {

#ifndef GHOSTRIGGER_NATIVE_NATIVECORE_MATH_NATIVE_FUNCTION_IMPLEMENTATION_DEFINED
#define GHOSTRIGGER_NATIVE_NATIVECORE_MATH_NATIVE_FUNCTION_IMPLEMENTATION_DEFINED
struct NativeFunctionImplementation {
    const char* project;
    const char* native_namespace;
    const char* python_file;
    const char* qualname;
    const char* callable_type;
    const char* implementation_status;
    bool native_first;
    bool python_runtime_required;
    bool python_fallback_allowed;
    const char* contract_json;
};
#endif // GHOSTRIGGER_NATIVE_NATIVECORE_MATH_NATIVE_FUNCTION_IMPLEMENTATION_DEFINED

const NativeFunctionImplementation& vec3_line_12_da706aff_native();
const NativeFunctionImplementation& quat_line_20_bfeb5cfe_native();
const NativeFunctionImplementation& clamp_line_28_964ba430_native();
const NativeFunctionImplementation& normalize_line_32_73cf2afa_native();
const NativeFunctionImplementation& cross_line_40_0f4881f7_native();
const NativeFunctionImplementation& dot_line_46_fded9f72_native();
const NativeFunctionImplementation& add_line_52_3eb313f3_native();
const NativeFunctionImplementation& sub_line_58_d3dabbe7_native();
const NativeFunctionImplementation& mul_line_64_4e651ed0_native();
const NativeFunctionImplementation& length_line_69_51ada62f_native();
const NativeFunctionImplementation& normalize_quat_line_74_d07494f2_native();
const NativeFunctionImplementation& multiply_quat_line_82_fa8b2261_native();
const NativeFunctionImplementation& quat_to_euler_degrees_line_95_271d5fa6_native();
const NativeFunctionImplementation& euler_degrees_to_quat_line_112_2ae0e9b6_native();
const NativeFunctionImplementation& rotate_vector_line_134_fddb0fc9_native();
const NativeFunctionImplementation& quaternion_from_basis_line_148_6e0ad258_native();
const NativeFunctionImplementation& look_at_quaternion_line_170_c86ad5f7_native();
const NativeFunctionImplementation& camera_forward_line_182_97f0cbf6_native();
const NativeFunctionImplementation& focal_length_to_fov_line_186_216a6bb7_native();
const NativeFunctionImplementation& fov_to_focal_length_line_192_d95c176d_native();
const NativeFunctionImplementation& normalize_line_12_5e7a1d95_native();
const NativeFunctionImplementation& clean_tex_name_line_17_fa59d26b_native();
const NativeFunctionImplementation& cross_line_32_a7ce3031_native();
const NativeFunctionImplementation& dot_line_35_a3016288_native();
const NativeFunctionImplementation& sub_line_38_5f8962f1_native();
const NativeFunctionImplementation& add_line_41_cacfb5f6_native();
const NativeFunctionImplementation& clamp_line_44_a86ae5fa_native();
const NativeFunctionImplementation& lerp_line_60_2ecd30dc_native();
const NativeFunctionImplementation& uwrap_global_line_69_0be67044_native();
const NativeFunctionImplementation& edge_has_seam_global_line_76_a959f027_native();
const NativeFunctionImplementation& vflip_nontiled_line_83_bb0f7bb3_native();
const NativeFunctionImplementation& vflip_tiled_line_87_b741c262_native();
const NativeFunctionImplementation& float_to_sort_key_line_104_acaed1dd_native();
const NativeFunctionImplementation& compute_screen_size_ratio_line_124_7c27ba50_native();
const NativeFunctionImplementation& matrix_from_pos_quat_np_line_9_6668c9bb_native();
const NativeFunctionImplementation& mat4_perspective_line_35_f4ed5d7e_native();
const NativeFunctionImplementation& mat4_lookat_line_58_e7dc6c4c_native();
const NativeFunctionImplementation& mat4_identity_line_84_76645c93_native();
const NativeFunctionImplementation& mat4_tobytes_line_88_9ca84932_native();
const NativeFunctionImplementation& mat4_mul_line_97_f7982823_native();
const NativeFunctionImplementation& mat3_normal_line_102_2ab1c881_native();
const NativeFunctionImplementation& scene_gpu_root_for_node_line_111_eedf9620_native();
const NativeFunctionImplementation& mat4_from_pos_quat_scale_line_122_6ac44af9_native();
const NativeFunctionImplementation& scene_gpu_model_matrix_line_134_b2f2d97f_native();
const NativeFunctionImplementation& bas_attachment_local_transform_np_line_145_94d9b84c_native();
const NativeFunctionImplementation& quat_multiply_xyzw_line_187_99bda164_native();
const NativeFunctionImplementation& scene_authored_world_transform_line_198_200339fa_native();
const NativeFunctionImplementation& quat_rotate_batch_line_240_b1a560c8_native();
const NativeFunctionImplementation& module_anchor_relative_position_line_8_52247966_native();
const NativeFunctionImplementation& as_vec3_line_20_345b457a_native();
const NativeFunctionImplementation& normalize_line_24_ceecad54_native();
const NativeFunctionImplementation& ray_from_mouse_line_32_81b9804f_native();
const NativeFunctionImplementation& closest_point_on_ray_line_48_cf5b387a_native();
const NativeFunctionImplementation& closest_point_between_rays_line_56_2846b051_native();
const NativeFunctionImplementation& project_point_to_screen_line_83_7dc10361_native();
const NativeFunctionImplementation& screen_space_distance_line_88_40ef8610_native();
const NativeFunctionImplementation& axis_drag_delta_line_94_6097c784_native();
const NativeFunctionImplementation& rotation_angle_from_mouse_delta_line_123_2cd65e6d_native();
const NativeFunctionImplementation& axis_quaternion_line_137_9ff6dddc_native();
const NativeFunctionImplementation& multiply_quaternions_line_148_87a2989b_native();
const NativeFunctionImplementation& rotate_vector_line_163_a9ade386_native();
const NativeFunctionImplementation& build_translation_matrix_line_179_4dd3de4a_native();
const NativeFunctionImplementation& build_rotation_matrix_line_185_0bd655cc_native();
const NativeFunctionImplementation& build_scale_matrix_line_201_c8302f11_native();
const NativeFunctionImplementation& normalize_line_80_83d9037c_native();
const NativeFunctionImplementation& cross_line_88_23256461_native();
const NativeFunctionImplementation& dot_line_99_fe1e43f0_native();
const NativeFunctionImplementation& azimuth_elevation_from_direction_line_103_3a4f7690_native();
const NativeFunctionImplementation& action_from_view_name_line_112_0a304fd2_native();
const NativeFunctionImplementation& target_for_action_line_138_9b1666fa_native();
const NativeFunctionImplementation& target_for_region_line_145_7affcdba_native();
const NativeFunctionImplementation& view_direction_from_angles_line_153_320edb52_native();
const NativeFunctionImplementation& camera_basis_from_angles_line_162_173ba890_native();
const NativeFunctionImplementation& view_orientation_quaternion_line_178_65a32831_native();

const NativeFunctionImplementation* modulefunctions_native_functions(std::size_t& count);

} // namespace ghostrigger::native::nativecore::math
