#pragma once

#include <cstddef>

namespace ghostrigger::tools::workflow::export_ {

#ifndef GHOSTRIGGER_TOOLS_EXPORT_NATIVE_FUNCTION_IMPLEMENTATION_DEFINED
#define GHOSTRIGGER_TOOLS_EXPORT_NATIVE_FUNCTION_IMPLEMENTATION_DEFINED
struct NativeFunctionImplementation {
    const char* project;
    const char* native_namespace;
    const char* python_file;
    const char* qualname;
    const char* callable_type;
    const char* implementation_status;
    bool native_first;
    bool python_runtime_required;
    bool python_fallback_allowed;
    const char* contract_json;
};
#endif // GHOSTRIGGER_TOOLS_EXPORT_NATIVE_FUNCTION_IMPLEMENTATION_DEFINED

const NativeFunctionImplementation& preflight_character_mdl_export_line_116_aa242863_native();
const NativeFunctionImplementation& validate_character_rig_state_line_179_ffa38ca7_native();
const NativeFunctionImplementation& validate_native_template_rig_provenance_line_213_036331f4_native();
const NativeFunctionImplementation& validate_skin_binding_evidence_line_405_ae667c90_native();
const NativeFunctionImplementation& donor_weight_fit_landmark_gaps_line_475_f54ff540_native();
const NativeFunctionImplementation& parse_fit_landmark_label_line_508_10af7e98_native();
const NativeFunctionImplementation& validate_auto_fit_evidence_line_517_70348b7d_native();
const NativeFunctionImplementation& validate_paired_landmark_alignment_line_758_f5603eaf_native();
const NativeFunctionImplementation& validate_auto_fit_transform_matrices_line_859_b9354dd3_native();
const NativeFunctionImplementation& auto_fit_matrix3_line_921_4a920390_native();
const NativeFunctionImplementation& matrix3_determinant_line_938_6157aac0_native();
const NativeFunctionImplementation& rotation_orthonormal_error_line_947_468809e5_native();
const NativeFunctionImplementation& max_scaled_matrix_delta_line_960_06908cbd_native();
const NativeFunctionImplementation& validate_toe_forward_alignment_line_974_4a75e1c8_native();
const NativeFunctionImplementation& auto_fit_frame_has_toe_landmarks_line_1079_9ae524d9_native();
const NativeFunctionImplementation& auto_fit_should_require_toe_forward_line_1090_aade8bd2_native();
const NativeFunctionImplementation& auto_fit_source_landmark_sources_line_1111_587e7165_native();
const NativeFunctionImplementation& auto_fit_imported_skeleton_guide_evidence_line_1123_252f4a80_native();
const NativeFunctionImplementation& validate_native_render_replacement_evidence_line_1128_dba3cfa7_native();
const NativeFunctionImplementation& replacement_path_line_1275_7cf4be96_native();
const NativeFunctionImplementation& replacement_fact_mismatches_line_1287_dba30ae0_native();
const NativeFunctionImplementation& safe_int_line_1319_1631192e_native();
const NativeFunctionImplementation& validate_resref_line_1326_e34910dd_native();
const NativeFunctionImplementation& validate_native_snapshot_game_line_1349_3fe16df3_native();
const NativeFunctionImplementation& validate_source_provenance_line_1423_e03d476e_native();
const NativeFunctionImplementation& validate_supermodel_line_1449_cf2541ab_native();
const NativeFunctionImplementation& validate_native_dag_line_1505_dd4a3dd4_native();
const NativeFunctionImplementation& validate_socket_categories_line_1596_86eefa41_native();
const NativeFunctionImplementation& validate_no_non_native_skeleton_nodes_line_1639_ac39bf03_native();
const NativeFunctionImplementation& is_exportable_mesh_payload_line_1684_13ca2b31_native();
const NativeFunctionImplementation& socket_category_evidence_details_line_1690_84020622_native();
const NativeFunctionImplementation& native_socket_evidence_details_line_1704_94ff91c3_native();
const NativeFunctionImplementation& socket_engine_evidence_details_line_1716_356388f5_native();
const NativeFunctionImplementation& engine_string_refs_for_names_line_1743_d168a375_native();
const NativeFunctionImplementation& validate_skin_payload_line_1760_16725093_native();
const NativeFunctionImplementation& validate_skin_material_evidence_line_1865_0d14fd6c_native();
const NativeFunctionImplementation& payload_texture_names_line_1975_64c0d943_native();
const NativeFunctionImplementation& validate_skin_geometry_values_line_2000_d4504887_native();
const NativeFunctionImplementation& validate_bind_transform_rows_line_2106_f701f829_native();
const NativeFunctionImplementation& validate_bone_map_targets_line_2137_d88ab004_native();
const NativeFunctionImplementation& numeric_components_line_2248_2b62a312_native();
const NativeFunctionImplementation& safe_float_line_2278_03fb1235_native();
const NativeFunctionImplementation& all_fconstructe_line_2285_48f4e76a_native();
const NativeFunctionImplementation& validate_skin_rows_line_2289_6dc6c2e4_native();
const NativeFunctionImplementation& issue_line_2409_8e65a89f_native();
const NativeFunctionImplementation& iter_nodes_line_2431_f2998e96_native();
const NativeFunctionImplementation& node_path_line_2452_cd1eab18_native();
const NativeFunctionImplementation& find_node_exact_path_line_2467_fe0373f0_native();
const NativeFunctionImplementation& normalize_kotor_game_line_2474_18b302ab_native();
const NativeFunctionImplementation& casefold_line_2501_f337de76_native();
const NativeFunctionImplementation& find_node_exact_name_line_2505_84c25b34_native();
const NativeFunctionImplementation& export_character_mdl_mdx_transaction_line_102_218afe87_native();
const NativeFunctionImplementation& preflight_options_for_request_line_254_bd4506e0_native();
const NativeFunctionImplementation& reload_preflight_options_line_262_9cec3396_native();
const NativeFunctionImplementation& verify_reloaded_native_dag_contract_line_279_602cf6b4_native();
const NativeFunctionImplementation& verify_reloaded_payload_contract_line_395_50e170c3_native();
const NativeFunctionImplementation& reload_dag_issue_line_495_8813693a_native();
const NativeFunctionImplementation& native_snapshot_reload_evidence_line_523_4ca18932_native();
const NativeFunctionImplementation& payload_issue_line_537_94b7d1fe_native();
const NativeFunctionImplementation& character_payload_mesh_names_line_563_1a78df11_native();
const NativeFunctionImplementation& payload_summaries_by_name_line_588_031ad60e_native();
const NativeFunctionImplementation& payload_summary_line_602_dec2d15b_native();
const NativeFunctionImplementation& write_validation_artifacts_line_614_2ce1efee_native();
const NativeFunctionImplementation& validation_json_path_line_651_11c7dca2_native();
const NativeFunctionImplementation& validation_text_path_line_655_3a894453_native();
const NativeFunctionImplementation& staged_output_hashes_line_659_ae547bce_native();
const NativeFunctionImplementation& file_hash_line_678_acf44455_native();
const NativeFunctionImplementation& model_resref_line_689_e64a5a7c_native();
const NativeFunctionImplementation& character_builder_workflow_evidence_line_693_34ccfc58_native();
const NativeFunctionImplementation& reloaded_model_summary_line_758_bc875f31_native();
const NativeFunctionImplementation& model_nodes_line_797_63ee0646_native();
const NativeFunctionImplementation& node_path_line_818_ddfb19ea_native();
const NativeFunctionImplementation& json_safe_line_833_0482c07c_native();
const NativeFunctionImplementation& export_issue_line_845_4b621b1f_native();
const NativeFunctionImplementation& import_mdl_binary_writer_line_863_4662bac7_native();
const NativeFunctionImplementation& load_kotor_model_from_file_line_869_82436e03_native();
const NativeFunctionImplementation& run_export_job_line_108_e68b41e9_native();
const NativeFunctionImplementation& preflight_export_request_line_263_01b4bba5_native();
const NativeFunctionImplementation& validate_staged_outputs_line_319_8e66a640_native();
const NativeFunctionImplementation& result_line_334_e9ef6bd5_native();
const NativeFunctionImplementation& single_issue_report_line_362_5757b4ff_native();
const NativeFunctionImplementation& issue_line_385_4db8c74f_native();
const NativeFunctionImplementation& publish_line_401_a53a92e7_native();
const NativeFunctionImplementation& shared_output_parent_line_413_001c658b_native();
const NativeFunctionImplementation& rollback_promoted_outputs_line_422_6cf28be4_native();
const NativeFunctionImplementation& final_manifest_path_line_439_188f8463_native();
const NativeFunctionImplementation& normalized_path_key_line_446_7fbdeaec_native();
const NativeFunctionImplementation& safe_job_id_line_450_e73ab220_native();
const NativeFunctionImplementation& ensure_json_serializable_line_455_dc882db9_native();
const NativeFunctionImplementation& decode_accessor_line_152_6f438c5e_native();
const NativeFunctionImplementation& resolve_buffers_line_231_3b6565af_native();
const NativeFunctionImplementation& matrix_to_trs_line_265_79964a2c_native();
const NativeFunctionImplementation& node_trs_from_mapping_line_318_b07a17f5_native();
const NativeFunctionImplementation& node_scale_from_mapping_line_333_5454ffdb_native();
const NativeFunctionImplementation& node_trs_from_object_line_346_bdd95aaa_native();
const NativeFunctionImplementation& node_scale_from_object_line_361_ddbf387c_native();
const NativeFunctionImplementation& mul_scale_line_369_72dca566_native();
const NativeFunctionImplementation& apply_scale_to_pos_line_376_1219d937_native();
const NativeFunctionImplementation& compose_gltf_world_line_383_c0f9e7e1_native();
const NativeFunctionImplementation& gltf_root_indices_line_400_1b3f99ac_native();
const NativeFunctionImplementation& candidate_blender_executables_line_1082_aaa33477_native();
const NativeFunctionImplementation& blender_sort_key_line_1125_18a02b8a_native();
const NativeFunctionImplementation& convert_fbx_to_glb_with_blender_line_1136_428ff1fd_native();
const NativeFunctionImplementation& auto_import_line_1184_b404afc0_native();
const NativeFunctionImplementation& build_skin_data_line_1215_fcd8f9f0_native();
const NativeFunctionImplementation& channel_to_controller_line_1238_6e25f4a7_native();
const NativeFunctionImplementation& fill_material_pygltflib_line_1258_6367fccf_native();
const NativeFunctionImplementation& asset_relative_line_18_5ce50433_native();
const NativeFunctionImplementation& build_output_paths_line_27_18384c92_native();
const NativeFunctionImplementation& summarize_model_line_41_3b22d89c_native();
const NativeFunctionImplementation& inspect_fbx_skin_objects_line_85_bdc78f34_native();
const NativeFunctionImplementation& export_model_for_unity_line_159_63d8706b_native();
const NativeFunctionImplementation& as_list_line_10_902fc7b4_native();
const NativeFunctionImplementation& clip_name_line_20_8f3b8c4f_native();
const NativeFunctionImplementation& renderer_type_line_28_e82cbec7_native();
const NativeFunctionImplementation& renderer_int_line_36_b33aab39_native();
const NativeFunctionImplementation& material_count_line_48_9d6865dc_native();
const NativeFunctionImplementation& build_unity_import_manifest_line_61_0bc29d4a_native();
const NativeFunctionImplementation& validate_unity_import_file_line_180_e7e3ce03_native();

const NativeFunctionImplementation* modulefunctions_native_functions(std::size_t& count);

} // namespace ghostrigger::tools::workflow::export_
