#pragma once

#include <cstddef>

namespace ghostrigger::phase15::ghostrigger_windows_animationretargetworkbench {

using PythonFunctionDescriptorJson = const char* (*)();

struct PythonFunctionDescriptorEntry {
    const char* python_file;
    const char* qualname;
    const char* function_type;
    PythonFunctionDescriptorJson descriptor_json;
};

const char* src_gui_windows_qt_retarget_workbench_controller_populate_retarget_mode_combo_line_793_e0c7b032_descriptor_json();
const char* src_gui_windows_qt_retarget_workbench_controller_combo_current_retarget_mode_line_812_445ddc05_descriptor_json();
const char* src_gui_windows_qt_retarget_workbench_controller_pending_status_for_mode_line_821_43e64cec_descriptor_json();
const char* src_gui_windows_qt_retarget_workbench_controller_mode_status_for_mode_line_829_7a8a9003_descriptor_json();
const char* src_gui_windows_qt_retarget_workbench_controller_human_kind_line_839_cc62b965_descriptor_json();
const char* src_gui_windows_qt_retarget_workbench_controller_verified_source_to_aurora_solver_options_line_851_549a3da5_descriptor_json();
const char* src_gui_windows_qt_retarget_workbench_controller_basis_conversion_from_metadata_line_874_417e4279_descriptor_json();
const char* src_gui_windows_qt_source_clip_preview_model_build_source_clip_preview_model_line_32_7c14f1c2_descriptor_json();
const char* src_gui_windows_qt_source_clip_preview_model_apply_compact_preview_positions_line_99_3bf4df82_descriptor_json();
const char* src_gui_windows_qt_source_clip_preview_model_source_clip_parent_local_position_line_115_38a0f9ee_descriptor_json();
const char* src_gui_windows_qt_source_clip_preview_model_rotate_world_delta_to_parent_local_line_145_57c8bf0a_descriptor_json();
const char* src_gui_windows_qt_source_clip_preview_model_source_clip_animation_rows_line_159_71a15d98_descriptor_json();
const char* src_gui_windows_qt_source_clip_preview_model_animation_length_line_205_791e7d64_descriptor_json();
const char* src_gui_windows_qt_source_clip_preview_model_optional_float_line_218_afaaa5a4_descriptor_json();
const char* src_gui_windows_qt_source_clip_preview_model_optional_int_line_228_d1b4f475_descriptor_json();
const char* src_gui_windows_qt_source_clip_preview_model_append_mesh_preview_nodes_line_235_73b55fcd_descriptor_json();
const char* src_gui_windows_qt_source_clip_preview_model_apply_transform_to_node_line_281_00ea90d0_descriptor_json();
const char* src_gui_windows_qt_source_clip_preview_model_bounds_from_clip_line_289_539e075b_descriptor_json();
const char* src_gui_windows_qt_source_clip_preview_model_merge_bounds_line_313_5038bb1e_descriptor_json();
const char* src_gui_windows_qt_source_clip_preview_model_finite_position_line_329_ab6d559f_descriptor_json();
const char* src_gui_windows_qt_source_clip_preview_model_finite_quat_line_343_fa611792_descriptor_json();
const char* src_gui_windows_qt_source_clip_preview_model_radius_for_bounds_line_361_fdab8f35_descriptor_json();
const char* src_gui_windows_qt_source_clip_preview_model_root_name_for_clip_line_368_b9e34795_descriptor_json();

const PythonFunctionDescriptorEntry* modulefunctions_descriptors(std::size_t& count);

} // namespace ghostrigger::phase15::ghostrigger_windows_animationretargetworkbench
