#pragma once

#include <cstddef>

namespace ghostrigger::phase15::ghostrigger_level {

using PythonFunctionDescriptorJson = const char* (*)();

struct PythonFunctionDescriptorEntry {
    const char* python_file;
    const char* qualname;
    const char* function_type;
    PythonFunctionDescriptorJson descriptor_json;
};

const char* src_core_level_kmap_model_leveltransform_to_dict_line_57_822773a7_descriptor_json();
const char* src_core_level_kmap_model_walkmeshreference_to_dict_line_90_16009c05_descriptor_json();
const char* src_core_level_kmap_model_roominstance_to_dict_line_138_e1b48db5_descriptor_json();
const char* src_core_level_kmap_model_moduleinstance_to_dict_line_189_861eb08e_descriptor_json();
const char* src_core_level_kmap_model_blueprintentry_to_dict_line_231_fb4c2c3f_descriptor_json();
const char* src_core_level_kmap_model_texturereference_to_dict_line_267_009ad0a5_descriptor_json();
const char* src_core_level_kmap_model_materialreference_to_dict_line_300_b4f4bcee_descriptor_json();
const char* src_core_level_kmap_model_kmapproject_mark_dirty_line_342_c3d65644_descriptor_json();
const char* src_core_level_kmap_model_kmapproject_find_room_line_346_092336cf_descriptor_json();
const char* src_core_level_kmap_model_kmapproject_find_module_line_349_1d605726_descriptor_json();
const char* src_core_level_kmap_model_kmapproject_find_walkmesh_line_352_bc74da50_descriptor_json();
const char* src_core_level_kmap_model_kmapproject_find_blueprint_line_355_58d71e76_descriptor_json();
const char* src_core_level_kmap_project_kmapprojectmanager_init_line_12_f38ef493_descriptor_json();
const char* src_core_level_kmap_project_kmapprojectmanager_new_line_16_6b5c0fd8_descriptor_json();
const char* src_core_level_kmap_project_kmapprojectmanager_open_line_21_bcb69348_descriptor_json();
const char* src_core_level_kmap_project_kmapprojectmanager_save_line_25_23a9310b_descriptor_json();
const char* src_core_level_kmap_project_kmapprojectmanager_save_as_line_28_da934efb_descriptor_json();
const char* src_core_level_kmap_validator_kmapvalidationissue_to_dict_line_21_125302ee_descriptor_json();
const char* src_core_level_kmap_validator_kmapvalidator_validate_line_32_740ed46c_descriptor_json();
const char* src_core_level_kmap_validator_kmapvalidator_validate_file_version_line_94_7646ced8_descriptor_json();
const char* src_core_level_kmap_validator_kmapvalidator_duplicate_ids_line_105_2b549446_descriptor_json();
const char* src_core_level_level_export_bridge_levelexportbridge_init_line_47_bc39fe48_descriptor_json();
const char* src_core_level_level_export_bridge_levelexportbridge_export_fbx_line_50_26c31c6c_descriptor_json();
const char* src_core_level_level_scene_levelscene_add_module_line_23_e53312de_descriptor_json();
const char* src_core_level_level_scene_levelscene_remove_module_line_41_3071783c_descriptor_json();
const char* src_core_level_level_scene_levelscene_add_room_line_54_7891fdf3_descriptor_json();
const char* src_core_level_level_scene_levelscene_remove_room_line_79_c5b35381_descriptor_json();
const char* src_core_level_level_scene_levelscene_duplicate_room_line_90_b99dc1f8_descriptor_json();
const char* src_core_level_level_scene_levelscene_associate_walkmesh_line_110_67e30748_descriptor_json();
const char* src_core_level_level_scene_levelscene_add_blueprint_line_133_765063f8_descriptor_json();
const char* src_core_level_level_scene_levelscene_select_line_151_ee3a0ffa_descriptor_json();
const char* src_core_level_level_scene_levelscene_set_transform_line_157_365bd42d_descriptor_json();
const char* src_core_level_level_scene_levelscene_set_visibility_line_167_ece9b555_descriptor_json();
const char* src_core_level_level_scene_levelscene_set_locked_line_175_28f8c55a_descriptor_json();
const char* src_core_level_level_texture_resolver_leveltextureresolver_init_line_12_d98b7710_descriptor_json();
const char* src_core_level_level_texture_resolver_leveltextureresolver_resolve_line_15_83efc1ce_descriptor_json();
const char* src_core_level_level_texture_resolver_leveltextureresolver_track_texture_line_27_127945bc_descriptor_json();

const PythonFunctionDescriptorEntry* instancemethods_descriptors(std::size_t& count);

} // namespace ghostrigger::phase15::ghostrigger_level
