#pragma once

#include <cstddef>

namespace ghostrigger::native::core::host {

struct NativeDependencySpec {
    const wchar_t* name;
    const wchar_t* dll_name;
    const char* version_export;
    const char* capabilities_export;
};

inline constexpr NativeDependencySpec kNativeDependencySpecs[] = {
    {L"GhostRigger.Adapters.Files", L"GhostRigger.Adapters.Files.dll", "gr_adapters_files_version", "gr_adapters_files_capabilities_json"},
    {L"GhostRigger.Adapters.GPU", L"GhostRigger.Adapters.GPU.dll", "gr_adapters_gpu_version", "gr_adapters_gpu_capabilities_json"},
    {L"GhostRigger.Adapters.Qt.Autorig", L"GhostRigger.Adapters.Qt.Autorig.dll", "gr_adapters_qt_autorig_version", "gr_adapters_qt_autorig_capabilities_json"},
    {L"GhostRigger.Adapters.Qt.IPC", L"GhostRigger.Adapters.Qt.IPC.dll", "gr_adapters_qt_ipc_version", "gr_adapters_qt_ipc_capabilities_json"},
    {L"GhostRigger.Adapters.Qt.Viewport", L"GhostRigger.Adapters.Qt.Viewport.dll", "gr_adapters_qt_viewport_version", "gr_adapters_qt_viewport_capabilities_json"},
    {L"GhostRigger.Adapters.Rendering", L"GhostRigger.Adapters.Rendering.dll", "gr_adapters_rendering_version", "gr_adapters_rendering_capabilities_json"},
    {L"GhostRigger.Adapters.Scripting", L"GhostRigger.Adapters.Scripting.dll", "gr_adapters_scripts_version", "gr_adapters_scripts_capabilities_json"},
    {L"GhostRigger.Core.Workflow.Animation", L"GhostRigger.Core.Workflow.Animation.dll", "gr_animation_version", "gr_animation_capabilities_json"},
    {L"GhostRigger.Core.Workflow.AnimationRetargeting", L"GhostRigger.Core.Workflow.AnimationRetargeting.dll", "gr_animation_retargeting_version", "gr_animation_retargeting_capabilities_json"},
    {L"GhostRigger.Core.Resources.Assets", L"GhostRigger.Core.Resources.Assets.dll", "gr_assets_version", "gr_assets_capabilities_json"},
    {L"GhostRigger.Core.Workflow.Autorig", L"GhostRigger.Core.Workflow.Autorig.dll", "gr_autorig_version", "gr_autorig_capabilities_json"},
    {L"GhostRigger.Core.Math.Camera", L"GhostRigger.Core.Math.Camera.dll", "gr_camera_version", "gr_camera_capabilities_json"},
    {L"GhostRigger.Core.Workflow.Characters", L"GhostRigger.Core.Workflow.Characters.dll", "gr_characters_version", "gr_characters_capabilities_json"},
    {L"GhostRigger.Core.IO.Conversion", L"GhostRigger.Core.IO.Conversion.dll", "gr_converters_version", "gr_converters_capabilities_json"},
    {L"GhostRigger.Runtime.Core.Diagnostics", L"GhostRigger.Runtime.Core.Diagnostics.dll", "gr_diagnostics_version", "gr_diagnostics_capabilities_json"},
    {L"GhostRigger.Core.IO.Export", L"GhostRigger.Core.IO.Export.dll", "gr_export_version", "gr_export_capabilities_json"},
    {L"GhostRigger.Core.IO.Serialization.GFF", L"GhostRigger.Core.IO.Serialization.GFF.dll", "gr_formats_version", "gr_formats_capabilities_json"},
    {L"GhostRigger.Core.GUI.Display.Camera", L"GhostRigger.Core.GUI.Display.Camera.dll", "gr_gui_camera_version", "gr_gui_camera_capabilities_json"},
    {L"GhostRigger.Core.GUI.Display.Dialogs", L"GhostRigger.Core.GUI.Display.Dialogs.dll", "gr_gui_dialogs_version", "gr_gui_dialogs_capabilities_json"},
    {L"GhostRigger.Core.GUI.Display.Overlays.Gizmo", L"GhostRigger.Core.GUI.Display.Overlays.Gizmo.dll", "gr_gui_gizmo_version", "gr_gui_gizmo_capabilities_json"},
    {L"GhostRigger.Core.GUI.Display.Integration", L"GhostRigger.Core.GUI.Display.Integration.dll", "gr_gui_integration_version", "gr_gui_integration_capabilities_json"},
    {L"GhostRigger.Core.GUI.Display.Lighting", L"GhostRigger.Core.GUI.Display.Lighting.dll", "gr_gui_lighting_version", "gr_gui_lighting_capabilities_json"},
    {L"GhostRigger.Core.GUI.Display.Panels", L"GhostRigger.Core.GUI.Display.Panels.dll", "gr_gui_panels_version", "gr_gui_panels_capabilities_json"},
    {L"GhostRigger.Core.GUI.Display.Rendering", L"GhostRigger.Core.GUI.Display.Rendering.dll", "gr_gui_rendering_version", "gr_gui_rendering_capabilities_json"},
    {L"GhostRigger.Core.GUI.Display.SequenceEditor", L"GhostRigger.Core.GUI.Display.SequenceEditor.dll", "gr_gui_sequence_editor_version", "gr_gui_sequence_editor_capabilities_json"},
    {L"GhostRigger.Core.GUI.Display.Textures", L"GhostRigger.Core.GUI.Display.Textures.dll", "gr_gui_textures_version", "gr_gui_textures_capabilities_json"},
    {L"GhostRigger.Core.GUI.Display.Theme", L"GhostRigger.Core.GUI.Display.Theme.dll", "gr_gui_theme_version", "gr_gui_theme_capabilities_json"},
    {L"GhostRigger.Core.GUI.Display.Viewports", L"GhostRigger.Core.GUI.Display.Viewports.dll", "gr_gui_viewports_version", "gr_gui_viewports_capabilities_json"},
    {L"GhostRigger.Core.Resources.Game", L"GhostRigger.Core.Resources.Game.dll", "gr_game_version", "gr_game_capabilities_json"},
    {L"GhostRigger.Core.Resources.GameLibrary", L"GhostRigger.Core.Resources.GameLibrary.dll", "gr_game_library_version", "gr_game_library_capabilities_json"},
    {L"GhostRigger.Core.Math.Geometry", L"GhostRigger.Core.Math.Geometry.dll", "gr_geometry_version", "gr_geometry_capabilities_json"},
    {L"GhostRigger.Core.GUI.Helpers.Gizmo", L"GhostRigger.Core.GUI.Helpers.Gizmo.dll", "gr_gizmo_version", "gr_gizmo_capabilities_json"},
    {L"GhostRigger.Core.Rendering.Textures", L"GhostRigger.Core.Rendering.Textures.dll", "gr_graphics_version", "gr_graphics_capabilities_json"},
    {L"GhostRigger.Core.IO.FBX", L"GhostRigger.Core.IO.FBX.dll", "gr_io_version", "gr_io_capabilities_json"},
    {L"GhostRigger.Core.IO.MDL", L"GhostRigger.Core.IO.MDL.dll", "gr_mdl_version", "gr_mdl_capabilities_json"},
    {L"GhostRigger.Core.Automation.IPC", L"GhostRigger.Core.Automation.IPC.dll", "gr_ipc_version", "gr_ipc_capabilities_json"},
    {L"GhostRigger.Runtime.Core.Infrastructure", L"GhostRigger.Runtime.Core.Infrastructure.dll", "gr_infra_version", "gr_infra_capabilities_json"},
    {L"GhostRigger.Core.Automation.MCP", L"GhostRigger.Core.Automation.MCP.dll", "gr_kotor_mcp_version", "gr_kotor_mcp_capabilities_json"},
    {L"GhostRigger.Core.Scene.Level", L"GhostRigger.Core.Scene.Level.dll", "gr_level_version", "gr_level_capabilities_json"},
    {L"GhostRigger.Core.Rendering.Lighting", L"GhostRigger.Core.Rendering.Lighting.dll", "gr_lighting_version", "gr_lighting_capabilities_json"},
    {L"GhostRigger.Core.Math", L"GhostRigger.Core.Math.dll", "gr_math_version", "gr_math_capabilities_json"},
    {L"GhostRigger.Core.Math.Measurement", L"GhostRigger.Core.Math.Measurement.dll", "gr_measurement_version", "gr_measurement_capabilities_json"},
    {L"GhostRigger.Core.Tools.Mesh", L"GhostRigger.Core.Tools.Mesh.dll", "gr_mesh_tools_version", "gr_mesh_tools_capabilities_json"},
    {L"GhostRigger.Core.Scene.Modules", L"GhostRigger.Core.Scene.Modules.dll", "gr_modules_version", "gr_modules_capabilities_json"},
    {L"GhostRigger.Native.Core.Foundation", L"GhostRigger.Native.Core.Foundation.dll", "gr_native_core_version", "gr_native_core_capabilities_json"},
    {L"GhostRigger.Native.Core.Diagnostics", L"GhostRigger.Native.Core.Diagnostics.dll", "gr_native_core_diagnostics_version", "gr_native_core_diagnostics_capabilities_json"},
    {L"GhostRigger.Native.Core.Math", L"GhostRigger.Native.Core.Math.dll", "gr_native_core_math_version", "gr_native_core_math_capabilities_json"},
    {L"GhostRigger.Core.Rendering.Ports", L"GhostRigger.Core.Rendering.Ports.dll", "gr_ports_version", "gr_ports_capabilities_json"},
    {L"GhostRigger.Core.Project", L"GhostRigger.Core.Project.dll", "gr_project_version", "gr_project_capabilities_json"},
    {L"GhostRigger.Core.Rendering.Contracts", L"GhostRigger.Core.Rendering.Contracts.dll", "gr_renderer_contracts_version", "gr_renderer_contracts_capabilities_json"},
    {L"GhostRigger.Core.Rendering.Backends.D3D12", L"GhostRigger.Core.Rendering.Backends.D3D12.dll", "gr_renderer_d3d12_version", "gr_renderer_d3d12_capabilities_json"},
    {L"GhostRigger.Core.Rendering.Backends.ModernGL", L"GhostRigger.Core.Rendering.Backends.ModernGL.dll", "gr_renderer_moderngl_version", "gr_renderer_moderngl_capabilities_json"},
    {L"GhostRigger.Core.Rendering.Backends.Null", L"GhostRigger.Core.Rendering.Backends.Null.dll", "gr_renderer_null_version", "gr_renderer_null_capabilities_json"},
    {L"GhostRigger.Core.Rendering.Backends.PyGFX", L"GhostRigger.Core.Rendering.Backends.PyGFX.dll", "gr_renderer_pygfx_version", "gr_renderer_pygfx_capabilities_json"},
    {L"GhostRigger.Core.Rendering", L"GhostRigger.Core.Rendering.dll", "gr_rendering_version", "gr_rendering_capabilities_json"},
    {L"GhostRigger.Core.Resources", L"GhostRigger.Core.Resources.dll", "gr_resources_version", "gr_resources_capabilities_json"},
    {L"GhostRigger.Core.Workflow.Retargeting", L"GhostRigger.Core.Workflow.Retargeting.dll", "gr_retargeting_version", "gr_retargeting_capabilities_json"},
    {L"GhostRigger.Runtime.Core.Host", L"GhostRigger.Runtime.Core.Host.dll", "gr_runtime_version", ""},
    {L"GhostRigger.Runtime.Shared.Contracts", L"GhostRigger.Runtime.Shared.Contracts.dll", "gr_runtime_shared_contracts_version", "gr_runtime_shared_contracts_capabilities_json"},
    {L"GhostRigger.Runtime.Shared.Descriptors", L"GhostRigger.Runtime.Shared.Descriptors.dll", "gr_runtime_shared_descriptors_version", "gr_runtime_shared_descriptors_capabilities_json"},
    {L"GhostRigger.Runtime.Shared.Resources", L"GhostRigger.Runtime.Shared.Resources.dll", "gr_runtime_shared_resources_version", "gr_runtime_shared_resources_capabilities_json"},
    {L"GhostRigger.Core.Scene", L"GhostRigger.Core.Scene.dll", "gr_scene_version", "gr_scene_capabilities_json"},
    {L"GhostRigger.Core.Scene.Skeleton", L"GhostRigger.Core.Scene.Skeleton.dll", "gr_skeleton_version", "gr_skeleton_capabilities_json"},
    {L"GhostRigger.Core.Tools.Special", L"GhostRigger.Core.Tools.Special.dll", "gr_special_version", "gr_special_capabilities_json"},
    {L"GhostRigger.Core.Formats.TwoDA", L"GhostRigger.Core.Formats.TwoDA.dll", "gr_templates_version", "gr_templates_capabilities_json"},
    {L"GhostRigger.Core.Tools.BAS", L"GhostRigger.Core.Tools.BAS.dll", "gr_tools_body_attachment_system_version", "gr_tools_body_attachment_system_capabilities_json"},
    {L"GhostRigger.Core.Tools.Camera", L"GhostRigger.Core.Tools.Camera.dll", "gr_tools_camera_version", "gr_tools_camera_capabilities_json"},
    {L"GhostRigger.Core.Tools.CharacterBuilder", L"GhostRigger.Core.Tools.CharacterBuilder.dll", "gr_tools_character_builder_version", "gr_tools_character_builder_capabilities_json"},
    {L"GhostRigger.Core.Tools.ContentBrowser", L"GhostRigger.Core.Tools.ContentBrowser.dll", "gr_tools_content_browser_version", "gr_tools_content_browser_capabilities_json"},
    {L"GhostRigger.Core.Tools.Export", L"GhostRigger.Core.Tools.Export.dll", "gr_tools_export_version", "gr_tools_export_capabilities_json"},
    {L"GhostRigger.Core.Tools.Lighting", L"GhostRigger.Core.Tools.Lighting.dll", "gr_tools_lighting_version", "gr_tools_lighting_capabilities_json"},
    {L"GhostRigger.Core.Tools.ModuleMeshes", L"GhostRigger.Core.Tools.ModuleMeshes.dll", "gr_tools_module_meshes_version", "gr_tools_module_meshes_capabilities_json"},
    {L"GhostRigger.Core.Tools.NodeSkeletonBrowser", L"GhostRigger.Core.Tools.NodeSkeletonBrowser.dll", "gr_tools_nodes_skeleton_browser_version", "gr_tools_nodes_skeleton_browser_capabilities_json"},
    {L"GhostRigger.Core.Tools.PivotControls", L"GhostRigger.Core.Tools.PivotControls.dll", "gr_tools_pivot_controls_version", "gr_tools_pivot_controls_capabilities_json"},
    {L"GhostRigger.Core.Tools.Properties", L"GhostRigger.Core.Tools.Properties.dll", "gr_tools_properties_version", "gr_tools_properties_capabilities_json"},
    {L"GhostRigger.Core.Tools.ResourceBrowser", L"GhostRigger.Core.Tools.ResourceBrowser.dll", "gr_tools_resource_browser_version", "gr_tools_resource_browser_capabilities_json"},
    {L"GhostRigger.Core.Tools.Retargeting", L"GhostRigger.Core.Tools.Retargeting.dll", "gr_tools_retargeting_version", "gr_tools_retargeting_capabilities_json"},
    {L"GhostRigger.Core.Tools.SceneInformation", L"GhostRigger.Core.Tools.SceneInformation.dll", "gr_tools_scene_information_version", "gr_tools_scene_information_capabilities_json"},
    {L"GhostRigger.Core.Tools.SequenceEditor", L"GhostRigger.Core.Tools.SequenceEditor.dll", "gr_tools_sequence_editor_version", "gr_tools_sequence_editor_capabilities_json"},
    {L"GhostRigger.Core.Tools.SpriteMaterials", L"GhostRigger.Core.Tools.SpriteMaterials.dll", "gr_tools_sprite_materials_version", "gr_tools_sprite_materials_capabilities_json"},
    {L"GhostRigger.Core.Tools.TwoDABrowser", L"GhostRigger.Core.Tools.TwoDABrowser.dll", "gr_tools_two_da_browser_version", "gr_tools_two_da_browser_capabilities_json"},
    {L"GhostRigger.Adapters.Unreal", L"GhostRigger.Adapters.Unreal.dll", "gr_unreal_version", "gr_unreal_capabilities_json"},
    {L"GhostRigger.Core.Validation", L"GhostRigger.Core.Validation.dll", "gr_validation_version", "gr_validation_capabilities_json"},
    {L"GhostRigger.Core.Scene.Walkmesh", L"GhostRigger.Core.Scene.Walkmesh.dll", "gr_walkmesh_version", "gr_walkmesh_capabilities_json"},
    {L"GhostRigger.Core.Tools.Retargeting.Workbench", L"GhostRigger.Core.Tools.Retargeting.Workbench.dll", "gr_windows_animation_retarget_workbench_version", "gr_windows_animation_retarget_workbench_capabilities_json"},
    {L"GhostRigger.Core.Tools.Rigging", L"GhostRigger.Core.Tools.Rigging.dll", "gr_windows_legacy_rigging_window_version", "gr_windows_legacy_rigging_window_capabilities_json"},
    {L"GhostRigger.Core.Tools.ModuleEditor", L"GhostRigger.Core.Tools.ModuleEditor.dll", "gr_windows_level_editor_version", "gr_windows_level_editor_capabilities_json"},
    {L"GhostRigger.Core.GUI.Display.Shell.Main", L"GhostRigger.Core.GUI.Display.Shell.Main.dll", "gr_windows_main_window_version", "gr_windows_main_window_capabilities_json"},
    {L"GhostRigger.Core.Tools.UnrealAnimator", L"GhostRigger.Core.Tools.UnrealAnimator.dll", "gr_windows_unreal_animator_window_version", "gr_windows_unreal_animator_window_capabilities_json"},
    {L"GhostRigger.Core.Tools.Workbench", L"GhostRigger.Core.Tools.Workbench.dll", "gr_workbench_version", "gr_workbench_capabilities_json"},
    {L"GhostRigger.Core.Workflow", L"GhostRigger.Core.Workflow.dll", "gr_workflow_version", "gr_workflow_capabilities_json"},
};

inline constexpr std::size_t kNativeDependencySpecCount = sizeof(kNativeDependencySpecs) / sizeof(kNativeDependencySpecs[0]);

} // namespace ghostrigger::native::core::host
