#pragma once

#include <cstddef>

namespace ghostrigger::native_host {

struct NativeDependencySpec {
    const wchar_t* name;
    const wchar_t* dll_name;
};

inline constexpr NativeDependencySpec kNativeDependencySpecs[] = {
    {L"GhostRigger.Core.Automation", L"GhostRigger.Core.Automation.dll"},
    {L"GhostRigger.Core.Bridge", L"GhostRigger.Core.Bridge.dll"},
    {L"GhostRigger.Core.GUI.Display.Dialogs", L"GhostRigger.Core.GUI.Display.Dialogs.dll"},
    {L"GhostRigger.Core.GUI.Display.Integration", L"GhostRigger.Core.GUI.Display.Integration.dll"},
    {L"GhostRigger.Core.GUI.Display.Lighting", L"GhostRigger.Core.GUI.Display.Lighting.dll"},
    {L"GhostRigger.Core.GUI.Display.Overlays.Gizmo", L"GhostRigger.Core.GUI.Display.Overlays.Gizmo.dll"},
    {L"GhostRigger.Core.GUI.Display.Panels", L"GhostRigger.Core.GUI.Display.Panels.dll"},
    {L"GhostRigger.Core.GUI.Display.Rendering", L"GhostRigger.Core.GUI.Display.Rendering.dll"},
    {L"GhostRigger.Core.GUI.Display.SequenceEditor", L"GhostRigger.Core.GUI.Display.SequenceEditor.dll"},
    {L"GhostRigger.Core.GUI.Display.Shell.Main", L"GhostRigger.Core.GUI.Display.Shell.Main.dll"},
    {L"GhostRigger.Core.GUI.Display.Textures", L"GhostRigger.Core.GUI.Display.Textures.dll"},
    {L"GhostRigger.Core.GUI.Display.Theme", L"GhostRigger.Core.GUI.Display.Theme.dll"},
    {L"GhostRigger.Core.GUI.Display.Viewports", L"GhostRigger.Core.GUI.Display.Viewports.dll"},
    {L"GhostRigger.Core.GUI.Helpers.Gizmo", L"GhostRigger.Core.GUI.Helpers.Gizmo.dll"},
    {L"GhostRigger.Core.IO.Export", L"GhostRigger.Core.IO.Export.dll"},
    {L"GhostRigger.Core.IO.File.Conversion", L"GhostRigger.Core.IO.File.Conversion.dll"},
    {L"GhostRigger.Core.IO.File.Format", L"GhostRigger.Core.IO.File.Format.dll"},
    {L"GhostRigger.Core.IO.File.Write", L"GhostRigger.Core.IO.File.Write.dll"},
    {L"GhostRigger.Core.Math", L"GhostRigger.Core.Math.dll"},
    {L"GhostRigger.Core.Project", L"GhostRigger.Core.Project.dll"},
    {L"GhostRigger.Core.Qt.Autorig", L"GhostRigger.Core.Qt.Autorig.dll"},
    {L"GhostRigger.Core.Qt.Viewport", L"GhostRigger.Core.Qt.Viewport.dll"},
    {L"GhostRigger.Core.Rendering", L"GhostRigger.Core.Rendering.dll"},
    {L"GhostRigger.Core.Rendering.Backends.D3D12", L"GhostRigger.Core.Rendering.Backends.D3D12.dll"},
    {L"GhostRigger.Core.Rendering.Backends.ModernGL", L"GhostRigger.Core.Rendering.Backends.ModernGL.dll"},
    {L"GhostRigger.Core.Rendering.Backends.Null", L"GhostRigger.Core.Rendering.Backends.Null.dll"},
    {L"GhostRigger.Core.Rendering.Backends.PyGFX", L"GhostRigger.Core.Rendering.Backends.PyGFX.dll"},
    {L"GhostRigger.Core.Rendering.Contracts", L"GhostRigger.Core.Rendering.Contracts.dll"},
    {L"GhostRigger.Core.Rendering.GPU", L"GhostRigger.Core.Rendering.GPU.dll"},
    {L"GhostRigger.Core.Rendering.Lighting", L"GhostRigger.Core.Rendering.Lighting.dll"},
    {L"GhostRigger.Core.Rendering.Ports", L"GhostRigger.Core.Rendering.Ports.dll"},
    {L"GhostRigger.Core.Rendering.Textures", L"GhostRigger.Core.Rendering.Textures.dll"},
    {L"GhostRigger.Core.Resources", L"GhostRigger.Core.Resources.dll"},
    {L"GhostRigger.Core.Resources.Assets", L"GhostRigger.Core.Resources.Assets.dll"},
    {L"GhostRigger.Core.Resources.Game", L"GhostRigger.Core.Resources.Game.dll"},
    {L"GhostRigger.Core.Resources.GameLibrary", L"GhostRigger.Core.Resources.GameLibrary.dll"},
    {L"GhostRigger.Core.Scene", L"GhostRigger.Core.Scene.dll"},
    {L"GhostRigger.Core.Scene.Level", L"GhostRigger.Core.Scene.Level.dll"},
    {L"GhostRigger.Core.Scene.Modules", L"GhostRigger.Core.Scene.Modules.dll"},
    {L"GhostRigger.Core.Scene.Skeleton", L"GhostRigger.Core.Scene.Skeleton.dll"},
    {L"GhostRigger.Core.Scene.Walkmesh", L"GhostRigger.Core.Scene.Walkmesh.dll"},
    {L"GhostRigger.Core.Tools.BAS", L"GhostRigger.Core.Tools.BAS.dll"},
    {L"GhostRigger.Core.Tools.Camera", L"GhostRigger.Core.Tools.Camera.dll"},
    {L"GhostRigger.Core.Tools.CharacterBuilder", L"GhostRigger.Core.Tools.CharacterBuilder.dll"},
    {L"GhostRigger.Core.Tools.ContentBrowser", L"GhostRigger.Core.Tools.ContentBrowser.dll"},
    {L"GhostRigger.Core.Tools.Export", L"GhostRigger.Core.Tools.Export.dll"},
    {L"GhostRigger.Core.Tools.Lighting", L"GhostRigger.Core.Tools.Lighting.dll"},
    {L"GhostRigger.Core.Tools.Mesh", L"GhostRigger.Core.Tools.Mesh.dll"},
    {L"GhostRigger.Core.Tools.ModuleEditor", L"GhostRigger.Core.Tools.ModuleEditor.dll"},
    {L"GhostRigger.Core.Tools.ModuleMeshes", L"GhostRigger.Core.Tools.ModuleMeshes.dll"},
    {L"GhostRigger.Core.Tools.NodeSkeletonBrowser", L"GhostRigger.Core.Tools.NodeSkeletonBrowser.dll"},
    {L"GhostRigger.Core.Tools.PivotControls", L"GhostRigger.Core.Tools.PivotControls.dll"},
    {L"GhostRigger.Core.Tools.Properties", L"GhostRigger.Core.Tools.Properties.dll"},
    {L"GhostRigger.Core.Tools.ResourceBrowser", L"GhostRigger.Core.Tools.ResourceBrowser.dll"},
    {L"GhostRigger.Core.Tools.Retargeting", L"GhostRigger.Core.Tools.Retargeting.dll"},
    {L"GhostRigger.Core.Tools.Retargeting.Workbench", L"GhostRigger.Core.Tools.Retargeting.Workbench.dll"},
    {L"GhostRigger.Core.Tools.Rigging", L"GhostRigger.Core.Tools.Rigging.dll"},
    {L"GhostRigger.Core.Tools.SceneInformation", L"GhostRigger.Core.Tools.SceneInformation.dll"},
    {L"GhostRigger.Core.Tools.SequenceEditor", L"GhostRigger.Core.Tools.SequenceEditor.dll"},
    {L"GhostRigger.Core.Tools.Special", L"GhostRigger.Core.Tools.Special.dll"},
    {L"GhostRigger.Core.Tools.SpriteMaterials", L"GhostRigger.Core.Tools.SpriteMaterials.dll"},
    {L"GhostRigger.Core.Tools.TwoDABrowser", L"GhostRigger.Core.Tools.TwoDABrowser.dll"},
    {L"GhostRigger.Core.Tools.UnrealAnimator", L"GhostRigger.Core.Tools.UnrealAnimator.dll"},
    {L"GhostRigger.Core.Tools.Workbench", L"GhostRigger.Core.Tools.Workbench.dll"},
    {L"GhostRigger.Core.Validation", L"GhostRigger.Core.Validation.dll"},
    {L"GhostRigger.Core.Workflow", L"GhostRigger.Core.Workflow.dll"},
    {L"GhostRigger.Core.Workflow.Animation", L"GhostRigger.Core.Workflow.Animation.dll"},
    {L"GhostRigger.Core.Workflow.AnimationRetargeting", L"GhostRigger.Core.Workflow.AnimationRetargeting.dll"},
    {L"GhostRigger.Core.Workflow.Autorig", L"GhostRigger.Core.Workflow.Autorig.dll"},
    {L"GhostRigger.Core.Workflow.Characters", L"GhostRigger.Core.Workflow.Characters.dll"},
    {L"GhostRigger.Core.Workflow.Retargeting", L"GhostRigger.Core.Workflow.Retargeting.dll"},
    {L"GhostRigger.Native.Core.Diagnostics", L"GhostRigger.Native.Core.Diagnostics.dll"},
    {L"GhostRigger.Native.Core.Foundation", L"GhostRigger.Native.Core.Foundation.dll"},
    {L"GhostRigger.Native.Core.Math", L"GhostRigger.Native.Core.Math.dll"},
    {L"GhostRigger.Runtime.Core.Diagnostics", L"GhostRigger.Runtime.Core.Diagnostics.dll"},
    {L"GhostRigger.Runtime.Core.Host", L"GhostRigger.Runtime.Core.Host.dll"},
    {L"GhostRigger.Runtime.Core.Infrastructure", L"GhostRigger.Runtime.Core.Infrastructure.dll"},
    {L"GhostRigger.Runtime.Shared.Contracts", L"GhostRigger.Runtime.Shared.Contracts.dll"},
    {L"GhostRigger.Runtime.Shared.Descriptors", L"GhostRigger.Runtime.Shared.Descriptors.dll"},
    {L"GhostRigger.Runtime.Shared.Resources", L"GhostRigger.Runtime.Shared.Resources.dll"},
};

inline constexpr std::size_t kNativeDependencySpecCount = sizeof(kNativeDependencySpecs) / sizeof(kNativeDependencySpecs[0]);

} // namespace ghostrigger::native_host
