#pragma once

#include <cstddef>

namespace ghostrigger::native::core::host {

struct NativeDependencySpec {
    const wchar_t* name;
    const wchar_t* dll_name;
    const char* version_export;
    const char* capabilities_export;
};

inline constexpr NativeDependencySpec kNativeDependencySpecs[] = {
    {L"GhostRigger.Adapters.IO.Files", L"GhostRigger.Adapters.IO.Files.dll", "gr_adapters_files_version", "gr_adapters_files_capabilities_json"},
    {L"GhostRigger.Adapters.Hardware.GPU", L"GhostRigger.Adapters.Hardware.GPU.dll", "gr_adapters_gpu_version", "gr_adapters_gpu_capabilities_json"},
    {L"GhostRigger.Adapters.Qt.Autorig", L"GhostRigger.Adapters.Qt.Autorig.dll", "gr_adapters_qt_autorig_version", "gr_adapters_qt_autorig_capabilities_json"},
    {L"GhostRigger.Adapters.Qt.IPC", L"GhostRigger.Adapters.Qt.IPC.dll", "gr_adapters_qt_ipc_version", "gr_adapters_qt_ipc_capabilities_json"},
    {L"GhostRigger.Adapters.Qt.Viewport", L"GhostRigger.Adapters.Qt.Viewport.dll", "gr_adapters_qt_viewport_version", "gr_adapters_qt_viewport_capabilities_json"},
    {L"GhostRigger.Adapters.Rendering.Core", L"GhostRigger.Adapters.Rendering.Core.dll", "gr_adapters_rendering_version", "gr_adapters_rendering_capabilities_json"},
    {L"GhostRigger.Adapters.Scripting.Core", L"GhostRigger.Adapters.Scripting.Core.dll", "gr_adapters_scripts_version", "gr_adapters_scripts_capabilities_json"},
    {L"GhostRigger.Domain.Core.Animation", L"GhostRigger.Domain.Core.Animation.dll", "gr_animation_version", "gr_animation_capabilities_json"},
    {L"GhostRigger.Domain.Core.AnimationRetargeting", L"GhostRigger.Domain.Core.AnimationRetargeting.dll", "gr_animation_retargeting_version", "gr_animation_retargeting_capabilities_json"},
    {L"GhostRigger.Domain.Core.Assets", L"GhostRigger.Domain.Core.Assets.dll", "gr_assets_version", "gr_assets_capabilities_json"},
    {L"GhostRigger.Domain.Core.Autorig", L"GhostRigger.Domain.Core.Autorig.dll", "gr_autorig_version", "gr_autorig_capabilities_json"},
    {L"GhostRigger.Domain.Core.Camera", L"GhostRigger.Domain.Core.Camera.dll", "gr_camera_version", "gr_camera_capabilities_json"},
    {L"GhostRigger.Domain.Core.Characters", L"GhostRigger.Domain.Core.Characters.dll", "gr_characters_version", "gr_characters_capabilities_json"},
    {L"GhostRigger.Domain.Core.Converters", L"GhostRigger.Domain.Core.Converters.dll", "gr_converters_version", "gr_converters_capabilities_json"},
    {L"GhostRigger.Domain.Core.Diagnostics", L"GhostRigger.Domain.Core.Diagnostics.dll", "gr_diagnostics_version", "gr_diagnostics_capabilities_json"},
    {L"GhostRigger.Domain.Core.Export", L"GhostRigger.Domain.Core.Export.dll", "gr_export_version", "gr_export_capabilities_json"},
    {L"GhostRigger.Domain.Core.Formats", L"GhostRigger.Domain.Core.Formats.dll", "gr_formats_version", "gr_formats_capabilities_json"},
    {L"GhostRigger.GUI.Boundary.Camera", L"GhostRigger.GUI.Boundary.Camera.dll", "gr_gui_camera_version", "gr_gui_camera_capabilities_json"},
    {L"GhostRigger.GUI.Boundary.Dialogs", L"GhostRigger.GUI.Boundary.Dialogs.dll", "gr_gui_dialogs_version", "gr_gui_dialogs_capabilities_json"},
    {L"GhostRigger.GUI.Boundary.Gizmo", L"GhostRigger.GUI.Boundary.Gizmo.dll", "gr_gui_gizmo_version", "gr_gui_gizmo_capabilities_json"},
    {L"GhostRigger.GUI.Boundary.Integration", L"GhostRigger.GUI.Boundary.Integration.dll", "gr_gui_integration_version", "gr_gui_integration_capabilities_json"},
    {L"GhostRigger.GUI.Boundary.Lighting", L"GhostRigger.GUI.Boundary.Lighting.dll", "gr_gui_lighting_version", "gr_gui_lighting_capabilities_json"},
    {L"GhostRigger.GUI.Boundary.Panels", L"GhostRigger.GUI.Boundary.Panels.dll", "gr_gui_panels_version", "gr_gui_panels_capabilities_json"},
    {L"GhostRigger.GUI.Boundary.Rendering", L"GhostRigger.GUI.Boundary.Rendering.dll", "gr_gui_rendering_version", "gr_gui_rendering_capabilities_json"},
    {L"GhostRigger.GUI.Boundary.SequenceEditor", L"GhostRigger.GUI.Boundary.SequenceEditor.dll", "gr_gui_sequence_editor_version", "gr_gui_sequence_editor_capabilities_json"},
    {L"GhostRigger.GUI.Boundary.Textures", L"GhostRigger.GUI.Boundary.Textures.dll", "gr_gui_textures_version", "gr_gui_textures_capabilities_json"},
    {L"GhostRigger.GUI.Boundary.Theme", L"GhostRigger.GUI.Boundary.Theme.dll", "gr_gui_theme_version", "gr_gui_theme_capabilities_json"},
    {L"GhostRigger.GUI.Boundary.Viewports", L"GhostRigger.GUI.Boundary.Viewports.dll", "gr_gui_viewports_version", "gr_gui_viewports_capabilities_json"},
    {L"GhostRigger.Domain.Core.Game", L"GhostRigger.Domain.Core.Game.dll", "gr_game_version", "gr_game_capabilities_json"},
    {L"GhostRigger.Domain.Core.GameLibrary", L"GhostRigger.Domain.Core.GameLibrary.dll", "gr_game_library_version", "gr_game_library_capabilities_json"},
    {L"GhostRigger.Domain.Core.Geometry", L"GhostRigger.Domain.Core.Geometry.dll", "gr_geometry_version", "gr_geometry_capabilities_json"},
    {L"GhostRigger.Domain.Core.Gizmo", L"GhostRigger.Domain.Core.Gizmo.dll", "gr_gizmo_version", "gr_gizmo_capabilities_json"},
    {L"GhostRigger.Domain.Core.Graphics", L"GhostRigger.Domain.Core.Graphics.dll", "gr_graphics_version", "gr_graphics_capabilities_json"},
    {L"GhostRigger.Domain.Core.IO", L"GhostRigger.Domain.Core.IO.dll", "gr_io_version", "gr_io_capabilities_json"},
    {L"GhostRigger.Domain.Core.IPC", L"GhostRigger.Domain.Core.IPC.dll", "gr_ipc_version", "gr_ipc_capabilities_json"},
    {L"GhostRigger.Domain.Core.Infrastructure", L"GhostRigger.Domain.Core.Infrastructure.dll", "gr_infra_version", "gr_infra_capabilities_json"},
    {L"GhostRigger.Domain.Core.KotorMCP", L"GhostRigger.Domain.Core.KotorMCP.dll", "gr_kotor_mcp_version", "gr_kotor_mcp_capabilities_json"},
    {L"GhostRigger.Domain.Core.Level", L"GhostRigger.Domain.Core.Level.dll", "gr_level_version", "gr_level_capabilities_json"},
    {L"GhostRigger.Domain.Core.Lighting", L"GhostRigger.Domain.Core.Lighting.dll", "gr_lighting_version", "gr_lighting_capabilities_json"},
    {L"GhostRigger.Domain.Core.MDL", L"GhostRigger.Domain.Core.MDL.dll", "gr_mdl_version", "gr_mdl_capabilities_json"},
    {L"GhostRigger.Domain.Core.Math", L"GhostRigger.Domain.Core.Math.dll", "gr_math_version", "gr_math_capabilities_json"},
    {L"GhostRigger.Domain.Core.Measurement", L"GhostRigger.Domain.Core.Measurement.dll", "gr_measurement_version", "gr_measurement_capabilities_json"},
    {L"GhostRigger.Domain.Core.MeshTools", L"GhostRigger.Domain.Core.MeshTools.dll", "gr_mesh_tools_version", "gr_mesh_tools_capabilities_json"},
    {L"GhostRigger.Domain.Core.Modules", L"GhostRigger.Domain.Core.Modules.dll", "gr_modules_version", "gr_modules_capabilities_json"},
    {L"GhostRigger.Native.Core.Foundation", L"GhostRigger.Native.Core.Foundation.dll", "gr_native_core_version", "gr_native_core_capabilities_json"},
    {L"GhostRigger.Native.Core.Diagnostics", L"GhostRigger.Native.Core.Diagnostics.dll", "gr_native_core_diagnostics_version", "gr_native_core_diagnostics_capabilities_json"},
    {L"GhostRigger.Native.Core.Math", L"GhostRigger.Native.Core.Math.dll", "gr_native_core_math_version", "gr_native_core_math_capabilities_json"},
    {L"GhostRigger.Domain.Core.Ports", L"GhostRigger.Domain.Core.Ports.dll", "gr_ports_version", "gr_ports_capabilities_json"},
    {L"GhostRigger.Domain.Core.Project", L"GhostRigger.Domain.Core.Project.dll", "gr_project_version", "gr_project_capabilities_json"},
    {L"GhostRigger.Renderer.Shared.Contracts", L"GhostRigger.Renderer.Shared.Contracts.dll", "gr_renderer_contracts_version", "gr_renderer_contracts_capabilities_json"},
    {L"GhostRigger.Renderer.Backend.D3D12", L"GhostRigger.Renderer.Backend.D3D12.dll", "gr_renderer_d3d12_version", "gr_renderer_d3d12_capabilities_json"},
    {L"GhostRigger.Renderer.Backend.ModernGL", L"GhostRigger.Renderer.Backend.ModernGL.dll", "gr_renderer_moderngl_version", "gr_renderer_moderngl_capabilities_json"},
    {L"GhostRigger.Renderer.Backend.Null", L"GhostRigger.Renderer.Backend.Null.dll", "gr_renderer_null_version", "gr_renderer_null_capabilities_json"},
    {L"GhostRigger.Renderer.Backend.PyGFX", L"GhostRigger.Renderer.Backend.PyGFX.dll", "gr_renderer_pygfx_version", "gr_renderer_pygfx_capabilities_json"},
    {L"GhostRigger.Domain.Core.Rendering", L"GhostRigger.Domain.Core.Rendering.dll", "gr_rendering_version", "gr_rendering_capabilities_json"},
    {L"GhostRigger.Domain.Core.Resources", L"GhostRigger.Domain.Core.Resources.dll", "gr_resources_version", "gr_resources_capabilities_json"},
    {L"GhostRigger.Domain.Core.Retargeting", L"GhostRigger.Domain.Core.Retargeting.dll", "gr_retargeting_version", "gr_retargeting_capabilities_json"},
    {L"GhostRigger.Runtime.Core.Host", L"GhostRigger.Runtime.Core.Host.dll", "gr_runtime_version", ""},
    {L"GhostRigger.Runtime.Shared.Contracts", L"GhostRigger.Runtime.Shared.Contracts.dll", "gr_runtime_shared_contracts_version", "gr_runtime_shared_contracts_capabilities_json"},
    {L"GhostRigger.Runtime.Shared.Descriptors", L"GhostRigger.Runtime.Shared.Descriptors.dll", "gr_runtime_shared_descriptors_version", "gr_runtime_shared_descriptors_capabilities_json"},
    {L"GhostRigger.Runtime.Shared.Resources", L"GhostRigger.Runtime.Shared.Resources.dll", "gr_runtime_shared_resources_version", "gr_runtime_shared_resources_capabilities_json"},
    {L"GhostRigger.Domain.Core.Scene", L"GhostRigger.Domain.Core.Scene.dll", "gr_scene_version", "gr_scene_capabilities_json"},
    {L"GhostRigger.Domain.Core.Sequence", L"GhostRigger.Domain.Core.Sequence.dll", "gr_sequence_version", "gr_sequence_capabilities_json"},
    {L"GhostRigger.Domain.Core.Skeleton", L"GhostRigger.Domain.Core.Skeleton.dll", "gr_skeleton_version", "gr_skeleton_capabilities_json"},
    {L"GhostRigger.Domain.Core.Special", L"GhostRigger.Domain.Core.Special.dll", "gr_special_version", "gr_special_capabilities_json"},
    {L"GhostRigger.Systems.Feature.BAS", L"GhostRigger.Systems.Feature.BAS.dll", "gr_systems_bas_version", "gr_systems_bas_capabilities_json"},
    {L"GhostRigger.Domain.Core.Templates", L"GhostRigger.Domain.Core.Templates.dll", "gr_templates_version", "gr_templates_capabilities_json"},
    {L"GhostRigger.Tools.Workflow.BodyAttachmentSystem", L"GhostRigger.Tools.Workflow.BodyAttachmentSystem.dll", "gr_tools_body_attachment_system_version", "gr_tools_body_attachment_system_capabilities_json"},
    {L"GhostRigger.Tools.Workflow.Camera", L"GhostRigger.Tools.Workflow.Camera.dll", "gr_tools_camera_version", "gr_tools_camera_capabilities_json"},
    {L"GhostRigger.Tools.Workflow.CharacterBuilder", L"GhostRigger.Tools.Workflow.CharacterBuilder.dll", "gr_tools_character_builder_version", "gr_tools_character_builder_capabilities_json"},
    {L"GhostRigger.Tools.Workflow.ContentBrowser", L"GhostRigger.Tools.Workflow.ContentBrowser.dll", "gr_tools_content_browser_version", "gr_tools_content_browser_capabilities_json"},
    {L"GhostRigger.Tools.Workflow.Export", L"GhostRigger.Tools.Workflow.Export.dll", "gr_tools_export_version", "gr_tools_export_capabilities_json"},
    {L"GhostRigger.Tools.Workflow.Lighting", L"GhostRigger.Tools.Workflow.Lighting.dll", "gr_tools_lighting_version", "gr_tools_lighting_capabilities_json"},
    {L"GhostRigger.Tools.Workflow.ModuleMeshes", L"GhostRigger.Tools.Workflow.ModuleMeshes.dll", "gr_tools_module_meshes_version", "gr_tools_module_meshes_capabilities_json"},
    {L"GhostRigger.Tools.Workflow.NodeSkeletonBrowser", L"GhostRigger.Tools.Workflow.NodeSkeletonBrowser.dll", "gr_tools_nodes_skeleton_browser_version", "gr_tools_nodes_skeleton_browser_capabilities_json"},
    {L"GhostRigger.Tools.Workflow.PivotControls", L"GhostRigger.Tools.Workflow.PivotControls.dll", "gr_tools_pivot_controls_version", "gr_tools_pivot_controls_capabilities_json"},
    {L"GhostRigger.Tools.Workflow.Properties", L"GhostRigger.Tools.Workflow.Properties.dll", "gr_tools_properties_version", "gr_tools_properties_capabilities_json"},
    {L"GhostRigger.Tools.Workflow.ResourceBrowser", L"GhostRigger.Tools.Workflow.ResourceBrowser.dll", "gr_tools_resource_browser_version", "gr_tools_resource_browser_capabilities_json"},
    {L"GhostRigger.Tools.Workflow.Retargeting", L"GhostRigger.Tools.Workflow.Retargeting.dll", "gr_tools_retargeting_version", "gr_tools_retargeting_capabilities_json"},
    {L"GhostRigger.Tools.Workflow.SceneInformation", L"GhostRigger.Tools.Workflow.SceneInformation.dll", "gr_tools_scene_information_version", "gr_tools_scene_information_capabilities_json"},
    {L"GhostRigger.Tools.Workflow.SequenceEditor", L"GhostRigger.Tools.Workflow.SequenceEditor.dll", "gr_tools_sequence_editor_version", "gr_tools_sequence_editor_capabilities_json"},
    {L"GhostRigger.Tools.Workflow.SpriteMaterials", L"GhostRigger.Tools.Workflow.SpriteMaterials.dll", "gr_tools_sprite_materials_version", "gr_tools_sprite_materials_capabilities_json"},
    {L"GhostRigger.Tools.Workflow.TwoDABrowser", L"GhostRigger.Tools.Workflow.TwoDABrowser.dll", "gr_tools_two_da_browser_version", "gr_tools_two_da_browser_capabilities_json"},
    {L"GhostRigger.Domain.Core.Unreal", L"GhostRigger.Domain.Core.Unreal.dll", "gr_unreal_version", "gr_unreal_capabilities_json"},
    {L"GhostRigger.Domain.Core.Validation", L"GhostRigger.Domain.Core.Validation.dll", "gr_validation_version", "gr_validation_capabilities_json"},
    {L"GhostRigger.Domain.Core.Walkmesh", L"GhostRigger.Domain.Core.Walkmesh.dll", "gr_walkmesh_version", "gr_walkmesh_capabilities_json"},
    {L"GhostRigger.Windows.Workbench.AnimationRetarget", L"GhostRigger.Windows.Workbench.AnimationRetarget.dll", "gr_windows_animation_retarget_workbench_version", "gr_windows_animation_retarget_workbench_capabilities_json"},
    {L"GhostRigger.Windows.Legacy.Rigging", L"GhostRigger.Windows.Legacy.Rigging.dll", "gr_windows_legacy_rigging_window_version", "gr_windows_legacy_rigging_window_capabilities_json"},
    {L"GhostRigger.Windows.Editor.Level", L"GhostRigger.Windows.Editor.Level.dll", "gr_windows_level_editor_version", "gr_windows_level_editor_capabilities_json"},
    {L"GhostRigger.Windows.Shell.Main", L"GhostRigger.Windows.Shell.Main.dll", "gr_windows_main_window_version", "gr_windows_main_window_capabilities_json"},
    {L"GhostRigger.Windows.Workbench.UnrealAnimator", L"GhostRigger.Windows.Workbench.UnrealAnimator.dll", "gr_windows_unreal_animator_window_version", "gr_windows_unreal_animator_window_capabilities_json"},
    {L"GhostRigger.Domain.Core.Workbench", L"GhostRigger.Domain.Core.Workbench.dll", "gr_workbench_version", "gr_workbench_capabilities_json"},
    {L"GhostRigger.Domain.Core.Workflow", L"GhostRigger.Domain.Core.Workflow.dll", "gr_workflow_version", "gr_workflow_capabilities_json"},
};

inline constexpr std::size_t kNativeDependencySpecCount = sizeof(kNativeDependencySpecs) / sizeof(kNativeDependencySpecs[0]);

} // namespace ghostrigger::native::core::host
