#pragma once

#include <cstddef>

namespace ghostrigger::phase15::ghostrigger_tools_twodabrowser {

using PythonFunctionDescriptorJson = const char* (*)();

struct PythonFunctionDescriptorEntry {
    const char* python_file;
    const char* qualname;
    const char* function_type;
    PythonFunctionDescriptorJson descriptor_json;
};

const char* src_core_game_game_library_ext_res_type_name_line_147_01728658_descriptor_json();
const char* src_core_game_game_library_ext_res_type_ext_line_152_be86c927_descriptor_json();
const char* src_core_game_game_library_ext_read_2da_from_library_line_409_66611753_descriptor_json();
const char* src_core_game_game_library_ext_read_gff_from_library_line_426_a81c1965_descriptor_json();
const char* src_core_game_game_library_ext_list_all_resources_line_443_a95d6a3e_descriptor_json();
const char* src_core_resources_game_resource_provider_coerce_resource_query_line_167_aa2b5698_descriptor_json();
const char* src_core_resources_game_resource_provider_restype_to_extension_line_435_d168dbf6_descriptor_json();
const char* src_core_resources_game_resource_provider_records_from_install_line_442_29a1399c_descriptor_json();
const char* src_core_resources_game_resource_provider_override_records_line_460_fa1405f7_descriptor_json();
const char* src_core_resources_game_resource_provider_erf_records_line_484_f262248d_descriptor_json();
const char* src_core_resources_game_resource_provider_bif_records_line_522_923b63b9_descriptor_json();
const char* src_core_resources_game_resource_provider_record_line_553_2745da10_descriptor_json();
const char* src_core_resources_game_resource_provider_record_matches_line_585_f4a92796_descriptor_json();
const char* src_core_resources_game_resource_provider_sort_records_line_602_cf3d7f84_descriptor_json();
const char* src_core_resources_game_resource_provider_dedupe_records_line_616_788f2d14_descriptor_json();
const char* src_core_resources_game_resource_provider_shadow_warnings_line_628_0fd0c506_descriptor_json();
const char* src_core_resources_game_resource_provider_missing_message_line_639_8fea0f4d_descriptor_json();
const char* src_core_resources_game_resource_provider_safe_path_size_line_645_ca4cce06_descriptor_json();
const char* src_core_resources_game_resource_provider_clean_text_line_654_ba113744_descriptor_json();
const char* src_core_resources_game_resource_provider_clean_restype_line_663_96e19284_descriptor_json();
const char* src_core_resources_game_resource_provider_clean_game_line_672_dc0cf339_descriptor_json();
const char* src_core_resources_game_resource_provider_manager_game_name_line_684_d824b250_descriptor_json();
const char* src_core_resources_game_resource_provider_manager_install_line_688_f11c7825_descriptor_json();
const char* src_core_resources_game_resource_provider_resource_manager_type_id_line_696_88dd7962_descriptor_json();
const char* src_core_resources_game_resource_provider_resource_manager_restype_line_706_feb4e7a7_descriptor_json();
const char* src_core_resources_game_resource_provider_known_resource_type_ids_line_715_dd065008_descriptor_json();
const char* src_core_templates_twoda_split_2da_line_line_345_e1fcb025_descriptor_json();
const char* src_resources_game_detector_detect_kotor_dirs_line_59_58c316ed_descriptor_json();
const char* src_resources_game_detector_save_config_line_140_715b3b16_descriptor_json();
const char* src_resources_game_detector_load_config_line_159_231807ce_descriptor_json();
const char* src_resources_game_detector_list_all_candidates_line_172_cfdbd573_descriptor_json();
const char* src_resources_game_detector_is_kotor_dir_line_212_41b67c1f_descriptor_json();
const char* src_resources_game_detector_steam_library_paths_line_260_6ffd514b_descriptor_json();
const char* src_resources_game_detector_steam_candidates_line_324_c5aaa94d_descriptor_json();
const char* src_resources_game_detector_gog_candidates_line_369_7c4b8b65_descriptor_json();
const char* src_resources_game_detector_default_candidates_line_422_4e4dc2c4_descriptor_json();
const char* src_resources_game_detector_unique_paths_line_468_37e6a31e_descriptor_json();
const char* src_resources_game_detector_windows_drive_roots_line_484_9fabc71e_descriptor_json();
const char* src_resources_game_detector_registry_path_values_line_500_c1d5de92_descriptor_json();
const char* src_resources_game_detector_windows_registry_steam_roots_line_520_b845a039_descriptor_json();
const char* src_resources_game_detector_windows_registry_kotor_candidates_line_539_84aa7014_descriptor_json();
const char* src_resources_game_detector_windows_uninstall_kotor_candidates_line_568_2f969042_descriptor_json();
const char* src_resources_game_library_res_ext_line_125_0163fdc4_descriptor_json();
const char* src_resources_game_library_res_name_line_130_c437aa6c_descriptor_json();

const PythonFunctionDescriptorEntry* modulefunctions_descriptors(std::size_t& count);

} // namespace ghostrigger::phase15::ghostrigger_tools_twodabrowser
