#pragma once

#include <cstddef>

namespace ghostrigger::phase15::ghostrigger_systems_bas {

using PythonFunctionDescriptorJson = const char* (*)();

struct PythonFunctionDescriptorEntry {
    const char* python_file;
    const char* qualname;
    const char* function_type;
    PythonFunctionDescriptorJson descriptor_json;
};

const char* src_systems_bas_attachment_alignment_normalize_bas_resref_line_25_63472742_descriptor_json();
const char* src_systems_bas_attachment_alignment_normalize_bas_transform_line_34_2867dcbd_descriptor_json();
const char* src_systems_bas_attachment_alignment_default_bas_attachment_transform_line_55_2f890e53_descriptor_json();
const char* src_systems_bas_head_resolution_normalize_bas_model_resref_line_23_86f0d7ea_descriptor_json();
const char* src_systems_bas_head_resolution_resolve_bas_head_resref_line_53_eb599759_descriptor_json();
const char* src_systems_bas_head_resolution_looks_like_resref_line_117_4f528da4_descriptor_json();
const char* src_systems_bas_head_resolution_dedupe_line_126_3e37b23d_descriptor_json();
const char* src_systems_bas_head_resolution_model_exists_line_137_cff72b3c_descriptor_json();
const char* src_systems_bas_head_resolution_resolve_head_from_appearance_tables_line_160_7c6277c5_descriptor_json();
const char* src_systems_bas_head_resolution_body_name_head_candidates_line_194_0bf8d8d4_descriptor_json();
const char* src_systems_bas_model_recipe_default_bas_models_dir_line_38_472c515c_descriptor_json();
const char* src_systems_bas_model_recipe_safe_bas_recipe_stem_line_42_3b448488_descriptor_json();
const char* src_systems_bas_model_recipe_bas_model_identity_line_49_6dedf178_descriptor_json();
const char* src_systems_bas_model_recipe_build_bas_model_recipe_line_63_313e3e68_descriptor_json();
const char* src_systems_bas_model_recipe_save_bas_model_recipe_line_150_ffb1ac21_descriptor_json();
const char* src_systems_bas_model_recipe_normalize_bas_layer_transform_line_159_327c4094_descriptor_json();
const char* src_systems_bas_model_recipe_is_bas_model_recipe_line_179_666a474f_descriptor_json();
const char* src_systems_bas_model_recipe_load_bas_model_recipe_line_183_37c726d9_descriptor_json();
const char* src_systems_bas_preview_composer_reset_bas_model_node_traversal_line_19_e06bc21c_descriptor_json();
const char* src_systems_bas_preview_composer_find_model_node_line_37_4ef2e04a_descriptor_json();
const char* src_systems_bas_preview_composer_bas_slot_for_preview_socket_line_53_7b7e3031_descriptor_json();
const char* src_systems_bas_preview_composer_bas_socket_for_slot_line_66_5f721465_descriptor_json();
const char* src_systems_bas_preview_composer_tag_bas_attachment_subtree_line_71_e720aa75_descriptor_json();
const char* src_systems_bas_preview_composer_apply_bas_layer_transform_line_90_4bd48a78_descriptor_json();
const char* src_systems_bas_preview_composer_prepare_bas_layer_root_line_99_0cb421ed_descriptor_json();
const char* src_systems_bas_preview_composer_attach_bas_item_to_preview_line_116_b831a5bd_descriptor_json();
const char* src_systems_bas_preview_composer_build_bas_preview_model_line_148_e4c9e40e_descriptor_json();

const PythonFunctionDescriptorEntry* modulefunctions_descriptors(std::size_t& count);

} // namespace ghostrigger::phase15::ghostrigger_systems_bas
