#pragma once

#include <cstddef>

namespace ghostrigger::phase15::ghostrigger_retargeting {

using PythonFunctionDescriptorJson = const char* (*)();

struct PythonFunctionDescriptorEntry {
    const char* python_file;
    const char* qualname;
    const char* function_type;
    PythonFunctionDescriptorJson descriptor_json;
};

const char* src_core_retargeting_aurora_animation_writer_auroraanimationwriter_validate_export_motion_amplitude_line_747_c09f7fed_descriptor_json();
const char* src_core_retargeting_aurora_animation_writer_auroraanimationwriter_source_world_rotation_amplitude_degrees_line_796_4382d513_descriptor_json();
const char* src_core_retargeting_aurora_animation_writer_auroraanimationwriter_export_orientation_amplitude_degrees_line_805_5f8de857_descriptor_json();
const char* src_core_retargeting_aurora_animation_writer_auroraanimationwriter_hemisphere_continuous_xyzw_line_1099_fb94c156_descriptor_json();
const char* src_core_retargeting_aurora_animation_writer_auroraanimationwriter_constant_orientation_values_line_1111_7ff6d28f_descriptor_json();
const char* src_core_retargeting_aurora_animation_writer_auroraanimationwriter_position_values_from_frames_line_1133_1d0e9e8a_descriptor_json();
const char* src_core_retargeting_coordinate_converter_quaternion_from_xyzw_line_28_290fd502_descriptor_json();
const char* src_core_retargeting_source_animation_transform_from_matrix_line_109_7fa18a91_descriptor_json();

const PythonFunctionDescriptorEntry* classmethods_descriptors(std::size_t& count);

} // namespace ghostrigger::phase15::ghostrigger_retargeting
