#pragma once

#include <cstddef>

namespace ghostrigger::phase15::ghostrigger_retargeting {

using PythonFunctionDescriptorJson = const char* (*)();

struct PythonFunctionDescriptorEntry {
    const char* python_file;
    const char* qualname;
    const char* function_type;
    PythonFunctionDescriptorJson descriptor_json;
};

const char* src_core_retargeting_animation_injector_animationinjectionrequest_post_init_line_48_ceaa5d15_descriptor_json();
const char* src_core_retargeting_animation_injector_animationinjectionresult_to_dict_line_95_6e619e72_descriptor_json();
const char* src_core_retargeting_animation_injector_animationinjector_init_line_127_c9b043f0_descriptor_json();
const char* src_core_retargeting_animation_injector_animationinjector_load_target_model_line_144_19d93667_descriptor_json();
const char* src_core_retargeting_animation_injector_animationinjector_extract_for_injection_line_154_dbc8e639_descriptor_json();
const char* src_core_retargeting_animation_injector_animationinjector_inject_line_282_b493422c_descriptor_json();
const char* src_core_retargeting_apose_compatibility_aposecompatibilityreport_failing_bones_line_54_7124774f_descriptor_json();
const char* src_core_retargeting_aurora_animation_writer_auroraanimationinjectionrequest_post_init_line_383_9bce2c12_descriptor_json();
const char* src_core_retargeting_aurora_animation_writer_auroraanimationinjectionresult_to_dict_line_426_a0b6543e_descriptor_json();
const char* src_core_retargeting_aurora_animation_writer_auroraanimationwriter_inject_line_467_8052a798_descriptor_json();
const char* src_core_retargeting_aurora_animation_writer_auroraanimationwriter_inject_animation_block_line_531_12187f17_descriptor_json();
const char* src_core_retargeting_aurora_animation_writer_auroraanimationwriter_finish_line_577_b2ebdc76_descriptor_json();
const char* src_core_retargeting_aurora_animation_writer_auroraanimationwriter_load_model_line_601_53882838_descriptor_json();
const char* src_core_retargeting_aurora_animation_writer_auroraanimationwriter_load_output_model_line_615_4ebaae4f_descriptor_json();
const char* src_core_retargeting_aurora_animation_writer_auroraanimationwriter_write_animation_block_to_output_line_623_37d2c8e2_descriptor_json();
const char* src_core_retargeting_aurora_animation_writer_auroraanimationwriter_build_animation_from_r3a_line_840_e761ba6b_descriptor_json();
const char* src_core_retargeting_aurora_animation_writer_auroraanimationwriter_capture_aurora_rest_bases_line_1172_92d11606_descriptor_json();
const char* src_core_retargeting_aurora_animation_writer_auroraanimationwriter_source_rest_basis_aurora_line_1182_ac67e1d8_descriptor_json();
const char* src_core_retargeting_aurora_animation_writer_auroraanimationwriter_basis_change_for_curve_line_1205_ae37c401_descriptor_json();
const char* src_core_retargeting_aurora_animation_writer_auroraanimationwriter_motion_rotation_xyzw_from_ue5_world_line_1227_069bdd3a_descriptor_json();
const char* src_core_retargeting_aurora_animation_writer_auroraanimationwriter_local_rotation_xyzw_from_ue5_world_line_1294_6527215d_descriptor_json();
const char* src_core_retargeting_baker_bindoffsets_offset_for_line_87_b1291706_descriptor_json();
const char* src_core_retargeting_coordinate_basisconversion_post_init_line_31_a3d820d0_descriptor_json();
const char* src_core_retargeting_coordinate_basisconversion_convert_point_line_42_a75568cf_descriptor_json();
const char* src_core_retargeting_coordinate_basisconversion_convert_rotation_matrix_line_48_7b84d22c_descriptor_json();
const char* src_core_retargeting_coordinate_basisconversion_convert_transform_line_55_2a7151d9_descriptor_json();
const char* src_core_retargeting_coordinate_converter_quaternion_normalized_line_31_e6781df6_descriptor_json();
const char* src_core_retargeting_coordinate_converter_quaternion_to_xyzw_line_37_654744c5_descriptor_json();
const char* src_core_retargeting_coordinate_converter_quaternion_to_wxyz_line_40_9559ad20_descriptor_json();
const char* src_core_retargeting_coordinate_converter_vector3_to_xyz_line_50_47851b02_descriptor_json();
const char* src_core_retargeting_coordinate_normalizer_bindposeregistry_has_bone_line_175_2fc80d6d_descriptor_json();
const char* src_core_retargeting_coordinate_normalizer_bindposeregistry_world_matrix_line_178_b8f8d250_descriptor_json();
const char* src_core_retargeting_coordinate_normalizer_bindposeregistry_world_inverse_line_181_88ae9802_descriptor_json();
const char* src_core_retargeting_coordinate_normalizer_bindposeregistry_local_matrix_line_184_e0d21f39_descriptor_json();
const char* src_core_retargeting_coordinate_normalizer_bindposeregistry_parent_key_line_187_e3dc5179_descriptor_json();
const char* src_core_retargeting_coordinate_normalizer_bindposeregistry_world_position_line_190_8faada34_descriptor_json();
const char* src_core_retargeting_coordinate_normalizer_bindposeregistry_world_rotation_line_193_46dbf0b7_descriptor_json();
const char* src_core_retargeting_coordinate_normalizer_bindposeregistry_local_position_line_196_20843e6e_descriptor_json();
const char* src_core_retargeting_coordinate_normalizer_bindposeregistry_local_rotation_line_199_1b53fa82_descriptor_json();
const char* src_core_retargeting_coordinate_normalizer_coordinatenormalizer_normalize_aurora_bind_line_208_c852e89e_descriptor_json();
const char* src_core_retargeting_coordinate_normalizer_coordinatenormalizer_normalize_ue5_bind_line_211_9170d580_descriptor_json();
const char* src_core_retargeting_coordinate_normalizer_coordinatenormalizer_normalize_model_bind_line_217_164a1d92_descriptor_json();
const char* src_core_retargeting_coordinate_normalizer_coordinatenormalizer_normalize_vertex_positions_line_266_bd7479a8_descriptor_json();
const char* src_core_retargeting_coordinate_normalizer_coordinatenormalizer_compare_g5_inverse_bind_line_272_95417f98_descriptor_json();
const char* src_core_retargeting_fbx_backend_abstractfbximporter_import_animation_line_60_f95fd45c_descriptor_json();
const char* src_core_retargeting_fbx_backend_abstractfbximporter_is_available_line_64_6147a1c9_descriptor_json();
const char* src_core_retargeting_fbx_backend_abstractfbximporter_get_backend_info_line_68_bc986f78_descriptor_json();
const char* src_core_retargeting_fbx_backend_blenderfbximporter_init_line_78_2e2805f5_descriptor_json();
const char* src_core_retargeting_fbx_backend_blenderfbximporter_resolve_executable_line_81_2b547bfe_descriptor_json();
const char* src_core_retargeting_fbx_backend_blenderfbximporter_is_available_line_84_98a69ba4_descriptor_json();
const char* src_core_retargeting_fbx_backend_blenderfbximporter_get_backend_info_line_91_5528fc06_descriptor_json();
const char* src_core_retargeting_fbx_backend_blenderfbximporter_import_animation_line_121_9f280f8f_descriptor_json();
const char* src_core_retargeting_fbx_backend_autodesksdkfbximporter_init_line_136_6e646613_descriptor_json();
const char* src_core_retargeting_fbx_backend_autodesksdkfbximporter_load_module_line_143_e2268e28_descriptor_json();
const char* src_core_retargeting_fbx_backend_autodesksdkfbximporter_initialize_sdk_line_150_1e5af217_descriptor_json();
const char* src_core_retargeting_fbx_backend_autodesksdkfbximporter_is_available_line_168_ba9714be_descriptor_json();
const char* src_core_retargeting_fbx_backend_autodesksdkfbximporter_get_backend_info_line_171_4b9c9339_descriptor_json();
const char* src_core_retargeting_fbx_backend_autodesksdkfbximporter_import_animation_line_189_f204d549_descriptor_json();
const char* src_core_retargeting_fbx_exporter_fbxexportmanifest_to_json_dict_line_117_cfbf64be_descriptor_json();
const char* src_core_retargeting_fbx_importer_fbxbackendscene_evaluate_global_transform_line_80_d0b9b24d_descriptor_json();
const char* src_core_retargeting_fbx_importer_fbxbackend_load_scene_line_87_e0d4ca5b_descriptor_json();
const char* src_core_retargeting_fbx_importer_blenderfbxbackendscene_evaluate_global_transform_line_106_9cc4af6f_descriptor_json();
const char* src_core_retargeting_fbx_importer_blenderfbxbackendscene_bind_global_transform_line_118_847397f8_descriptor_json();
const char* src_core_retargeting_fbx_importer_blenderfbxbackend_load_scene_line_134_a13a71c9_descriptor_json();
const char* src_core_retargeting_fbx_importer_blenderfbxbackend_extract_payload_line_153_c4ce3e2e_descriptor_json();
const char* src_core_retargeting_fbx_importer_blenderfbxbackend_output_json_path_line_167_6aab997b_descriptor_json();
const char* src_core_retargeting_mixamo_source_adapter_mixamosourceadapter_adapt_line_114_6dbac899_descriptor_json();
const char* src_core_retargeting_retarget_calibration_retargetcalibrationreport_by_target_parent_line_71_565aea89_descriptor_json();
const char* src_core_retargeting_retarget_mapping_retargetprofilevalidationreport_add_error_line_63_08e0d974_descriptor_json();
const char* src_core_retargeting_retarget_mapping_retargetprofilevalidationreport_add_warning_line_67_c1c83afc_descriptor_json();
const char* src_core_retargeting_retarget_preview_retargetviewportadapter_set_model_line_104_fe5ea624_descriptor_json();
const char* src_core_retargeting_retarget_preview_retargetviewportadapter_set_active_animation_line_107_a5d8fc8d_descriptor_json();
const char* src_core_retargeting_retarget_preview_retargetviewportadapter_set_time_line_110_254d2486_descriptor_json();
const char* src_core_retargeting_retarget_preview_retargetviewportadapter_play_line_113_145fe871_descriptor_json();
const char* src_core_retargeting_retarget_preview_retargetviewportadapter_pause_line_116_98d2f646_descriptor_json();
const char* src_core_retargeting_retarget_preview_retargetviewportadapter_enable_node_overlay_line_119_4f24f60d_descriptor_json();
const char* src_core_retargeting_retarget_preview_export_retargetpreviewexportrequest_post_init_line_57_ba444119_descriptor_json();
const char* src_core_retargeting_reverse_renamer_reverserenamespec_as_payload_line_44_97b47cb8_descriptor_json();
const char* src_core_retargeting_sampler_stockcorpusresourcemanager_init_line_65_615763ed_descriptor_json();
const char* src_core_retargeting_sampler_stockcorpusresourcemanager_load_model_line_68_0fb8e9c0_descriptor_json();
const char* src_core_retargeting_skeleton_renamer_renamespec_as_payload_line_78_3e2ae4d9_descriptor_json();
const char* src_core_retargeting_source_animation_transform_to_matrix_line_128_06b7efd1_descriptor_json();
const char* src_core_retargeting_source_animation_transform_is_finite_line_135_826ee869_descriptor_json();
const char* src_core_retargeting_source_animation_sourceskeletonclip_pose_at_time_line_184_8c63d90e_descriptor_json();
const char* src_core_retargeting_source_skeleton_audit_sourceanimationaudit_add_error_line_24_7c881d7b_descriptor_json();
const char* src_core_retargeting_source_skeleton_audit_sourceanimationaudit_add_warning_line_28_31635c34_descriptor_json();
const char* src_core_retargeting_ue5_source_adapter_ue5sourceadapterresult_target_for_line_86_18616d1b_descriptor_json();
const char* src_core_retargeting_ue5_source_adapter_ue5sourceadapterresult_to_dict_line_93_bbaca1ad_descriptor_json();
const char* src_core_retargeting_ue5_source_adapter_ue5sourceadapter_init_line_114_76078a13_descriptor_json();
const char* src_core_retargeting_ue5_source_adapter_ue5sourceadapter_adapt_line_126_8c8341fe_descriptor_json();
const char* src_core_retargeting_ue_fbx_exporter_unrealfbxanimationexportbackend_is_available_line_32_99101df3_descriptor_json();
const char* src_core_retargeting_ue_fbx_exporter_unrealfbxanimationexportbackend_export_animation_clip_line_35_6e195661_descriptor_json();
const char* src_core_retargeting_unreal_target_skeleton_unrealtargetskeleton_node_by_name_line_50_22c011f4_descriptor_json();

const PythonFunctionDescriptorEntry* instancemethods_descriptors(std::size_t& count);

} // namespace ghostrigger::phase15::ghostrigger_retargeting
