#pragma once

#include <cstddef>

namespace ghostrigger::retargeting {

#ifndef GHOSTRIGGER_RETARGETING_NATIVE_FUNCTION_IMPLEMENTATION_DEFINED
#define GHOSTRIGGER_RETARGETING_NATIVE_FUNCTION_IMPLEMENTATION_DEFINED
struct NativeFunctionImplementation {
    const char* project;
    const char* native_namespace;
    const char* python_file;
    const char* qualname;
    const char* callable_type;
    const char* implementation_status;
    bool native_first;
    bool python_runtime_required;
    bool python_fallback_allowed;
    const char* contract_json;
};
#endif // GHOSTRIGGER_RETARGETING_NATIVE_FUNCTION_IMPLEMENTATION_DEFINED

const NativeFunctionImplementation& animationinjectionrequest_post_construct_line_48_ceaa5d15_native();
const NativeFunctionImplementation& animationinjectionresult_to_dict_line_95_6e619e72_native();
const NativeFunctionImplementation& animationinjector_construct_line_127_c9b043f0_native();
const NativeFunctionImplementation& animationinjector_load_target_model_line_144_19d93667_native();
const NativeFunctionImplementation& animationinjector_extract_for_injection_line_154_dbc8e639_native();
const NativeFunctionImplementation& animationinjector_inject_line_282_b493422c_native();
const NativeFunctionImplementation& aposecompatibilityreport_failing_bones_line_54_7124774f_native();
const NativeFunctionImplementation& auroraanimationinjectionrequest_post_construct_line_383_9bce2c12_native();
const NativeFunctionImplementation& auroraanimationinjectionresult_to_dict_line_426_a0b6543e_native();
const NativeFunctionImplementation& auroraanimationwriter_inject_line_467_8052a798_native();
const NativeFunctionImplementation& auroraanimationwriter_inject_animation_block_line_531_12187f17_native();
const NativeFunctionImplementation& auroraanimationwriter_finish_line_577_b2ebdc76_native();
const NativeFunctionImplementation& auroraanimationwriter_load_model_line_601_53882838_native();
const NativeFunctionImplementation& auroraanimationwriter_load_output_model_line_615_4ebaae4f_native();
const NativeFunctionImplementation& auroraanimationwriter_write_animation_block_to_output_line_623_37d2c8e2_native();
const NativeFunctionImplementation& auroraanimationwriter_build_animation_from_r3a_line_840_e761ba6b_native();
const NativeFunctionImplementation& auroraanimationwriter_capture_aurora_rest_bases_line_1172_92d11606_native();
const NativeFunctionImplementation& auroraanimationwriter_source_rest_basis_aurora_line_1182_ac67e1d8_native();
const NativeFunctionImplementation& auroraanimationwriter_basis_change_for_curve_line_1205_ae37c401_native();
const NativeFunctionImplementation& auroraanimationwriter_motion_rotation_xyzw_from_ue5_world_line_1227_069bdd3a_native();
const NativeFunctionImplementation& auroraanimationwriter_local_rotation_xyzw_from_ue5_world_line_1294_6527215d_native();
const NativeFunctionImplementation& bindoffsets_offset_for_line_87_b1291706_native();
const NativeFunctionImplementation& basisconversion_post_construct_line_31_a3d820d0_native();
const NativeFunctionImplementation& basisconversion_convert_point_line_42_a75568cf_native();
const NativeFunctionImplementation& basisconversion_convert_rotation_matrix_line_48_7b84d22c_native();
const NativeFunctionImplementation& basisconversion_convert_transform_line_55_2a7151d9_native();
const NativeFunctionImplementation& quaternion_normalized_line_31_e6781df6_native();
const NativeFunctionImplementation& quaternion_to_xyzw_line_37_654744c5_native();
const NativeFunctionImplementation& quaternion_to_wxyz_line_40_9559ad20_native();
const NativeFunctionImplementation& vector3_to_xyz_line_50_47851b02_native();
const NativeFunctionImplementation& bindposeregistry_has_bone_line_175_2fc80d6d_native();
const NativeFunctionImplementation& bindposeregistry_world_matrix_line_178_b8f8d250_native();
const NativeFunctionImplementation& bindposeregistry_world_inverse_line_181_88ae9802_native();
const NativeFunctionImplementation& bindposeregistry_local_matrix_line_184_e0d21f39_native();
const NativeFunctionImplementation& bindposeregistry_parent_key_line_187_e3dc5179_native();
const NativeFunctionImplementation& bindposeregistry_world_position_line_190_8faada34_native();
const NativeFunctionImplementation& bindposeregistry_world_rotation_line_193_46dbf0b7_native();
const NativeFunctionImplementation& bindposeregistry_local_position_line_196_20843e6e_native();
const NativeFunctionImplementation& bindposeregistry_local_rotation_line_199_1b53fa82_native();
const NativeFunctionImplementation& coordinatenormalizer_normalize_aurora_bind_line_208_c852e89e_native();
const NativeFunctionImplementation& coordinatenormalizer_normalize_ue5_bind_line_211_9170d580_native();
const NativeFunctionImplementation& coordinatenormalizer_normalize_model_bind_line_217_164a1d92_native();
const NativeFunctionImplementation& coordinatenormalizer_normalize_vertex_positions_line_266_bd7479a8_native();
const NativeFunctionImplementation& coordinatenormalizer_compare_g5_inverse_bind_line_272_95417f98_native();
const NativeFunctionImplementation& abstractfbximporter_import_animation_line_60_f95fd45c_native();
const NativeFunctionImplementation& abstractfbximporter_is_available_line_64_6147a1c9_native();
const NativeFunctionImplementation& abstractfbximporter_get_backend_info_line_68_bc986f78_native();
const NativeFunctionImplementation& blenderfbximporter_construct_line_78_2e2805f5_native();
const NativeFunctionImplementation& blenderfbximporter_resolve_executable_line_81_2b547bfe_native();
const NativeFunctionImplementation& blenderfbximporter_is_available_line_84_98a69ba4_native();
const NativeFunctionImplementation& blenderfbximporter_get_backend_info_line_91_5528fc06_native();
const NativeFunctionImplementation& blenderfbximporter_import_animation_line_121_9f280f8f_native();
const NativeFunctionImplementation& autodesksdkfbximporter_construct_line_136_6e646613_native();
const NativeFunctionImplementation& autodesksdkfbximporter_load_module_line_143_e2268e28_native();
const NativeFunctionImplementation& autodesksdkfbximporter_constructialize_sdk_line_150_1e5af217_native();
const NativeFunctionImplementation& autodesksdkfbximporter_is_available_line_168_ba9714be_native();
const NativeFunctionImplementation& autodesksdkfbximporter_get_backend_info_line_171_4b9c9339_native();
const NativeFunctionImplementation& autodesksdkfbximporter_import_animation_line_189_f204d549_native();
const NativeFunctionImplementation& fbxexportmanifest_to_json_dict_line_117_cfbf64be_native();
const NativeFunctionImplementation& fbxbackendscene_evaluate_global_transform_line_80_d0b9b24d_native();
const NativeFunctionImplementation& fbxbackend_load_scene_line_87_e0d4ca5b_native();
const NativeFunctionImplementation& blenderfbxbackendscene_evaluate_global_transform_line_106_9cc4af6f_native();
const NativeFunctionImplementation& blenderfbxbackendscene_bind_global_transform_line_118_847397f8_native();
const NativeFunctionImplementation& blenderfbxbackend_load_scene_line_134_a13a71c9_native();
const NativeFunctionImplementation& blenderfbxbackend_extract_payload_line_153_c4ce3e2e_native();
const NativeFunctionImplementation& blenderfbxbackend_output_json_path_line_167_6aab997b_native();
const NativeFunctionImplementation& mixamosourceadapter_adapt_line_114_6dbac899_native();
const NativeFunctionImplementation& retargetcalibrationreport_by_target_parent_line_71_565aea89_native();
const NativeFunctionImplementation& retargetprofilevalidationreport_add_error_line_63_08e0d974_native();
const NativeFunctionImplementation& retargetprofilevalidationreport_add_warning_line_67_c1c83afc_native();
const NativeFunctionImplementation& retargetviewportadapter_set_model_line_104_fe5ea624_native();
const NativeFunctionImplementation& retargetviewportadapter_set_active_animation_line_107_a5d8fc8d_native();
const NativeFunctionImplementation& retargetviewportadapter_set_time_line_110_254d2486_native();
const NativeFunctionImplementation& retargetviewportadapter_play_line_113_145fe871_native();
const NativeFunctionImplementation& retargetviewportadapter_pause_line_116_98d2f646_native();
const NativeFunctionImplementation& retargetviewportadapter_enable_node_overlay_line_119_4f24f60d_native();
const NativeFunctionImplementation& retargetpreviewexportrequest_post_construct_line_57_ba444119_native();
const NativeFunctionImplementation& reverserenamespec_as_payload_line_44_97b47cb8_native();
const NativeFunctionImplementation& stockcorpusresourcemanager_construct_line_65_615763ed_native();
const NativeFunctionImplementation& stockcorpusresourcemanager_load_model_line_68_0fb8e9c0_native();
const NativeFunctionImplementation& renamespec_as_payload_line_78_3e2ae4d9_native();
const NativeFunctionImplementation& transform_to_matrix_line_128_06b7efd1_native();
const NativeFunctionImplementation& transform_is_fconstructe_line_135_826ee869_native();
const NativeFunctionImplementation& sourceskeletonclip_pose_at_time_line_184_8c63d90e_native();
const NativeFunctionImplementation& sourceanimationaudit_add_error_line_24_7c881d7b_native();
const NativeFunctionImplementation& sourceanimationaudit_add_warning_line_28_31635c34_native();
const NativeFunctionImplementation& ue5sourceadapterresult_target_for_line_86_18616d1b_native();
const NativeFunctionImplementation& ue5sourceadapterresult_to_dict_line_93_bbaca1ad_native();
const NativeFunctionImplementation& ue5sourceadapter_construct_line_114_76078a13_native();
const NativeFunctionImplementation& ue5sourceadapter_adapt_line_126_8c8341fe_native();
const NativeFunctionImplementation& unrealfbxanimationexportbackend_is_available_line_32_99101df3_native();
const NativeFunctionImplementation& unrealfbxanimationexportbackend_export_animation_clip_line_35_6e195661_native();
const NativeFunctionImplementation& unrealtargetskeleton_node_by_name_line_50_22c011f4_native();

const NativeFunctionImplementation* instancemethods_native_functions(std::size_t& count);

} // namespace ghostrigger::retargeting
