#pragma once

#include <cstddef>

namespace ghostrigger::core::tools::retargeting {

#ifndef GHOSTRIGGER_TOOLS_RETARGETING_NATIVE_FUNCTION_IMPLEMENTATION_DEFINED
#define GHOSTRIGGER_TOOLS_RETARGETING_NATIVE_FUNCTION_IMPLEMENTATION_DEFINED
struct NativeFunctionImplementation {
    const char* project;
    const char* native_namespace;
    const char* python_file;
    const char* qualname;
    const char* callable_type;
    const char* implementation_status;
    bool native_first;
    bool python_runtime_required;
    bool python_fallback_allowed;
    const char* contract_json;
};
#endif // GHOSTRIGGER_TOOLS_RETARGETING_NATIVE_FUNCTION_IMPLEMENTATION_DEFINED

const NativeFunctionImplementation& animationinjector_sha256_line_131_7e1dc125_native();
const NativeFunctionImplementation& animationinjector_game_version_line_139_fec0e21e_native();
const NativeFunctionImplementation& auroraanimationwriter_sha256_line_456_c6a70532_native();
const NativeFunctionImplementation& auroraanimationwriter_game_version_line_464_9564893d_native();
const NativeFunctionImplementation& auroraanimationwriter_discard_outputs_line_589_db2226a0_native();
const NativeFunctionImplementation& auroraanimationwriter_animation_frame_count_line_739_4a6ad467_native();
const NativeFunctionImplementation& auroraanimationwriter_is_motion_gate_node_line_779_8cc47c80_native();
const NativeFunctionImplementation& auroraanimationwriter_normalize_quat_wxyz_line_819_95a5aeda_native();
const NativeFunctionImplementation& auroraanimationwriter_rotation_amplitude_wxyz_line_829_4624e937_native();
const NativeFunctionImplementation& auroraanimationwriter_normalized_times_line_1059_4886e8e5_native();
const NativeFunctionImplementation& auroraanimationwriter_merge_controller_times_line_1072_e9fbed77_native();
const NativeFunctionImplementation& auroraanimationwriter_fallback_animation_times_line_1079_3435b31a_native();
const NativeFunctionImplementation& auroraanimationwriter_normalize_quat_xyzw_line_1089_6b726730_native();
const NativeFunctionImplementation& auroraanimationwriter_three_floats_line_1120_735e824e_native();
const NativeFunctionImplementation& auroraanimationwriter_position_values_have_motion_line_1150_71694b90_native();
const NativeFunctionImplementation& auroraanimationwriter_is_root_or_pelvis_node_line_1161_0ea878bb_native();
const NativeFunctionImplementation& auroraanimationwriter_four_floats_line_1371_a7f0019a_native();
const NativeFunctionImplementation& auroraanimationwriter_validate_controller_rows_line_1377_ba7a6429_native();
const NativeFunctionImplementation& auroraanimationwriter_find_local_animation_index_line_1390_5605003a_native();
const NativeFunctionImplementation& fbxbackendfactory_backend_type_from_string_line_205_2c02004a_native();
const NativeFunctionImplementation& fbxbackendfactory_get_importer_line_212_5fc6f7dd_native();
const NativeFunctionImplementation& fbxbackendfactory_get_importer_from_environment_line_245_13512b07_native();
const NativeFunctionImplementation& fbxbackendfactory_list_available_backends_line_254_3acfe2e2_native();

const NativeFunctionImplementation* staticmethods_native_functions(std::size_t& count);

} // namespace ghostrigger::core::tools::retargeting
