#pragma once

#include <cstddef>

namespace ghostrigger::core::tools::properties {

#ifndef GHOSTRIGGER_TOOLS_PROPERTIES_NATIVE_FUNCTION_IMPLEMENTATION_DEFINED
#define GHOSTRIGGER_TOOLS_PROPERTIES_NATIVE_FUNCTION_IMPLEMENTATION_DEFINED
struct NativeFunctionImplementation {
    const char* project;
    const char* native_namespace;
    const char* python_file;
    const char* qualname;
    const char* callable_type;
    const char* implementation_status;
    bool native_first;
    bool python_runtime_required;
    bool python_fallback_allowed;
    const char* contract_json;
};
#endif // GHOSTRIGGER_TOOLS_PROPERTIES_NATIVE_FUNCTION_IMPLEMENTATION_DEFINED

const NativeFunctionImplementation& moduleeditorpropertiespanel_construct_line_16_ce9980b1_native();
const NativeFunctionImplementation& moduleeditorpropertiespanel_set_project_line_47_4e2225b7_native();
const NativeFunctionImplementation& moduleeditorpropertiespanel_set_selection_line_50_5f16ea76_native();
const NativeFunctionImplementation& moduleeditorpropertiespanel_vector_row_line_73_99645798_native();
const NativeFunctionImplementation& moduleeditorpropertiespanel_vector_line_89_75abe538_native();
const NativeFunctionImplementation& moduleeditorpropertiespanel_transform_changed_line_92_04f04e3f_native();
const NativeFunctionImplementation& moduleeditorpropertiespanel_name_changed_line_100_496f9f58_native();
const NativeFunctionImplementation& qtinspectorpanel_construct_line_147_6a68d751_native();
const NativeFunctionImplementation& qtinspectorpanel_build_line_204_d992fe69_native();
const NativeFunctionImplementation& qtinspectorpanel_apply_ghost_theme_line_234_75e0f748_native();
const NativeFunctionImplementation& qtinspectorpanel_apply_ghost_layout_line_242_c0d1b835_native();
const NativeFunctionImplementation& qtinspectorpanel_page_layout_line_252_cc1665e8_native();
const NativeFunctionImplementation& qtinspectorpanel_build_page_for_step_line_260_1ba0b966_native();
const NativeFunctionImplementation& qtinspectorpanel_populate_load_page_line_282_932c5e72_native();
const NativeFunctionImplementation& qtinspectorpanel_add_skeleton_template_picker_line_410_17abb09e_native();
const NativeFunctionImplementation& qtinspectorpanel_populate_assign_skeleton_page_line_465_b7f843f1_native();
const NativeFunctionImplementation& qtinspectorpanel_populate_preview_page_line_501_ca911a88_native();
const NativeFunctionImplementation& qtinspectorpanel_populate_check_model_page_line_587_12f0274f_native();
const NativeFunctionImplementation& qtinspectorpanel_set_check_model_result_line_631_5dfa1424_native();
const NativeFunctionImplementation& qtinspectorpanel_populate_rig_page_line_686_baea0fb7_native();
const NativeFunctionImplementation& qtinspectorpanel_set_hand_rig_status_line_931_64663f92_native();
const NativeFunctionImplementation& qtinspectorpanel_set_hand_masked_bones_line_950_834fe8ee_native();
const NativeFunctionImplementation& qtinspectorpanel_set_body_rig_status_line_967_2fc3d1bb_native();
const NativeFunctionImplementation& qtinspectorpanel_configure_skeleton_template_search_line_987_d2e6a8a1_native();
const NativeFunctionImplementation& qtinspectorpanel_show_skeleton_template_completions_line_1001_4da0bddf_native();
const NativeFunctionImplementation& qtinspectorpanel_set_skeleton_template_options_line_1019_1a4439be_native();
const NativeFunctionImplementation& qtinspectorpanel_selected_skeleton_template_key_line_1093_99a2bbb9_native();
const NativeFunctionImplementation& qtinspectorpanel_set_selected_skeleton_template_key_line_1121_aec55f33_native();
const NativeFunctionImplementation& qtinspectorpanel_set_skeleton_template_status_line_1142_f5406ee9_native();
const NativeFunctionImplementation& qtinspectorpanel_populate_check_actor_page_line_1163_8e8d3c1f_native();
const NativeFunctionImplementation& qtinspectorpanel_set_preview_animations_line_1240_766de63e_native();
const NativeFunctionImplementation& qtinspectorpanel_set_preview_status_line_1281_c94fe6aa_native();
const NativeFunctionImplementation& qtinspectorpanel_populate_motions_page_line_1296_bdb80fe0_native();
const NativeFunctionImplementation& qtinspectorpanel_selected_motion_source_line_1425_7a0f74af_native();
const NativeFunctionImplementation& qtinspectorpanel_selected_motion_supermodel_line_1431_2d48b02a_native();
const NativeFunctionImplementation& qtinspectorpanel_set_motion_assignment_status_line_1441_eddfed9d_native();
const NativeFunctionImplementation& qtinspectorpanel_set_motion_assignment_line_1456_276e7b2c_native();
const NativeFunctionImplementation& qtinspectorpanel_set_animation_library_line_1471_49f12e25_native();
const NativeFunctionImplementation& qtinspectorpanel_set_preview_attachment_source_line_1505_2a0fb8fa_native();
const NativeFunctionImplementation& qtinspectorpanel_set_preview_attachment_status_line_1515_ee76196c_native();
const NativeFunctionImplementation& qtinspectorpanel_populate_validate_page_line_1530_3ed83164_native();
const NativeFunctionImplementation& qtinspectorpanel_set_validate_for_export_result_line_1593_f3bfba3c_native();
const NativeFunctionImplementation& qtinspectorpanel_set_export_status_line_1646_6d09d1a2_native();
const NativeFunctionImplementation& qtinspectorpanel_build_head_facial_palette_line_1663_4e406e74_native();
const NativeFunctionImplementation& qtinspectorpanel_build_bone_group_line_1782_0aa43eb7_native();
const NativeFunctionImplementation& qtinspectorpanel_build_viseme_panel_line_1813_c93b035a_native();
const NativeFunctionImplementation& qtinspectorpanel_set_viseme_status_line_1918_4687e7e6_native();
const NativeFunctionImplementation& qtinspectorpanel_build_phoneme_panel_line_1937_bb5361b9_native();
const NativeFunctionImplementation& qtinspectorpanel_set_phoneme_status_line_2069_ffa1f604_native();
const NativeFunctionImplementation& qtinspectorpanel_make_unit_slider_line_2090_81ab91f2_native();
const NativeFunctionImplementation& qtinspectorpanel_on_joint_selected_line_2100_92515a09_native();
const NativeFunctionImplementation& qtinspectorpanel_on_skeleton_template_index_changed_line_2116_f77f6429_native();
const NativeFunctionImplementation& qtinspectorpanel_emit_skeleton_template_from_text_line_2121_f00bada3_native();
const NativeFunctionImplementation& qtinspectorpanel_emit_fit_adjustment_line_2138_88f7fe86_native();
const NativeFunctionImplementation& qtinspectorpanel_set_step_line_2153_d9116f86_native();
const NativeFunctionImplementation& qtinspectorpanel_current_step_line_2170_900884c9_native();
const NativeFunctionImplementation& qtinspectorpanel_set_symmetry_enabled_line_2178_ea167c4e_native();
const NativeFunctionImplementation& qtinspectorpanel_symmetry_enabled_line_2188_0b3f3262_native();
const NativeFunctionImplementation& qtinspectorpanel_selected_fit_override_line_2194_64694703_native();
const NativeFunctionImplementation& qtinspectorpanel_set_fit_adjustment_line_2211_b3fd72d7_native();
const NativeFunctionImplementation& qtinspectorpanel_set_fit_adjustment_status_line_2254_3e5fef00_native();
const NativeFunctionImplementation& qtinspectorpanel_set_import_fit_report_line_2266_11c03714_native();
const NativeFunctionImplementation& qtinspectorpanel_populate_joints_line_2436_7760a829_native();
const NativeFunctionImplementation& qtinspectorpanel_set_active_mode_line_2457_1e155f3b_native();
const NativeFunctionImplementation& qtinspectorpanel_active_mode_line_2510_f766d5ed_native();
const NativeFunctionImplementation& qtinspectorpanel_head_facial_bone_buttons_line_2514_0fe6eeed_native();
const NativeFunctionImplementation& qtinspectorpanel_head_viseme_buttons_line_2523_afda283b_native();
const NativeFunctionImplementation& qtinspectorpanel_head_phoneme_combos_line_2532_d10732de_native();
const NativeFunctionImplementation& qtpropertiespanel_construct_line_56_4af5b4ed_native();
const NativeFunctionImplementation& qtpropertiespanel_build_line_72_2b5bfffc_native();
const NativeFunctionImplementation& qtpropertiespanel_set_measurement_settings_line_110_f0e7fb63_native();
const NativeFunctionImplementation& qtpropertiespanel_set_module_browser_only_line_125_1a3d3c55_native();
const NativeFunctionImplementation& qtpropertiespanel_build_module_mesh_tab_line_140_8da5ecd3_native();
const NativeFunctionImplementation& qtpropertiespanel_show_module_browser_context_menu_line_292_a01941a3_native();
const NativeFunctionImplementation& qtpropertiespanel_spin_line_317_f23d7e07_native();
const NativeFunctionImplementation& qtpropertiespanel_build_character_mode_row_line_326_217e800a_native();
const NativeFunctionImplementation& qtpropertiespanel_update_character_mode_badge_line_382_c7ebbea7_native();
const NativeFunctionImplementation& qtpropertiespanel_set_character_mode_line_410_f4146cd4_native();
const NativeFunctionImplementation& qtpropertiespanel_on_mode_override_changed_line_439_3ea0bc70_native();
const NativeFunctionImplementation& qtpropertiespanel_apply_transform_line_461_5eaca3a7_native();
const NativeFunctionImplementation& qtpropertiespanel_show_model_line_478_4b483cb1_native();
const NativeFunctionImplementation& qtpropertiespanel_show_scene_object_line_546_4795baf9_native();
const NativeFunctionImplementation& qtpropertiespanel_scene_object_runtime_stats_line_596_72b2dba8_native();
const NativeFunctionImplementation& qtpropertiespanel_show_node_line_631_15ec320f_native();
const NativeFunctionImplementation& qtpropertiespanel_mesh_label_line_694_c6a447d1_native();
const NativeFunctionImplementation& qtpropertiespanel_is_module_mesh_candidate_line_697_32b1e2f0_native();
const NativeFunctionImplementation& qtpropertiespanel_is_walkmesh_candidate_line_702_53b8fb69_native();
const NativeFunctionImplementation& qtpropertiespanel_is_null_mesh_candidate_line_712_c2e27f58_native();
const NativeFunctionImplementation& qtpropertiespanel_is_wall_mesh_candidate_line_716_bc746dfd_native();
const NativeFunctionImplementation& qtpropertiespanel_module_mesh_candidates_line_721_59fb6a69_native();
const NativeFunctionImplementation& qtpropertiespanel_populate_module_meshes_line_740_be2ba533_native();
const NativeFunctionImplementation& qtpropertiespanel_filter_module_meshes_line_807_8ef6f3b9_native();
const NativeFunctionImplementation& qtpropertiespanel_selected_module_meshes_line_825_fbe6daa6_native();
const NativeFunctionImplementation& qtpropertiespanel_on_module_mesh_selection_changed_line_838_2a18aa18_native();
const NativeFunctionImplementation& qtpropertiespanel_on_module_mesh_item_clicked_line_847_ebe7f4f2_native();
const NativeFunctionImplementation& qtpropertiespanel_select_module_mesh_line_862_66186ed9_native();
const NativeFunctionImplementation& qtpropertiespanel_has_module_mesh_line_865_0e9e33a5_native();
const NativeFunctionImplementation& qtpropertiespanel_select_module_meshes_line_877_25022192_native();
const NativeFunctionImplementation& qtpropertiespanel_select_module_mesh_by_label_line_908_fc211601_native();
const NativeFunctionImplementation& qtpropertiespanel_select_all_module_meshes_line_945_a1affd21_native();
const NativeFunctionImplementation& qtpropertiespanel_refresh_module_mesh_rows_line_957_c74f1407_native();
const NativeFunctionImplementation& qtpropertiespanel_refresh_module_mesh_rows_line_974_f08580ba_native();
const NativeFunctionImplementation& qtpropertiespanel_set_meshes_hidden_line_977_2483d454_native();
const NativeFunctionImplementation& qtpropertiespanel_set_selected_meshes_hidden_line_989_b2ada0d0_native();
const NativeFunctionImplementation& qtpropertiespanel_hide_unselected_module_meshes_line_992_b17ce693_native();
const NativeFunctionImplementation& qtpropertiespanel_unhide_all_module_meshes_line_1006_885248c4_native();
const NativeFunctionImplementation& qtpropertiespanel_create_selection_set_from_panel_line_1015_262d97e6_native();
const NativeFunctionImplementation& qtpropertiespanel_create_mesh_group_from_panel_line_1028_b338472d_native();

const NativeFunctionImplementation* instancemethods_native_functions(std::size_t& count);

} // namespace ghostrigger::core::tools::properties
