#pragma once

#include <cstddef>

namespace ghostrigger::phase15::ghostrigger_lighting {

using PythonFunctionDescriptorJson = const char* (*)();

struct PythonFunctionDescriptorEntry {
    const char* python_file;
    const char* qualname;
    const char* function_type;
    PythonFunctionDescriptorJson descriptor_json;
};

const char* src_core_lighting_light_gizmo_renderer_helper_cache_key_line_29_fe883150_descriptor_json();
const char* src_core_lighting_light_model_vec3_line_15_ea1ef636_descriptor_json();
const char* src_core_lighting_light_model_quat_line_23_9d1219b1_descriptor_json();
const char* src_core_lighting_lightmap_bake_job_ordered_unique_line_86_08ee5861_descriptor_json();
const char* src_core_lighting_lightmap_bake_settings_int_line_168_43cff09d_descriptor_json();
const char* src_core_lighting_lightmap_bake_settings_positive_float_line_175_e6519143_descriptor_json();
const char* src_core_lighting_lightmap_bake_settings_non_negative_float_line_187_f3fc45c8_descriptor_json();
const char* src_core_lighting_lightmap_export_bridge_get_baked_lightmap_assignments_line_9_97e5a840_descriptor_json();
const char* src_core_lighting_lightmap_export_bridge_resolve_lightmap_for_material_line_23_e6e1e87d_descriptor_json();
const char* src_core_lighting_lightmap_export_bridge_export_baked_lightmap_manifest_line_30_134709fd_descriptor_json();
const char* src_core_lighting_lightmap_lighting_solver_light_color_line_258_270ce3ee_descriptor_json();
const char* src_core_lighting_lightmap_lighting_solver_intensity_line_266_a0f6c696_descriptor_json();
const char* src_core_lighting_lightmap_lighting_solver_normalized_line_270_1d1920f5_descriptor_json();
const char* src_core_lighting_lightmap_lighting_solver_normalized_rows_line_277_83e2c19e_descriptor_json();
const char* src_core_lighting_lightmap_rasterizer_world_vertices_line_163_8d640a13_descriptor_json();
const char* src_core_lighting_lightmap_rasterizer_world_normals_line_183_427aff6f_descriptor_json();
const char* src_core_lighting_lightmap_rasterizer_face_normal_line_209_707900aa_descriptor_json();
const char* src_core_lighting_lightmap_rasterizer_normalize_line_215_9af20a50_descriptor_json();
const char* src_core_lighting_lightmap_rasterizer_safe_rgb_line_222_d5ecb289_descriptor_json();
const char* src_core_lighting_lightmap_shadow_solver_ray_triangle_line_151_095a4e62_descriptor_json();
const char* src_core_lighting_lightmap_shadow_solver_direction_from_light_line_173_8fdb3115_descriptor_json();
const char* src_core_lighting_lightmap_uv_validator_uv_attr_for_channel_line_265_94958336_descriptor_json();
const char* src_core_lighting_lightmap_uv_validator_face_uv_attr_for_channel_line_269_f902752e_descriptor_json();
const char* src_core_lighting_lightmap_uv_validator_area2_line_273_5803e566_descriptor_json();
const char* src_core_lighting_lightmap_uv_validator_tri_world_area_line_278_3db13ea2_descriptor_json();
const char* src_core_lighting_lightmap_uv_validator_triangles_overlap_2d_line_288_2d9b40ea_descriptor_json();
const char* src_core_lighting_lightmap_uv_validator_project_line_305_48bdb73c_descriptor_json();
const char* src_core_lighting_particle_emitter_lerp_line_262_4a01fb4d_descriptor_json();
const char* src_core_lighting_particle_emitter_lerp3_line_267_4eac5829_descriptor_json();
const char* src_core_lighting_particle_emitter_interp3_line_275_dd2a8490_descriptor_json();
const char* src_core_lighting_particle_emitter_interp1_line_288_2fcde030_descriptor_json();
const char* src_core_lighting_particle_emitter_clamp_line_296_6765db79_descriptor_json();
const char* src_core_lighting_particle_emitter_make_emitter_from_node_line_633_9f489d15_descriptor_json();
const char* src_core_lighting_particle_emitter_build_emitter_manager_from_model_line_646_2b267f1a_descriptor_json();
const char* src_core_lighting_render_data_build_scene_lighting_render_data_line_74_b9cc29df_descriptor_json();
const char* src_core_lighting_render_data_light_kind_int_line_138_c4fe1262_descriptor_json();
const char* src_core_lighting_render_data_build_light_helper_line_batches_line_154_8e565fb7_descriptor_json();
const char* src_core_lighting_render_data_build_light_volume_line_batches_line_169_e4f01027_descriptor_json();
const char* src_core_lighting_render_data_light_nodes_line_184_449b65be_descriptor_json();
const char* src_core_lighting_render_data_light_from_node_line_194_3725f44a_descriptor_json();
const char* src_core_lighting_render_data_lighting_revision_line_242_8416abf2_descriptor_json();
const char* src_core_lighting_render_data_ambient_tuple_line_268_136d8805_descriptor_json();
const char* src_core_lighting_render_data_vec3_line_275_75cdf5df_descriptor_json();
const char* src_core_lighting_render_data_quat_line_283_ee250e87_descriptor_json();
const char* src_core_lighting_render_data_color_line_291_95584596_descriptor_json();
const char* src_core_lighting_render_data_rotate_vec_by_quat_line_296_e7f6c6ce_descriptor_json();
const char* src_core_lighting_render_data_helper_color_line_312_c70564c4_descriptor_json();
const char* src_core_lighting_render_data_marker_lines_line_331_efd220e4_descriptor_json();
const char* src_core_lighting_render_data_volume_lines_line_336_a7204b92_descriptor_json();
const char* src_core_lighting_render_data_ring_line_393_625107a8_descriptor_json();
const char* src_core_lighting_render_data_basis_line_405_fbffbad0_descriptor_json();
const char* src_core_lighting_render_data_v_add_line_413_9148d8d5_descriptor_json();
const char* src_core_lighting_render_data_v_sub_line_417_8bbb1f08_descriptor_json();
const char* src_core_lighting_render_data_v_mul_line_421_38ed9dd0_descriptor_json();
const char* src_core_lighting_render_data_v_cross_line_425_5a3b02bc_descriptor_json();
const char* src_core_lighting_render_data_v_norm_line_433_4e834692_descriptor_json();

const PythonFunctionDescriptorEntry* modulefunctions_descriptors(std::size_t& count);

} // namespace ghostrigger::phase15::ghostrigger_lighting
