#pragma once

#include <cstddef>

namespace ghostrigger::camera {

#ifndef GHOSTRIGGER_CAMERA_NATIVE_FUNCTION_IMPLEMENTATION_DEFINED
#define GHOSTRIGGER_CAMERA_NATIVE_FUNCTION_IMPLEMENTATION_DEFINED
struct NativeFunctionImplementation {
    const char* project;
    const char* native_namespace;
    const char* python_file;
    const char* qualname;
    const char* callable_type;
    const char* implementation_status;
    bool native_first;
    bool python_runtime_required;
    bool python_fallback_allowed;
    const char* contract_json;
};
#endif // GHOSTRIGGER_CAMERA_NATIVE_FUNCTION_IMPLEMENTATION_DEFINED

const NativeFunctionImplementation& arcballcamera_construct_line_23_1d73f6c8_native();
const NativeFunctionImplementation& arcballcamera_eye_line_36_9782424e_native();
const NativeFunctionImplementation& arcballcamera_orbit_line_48_b14ec1c3_native();
const NativeFunctionImplementation& arcballcamera_zoom_line_52_129c113e_native();
const NativeFunctionImplementation& arcballcamera_sync_close_clip_plane_line_56_2c68ecf4_native();
const NativeFunctionImplementation& arcballcamera_pan_line_62_d765e051_native();
const NativeFunctionImplementation& arcballcamera_frame_bounds_line_72_810353a6_native();
const NativeFunctionImplementation& arcballcamera_view_matrix_line_158_18ded173_native();
const NativeFunctionImplementation& arcballcamera_project_line_170_279997e3_native();
const NativeFunctionImplementation& cameracontroller_construct_line_10_abc7c703_native();
const NativeFunctionImplementation& cameracontroller_create_camera_line_14_6536d853_native();
const NativeFunctionImplementation& cameracontroller_create_camera_from_current_view_line_21_e63c91f9_native();
const NativeFunctionImplementation& cameracontroller_align_active_camera_to_view_line_27_0cac1f58_native();
const NativeFunctionImplementation& cameracontroller_align_view_to_selected_camera_line_34_31451bf2_native();
const NativeFunctionImplementation& cameramanager_construct_line_13_b4852ba2_native();
const NativeFunctionImplementation& cameramanager_set_model_line_19_85894f25_native();
const NativeFunctionImplementation& cameramanager_create_camera_line_28_efc01acd_native();
const NativeFunctionImplementation& cameramanager_add_camera_line_34_b48446ac_native();
const NativeFunctionImplementation& cameramanager_delete_camera_line_43_231d2ba5_native();
const NativeFunctionImplementation& cameramanager_delete_selected_line_62_92db9d35_native();
const NativeFunctionImplementation& cameramanager_duplicate_camera_line_71_e4ab6be2_native();
const NativeFunctionImplementation& cameramanager_rename_camera_line_80_8cd00074_native();
const NativeFunctionImplementation& cameramanager_get_camera_line_90_f3bd886c_native();
const NativeFunctionImplementation& cameramanager_find_by_name_line_93_58921fd6_native();
const NativeFunctionImplementation& cameramanager_find_by_original_line_97_57cf2ffe_native();
const NativeFunctionImplementation& cameramanager_get_all_cameras_line_102_9c88c20f_native();
const NativeFunctionImplementation& cameramanager_set_active_camera_line_105_81e95322_native();
const NativeFunctionImplementation& cameramanager_clear_active_camera_line_114_f1743a67_native();
const NativeFunctionImplementation& cameramanager_get_active_camera_line_118_0521ec87_native();
const NativeFunctionImplementation& cameramanager_select_camera_line_121_986c5db3_native();
const NativeFunctionImplementation& cameramanager_select_many_line_135_c6e13687_native();
const NativeFunctionImplementation& cameramanager_clear_camera_selection_line_141_a61c667b_native();
const NativeFunctionImplementation& cameramanager_selected_cameras_line_146_30947e90_native();
const NativeFunctionImplementation& cameramanager_serialize_line_150_743d9ba1_native();
const NativeFunctionImplementation& cameramanager_deserialize_line_157_865800f1_native();
const NativeFunctionImplementation& cameramanager_sync_selection_flags_line_174_87d5e948_native();
const NativeFunctionImplementation& cameramanager_store_on_model_line_182_46a32e86_native();
const NativeFunctionImplementation& cameramanager_discover_cameras_line_190_6cf16fee_native();
const NativeFunctionImplementation& cameramanager_find_existing_node_line_202_755c6ea9_native();
const NativeFunctionImplementation& cameramanager_make_camera_node_line_211_ef285d05_native();
const NativeFunctionImplementation& cameramanager_sync_generated_nodes_line_229_e5600808_native();
const NativeFunctionImplementation& cameramanager_install_all_nodes_wrapper_line_239_8124a17b_native();
const NativeFunctionImplementation& cameramanager_next_name_line_267_0b9db4d6_native();
const NativeFunctionImplementation& ghostriggercamera_post_construct_line_56_423ffb3f_native();
const NativeFunctionImplementation& ghostriggercamera_to_dict_line_99_ab652d90_native();
const NativeFunctionImplementation& ghostriggercamera_serialize_line_106_45113c9e_native();
const NativeFunctionImplementation& ghostriggercamera_apply_to_original_line_109_936b44c6_native();
const NativeFunctionImplementation& ghostriggercamera_set_focal_length_line_138_f9c5ddcc_native();
const NativeFunctionImplementation& ghostriggercamera_set_field_of_view_line_142_4b0d4912_native();
const NativeFunctionImplementation& ghostriggercamera_set_sensor_line_146_c8c82154_native();
const NativeFunctionImplementation& ghostriggercamera_validate_line_151_e06f4474_native();
const NativeFunctionImplementation& ghostriggercamera_copy_generated_line_177_4982c913_native();
const NativeFunctionImplementation& camerapicker_construct_line_12_c9b82ff6_native();
const NativeFunctionImplementation& camerapicker_hit_test_line_15_7fec2eba_native();
const NativeFunctionImplementation& rendersettings_validate_line_29_f02a7717_native();
const NativeFunctionImplementation& rendersettings_to_dict_line_36_892d86b4_native();
const NativeFunctionImplementation& cameraselection_construct_line_7_cf60e582_native();
const NativeFunctionImplementation& cameraselection_clear_line_11_b0f5d92a_native();
const NativeFunctionImplementation& cameraselection_set_single_line_15_54c5d7ee_native();
const NativeFunctionImplementation& cameraselection_set_many_line_19_2e250659_native();
const NativeFunctionImplementation& cameraselection_toggle_line_30_f4cf618b_native();
const NativeFunctionImplementation& cameraviewportadapter_construct_line_12_d784fb52_native();
const NativeFunctionImplementation& cameraviewportadapter_save_perspective_state_line_16_9050a32b_native();
const NativeFunctionImplementation& cameraviewportadapter_restore_perspective_state_line_28_cf794023_native();
const NativeFunctionImplementation& cameraviewportadapter_update_view_from_camera_line_40_eaf13771_native();
const NativeFunctionImplementation& cameraviewportadapter_update_camera_from_view_line_53_faf3a6ff_native();
const NativeFunctionImplementation& cameraviewportadapter_resolve_target_line_66_545d5fba_native();
const NativeFunctionImplementation& renderoutput_save_frame_line_10_a23b57e1_native();
const NativeFunctionImplementation& renderoutput_build_output_path_line_24_c41e799e_native();
const NativeFunctionImplementation& renderoutput_sanitize_filename_line_41_23370bbf_native();
const NativeFunctionImplementation& renderoutput_ensure_output_directory_line_46_02c83885_native();

const NativeFunctionImplementation* instancemethods_native_functions(std::size_t& count);

} // namespace ghostrigger::camera
