#pragma once

#include <cstddef>

namespace ghostrigger::phase15::ghostrigger_camera {

using PythonFunctionDescriptorJson = const char* (*)();

struct PythonFunctionDescriptorEntry {
    const char* python_file;
    const char* qualname;
    const char* function_type;
    PythonFunctionDescriptorJson descriptor_json;
};

const char* src_core_camera_arcball_camera_arcballcamera_init_line_23_1d73f6c8_descriptor_json();
const char* src_core_camera_arcball_camera_arcballcamera_eye_line_36_9782424e_descriptor_json();
const char* src_core_camera_arcball_camera_arcballcamera_orbit_line_48_b14ec1c3_descriptor_json();
const char* src_core_camera_arcball_camera_arcballcamera_zoom_line_52_129c113e_descriptor_json();
const char* src_core_camera_arcball_camera_arcballcamera_sync_close_clip_plane_line_56_2c68ecf4_descriptor_json();
const char* src_core_camera_arcball_camera_arcballcamera_pan_line_62_d765e051_descriptor_json();
const char* src_core_camera_arcball_camera_arcballcamera_frame_bounds_line_72_810353a6_descriptor_json();
const char* src_core_camera_arcball_camera_arcballcamera_view_matrix_line_158_18ded173_descriptor_json();
const char* src_core_camera_arcball_camera_arcballcamera_project_line_170_279997e3_descriptor_json();
const char* src_core_camera_camera_controller_cameracontroller_init_line_10_abc7c703_descriptor_json();
const char* src_core_camera_camera_controller_cameracontroller_create_camera_line_14_6536d853_descriptor_json();
const char* src_core_camera_camera_controller_cameracontroller_create_camera_from_current_view_line_21_e63c91f9_descriptor_json();
const char* src_core_camera_camera_controller_cameracontroller_align_active_camera_to_view_line_27_0cac1f58_descriptor_json();
const char* src_core_camera_camera_controller_cameracontroller_align_view_to_selected_camera_line_34_31451bf2_descriptor_json();
const char* src_core_camera_camera_manager_cameramanager_init_line_13_b4852ba2_descriptor_json();
const char* src_core_camera_camera_manager_cameramanager_set_model_line_19_85894f25_descriptor_json();
const char* src_core_camera_camera_manager_cameramanager_create_camera_line_28_efc01acd_descriptor_json();
const char* src_core_camera_camera_manager_cameramanager_add_camera_line_34_b48446ac_descriptor_json();
const char* src_core_camera_camera_manager_cameramanager_delete_camera_line_43_231d2ba5_descriptor_json();
const char* src_core_camera_camera_manager_cameramanager_delete_selected_line_62_92db9d35_descriptor_json();
const char* src_core_camera_camera_manager_cameramanager_duplicate_camera_line_71_e4ab6be2_descriptor_json();
const char* src_core_camera_camera_manager_cameramanager_rename_camera_line_80_8cd00074_descriptor_json();
const char* src_core_camera_camera_manager_cameramanager_get_camera_line_90_f3bd886c_descriptor_json();
const char* src_core_camera_camera_manager_cameramanager_find_by_name_line_93_58921fd6_descriptor_json();
const char* src_core_camera_camera_manager_cameramanager_find_by_original_line_97_57cf2ffe_descriptor_json();
const char* src_core_camera_camera_manager_cameramanager_get_all_cameras_line_102_9c88c20f_descriptor_json();
const char* src_core_camera_camera_manager_cameramanager_set_active_camera_line_105_81e95322_descriptor_json();
const char* src_core_camera_camera_manager_cameramanager_clear_active_camera_line_114_f1743a67_descriptor_json();
const char* src_core_camera_camera_manager_cameramanager_get_active_camera_line_118_0521ec87_descriptor_json();
const char* src_core_camera_camera_manager_cameramanager_select_camera_line_121_986c5db3_descriptor_json();
const char* src_core_camera_camera_manager_cameramanager_select_many_line_135_c6e13687_descriptor_json();
const char* src_core_camera_camera_manager_cameramanager_clear_camera_selection_line_141_a61c667b_descriptor_json();
const char* src_core_camera_camera_manager_cameramanager_selected_cameras_line_146_30947e90_descriptor_json();
const char* src_core_camera_camera_manager_cameramanager_serialize_line_150_743d9ba1_descriptor_json();
const char* src_core_camera_camera_manager_cameramanager_deserialize_line_157_865800f1_descriptor_json();
const char* src_core_camera_camera_manager_cameramanager_sync_selection_flags_line_174_87d5e948_descriptor_json();
const char* src_core_camera_camera_manager_cameramanager_store_on_model_line_182_46a32e86_descriptor_json();
const char* src_core_camera_camera_manager_cameramanager_discover_cameras_line_190_6cf16fee_descriptor_json();
const char* src_core_camera_camera_manager_cameramanager_find_existing_node_line_202_755c6ea9_descriptor_json();
const char* src_core_camera_camera_manager_cameramanager_make_camera_node_line_211_ef285d05_descriptor_json();
const char* src_core_camera_camera_manager_cameramanager_sync_generated_nodes_line_229_e5600808_descriptor_json();
const char* src_core_camera_camera_manager_cameramanager_install_all_nodes_wrapper_line_239_8124a17b_descriptor_json();
const char* src_core_camera_camera_manager_cameramanager_next_name_line_267_0b9db4d6_descriptor_json();
const char* src_core_camera_camera_model_ghostriggercamera_post_init_line_56_423ffb3f_descriptor_json();
const char* src_core_camera_camera_model_ghostriggercamera_to_dict_line_99_ab652d90_descriptor_json();
const char* src_core_camera_camera_model_ghostriggercamera_serialize_line_106_45113c9e_descriptor_json();
const char* src_core_camera_camera_model_ghostriggercamera_apply_to_original_line_109_936b44c6_descriptor_json();
const char* src_core_camera_camera_model_ghostriggercamera_set_focal_length_line_138_f9c5ddcc_descriptor_json();
const char* src_core_camera_camera_model_ghostriggercamera_set_field_of_view_line_142_4b0d4912_descriptor_json();
const char* src_core_camera_camera_model_ghostriggercamera_set_sensor_line_146_c8c82154_descriptor_json();
const char* src_core_camera_camera_model_ghostriggercamera_validate_line_151_e06f4474_descriptor_json();
const char* src_core_camera_camera_model_ghostriggercamera_copy_generated_line_177_4982c913_descriptor_json();
const char* src_core_camera_camera_picker_camerapicker_init_line_12_c9b82ff6_descriptor_json();
const char* src_core_camera_camera_picker_camerapicker_hit_test_line_15_7fec2eba_descriptor_json();
const char* src_core_camera_camera_render_settings_rendersettings_validate_line_29_f02a7717_descriptor_json();
const char* src_core_camera_camera_render_settings_rendersettings_to_dict_line_36_892d86b4_descriptor_json();
const char* src_core_camera_camera_selection_cameraselection_init_line_7_cf60e582_descriptor_json();
const char* src_core_camera_camera_selection_cameraselection_clear_line_11_b0f5d92a_descriptor_json();
const char* src_core_camera_camera_selection_cameraselection_set_single_line_15_54c5d7ee_descriptor_json();
const char* src_core_camera_camera_selection_cameraselection_set_many_line_19_2e250659_descriptor_json();
const char* src_core_camera_camera_selection_cameraselection_toggle_line_30_f4cf618b_descriptor_json();
const char* src_core_camera_camera_viewport_adapter_cameraviewportadapter_init_line_12_d784fb52_descriptor_json();
const char* src_core_camera_camera_viewport_adapter_cameraviewportadapter_save_perspective_state_line_16_9050a32b_descriptor_json();
const char* src_core_camera_camera_viewport_adapter_cameraviewportadapter_restore_perspective_state_line_28_cf794023_descriptor_json();
const char* src_core_camera_camera_viewport_adapter_cameraviewportadapter_update_view_from_camera_line_40_eaf13771_descriptor_json();
const char* src_core_camera_camera_viewport_adapter_cameraviewportadapter_update_camera_from_view_line_53_faf3a6ff_descriptor_json();
const char* src_core_camera_camera_viewport_adapter_cameraviewportadapter_resolve_target_line_66_545d5fba_descriptor_json();
const char* src_core_camera_render_output_renderoutput_save_frame_line_10_a23b57e1_descriptor_json();
const char* src_core_camera_render_output_renderoutput_build_output_path_line_24_c41e799e_descriptor_json();
const char* src_core_camera_render_output_renderoutput_sanitize_filename_line_41_23370bbf_descriptor_json();
const char* src_core_camera_render_output_renderoutput_ensure_output_directory_line_46_02c83885_descriptor_json();

const PythonFunctionDescriptorEntry* instancemethods_descriptors(std::size_t& count);

} // namespace ghostrigger::phase15::ghostrigger_camera
