#pragma once

#include <cstddef>

namespace ghostrigger::domain::core::measurement {

#ifndef GHOSTRIGGER_MEASUREMENT_NATIVE_FUNCTION_IMPLEMENTATION_DEFINED
#define GHOSTRIGGER_MEASUREMENT_NATIVE_FUNCTION_IMPLEMENTATION_DEFINED
struct NativeFunctionImplementation {
    const char* project;
    const char* native_namespace;
    const char* python_file;
    const char* qualname;
    const char* callable_type;
    const char* implementation_status;
    bool native_first;
    bool python_runtime_required;
    bool python_fallback_allowed;
    const char* contract_json;
};
#endif // GHOSTRIGGER_MEASUREMENT_NATIVE_FUNCTION_IMPLEMENTATION_DEFINED

const NativeFunctionImplementation& anglesnap_construct_line_10_d32771ad_native();
const NativeFunctionImplementation& anglesnap_set_enabled_line_15_f4dd860e_native();
const NativeFunctionImplementation& anglesnap_toggle_line_18_418e58ac_native();
const NativeFunctionImplementation& anglesnap_set_increment_degrees_line_22_dd56794d_native();
const NativeFunctionImplementation& anglesnap_snap_degrees_line_25_5c6cf86d_native();
const NativeFunctionImplementation& anglesnap_snap_radians_line_32_4d8afb99_native();
const NativeFunctionImplementation& anglesnap_apply_to_euler_line_37_6dc489f4_native();
const NativeFunctionImplementation& anglesnap_apply_delta_line_40_99081e10_native();
const NativeFunctionImplementation& dimensioncalculator_calculate_line_46_6073e550_native();
const NativeFunctionImplementation& dimensioncalculator_bounds_line_73_60c5fb14_native();
const NativeFunctionImplementation& dimensioncalculator_position_line_102_0da1b6a7_native();
const NativeFunctionImplementation& gridmeasurement_construct_line_12_1d7adb30_native();
const NativeFunctionImplementation& gridmeasurement_update_line_31_773c6a0f_native();
const NativeFunctionImplementation& gridmeasurement_format_label_line_51_e8907977_native();
const NativeFunctionImplementation& gridmeasurement_label_stride_line_54_db2cc245_native();
const NativeFunctionImplementation& gridmeasurement_extent_for_bounds_line_62_dc2527b2_native();
const NativeFunctionImplementation& measurementcontroller_construct_line_15_498716e6_native();
const NativeFunctionImplementation& measurementcontroller_configure_line_23_9d657060_native();
const NativeFunctionImplementation& measurementcontroller_begin_measurement_line_27_ba0d6b4b_native();
const NativeFunctionImplementation& measurementcontroller_update_preview_line_33_59cc5677_native();
const NativeFunctionImplementation& measurementcontroller_finish_measurement_line_37_5984a976_native();
const NativeFunctionImplementation& measurementcontroller_clear_measurement_line_45_eb4cdc6d_native();
const NativeFunctionImplementation& measurementcontroller_get_delta_line_51_5accbef6_native();
const NativeFunctionImplementation& measurementcontroller_get_distance_line_57_bb0a03cc_native();
const NativeFunctionImplementation& measurementcontroller_formatted_distance_line_63_bc986bcc_native();
const NativeFunctionImplementation& measurementcontroller_draw_overlay_line_69_3849db42_native();
const NativeFunctionImplementation& measurementcontroller_active_segment_line_91_48418274_native();
const NativeFunctionImplementation& measurementformatter_construct_line_11_d5e8c44b_native();
const NativeFunctionImplementation& measurementformatter_distance_line_15_58e1ef9f_native();
const NativeFunctionImplementation& measurementformatter_angle_degrees_line_18_aef0df60_native();
const NativeFunctionImplementation& measurementformatter_scale_line_26_6218ca83_native();
const NativeFunctionImplementation& percentsnap_construct_line_9_85db9d3f_native();
const NativeFunctionImplementation& percentsnap_set_enabled_line_14_b1733eee_native();
const NativeFunctionImplementation& percentsnap_toggle_line_17_c32a5886_native();
const NativeFunctionImplementation& percentsnap_set_increment_percent_line_21_f5aa9c1c_native();
const NativeFunctionImplementation& percentsnap_snap_percent_line_28_223b9932_native();
const NativeFunctionImplementation& percentsnap_snap_scale_factor_line_34_cdc24c95_native();
const NativeFunctionImplementation& percentsnap_apply_to_scale_line_40_00f2f4d6_native();
const NativeFunctionImplementation& measurementsettings_to_dict_line_56_4b4eb962_native();
const NativeFunctionImplementation& unitsystem_construct_line_108_e33bdd36_native();
const NativeFunctionImplementation& unitsystem_set_system_unit_line_112_9b13b0a4_native();
const NativeFunctionImplementation& unitsystem_set_display_unit_line_122_0f8f235b_native();
const NativeFunctionImplementation& unitsystem_to_display_units_line_125_5418cfb9_native();
const NativeFunctionImplementation& unitsystem_to_system_units_line_128_c46e494d_native();
const NativeFunctionImplementation& unitsystem_convert_line_131_ce73130c_native();
const NativeFunctionImplementation& unitsystem_format_distance_line_137_42f4e6db_native();
const NativeFunctionImplementation& unitsystem_parse_distance_line_149_6cb943ce_native();

const NativeFunctionImplementation* instancemethods_native_functions(std::size_t& count);

} // namespace ghostrigger::domain::core::measurement
