#pragma once

#include <cstddef>

namespace ghostrigger::phase15::ghostrigger_autorig {

using PythonFunctionDescriptorJson = const char* (*)();

struct PythonFunctionDescriptorEntry {
    const char* python_file;
    const char* qualname;
    const char* function_type;
    PythonFunctionDescriptorJson descriptor_json;
};

const char* src_autorig_cloth_rig_clothconstraintpainter_generate_line_240_efff0de6_descriptor_json();
const char* src_autorig_cloth_rig_clothconstraintpainter_vertical_line_278_40ec8904_descriptor_json();
const char* src_autorig_cloth_rig_clothconstraintpainter_radial_line_311_1c700ca3_descriptor_json();
const char* src_autorig_cloth_rig_clothconstraintpainter_bone_dist_line_329_4cd44677_descriptor_json();
const char* src_autorig_cloth_rig_clothconstraintpainter_cape_gradient_line_347_2c916fc9_descriptor_json();
const char* src_autorig_cloth_rig_clothrigexporter_constraints_to_mdl_line_634_10d85b88_descriptor_json();
const char* src_autorig_cloth_rig_clothrigexporter_constraints_from_mdl_line_645_68b610a2_descriptor_json();
const char* src_autorig_grig_bonepin_from_rig_guide_line_129_145951e6_descriptor_json();
const char* src_autorig_grig_bonepin_from_dict_line_159_443dc003_descriptor_json();
const char* src_autorig_grig_vertexinfluence_from_skin_data_line_210_c98b3eea_descriptor_json();
const char* src_autorig_retarget_engine_modelorientfixer_rot_yup_to_zup_line_131_df3a320f_descriptor_json();
const char* src_autorig_retarget_engine_modelorientfixer_rot_xup_to_zup_line_137_3e355925_descriptor_json();
const char* src_autorig_retarget_engine_modelorientfixer_rot_normal_yup_to_zup_line_143_cbc52c49_descriptor_json();
const char* src_autorig_retarget_engine_modelorientfixer_rot_normal_xup_to_zup_line_149_80392f02_descriptor_json();
const char* src_autorig_retarget_engine_modelorientfixer_detect_line_156_0f510b88_descriptor_json();
const char* src_autorig_retarget_engine_scalesolver_span_line_444_e3f3ed06_descriptor_json();
const char* src_autorig_retarget_engine_meshscaler_apply_line_480_c7319569_descriptor_json();
const char* src_autorig_retarget_engine_animationretargeter_transfer_line_537_502029a0_descriptor_json();
const char* src_autorig_retarget_engine_retargetengine_height_line_664_ef4553b0_descriptor_json();
const char* src_autorig_retarget_engine_retargetengine_bone_count_line_669_82fc178b_descriptor_json();
const char* src_autorig_retarget_engine_retargetengine_mesh_count_line_676_f1f1315f_descriptor_json();

const PythonFunctionDescriptorEntry* staticmethods_descriptors(std::size_t& count);

} // namespace ghostrigger::phase15::ghostrigger_autorig
