#pragma once

#include <cstddef>

namespace ghostrigger::phase15::ghostrigger_renderer_moderngl {

using PythonFunctionDescriptorJson = const char* (*)();

struct PythonFunctionDescriptorEntry {
    const char* python_file;
    const char* qualname;
    const char* function_type;
    PythonFunctionDescriptorJson descriptor_json;
};

const char* src_adapters_rendering_moderngl_renderer_modernglrenderer_is_available_line_16_4dce079c_descriptor_json();
const char* src_adapters_rendering_moderngl_renderer_modernglrenderer_get_capabilities_line_22_9b254c23_descriptor_json();
const char* src_adapters_rendering_moderngl_renderer_modernglrenderer_create_surface_widget_line_58_fcbf9cc9_descriptor_json();
const char* src_adapters_rendering_moderngl_renderer_modernglrenderer_shutdown_line_71_30fcaa88_descriptor_json();
const char* src_adapters_rendering_moderngl_renderer_modernglrenderer_get_diagnostics_line_74_95780033_descriptor_json();
const char* src_adapters_rendering_moderngl_renderer_impl_gpurenderer_init_line_119_61df0576_descriptor_json();
const char* src_adapters_rendering_moderngl_renderer_impl_gpurenderer_set_theme_colors_line_225_f20578ea_descriptor_json();
const char* src_adapters_rendering_moderngl_renderer_impl_gpurenderer_reset_theme_colors_line_246_bda6efb5_descriptor_json();
const char* src_adapters_rendering_moderngl_renderer_impl_gpurenderer_set_native_palette_colors_line_281_b212e65d_descriptor_json();
const char* src_adapters_rendering_moderngl_renderer_impl_gpurenderer_ensure_context_line_314_25c2af90_descriptor_json();
const char* src_adapters_rendering_moderngl_renderer_impl_gpurenderer_release_line_385_6a0a4746_descriptor_json();
const char* src_adapters_rendering_moderngl_renderer_impl_gpurenderer_clear_caches_line_458_f2274f6d_descriptor_json();
const char* src_adapters_rendering_moderngl_renderer_impl_gpurenderer_reset_framebuffers_line_501_298c6e38_descriptor_json();
const char* src_adapters_rendering_moderngl_renderer_impl_gpurenderer_reset_frame_state_line_530_adf6e548_descriptor_json();
const char* src_adapters_rendering_moderngl_renderer_impl_gpurenderer_debug_log_gl_error_line_561_23d41a7f_descriptor_json();
const char* src_adapters_rendering_moderngl_renderer_impl_gpurenderer_ensure_grid_vao_line_575_bab3fab4_descriptor_json();
const char* src_adapters_rendering_moderngl_renderer_impl_gpurenderer_draw_grid_line_607_3baffd68_descriptor_json();
const char* src_adapters_rendering_moderngl_renderer_impl_gpurenderer_is_node_selected_for_render_line_625_88d25b76_descriptor_json();
const char* src_adapters_rendering_moderngl_renderer_impl_gpurenderer_draw_light_gizmos_line_631_24acd509_descriptor_json();
const char* src_adapters_rendering_moderngl_renderer_impl_gpurenderer_scene_light_records_line_791_f8eedc72_descriptor_json();
const char* src_adapters_rendering_moderngl_renderer_impl_gpurenderer_upload_scene_lights_line_825_ab053838_descriptor_json();
const char* src_adapters_rendering_moderngl_renderer_impl_gpurenderer_render_line_888_e766348d_descriptor_json();
const char* src_adapters_rendering_moderngl_renderer_impl_gpurenderer_render_gpu_line_939_db7b458b_descriptor_json();
const char* src_adapters_rendering_moderngl_renderer_impl_gpurenderer_render_cpu_line_2597_0fe124ae_descriptor_json();
const char* src_adapters_rendering_moderngl_renderer_impl_gpurenderer_invalidate_node_line_2606_87f04150_descriptor_json();
const char* src_adapters_rendering_moderngl_renderer_impl_gpurenderer_invalidate_all_line_2616_9f1ddf0d_descriptor_json();
const char* src_adapters_rendering_moderngl_renderer_impl_gpurenderer_invalidate_node_cache_line_2626_d6d8cc76_descriptor_json();
const char* src_adapters_rendering_moderngl_renderer_impl_gpurenderer_node_classification_signature_line_2689_6209b048_descriptor_json();
const char* src_adapters_rendering_moderngl_renderer_impl_gpurenderer_perf_summary_line_2720_a06e6064_descriptor_json();
const char* src_adapters_rendering_moderngl_resources_gltexcache_init_line_53_8bba9174_descriptor_json();
const char* src_adapters_rendering_moderngl_resources_gltexcache_get_line_60_c67f2dd9_descriptor_json();
const char* src_adapters_rendering_moderngl_resources_gltexcache_upload_line_95_477dec88_descriptor_json();
const char* src_adapters_rendering_moderngl_resources_gltexcache_invalidate_line_181_cb708792_descriptor_json();
const char* src_adapters_rendering_moderngl_resources_gltexcache_clear_line_193_ec1ca963_descriptor_json();
const char* src_adapters_rendering_moderngl_resources_gpumesh_init_line_782_20e603b4_descriptor_json();
const char* src_adapters_rendering_moderngl_resources_gpumesh_release_line_801_e6c9cdff_descriptor_json();

const PythonFunctionDescriptorEntry* instancemethods_descriptors(std::size_t& count);

} // namespace ghostrigger::phase15::ghostrigger_renderer_moderngl
