#pragma once

#include <cstddef>

namespace ghostrigger::windows::unrealanimatorwindow {

#ifndef GHOSTRIGGER_WINDOWS_UNREALANIMATORWINDOW_NATIVE_FUNCTION_IMPLEMENTATION_DEFINED
#define GHOSTRIGGER_WINDOWS_UNREALANIMATORWINDOW_NATIVE_FUNCTION_IMPLEMENTATION_DEFINED
struct NativeFunctionImplementation {
    const char* project;
    const char* native_namespace;
    const char* python_file;
    const char* qualname;
    const char* callable_type;
    const char* implementation_status;
    bool native_first;
    bool python_runtime_required;
    bool python_fallback_allowed;
    const char* contract_json;
};
#endif // GHOSTRIGGER_WINDOWS_UNREALANIMATORWINDOW_NATIVE_FUNCTION_IMPLEMENTATION_DEFINED

const NativeFunctionImplementation& qtunrealanimatorwindow_construct_line_194_0dfed338_native();
const NativeFunctionImplementation& qtunrealanimatorwindow_build_actions_line_223_ea1e8557_native();
const NativeFunctionImplementation& qtunrealanimatorwindow_build_menu_line_253_388fe9fa_native();
const NativeFunctionImplementation& qtunrealanimatorwindow_build_statusbar_line_270_c1cec4ec_native();
const NativeFunctionImplementation& qtunrealanimatorwindow_build_central_line_273_434f64ce_native();
const NativeFunctionImplementation& qtunrealanimatorwindow_set_renderer_settings_line_311_abf213dc_native();
const NativeFunctionImplementation& qtunrealanimatorwindow_source_group_line_320_c11a51d3_native();
const NativeFunctionImplementation& qtunrealanimatorwindow_viewport_group_line_384_de334c2e_native();
const NativeFunctionImplementation& qtunrealanimatorwindow_single_viewport_group_line_403_836dd03b_native();
const NativeFunctionImplementation& qtunrealanimatorwindow_framebar_line_433_78cb782c_native();
const NativeFunctionImplementation& qtunrealanimatorwindow_target_group_line_458_47841ec2_native();
const NativeFunctionImplementation& qtunrealanimatorwindow_mapping_group_line_484_4edc1640_native();
const NativeFunctionImplementation& qtunrealanimatorwindow_set_navigation_profile_line_536_dcc4057f_native();
const NativeFunctionImplementation& qtunrealanimatorwindow_on_ue5_rig_export_completed_line_543_7c0c49d4_native();
const NativeFunctionImplementation& qtunrealanimatorwindow_set_supermodel_library_line_551_8069c02e_native();
const NativeFunctionImplementation& qtunrealanimatorwindow_set_source_model_line_559_5c0514f8_native();
const NativeFunctionImplementation& qtunrealanimatorwindow_prepare_source_supermodel_line_589_03672a1d_native();
const NativeFunctionImplementation& qtunrealanimatorwindow_clear_source_quinn_marks_line_597_0138472b_native();
const NativeFunctionImplementation& qtunrealanimatorwindow_remove_source_quinn_synthetic_bones_line_606_58bedd73_native();
const NativeFunctionImplementation& qtunrealanimatorwindow_ensure_source_quinn_bridge_bones_line_634_5ebc03dd_native();
const NativeFunctionImplementation& qtunrealanimatorwindow_insert_source_bridge_chain_line_736_d9c32019_native();
const NativeFunctionImplementation& qtunrealanimatorwindow_ensure_source_spine_g_line_788_4c8b2567_native();
const NativeFunctionImplementation& qtunrealanimatorwindow_set_target_asset_line_888_78784dda_native();
const NativeFunctionImplementation& qtunrealanimatorwindow_import_target_fbx_line_908_86bf5f48_native();
const NativeFunctionImplementation& qtunrealanimatorwindow_refresh_mapping_line_944_997ec38a_native();
const NativeFunctionImplementation& qtunrealanimatorwindow_target_bone_names_line_999_4b610ba6_native();
const NativeFunctionImplementation& qtunrealanimatorwindow_current_mapping_report_line_1011_cc0bca5e_native();
const NativeFunctionImplementation& qtunrealanimatorwindow_on_mapping_changed_line_1022_769cf6ee_native();
const NativeFunctionImplementation& qtunrealanimatorwindow_selected_animation_name_line_1032_5ab32f92_native();
const NativeFunctionImplementation& qtunrealanimatorwindow_selected_source_animation_line_1036_e8b4b43c_native();
const NativeFunctionImplementation& qtunrealanimatorwindow_force_gpu_for_animation_preview_line_1055_cb72f62f_native();
const NativeFunctionImplementation& qtunrealanimatorwindow_restore_gpu_after_animation_preview_line_1064_f77f491e_native();
const NativeFunctionImplementation& qtunrealanimatorwindow_on_animation_selection_changed_line_1069_6c50f2bf_native();
const NativeFunctionImplementation& qtunrealanimatorwindow_arm_selected_animation_preview_line_1079_491ef237_native();
const NativeFunctionImplementation& qtunrealanimatorwindow_set_framebars_enabled_line_1107_9ff870a3_native();
const NativeFunctionImplementation& qtunrealanimatorwindow_set_framebar_time_line_1113_08cd02a4_native();
const NativeFunctionImplementation& qtunrealanimatorwindow_update_playback_controls_line_1130_31f69d17_native();
const NativeFunctionImplementation& qtunrealanimatorwindow_preview_selected_animation_line_1148_ec865c23_native();
const NativeFunctionImplementation& qtunrealanimatorwindow_stop_preview_line_1166_670679c0_native();
const NativeFunctionImplementation& qtunrealanimatorwindow_scrub_preview_line_1179_593709c4_native();
const NativeFunctionImplementation& qtunrealanimatorwindow_apply_preview_pose_line_1188_7b35bab8_native();
const NativeFunctionImplementation& qtunrealanimatorwindow_tick_preview_line_1213_94b5a3f8_native();
const NativeFunctionImplementation& qtunrealanimatorwindow_bake_selected_animation_line_1246_84f46027_native();
const NativeFunctionImplementation& qtunrealanimatorwindow_export_fbx_animation_line_1271_c58b52be_native();
const NativeFunctionImplementation& qtunrealanimatorwindow_selected_source_row_line_1312_7a88e21a_native();
const NativeFunctionImplementation& qtunrealanimatorwindow_request_selected_source_line_1316_b26c54f9_native();
const NativeFunctionImplementation& qtunrealanimatorwindow_populate_source_library_line_1321_1a8d9378_native();
const NativeFunctionImplementation& qtunrealanimatorwindow_populate_source_bones_line_1340_17724219_native();
const NativeFunctionImplementation& qtunrealanimatorwindow_is_source_bone_node_line_1376_5822a87f_native();
const NativeFunctionImplementation& qtunrealanimatorwindow_is_potential_source_bone_node_line_1379_90087d3f_native();
const NativeFunctionImplementation& qtunrealanimatorwindow_on_source_bone_selected_line_1399_57b695ce_native();
const NativeFunctionImplementation& qtunrealanimatorwindow_selected_source_bone_node_line_1408_c12dbbbe_native();
const NativeFunctionImplementation& qtunrealanimatorwindow_update_source_synthetic_buttons_line_1414_93073ceb_native();
const NativeFunctionImplementation& qtunrealanimatorwindow_prompt_add_source_synthetic_bone_line_1425_fde12ab4_native();
const NativeFunctionImplementation& qtunrealanimatorwindow_prompt_insert_source_synthetic_bone_line_1438_4b3b45f1_native();
const NativeFunctionImplementation& qtunrealanimatorwindow_add_source_synthetic_bone_line_1452_7d40671f_native();
const NativeFunctionImplementation& qtunrealanimatorwindow_append_manual_synthetic_child_line_1485_aeb0df08_native();
const NativeFunctionImplementation& qtunrealanimatorwindow_insert_manual_synthetic_before_child_line_1503_cda590e6_native();
const NativeFunctionImplementation& qtunrealanimatorwindow_unique_source_bone_name_line_1519_75326972_native();
const NativeFunctionImplementation& qtunrealanimatorwindow_delete_selected_source_synthetic_bone_line_1529_cfe77848_native();
const NativeFunctionImplementation& qtunrealanimatorwindow_delete_source_synthetic_node_line_1542_932a16d7_native();
const NativeFunctionImplementation& qtunrealanimatorwindow_refresh_source_after_synthetic_edit_line_1565_fc73720b_native();
const NativeFunctionImplementation& qtunrealanimatorwindow_select_source_bone_node_line_1579_07daca51_native();
const NativeFunctionImplementation& qtunrealanimatorwindow_populate_target_bones_line_1588_c65b9669_native();
const NativeFunctionImplementation& qtunrealanimatorwindow_cycle_animator_gizmo_line_1611_296974e0_native();
const NativeFunctionImplementation& qtunrealanimatorwindow_on_target_bone_selected_line_1617_d9330f97_native();
const NativeFunctionImplementation& qtunrealanimatorwindow_source_label_text_line_1625_bb285c26_native();
const NativeFunctionImplementation& qtunrealanimatorwindow_source_label_tooltip_line_1635_533a10e2_native();

const NativeFunctionImplementation* instancemethods_native_functions(std::size_t& count);

} // namespace ghostrigger::windows::unrealanimatorwindow
