#pragma once

#include <cstddef>

namespace ghostrigger::phase15::ghostrigger_tools_sceneinformation {

using PythonFunctionDescriptorJson = const char* (*)();

struct PythonFunctionDescriptorEntry {
    const char* python_file;
    const char* qualname;
    const char* function_type;
    PythonFunctionDescriptorJson descriptor_json;
};

const char* src_core_scene_axis_mode_finite_basis_line_46_4c390260_descriptor_json();
const char* src_core_scene_axis_mode_normalize_line_56_203ee454_descriptor_json();
const char* src_core_scene_axis_mode_quat_to_basis_line_67_e86d6c6b_descriptor_json();
const char* src_core_scene_axis_mode_camera_basis_line_83_eed8416e_descriptor_json();
const char* src_core_scene_kmax_scene_utc_now_iso_line_17_b20f8872_descriptor_json();
const char* src_core_scene_lyt_room_graph_import_module_format_line_103_fb85bfec_descriptor_json();
const char* src_core_scene_lyt_room_graph_normalise_resref_line_110_52ae0b09_descriptor_json();
const char* src_core_scene_lyt_room_graph_module_from_input_line_114_a7371975_descriptor_json();
const char* src_core_scene_lyt_room_graph_lyt_from_input_line_118_b47cc422_descriptor_json();
const char* src_core_scene_lyt_room_graph_vis_from_input_line_125_b308cc05_descriptor_json();
const char* src_core_scene_lyt_room_graph_room_wok_index_line_132_960b1b62_descriptor_json();
const char* src_core_scene_lyt_room_graph_translation_matrix_line_140_0e8336ea_descriptor_json();
const char* src_core_scene_lyt_room_graph_position_from_room_line_150_7b816fe4_descriptor_json();
const char* src_core_scene_lyt_room_graph_position_from_hook_line_158_c0a228fb_descriptor_json();
const char* src_core_scene_lyt_room_graph_room_distance_line_166_0081867a_descriptor_json();
const char* src_core_scene_lyt_room_graph_nearest_room_line_173_2a37cff1_descriptor_json();
const char* src_core_scene_lyt_room_graph_visibility_dict_line_179_ab5822c8_descriptor_json();
const char* src_core_scene_lyt_room_graph_bounds_line_189_8abb30d8_descriptor_json();
const char* src_core_scene_lyt_room_graph_build_lyt_room_graph_line_198_f7165eba_descriptor_json();
const char* src_core_scene_lyt_room_graph_create_lyt_layout_line_340_97f1176d_descriptor_json();
const char* src_core_scene_lyt_room_graph_add_room_to_lyt_line_355_96f89336_descriptor_json();
const char* src_core_scene_lyt_room_graph_move_room_in_lyt_line_372_c47dfc7c_descriptor_json();
const char* src_core_scene_module_scene_import_resolve_module_room_placement_line_43_53a9fd5b_descriptor_json();
const char* src_core_scene_module_scene_import_resource_bytes_line_96_b2ad732d_descriptor_json();
const char* src_core_scene_scene_manager_dot3_line_42_627e4793_descriptor_json();
const char* src_core_scene_scene_manager_sub3_line_46_ac7929d6_descriptor_json();
const char* src_core_scene_scene_manager_add3_line_50_4fb43154_descriptor_json();
const char* src_core_scene_scene_manager_scale3_line_54_9f79e6e4_descriptor_json();
const char* src_core_scene_scene_manager_norm3_line_58_feb0e0e5_descriptor_json();
const char* src_core_scene_scene_manager_cross3_line_65_74e72371_descriptor_json();
const char* src_core_scene_scene_manager_get_character_registry_line_987_4ffb0beb_descriptor_json();
const char* src_core_scene_scene_manager_reset_character_registry_line_1000_086c29d4_descriptor_json();
const char* src_core_scene_scene_object_vec3_line_10_91771333_descriptor_json();
const char* src_core_scene_vis_editor_import_module_format_line_70_342f215b_descriptor_json();
const char* src_core_scene_vis_editor_import_lyt_room_graph_line_77_38726069_descriptor_json();
const char* src_core_scene_vis_editor_normalise_resref_line_84_dc8a039a_descriptor_json();
const char* src_core_scene_vis_editor_module_from_input_line_88_750e55c5_descriptor_json();
const char* src_core_scene_vis_editor_graph_from_input_line_92_1dba7cb7_descriptor_json();
const char* src_core_scene_vis_editor_vis_from_input_line_98_d0959548_descriptor_json();
const char* src_core_scene_vis_editor_ensure_vis_line_105_0f1cc986_descriptor_json();
const char* src_core_scene_vis_editor_room_ids_line_117_d85dfe1c_descriptor_json();
const char* src_core_scene_vis_editor_visibility_dict_line_121_236bec87_descriptor_json();
const char* src_core_scene_vis_editor_set_visibility_line_139_387137db_descriptor_json();
const char* src_core_scene_vis_editor_persist_state_visibility_line_143_48e1c539_descriptor_json();
const char* src_core_scene_vis_editor_connections_line_147_976fb1dc_descriptor_json();
const char* src_core_scene_vis_editor_build_vis_editor_state_line_161_5d5f689f_descriptor_json();
const char* src_core_scene_vis_editor_preview_visibility_line_212_cfd3a926_descriptor_json();
const char* src_core_scene_vis_editor_add_visibility_link_line_229_9d1091a2_descriptor_json();
const char* src_core_scene_vis_editor_remove_visibility_link_line_257_19987c9f_descriptor_json();
const char* src_core_scene_vis_editor_make_full_visibility_line_281_9e4b6966_descriptor_json();
const char* src_core_scene_vis_editor_create_vis_data_line_297_95615bb2_descriptor_json();

const PythonFunctionDescriptorEntry* modulefunctions_descriptors(std::size_t& count);

} // namespace ghostrigger::phase15::ghostrigger_tools_sceneinformation
