#pragma once

#include <cstddef>

namespace ghostrigger::phase15::ghostrigger_tools_sceneinformation {

using PythonFunctionDescriptorJson = const char* (*)();

struct PythonFunctionDescriptorEntry {
    const char* python_file;
    const char* qualname;
    const char* function_type;
    PythonFunctionDescriptorJson descriptor_json;
};

const char* src_core_scene_scene_manager_frustum_update_from_matrix_plane_line_139_e5dad599_descriptor_json();
const char* src_core_scene_scene_manager_frustum_update_from_camera_plane_through_pos_line_198_93dc44e6_descriptor_json();
const char* src_gui_panels_qt_inspector_panel_qtinspectorpanel_populate_preview_page_emit_attach_line_549_659529d3_descriptor_json();
const char* src_gui_panels_qt_inspector_panel_qtinspectorpanel_set_skeleton_template_options_field_line_1031_d2726e75_descriptor_json();
const char* src_gui_panels_qt_inspector_panel_qtinspectorpanel_populate_check_actor_page_emit_play_line_1199_a571dc67_descriptor_json();
const char* src_gui_panels_qt_inspector_panel_qtinspectorpanel_populate_motions_page_emit_library_play_line_1396_3ba0872d_descriptor_json();
const char* src_gui_panels_qt_inspector_panel_qtinspectorpanel_selected_fit_override_combo_value_line_2196_d1277435_descriptor_json();
const char* src_gui_panels_qt_inspector_panel_qtinspectorpanel_set_import_fit_report_fmt_error_line_2378_c31444bf_descriptor_json();
const char* src_gui_panels_qt_scene_outliner_panel_qtsceneoutlinerpanel_expanded_item_keys_walk_line_299_d41db2af_descriptor_json();
const char* src_gui_panels_qt_scene_outliner_panel_qtsceneoutlinerpanel_restore_expanded_item_keys_walk_line_314_2bc3db2d_descriptor_json();

const PythonFunctionDescriptorEntry* nestedfunctions_descriptors(std::size_t& count);

} // namespace ghostrigger::phase15::ghostrigger_tools_sceneinformation
