#pragma once

#include <cstddef>

namespace ghostrigger::core::rendering {

#ifndef GHOSTRIGGER_RENDERING_NATIVE_FUNCTION_IMPLEMENTATION_DEFINED
#define GHOSTRIGGER_RENDERING_NATIVE_FUNCTION_IMPLEMENTATION_DEFINED
struct NativeFunctionImplementation {
    const char* project;
    const char* native_namespace;
    const char* python_file;
    const char* qualname;
    const char* callable_type;
    const char* implementation_status;
    bool native_first;
    bool python_runtime_required;
    bool python_fallback_allowed;
    const char* contract_json;
};
#endif // GHOSTRIGGER_RENDERING_NATIVE_FUNCTION_IMPLEMENTATION_DEFINED

const NativeFunctionImplementation& paste_textured_triangle_tint_line_587_5193742e_native();
const NativeFunctionImplementation& renderergeometrymixin_lbs_vertex_bind_fallback_line_527_d2878eec_native();
const NativeFunctionImplementation& rendereroverlaymixin_draw_bones_is_bone_node_line_147_aa7a9b54_native();
const NativeFunctionImplementation& rendereroverlaymixin_draw_bones_nearest_bone_ancestor_line_172_934eb3bd_native();
const NativeFunctionImplementation& rendereroverlaymixin_draw_bones_draw_bone_segment_line_186_898ea37e_native();
const NativeFunctionImplementation& rendereroverlaymixin_draw_bones_bone_world_pos_line_220_e47613ba_native();
const NativeFunctionImplementation& rendereroverlaymixin_draw_bones_process_bone_node_line_234_6b881f0b_native();
const NativeFunctionImplementation& rendereroverlaymixin_draw_gimbal_rotated_ellipse_points_line_600_f373ac21_native();
const NativeFunctionImplementation& rendereroverlaymixin_draw_gimbal_draw_polyline_line_615_72d7a6a0_native();
const NativeFunctionImplementation& rendereroverlaymixin_draw_gimbal_draw_hatch_line_621_07987ada_native();
const NativeFunctionImplementation& rendereroverlaymixin_draw_character_fit_overlay_point_line_744_81c8a916_native();
const NativeFunctionImplementation& rendereroverlaymixin_draw_character_fit_overlay_axis_color_line_752_2684be83_native();
const NativeFunctionImplementation& rendereroverlaymixin_draw_character_fit_overlay_draw_group_line_762_2cdb9232_native();
const NativeFunctionImplementation& rendereroverlaymixin_draw_ext_skeleton_bp_line_828_91e1d42b_native();
const NativeFunctionImplementation& rendereroverlaymixin_draw_ext_skeleton_draw_ext_bone_line_832_a2494a89_native();
const NativeFunctionImplementation& rendereroverlaymixin_draw_axes_axis_end_line_988_7ac64d99_native();
const NativeFunctionImplementation& rendererrenderloopmixin_project_clipped_line_to_camera_line_333_51e07c49_native();
const NativeFunctionImplementation& rendererrenderloopmixin_project_clipped_line_to_screen_line_363_bc00ed77_native();
const NativeFunctionImplementation& texturecache_sample_bilinear_rgba_line_798_2d60ae01_native();
const NativeFunctionImplementation& texture_content_stats_sample_line_180_6862de25_native();
const NativeFunctionImplementation& skin_3g_candidate_records_norm_pos_line_1096_04f54701_native();
const NativeFunctionImplementation& skin_3g_candidate_records_delta_to_production_line_1109_482a84f4_native();
const NativeFunctionImplementation& compositemodel_construct_bb_line_204_ce6728e6_native();
const NativeFunctionImplementation& cached_world_position_resolver_world_transform_line_189_c0b42698_native();
const NativeFunctionImplementation& cached_world_position_resolver_world_position_line_217_44c528c3_native();

const NativeFunctionImplementation* nestedfunctions_native_functions(std::size_t& count);

} // namespace ghostrigger::core::rendering
