#pragma once

#include <cstddef>

namespace ghostrigger::adapters::rendering {

#ifndef GHOSTRIGGER_ADAPTERS_RENDERING_NATIVE_FUNCTION_IMPLEMENTATION_DEFINED
#define GHOSTRIGGER_ADAPTERS_RENDERING_NATIVE_FUNCTION_IMPLEMENTATION_DEFINED
struct NativeFunctionImplementation {
    const char* project;
    const char* native_namespace;
    const char* python_file;
    const char* qualname;
    const char* callable_type;
    const char* implementation_status;
    bool native_first;
    bool python_runtime_required;
    bool python_fallback_allowed;
    const char* contract_json;
};
#endif // GHOSTRIGGER_ADAPTERS_RENDERING_NATIVE_FUNCTION_IMPLEMENTATION_DEFINED

const NativeFunctionImplementation& getattr_line_139_8e4ea95a_native();
const NativeFunctionImplementation& dir_line_148_2084c3bf_native();
const NativeFunctionImplementation& getattr_line_94_76a1a6a9_native();
const NativeFunctionImplementation& dir_line_104_98f7a527_native();
const NativeFunctionImplementation& vbo_builder_line_20_92b405a6_native();
const NativeFunctionImplementation& iter_mesh_render_data_line_28_ef5528d1_native();
const NativeFunctionImplementation& extract_node_arrays_line_33_a10d76a2_native();
const NativeFunctionImplementation& getattr_line_38_e5b7d284_native();
const NativeFunctionImplementation& dir_line_46_405f5132_native();
const NativeFunctionImplementation& benchmark_line_14_c611fb3e_native();
const NativeFunctionImplementation& main_line_13_27f93f97_native();
const NativeFunctionImplementation& moderngl_runtime_available_line_24_aa071366_native();
const NativeFunctionImplementation& clear_prebuilt_static_gpu_mesh_data_line_209_484b9fb7_native();
const NativeFunctionImplementation& clear_prebuilt_static_gpu_model_data_line_232_f767db21_native();
const NativeFunctionImplementation& prebuilt_static_gpu_mesh_data_line_256_193fad4b_native();
const NativeFunctionImplementation& prebuild_static_gpu_mesh_data_line_273_28f9e2c6_native();
const NativeFunctionImplementation& build_vbo_data_line_345_6f99b251_native();
const NativeFunctionImplementation& render_model_autoframe_line_20_fa38dc9f_native();
const NativeFunctionImplementation& repo_root_line_664_6b579e67_native();
const NativeFunctionImplementation& candidate_paths_line_668_f7698985_native();
const NativeFunctionImplementation& decode_json_line_681_c57c56f2_native();
const NativeFunctionImplementation& cpu_skinning_fallback_batch_item_to_dict_line_2301_c912dd2d_native();
const NativeFunctionImplementation& gpu_skinning_dispatch_item_to_dict_line_2317_1641aa65_native();
const NativeFunctionImplementation& resource_upload_item_to_dict_line_2330_e0df7076_native();
const NativeFunctionImplementation& device_resource_item_to_dict_line_2343_e563a16f_native();
const NativeFunctionImplementation& device_resource_upload_commit_item_to_dict_line_2357_3561c33e_native();
const NativeFunctionImplementation& device_resource_transition_item_to_dict_line_2367_2441bd93_native();
const NativeFunctionImplementation& draw_item_to_dict_line_2379_c431326f_native();
const NativeFunctionImplementation& draw_batch_to_dict_line_2391_5c57f3e4_native();
const NativeFunctionImplementation& vec3_line_2402_56084119_native();
const NativeFunctionImplementation& vec4_line_2409_62260cb6_native();
const NativeFunctionImplementation& flatten_matrices_line_2416_35af63bb_native();
const NativeFunctionImplementation& flatten_transform_matrix_line_2438_9cea9dfc_native();
const NativeFunctionImplementation& flatten_positions_line_2457_0bcbec57_native();
const NativeFunctionImplementation& flatten_indices_line_2480_ecd95aee_native();
const NativeFunctionImplementation& flatten_skin_indices_line_2493_911ca48c_native();
const NativeFunctionImplementation& flatten_skin_weights_line_2498_78ccf10b_native();
const NativeFunctionImplementation& flatten_matrix_like_line_2503_f898edc6_native();
const NativeFunctionImplementation& flatten_numeric_line_2526_8e5122e0_native();
const NativeFunctionImplementation& texture_bytes_line_2539_6cf97f46_native();
const NativeFunctionImplementation& safe_len_line_875_2b260a11_native();
const NativeFunctionImplementation& material_slot_line_886_8b4e8754_native();
const NativeFunctionImplementation& mesh_flags_line_894_b4ae071b_native();
const NativeFunctionImplementation& material_color_line_906_28e11dac_native();
const NativeFunctionImplementation& mesh_bounds_line_923_45af63f7_native();
const NativeFunctionImplementation& frame_flags_line_960_3d801e42_native();
const NativeFunctionImplementation& pick_ray_from_request_line_973_841d79ad_native();
const NativeFunctionImplementation& vec3_line_986_da54c03f_native();
const NativeFunctionImplementation& texture_key_line_993_1fc5daf0_native();
const NativeFunctionImplementation& texture_size_line_1001_0591e482_native();
const NativeFunctionImplementation& texture_byte_size_line_1015_f6e27853_native();
const NativeFunctionImplementation& texture_format_line_1032_b2b58131_native();
const NativeFunctionImplementation& texture_flags_line_1040_8f25e810_native();
const NativeFunctionImplementation& texture_payload_line_1049_e8478aed_native();
const NativeFunctionImplementation& texture_row_pitch_line_1068_087037f2_native();
const NativeFunctionImplementation& stable_clip_hash_line_1078_2e4c8ef1_native();
const NativeFunctionImplementation& gpu_runtime_imported_line_26_47280230_native();
const NativeFunctionImplementation& prepare_pygfx_wgpu_environment_line_32_ef7d19d9_native();
const NativeFunctionImplementation& renderer_for_backend_line_26_97b0c440_native();
const NativeFunctionImplementation& dedupe_line_39_889a5836_native();
const NativeFunctionImplementation& render_kwargs_for_line_47_c3c86eb3_native();
const NativeFunctionImplementation& fallback_order_line_63_da1d0371_native();
const NativeFunctionImplementation& renderer_capabilities_snapshot_line_93_70d11e0e_native();
const NativeFunctionImplementation& create_viewport_renderer_line_353_9176ad1d_native();
const NativeFunctionImplementation& probe_script_line_73_458ebad6_native();
const NativeFunctionImplementation& getattr_line_35_3a809ba4_native();
const NativeFunctionImplementation& dir_line_45_972c5fdd_native();

const NativeFunctionImplementation* modulefunctions_native_functions(std::size_t& count);

} // namespace ghostrigger::adapters::rendering
