#pragma once

#include <cstddef>

namespace ghostrigger::phase15::ghostrigger_adapters_rendering {

using PythonFunctionDescriptorJson = const char* (*)();

struct PythonFunctionDescriptorEntry {
    const char* python_file;
    const char* qualname;
    const char* function_type;
    PythonFunctionDescriptorJson descriptor_json;
};

const char* src_adapters_rendering_gpu_diagnostics_exports_getattr_line_139_8e4ea95a_descriptor_json();
const char* src_adapters_rendering_gpu_diagnostics_exports_dir_line_148_2084c3bf_descriptor_json();
const char* src_adapters_rendering_gpu_renderer_exports_getattr_line_94_76a1a6a9_descriptor_json();
const char* src_adapters_rendering_gpu_renderer_exports_dir_line_104_98f7a527_descriptor_json();
const char* src_adapters_rendering_mesh_render_data_vbo_builder_line_20_92b405a6_descriptor_json();
const char* src_adapters_rendering_mesh_render_data_iter_mesh_render_data_line_28_ef5528d1_descriptor_json();
const char* src_adapters_rendering_mesh_render_data_extract_node_arrays_line_33_a10d76a2_descriptor_json();
const char* src_adapters_rendering_mesh_render_data_getattr_line_38_e5b7d284_descriptor_json();
const char* src_adapters_rendering_mesh_render_data_dir_line_46_405f5132_descriptor_json();
const char* src_adapters_rendering_moderngl_benchmark_benchmark_line_14_c611fb3e_descriptor_json();
const char* src_adapters_rendering_moderngl_cli_main_line_13_27f93f97_descriptor_json();
const char* src_adapters_rendering_moderngl_legacy_bridge_moderngl_runtime_available_line_24_aa071366_descriptor_json();
const char* src_adapters_rendering_moderngl_resources_clear_prebuilt_static_gpu_mesh_data_line_209_484b9fb7_descriptor_json();
const char* src_adapters_rendering_moderngl_resources_clear_prebuilt_static_gpu_model_data_line_232_f767db21_descriptor_json();
const char* src_adapters_rendering_moderngl_resources_prebuilt_static_gpu_mesh_data_line_256_193fad4b_descriptor_json();
const char* src_adapters_rendering_moderngl_resources_prebuild_static_gpu_mesh_data_line_273_28f9e2c6_descriptor_json();
const char* src_adapters_rendering_moderngl_resources_build_vbo_data_line_345_6f99b251_descriptor_json();
const char* src_adapters_rendering_moderngl_scene_helpers_render_model_autoframe_line_20_fa38dc9f_descriptor_json();
const char* src_adapters_rendering_native_core_binding_repo_root_line_664_6b579e67_descriptor_json();
const char* src_adapters_rendering_native_core_binding_candidate_paths_line_668_f7698985_descriptor_json();
const char* src_adapters_rendering_native_core_binding_decode_json_line_681_c57c56f2_descriptor_json();
const char* src_adapters_rendering_native_core_binding_cpu_skinning_fallback_batch_item_to_dict_line_2301_c912dd2d_descriptor_json();
const char* src_adapters_rendering_native_core_binding_gpu_skinning_dispatch_item_to_dict_line_2317_1641aa65_descriptor_json();
const char* src_adapters_rendering_native_core_binding_resource_upload_item_to_dict_line_2330_e0df7076_descriptor_json();
const char* src_adapters_rendering_native_core_binding_device_resource_item_to_dict_line_2343_e563a16f_descriptor_json();
const char* src_adapters_rendering_native_core_binding_device_resource_upload_commit_item_to_dict_line_2357_3561c33e_descriptor_json();
const char* src_adapters_rendering_native_core_binding_device_resource_transition_item_to_dict_line_2367_2441bd93_descriptor_json();
const char* src_adapters_rendering_native_core_binding_draw_item_to_dict_line_2379_c431326f_descriptor_json();
const char* src_adapters_rendering_native_core_binding_draw_batch_to_dict_line_2391_5c57f3e4_descriptor_json();
const char* src_adapters_rendering_native_core_binding_vec3_line_2402_56084119_descriptor_json();
const char* src_adapters_rendering_native_core_binding_vec4_line_2409_62260cb6_descriptor_json();
const char* src_adapters_rendering_native_core_binding_flatten_matrices_line_2416_35af63bb_descriptor_json();
const char* src_adapters_rendering_native_core_binding_flatten_transform_matrix_line_2438_9cea9dfc_descriptor_json();
const char* src_adapters_rendering_native_core_binding_flatten_positions_line_2457_0bcbec57_descriptor_json();
const char* src_adapters_rendering_native_core_binding_flatten_indices_line_2480_ecd95aee_descriptor_json();
const char* src_adapters_rendering_native_core_binding_flatten_skin_indices_line_2493_911ca48c_descriptor_json();
const char* src_adapters_rendering_native_core_binding_flatten_skin_weights_line_2498_78ccf10b_descriptor_json();
const char* src_adapters_rendering_native_core_binding_flatten_matrix_like_line_2503_f898edc6_descriptor_json();
const char* src_adapters_rendering_native_core_binding_flatten_numeric_line_2526_8e5122e0_descriptor_json();
const char* src_adapters_rendering_native_core_binding_texture_bytes_line_2539_6cf97f46_descriptor_json();
const char* src_adapters_rendering_native_core_renderer_safe_len_line_875_2b260a11_descriptor_json();
const char* src_adapters_rendering_native_core_renderer_material_slot_line_886_8b4e8754_descriptor_json();
const char* src_adapters_rendering_native_core_renderer_mesh_flags_line_894_b4ae071b_descriptor_json();
const char* src_adapters_rendering_native_core_renderer_material_color_line_906_28e11dac_descriptor_json();
const char* src_adapters_rendering_native_core_renderer_mesh_bounds_line_923_45af63f7_descriptor_json();
const char* src_adapters_rendering_native_core_renderer_frame_flags_line_960_3d801e42_descriptor_json();
const char* src_adapters_rendering_native_core_renderer_pick_ray_from_request_line_973_841d79ad_descriptor_json();
const char* src_adapters_rendering_native_core_renderer_vec3_line_986_da54c03f_descriptor_json();
const char* src_adapters_rendering_native_core_renderer_texture_key_line_993_1fc5daf0_descriptor_json();
const char* src_adapters_rendering_native_core_renderer_texture_size_line_1001_0591e482_descriptor_json();
const char* src_adapters_rendering_native_core_renderer_texture_byte_size_line_1015_f6e27853_descriptor_json();
const char* src_adapters_rendering_native_core_renderer_texture_format_line_1032_b2b58131_descriptor_json();
const char* src_adapters_rendering_native_core_renderer_texture_flags_line_1040_8f25e810_descriptor_json();
const char* src_adapters_rendering_native_core_renderer_texture_payload_line_1049_e8478aed_descriptor_json();
const char* src_adapters_rendering_native_core_renderer_texture_row_pitch_line_1068_087037f2_descriptor_json();
const char* src_adapters_rendering_native_core_renderer_stable_clip_hash_line_1078_2e4c8ef1_descriptor_json();
const char* src_adapters_rendering_pygfx_core_backend_env_gpu_runtime_imported_line_26_47280230_descriptor_json();
const char* src_adapters_rendering_pygfx_core_backend_env_prepare_pygfx_wgpu_environment_line_32_ef7d19d9_descriptor_json();
const char* src_adapters_rendering_renderer_factory_renderer_for_backend_line_26_97b0c440_descriptor_json();
const char* src_adapters_rendering_renderer_factory_dedupe_line_39_889a5836_descriptor_json();
const char* src_adapters_rendering_renderer_factory_render_kwargs_for_line_47_c3c86eb3_descriptor_json();
const char* src_adapters_rendering_renderer_factory_fallback_order_line_63_da1d0371_descriptor_json();
const char* src_adapters_rendering_renderer_factory_renderer_capabilities_snapshot_line_93_70d11e0e_descriptor_json();
const char* src_adapters_rendering_renderer_factory_create_viewport_renderer_line_353_9176ad1d_descriptor_json();
const char* src_adapters_rendering_wgpu_core_shared_probe_script_line_73_458ebad6_descriptor_json();
const char* src_adapters_rendering_wgpu_renderer_exports_getattr_line_35_3a809ba4_descriptor_json();
const char* src_adapters_rendering_wgpu_renderer_exports_dir_line_45_972c5fdd_descriptor_json();

const PythonFunctionDescriptorEntry* modulefunctions_descriptors(std::size_t& count);

} // namespace ghostrigger::phase15::ghostrigger_adapters_rendering
