#pragma once

#include <cstddef>

namespace ghostrigger::phase15::ghostrigger_adapters_rendering {

using PythonFunctionDescriptorJson = const char* (*)();

struct PythonFunctionDescriptorEntry {
    const char* python_file;
    const char* qualname;
    const char* function_type;
    PythonFunctionDescriptorJson descriptor_json;
};

const char* src_adapters_rendering_moderngl_renderer_impl_gpurenderer_reset_framebuffers_release_fbo_line_504_5019d095_descriptor_json();
const char* src_adapters_rendering_moderngl_renderer_impl_gpurenderer_draw_light_gizmos_add_line_line_637_feb19052_descriptor_json();
const char* src_adapters_rendering_moderngl_renderer_impl_gpurenderer_draw_light_gizmos_v_add_line_641_e59255a2_descriptor_json();
const char* src_adapters_rendering_moderngl_renderer_impl_gpurenderer_draw_light_gizmos_v_sub_line_642_47e39020_descriptor_json();
const char* src_adapters_rendering_moderngl_renderer_impl_gpurenderer_draw_light_gizmos_v_mul_line_643_28d82d5e_descriptor_json();
const char* src_adapters_rendering_moderngl_renderer_impl_gpurenderer_draw_light_gizmos_v_cross_line_644_062a2ffe_descriptor_json();
const char* src_adapters_rendering_moderngl_renderer_impl_gpurenderer_draw_light_gizmos_v_norm_line_648_022e6be3_descriptor_json();
const char* src_adapters_rendering_moderngl_renderer_impl_gpurenderer_draw_light_gizmos_basis_line_652_1b2b657d_descriptor_json();
const char* src_adapters_rendering_moderngl_renderer_impl_gpurenderer_draw_light_gizmos_ring_line_659_bc45f374_descriptor_json();
const char* src_adapters_rendering_moderngl_renderer_impl_gpurenderer_render_gpu_bas_attachment_root_for_node_line_1275_bb05e7ac_descriptor_json();
const char* src_adapters_rendering_moderngl_renderer_impl_gpurenderer_render_gpu_bas_attachment_socket_node_line_1285_92df5627_descriptor_json();
const char* src_adapters_rendering_moderngl_renderer_impl_gpurenderer_render_gpu_get_world_transform_line_1307_e9a27667_descriptor_json();
const char* src_adapters_rendering_moderngl_renderer_impl_gpurenderer_render_gpu_is_deform_helper_line_1491_5fbfa3f7_descriptor_json();
const char* src_adapters_rendering_moderngl_renderer_impl_gpurenderer_render_gpu_classify_node_line_1555_6979f6a4_descriptor_json();
const char* src_adapters_rendering_moderngl_renderer_impl_gpurenderer_render_gpu_draw_node_line_1668_31be6fd4_descriptor_json();
const char* src_adapters_rendering_moderngl_renderer_impl_gpurenderer_render_gpu_draw_node_multitex_line_2410_148a3c53_descriptor_json();
const char* src_adapters_rendering_moderngl_renderer_impl_gpurenderer_render_gpu_node_sort_depth_line_2463_88d9337c_descriptor_json();
const char* src_adapters_rendering_moderngl_scene_helpers_render_model_autoframe_axis_dist_line_72_357dc1a8_descriptor_json();
const char* src_adapters_rendering_pygfx_core_mesh_cache_pygfxmeshcache_build_geometric_boundary_edges_key_line_966_9d6153f3_descriptor_json();
const char* src_adapters_rendering_wgpu_core_renderer_wgpurenderer_create_gizmo_line_pipeline_create_pipeline_line_1086_a828ac49_descriptor_json();
const char* src_adapters_rendering_wgpu_core_renderer_wgpurenderer_draw_meshes_build_queue_line_1324_4c33a38f_descriptor_json();
const char* src_adapters_rendering_wgpu_core_renderer_wgpurenderer_draw_meshes_draw_pass_line_1420_012d61e7_descriptor_json();
const char* src_adapters_rendering_wgpu_core_renderer_wgpurenderer_mesh_model_matrix_stored_world_matrix_line_1576_96b0e67d_descriptor_json();
const char* src_adapters_rendering_wgpu_core_renderer_wgpurenderer_ensure_light_resource_score_line_1774_8290fbca_descriptor_json();
const char* src_adapters_rendering_wgpu_core_renderer_wgpurenderer_draw_light_overlays_draw_batches_line_1913_228e0eb1_descriptor_json();
const char* src_adapters_rendering_wgpu_core_renderer_wgpurenderer_draw_skeleton_overlay_draw_buffer_line_2042_17a991c9_descriptor_json();
const char* src_adapters_rendering_wgpu_core_renderer_wgpurenderer_get_or_upload_skeleton_resource_make_buffer_line_2092_22813374_descriptor_json();
const char* src_adapters_rendering_wgpu_core_resources_wgpuresourcecache_build_geometric_boundary_edges_key_line_275_e4f6976e_descriptor_json();

const PythonFunctionDescriptorEntry* nestedfunctions_descriptors(std::size_t& count);

} // namespace ghostrigger::phase15::ghostrigger_adapters_rendering
