#pragma once

#include <cstddef>

namespace ghostrigger::phase15::ghostrigger_adapters_rendering {

using PythonFunctionDescriptorJson = const char* (*)();

struct PythonFunctionDescriptorEntry {
    const char* python_file;
    const char* qualname;
    const char* function_type;
    PythonFunctionDescriptorJson descriptor_json;
};

const char* src_adapters_rendering_moderngl_renderer_impl_gpurenderer_rgb_float_line_268_e7b708a6_descriptor_json();
const char* src_adapters_rendering_moderngl_renderer_impl_gpurenderer_blend_rgb_line_272_744c4811_descriptor_json();
const char* src_adapters_rendering_moderngl_renderer_impl_gpurenderer_relative_luma_line_277_03566a15_descriptor_json();
const char* src_adapters_rendering_moderngl_renderer_impl_gpurenderer_light_kind_int_line_764_973329e8_descriptor_json();
const char* src_adapters_rendering_moderngl_renderer_impl_gpurenderer_rotate_vec_by_quat_line_776_71b2a311_descriptor_json();
const char* src_adapters_rendering_moderngl_renderer_impl_gpurenderer_sprite_text_line_2635_4ff16203_descriptor_json();
const char* src_adapters_rendering_moderngl_renderer_impl_gpurenderer_has_sprite_material_override_line_2641_2bdcd1ae_descriptor_json();
const char* src_adapters_rendering_pygfx_core_mesh_cache_pygfxmeshcache_view_style_key_line_73_7d5864ce_descriptor_json();
const char* src_adapters_rendering_pygfx_core_mesh_cache_pygfxmeshcache_can_update_dynamic_skin_buffers_line_295_455a3519_descriptor_json();
const char* src_adapters_rendering_pygfx_core_mesh_cache_pygfxmeshcache_mesh_indices_line_499_a8d77474_descriptor_json();
const char* src_adapters_rendering_pygfx_core_mesh_cache_pygfxmeshcache_pygfx_uvs_line_524_0ab18777_descriptor_json();
const char* src_adapters_rendering_pygfx_core_mesh_cache_pygfxmeshcache_selection_color_line_611_82a53301_descriptor_json();
const char* src_adapters_rendering_pygfx_core_mesh_cache_pygfxmeshcache_sprite_proxy_color_line_744_308da1c3_descriptor_json();
const char* src_adapters_rendering_pygfx_core_mesh_cache_pygfxmeshcache_use_skinned_wire_overlay_line_832_529bcbfc_descriptor_json();
const char* src_adapters_rendering_pygfx_core_mesh_cache_pygfxmeshcache_copy_local_transform_line_911_d051e563_descriptor_json();
const char* src_adapters_rendering_pygfx_core_mesh_cache_pygfxmeshcache_uses_sprite_wire_hull_line_922_5f57c073_descriptor_json();
const char* src_adapters_rendering_pygfx_core_mesh_cache_pygfxmeshcache_build_geometric_boundary_edges_line_960_df42799a_descriptor_json();
const char* src_adapters_rendering_pygfx_core_mesh_cache_pygfxmeshcache_source_visible_line_996_1beca7d8_descriptor_json();
const char* src_adapters_rendering_pygfx_core_mesh_cache_pygfxmeshcache_set_material_color_line_1000_3972cc11_descriptor_json();
const char* src_adapters_rendering_pygfx_core_mesh_cache_pygfxmeshcache_set_material_attr_line_1007_60785737_descriptor_json();
const char* src_adapters_rendering_pygfx_core_renderer_pygfxviewportrenderer_optional_module_line_83_b11e8b32_descriptor_json();
const char* src_adapters_rendering_pygfx_core_renderer_pygfxviewportrenderer_theme_color_line_510_2da2905f_descriptor_json();
const char* src_adapters_rendering_pygfx_core_renderer_pygfxviewportrenderer_set_object_color_line_534_b1d0cd8c_descriptor_json();
const char* src_adapters_rendering_pygfx_core_scene_bridge_pygfxscenebridge_vec3_line_534_e3f96754_descriptor_json();
const char* src_adapters_rendering_pygfx_core_scene_bridge_pygfxscenebridge_mesh_model_matrix_line_561_fad4b7d4_descriptor_json();
const char* src_adapters_rendering_wgpu_core_renderer_wgpurenderer_probe_availability_line_290_ec0f0532_descriptor_json();
const char* src_adapters_rendering_wgpu_core_renderer_wgpurenderer_capabilities_unavailable_line_423_e33a189d_descriptor_json();
const char* src_adapters_rendering_wgpu_core_renderer_wgpurenderer_lighting_mode_id_line_1854_7cbdc5b5_descriptor_json();
const char* src_adapters_rendering_wgpu_core_renderer_wgpurenderer_shader_complexity_id_line_1870_a358f0ee_descriptor_json();
const char* src_adapters_rendering_wgpu_core_renderer_wgpurenderer_line_vertices_from_gizmo_command_line_2119_64e1ea82_descriptor_json();
const char* src_adapters_rendering_wgpu_core_renderer_wgpurenderer_gizmo_command_cache_key_line_2132_f1ff6749_descriptor_json();
const char* src_adapters_rendering_wgpu_core_renderer_wgpurenderer_pick_id_to_color_line_2543_a952e8de_descriptor_json();
const char* src_adapters_rendering_wgpu_core_renderer_wgpurenderer_pick_id_from_rgba_line_2553_5942dfd3_descriptor_json();
const char* src_adapters_rendering_wgpu_core_renderer_wgpurenderer_mesh_sort_depth_from_center_line_2587_8f5601b7_descriptor_json();
const char* src_adapters_rendering_wgpu_core_renderer_wgpurenderer_scene_has_rigid_animation_meshes_line_2626_5d6cd13d_descriptor_json();
const char* src_adapters_rendering_wgpu_core_resources_wgpuresourcecache_uses_sprite_wire_hull_line_227_93a1c032_descriptor_json();
const char* src_adapters_rendering_wgpu_core_resources_wgpuresourcecache_build_geometric_boundary_edges_line_267_05339e70_descriptor_json();
const char* src_adapters_rendering_wgpu_core_resources_wgpuresourcecache_rgba8_mip_chain_line_555_9ee8d314_descriptor_json();
const char* src_adapters_rendering_wgpu_core_resources_wgpuresourcecache_texture_format_line_588_bf2090f3_descriptor_json();

const PythonFunctionDescriptorEntry* staticmethods_descriptors(std::size_t& count);

} // namespace ghostrigger::phase15::ghostrigger_adapters_rendering
