"""Headless authored module metadata compiler for Map Studio.

This module owns the Map Studio policy for turning editable module/area
metadata into ARE and IFO resources.  It stays Qt-free so the future metadata
inspector can call the same compiler used by smoke exports.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any

from .authored_module_objects import ModuleEntryPoint, apply_entry_point_to_ifo
from .authored_module_project import AuthoredModuleMetadata, authored_resref_blocking_issue, normalise_resref


RGB = tuple[int, int, int]


@dataclass(frozen=True)
class AuthoredAreaMetadata:
    """Editable ARE metadata for an authored module area."""

    name: str = ""
    tag: str = ""
    comments: str = "Generated by GhostRigger Map Studio."
    unescapable: bool = False
    disable_transit: bool = False
    natural: bool = True
    player_vs_player: bool = False
    no_rest: bool = False
    sun_ambient: RGB = (64, 64, 64)
    sun_diffuse: RGB = (255, 255, 255)
    fog_color: RGB = (0, 0, 0)
    fog_near: float = 100.0
    fog_far: float = 200.0
    sun_fog_on: bool = False
    metadata: dict[str, Any] = field(default_factory=dict)


@dataclass(frozen=True)
class AuthoredModuleTimeMetadata:
    """Editable IFO time/progression metadata."""

    dawn_hour: int = 6
    dusk_hour: int = 18
    minutes_per_hour: int = 2
    expansion_pack: int = 0


@dataclass(frozen=True)
class AuthoredModuleMetadataValidation:
    ok: bool
    warnings: tuple[str, ...] = ()
    blocking_issues: tuple[str, ...] = ()


@dataclass(frozen=True)
class CompiledAuthoredModuleMetadata:
    """Serialized ARE/IFO output plus validation/provenance."""

    are_bytes: bytes
    ifo_bytes: bytes
    validation: AuthoredModuleMetadataValidation
    metadata: dict[str, Any] = field(default_factory=dict)


def _new_gff(content_name: str) -> Any:
    from pykotor.resource.formats.gff import GFF
    from pykotor.resource.formats.gff.gff_data import GFFContent

    return GFF(getattr(GFFContent, content_name))


def _bytes_gff(gff: Any) -> bytes:
    from pykotor.resource.formats.gff import bytes_gff

    return bytes_gff(gff)


def _locstring(text: str) -> Any:
    from pykotor.common.language import LocalizedString

    return LocalizedString.from_english(text)


def _set_loc(root: Any, label: str, text: str) -> None:
    try:
        root.set_locstring(label, _locstring(text))
    except Exception:
        root.set_string(label, text)


def _rgb(value: RGB) -> int:
    red = max(0, min(255, int(value[0])))
    green = max(0, min(255, int(value[1])))
    blue = max(0, min(255, int(value[2])))
    return (red << 16) | (green << 8) | blue


def _byte(value: bool) -> int:
    return 1 if bool(value) else 0


def validate_authored_module_metadata(
    module: AuthoredModuleMetadata,
    entry_point: ModuleEntryPoint,
    area: AuthoredAreaMetadata | None = None,
    time: AuthoredModuleTimeMetadata | None = None,
) -> AuthoredModuleMetadataValidation:
    """Validate ARE/IFO metadata before serialization."""

    area = area or AuthoredAreaMetadata()
    time = time or AuthoredModuleTimeMetadata()
    warnings: list[str] = []
    blocking: list[str] = []
    module_root = module.normalised_root()
    module_issue = authored_resref_blocking_issue("Authored module metadata", module.module_root)
    if module_issue:
        blocking.append(module_issue)
    entry_area = normalise_resref(entry_point.area_resref)
    entry_issue = authored_resref_blocking_issue("Module entry area", entry_point.area_resref)
    if entry_issue:
        blocking.append(entry_issue)
    if entry_area and module_root and entry_area != module_root:
        blocking.append(f"Module entry area {entry_area} does not match module resref {module_root}.")
    if not str(module.display_name or area.name or "").strip():
        warnings.append("Module has no display name; in-game UI may show a blank area name.")
    if float(area.fog_far) < float(area.fog_near):
        blocking.append("Fog far distance must be greater than or equal to fog near distance.")
    if not (0 <= int(time.dawn_hour) <= 23):
        blocking.append("Dawn hour must be between 0 and 23.")
    if not (0 <= int(time.dusk_hour) <= 23):
        blocking.append("Dusk hour must be between 0 and 23.")
    if int(time.minutes_per_hour) <= 0:
        blocking.append("Minutes per hour must be positive.")
    return AuthoredModuleMetadataValidation(
        ok=not blocking,
        warnings=tuple(warnings),
        blocking_issues=tuple(blocking),
    )


def build_authored_are_gff(module: AuthoredModuleMetadata, area: AuthoredAreaMetadata | None = None) -> Any:
    """Build an ARE GFF from authored area metadata."""

    area = area or AuthoredAreaMetadata()
    root_resref = module.normalised_root()
    display_name = str(area.name or module.display_name or root_resref)
    tag = normalise_resref(area.tag or module.tag or root_resref)
    gff = _new_gff("ARE")
    root = gff.root
    _set_loc(root, "Name", display_name)
    root.set_string("Tag", tag)
    root.set_string("Comments", area.comments)
    root.set_uint8("Unescapable", _byte(area.unescapable))
    root.set_uint8("DisableTransit", _byte(area.disable_transit))
    root.set_uint8("Natural", _byte(area.natural))
    root.set_uint8("PlayerVsPlayer", _byte(area.player_vs_player))
    root.set_uint8("NoRest", _byte(area.no_rest))
    root.set_uint32("SunAmbientColor", _rgb(area.sun_ambient))
    root.set_uint32("SunDiffuseColor", _rgb(area.sun_diffuse))
    root.set_uint32("FogColor", _rgb(area.fog_color))
    root.set_single("FogNearDist", float(area.fog_near))
    root.set_single("FogFarDist", float(area.fog_far))
    root.set_uint8("SunFog", _byte(area.sun_fog_on))
    return gff


def build_authored_ifo_gff(
    module: AuthoredModuleMetadata,
    entry_point: ModuleEntryPoint,
    time: AuthoredModuleTimeMetadata | None = None,
) -> Any:
    """Build an IFO GFF from authored module metadata and entry point."""

    time = time or AuthoredModuleTimeMetadata()
    root_resref = module.normalised_root()
    display_name = str(module.display_name or root_resref)
    tag = normalise_resref(module.tag or root_resref)
    gff = _new_gff("IFO")
    root = gff.root
    _set_loc(root, "Mod_Name", display_name)
    root.set_string("Mod_Tag", tag)
    apply_entry_point_to_ifo(root, entry_point)
    root.set_uint8("Mod_DawnHour", int(time.dawn_hour))
    root.set_uint8("Mod_DuskHour", int(time.dusk_hour))
    root.set_uint8("Mod_MinPerHour", int(time.minutes_per_hour))
    root.set_uint32("Expansion_Pack", int(time.expansion_pack))
    return gff


def build_authored_are_bytes(module: AuthoredModuleMetadata, area: AuthoredAreaMetadata | None = None) -> bytes:
    return _bytes_gff(build_authored_are_gff(module, area))


def build_authored_ifo_bytes(
    module: AuthoredModuleMetadata,
    entry_point: ModuleEntryPoint,
    time: AuthoredModuleTimeMetadata | None = None,
) -> bytes:
    return _bytes_gff(build_authored_ifo_gff(module, entry_point, time))


def compile_authored_module_metadata(
    module: AuthoredModuleMetadata,
    entry_point: ModuleEntryPoint,
    *,
    area: AuthoredAreaMetadata | None = None,
    time: AuthoredModuleTimeMetadata | None = None,
) -> CompiledAuthoredModuleMetadata:
    """Compile authored metadata into serialized ARE/IFO bytes."""

    validation = validate_authored_module_metadata(module, entry_point, area, time)
    if not validation.ok:
        raise ValueError("; ".join(validation.blocking_issues))
    area = area or AuthoredAreaMetadata()
    time = time or AuthoredModuleTimeMetadata()
    return CompiledAuthoredModuleMetadata(
        are_bytes=build_authored_are_bytes(module, area),
        ifo_bytes=build_authored_ifo_bytes(module, entry_point, time),
        validation=validation,
        metadata={
            "source": "src.core.modules.authored_module_metadata",
            "module_root": module.normalised_root(),
            "display_name": module.display_name,
            "tag": normalise_resref(module.tag or module.module_root),
            "fog_near": float(area.fog_near),
            "fog_far": float(area.fog_far),
            "dawn_hour": int(time.dawn_hour),
            "dusk_hour": int(time.dusk_hour),
        },
    )


__all__ = [
    "AuthoredAreaMetadata",
    "AuthoredModuleMetadataValidation",
    "AuthoredModuleTimeMetadata",
    "CompiledAuthoredModuleMetadata",
    "build_authored_are_bytes",
    "build_authored_are_gff",
    "build_authored_ifo_bytes",
    "build_authored_ifo_gff",
    "compile_authored_module_metadata",
    "validate_authored_module_metadata",
]
