"""Scale-preserving KotOR animation retargeting.

The viewport can already display a pose generated by one model on another
model when node names happen to line up. This module makes that explicit and
safe: rotations and motion deltas are transferred, target bind-pose bone
offsets are preserved, and scale controllers are ignored by default so the
target model does not change height, width, or bone length.
"""

from __future__ import annotations

import copy
from dataclasses import dataclass, field
from typing import Dict, Iterable, Optional

from ..animation_engine import AnimPose, NodePose
from ..model_data import Animation


_ALIASES: Dict[str, tuple[str, ...]] = {
    "rootdummy": ("root", "root_g", "dummyroot"),
    "pelvis_g": ("pelvis", "hips", "hip_g"),
    "torso_g": ("spine", "spine_g", "chest_g"),
    "torsoupr_g": ("spine1", "spine_01", "chest"),
    "neck_g": ("neck", "necklwr_g"),
    "headhook": ("head", "head_g", "headhook_g"),
    "rhand": ("r_hand", "rhand_g", "hand_r"),
    "lhand": ("l_hand", "lhand_g", "hand_l"),
    "rfoot_g": ("rfoot", "foot_r", "r_foot"),
    "lfoot_g": ("lfoot", "foot_l", "l_foot"),
}


@dataclass(frozen=True)
class RetargetConfig:
    """Controls how poses are transferred between skeletons."""

    preserve_model_scale: bool = True
    ignore_scale_keys: bool = True
    copy_material_animation: bool = True
    allow_unmapped_nodes: bool = False
    root_motion_scale: float = 1.0


@dataclass(frozen=True)
class BoneMappingReport:
    source_model: str = ""
    target_model: str = ""
    mapping: Dict[str, str] = field(default_factory=dict)
    exact_matches: int = 0
    alias_matches: int = 0
    missing_source: tuple[str, ...] = ()
    missing_target: tuple[str, ...] = ()

    @property
    def matched_count(self) -> int:
        return len(self.mapping)


@dataclass(frozen=True)
class RetargetResult:
    pose: AnimPose
    report: BoneMappingReport


def _nodes_by_name(model) -> Dict[str, object]:
    nodes = list(model.all_nodes()) if hasattr(model, "all_nodes") else []
    return {str(getattr(n, "name", "") or "").lower(): n for n in nodes if getattr(n, "name", "")}


def _candidate_names(source_name: str) -> Iterable[str]:
    key = source_name.lower()
    yield key
    for alias in _ALIASES.get(key, ()):
        yield alias.lower()
    for src, aliases in _ALIASES.items():
        if key in aliases:
            yield src
            for alias in aliases:
                yield alias.lower()


def build_bone_map(source_model, target_model) -> BoneMappingReport:
    """Build a conservative source-node-name to target-node-name map."""
    src_nodes = _nodes_by_name(source_model)
    dst_nodes = _nodes_by_name(target_model)
    mapping: Dict[str, str] = {}
    exact = 0
    alias = 0

    for src_name in src_nodes:
        target_name = ""
        for candidate in _candidate_names(src_name):
            if candidate in dst_nodes:
                target_name = candidate
                break
        if not target_name:
            continue
        mapping[src_name] = target_name
        if target_name == src_name:
            exact += 1
        else:
            alias += 1

    missing_source = tuple(sorted(src for src in src_nodes if src not in mapping))
    mapped_targets = set(mapping.values())
    missing_target = tuple(sorted(dst for dst in dst_nodes if dst not in mapped_targets))
    return BoneMappingReport(
        source_model=str(getattr(source_model, "name", "") or ""),
        target_model=str(getattr(target_model, "name", "") or ""),
        mapping=mapping,
        exact_matches=exact,
        alias_matches=alias,
        missing_source=missing_source,
        missing_target=missing_target,
    )


def _sub3(a, b) -> tuple[float, float, float]:
    return (
        float(a[0]) - float(b[0]),
        float(a[1]) - float(b[1]),
        float(a[2]) - float(b[2]),
    )


def _add3(a, b, scale: float = 1.0) -> tuple[float, float, float]:
    return (
        float(a[0]) + float(b[0]) * scale,
        float(a[1]) + float(b[1]) * scale,
        float(a[2]) + float(b[2]) * scale,
    )


def retarget_pose(
    source_pose: AnimPose,
    source_model,
    target_model,
    config: Optional[RetargetConfig] = None,
    mapping_report: Optional[BoneMappingReport] = None,
) -> RetargetResult:
    """Retarget one evaluated source pose onto ``target_model``.

    Source positions are converted back to animation deltas relative to the
    source bind pose, then re-applied to the target bind pose. This is the key
    guard that prevents source bone lengths from resizing the target model.
    """
    cfg = config or RetargetConfig()
    report = mapping_report or build_bone_map(source_model, target_model)
    src_nodes = _nodes_by_name(source_model)
    dst_nodes = _nodes_by_name(target_model)
    out = AnimPose(time=float(getattr(source_pose, "time", 0.0) or 0.0))

    for src_name, src_np in (getattr(source_pose, "nodes", {}) or {}).items():
        src_key = str(src_name or "").lower()
        dst_key = report.mapping.get(src_key)
        if not dst_key and cfg.allow_unmapped_nodes:
            dst_key = src_key
        if not dst_key or dst_key not in dst_nodes:
            continue

        src_node = src_nodes.get(src_key)
        dst_node = dst_nodes[dst_key]
        src_bind_pos = getattr(src_node, "position", (0.0, 0.0, 0.0)) if src_node else (0.0, 0.0, 0.0)
        dst_bind_pos = getattr(dst_node, "position", (0.0, 0.0, 0.0))
        delta = _sub3(getattr(src_np, "position", (0.0, 0.0, 0.0)), src_bind_pos)
        motion_scale = cfg.root_motion_scale if src_key in {"rootdummy", "root"} else 1.0
        position = _add3(dst_bind_pos, delta, motion_scale)

        out.nodes[dst_key] = NodePose(
            name=str(getattr(dst_node, "name", dst_key) or dst_key),
            position=position,
            rotation=tuple(getattr(src_np, "rotation", (0.0, 0.0, 0.0, 1.0))),
            scale=1.0 if cfg.ignore_scale_keys else float(getattr(src_np, "scale", 1.0) or 1.0),
            alpha=getattr(src_np, "alpha", None) if cfg.copy_material_animation else None,
            selfillum=getattr(src_np, "selfillum", None) if cfg.copy_material_animation else None,
        )

    return RetargetResult(pose=out, report=report)


def retarget_animation(
    source_animation: Animation,
    source_model,
    target_model,
    config: Optional[RetargetConfig] = None,
    mapping_report: Optional[BoneMappingReport] = None,
    name_suffix: str = "_retarget",
) -> tuple[Animation, BoneMappingReport]:
    """Create a target-model animation clip from ``source_animation``.

    KotOR position controllers are relative deltas, so they can be copied
    directly onto a target node without importing source bind offsets. Scale
    controllers are dropped by default.
    """
    cfg = config or RetargetConfig()
    report = mapping_report or build_bone_map(source_model, target_model)
    dst_nodes = _nodes_by_name(target_model)
    new_anim = Animation(
        name=f"{getattr(source_animation, 'name', 'animation')}{name_suffix}",
        length=float(getattr(source_animation, "length", 0.0) or 0.0),
        transition_time=float(getattr(source_animation, "transition_time", 0.25) or 0.25),
        anim_root=report.mapping.get(str(getattr(source_animation, "anim_root", "") or "").lower(), ""),
        events=copy.deepcopy(getattr(source_animation, "events", []) or []),
        nodes=[],
    )

    for src_anim_node in getattr(source_animation, "nodes", []) or []:
        src_key = str(getattr(src_anim_node, "name", "") or "").lower()
        dst_key = report.mapping.get(src_key)
        if not dst_key or dst_key not in dst_nodes:
            continue
        dst_node = dst_nodes[dst_key]
        anim_node = dst_node.clone_shallow() if hasattr(dst_node, "clone_shallow") else copy.copy(dst_node)
        anim_node.name = str(getattr(dst_node, "name", dst_key) or dst_key)
        anim_node.children = []
        anim_node.parent = None
        anim_node.controllers = []
        for ctrl in getattr(src_anim_node, "controllers", []) or []:
            ctype = int(ctrl.get("type", -1)) if isinstance(ctrl, dict) else -1
            if cfg.ignore_scale_keys and ctype == 36:
                continue
            new_ctrl = copy.deepcopy(ctrl)
            if ctype == 8 and src_key in {"rootdummy", "root"} and cfg.root_motion_scale != 1.0:
                values = []
                for val in new_ctrl.get("values", []) or []:
                    if len(val) >= 3:
                        values.append((
                            float(val[0]) * cfg.root_motion_scale,
                            float(val[1]) * cfg.root_motion_scale,
                            float(val[2]) * cfg.root_motion_scale,
                        ))
                    else:
                        values.append(val)
                new_ctrl["values"] = values
            anim_node.controllers.append(new_ctrl)
        if anim_node.controllers:
            new_anim.nodes.append(anim_node)

    return new_anim, report
