#pragma once

#include <cstddef>

namespace ghostrigger::core::ipc {

#ifndef GHOSTRIGGER_IPC_NATIVE_FUNCTION_IMPLEMENTATION_DEFINED
#define GHOSTRIGGER_IPC_NATIVE_FUNCTION_IMPLEMENTATION_DEFINED
struct NativeFunctionImplementation {
    const char* project;
    const char* native_namespace;
    const char* python_file;
    const char* qualname;
    const char* callable_type;
    const char* implementation_status;
    bool native_first;
    bool python_runtime_required;
    bool python_fallback_allowed;
    const char* contract_json;
};
#endif // GHOSTRIGGER_IPC_NATIVE_FUNCTION_IMPLEMENTATION_DEFINED

const NativeFunctionImplementation& ipc_call_async_worker_line_111_c8c78c69_native();
const NativeFunctionImplementation& log_result_cb_line_527_94e1f5ec_native();
const NativeFunctionImplementation& ghostriggeripcserver_invoke_callback_sync_runner_line_94_94b2b4b8_native();
const NativeFunctionImplementation& ghostriggeripcserver_run_server_ok_line_136_f1d36ee5_native();
const NativeFunctionImplementation& ghostriggeripcserver_run_server_err_line_142_ce2ffb8d_native();
const NativeFunctionImplementation& ghostriggeripcserver_run_server_payload_line_145_e1dd9c18_native();
const NativeFunctionImplementation& ghostriggeripcserver_run_server_handle_line_149_aa8ff1d0_native();
const NativeFunctionImplementation& ghostriggeripcserver_run_server_route_open_utc_line_181_be553c1b_native();
const NativeFunctionImplementation& ghostriggeripcserver_run_server_route_open_utp_line_185_2b8802c9_native();
const NativeFunctionImplementation& ghostriggeripcserver_run_server_route_open_utd_line_189_9bc98f5b_native();
const NativeFunctionImplementation& ghostriggeripcserver_run_server_route_open_mdl_line_193_ae54800b_native();
const NativeFunctionImplementation& ghostriggeripcserver_run_server_route_ping_line_197_5bd04d74_native();
const NativeFunctionImplementation& ghostriggeripcserver_run_server_route_reload_line_201_ed3c6fe3_native();
const NativeFunctionImplementation& ghostriggeripcserver_run_server_route_load_model_line_240_0191e9e5_native();
const NativeFunctionImplementation& ghostriggeripcserver_run_server_route_new_scene_line_256_b9cd96e3_native();
const NativeFunctionImplementation& ghostriggeripcserver_run_server_route_open_scene_line_269_3fe85f1c_native();
const NativeFunctionImplementation& ghostriggeripcserver_run_server_route_save_scene_line_284_44ccd221_native();
const NativeFunctionImplementation& ghostriggeripcserver_run_server_route_create_scene_camera_line_296_f347459f_native();
const NativeFunctionImplementation& ghostriggeripcserver_run_server_route_create_scene_light_line_310_db9d42f3_native();
const NativeFunctionImplementation& ghostriggeripcserver_run_server_route_select_scene_object_line_323_fa3b0fcf_native();
const NativeFunctionImplementation& ghostriggeripcserver_run_server_route_set_scene_object_visibility_line_338_b051ade2_native();
const NativeFunctionImplementation& ghostriggeripcserver_run_server_route_scene_object_command_line_354_1e2fef7a_native();
const NativeFunctionImplementation& ghostriggeripcserver_run_server_route_scene_object_properties_line_377_6b9fa135_native();
const NativeFunctionImplementation& ghostriggeripcserver_run_server_route_show_panel_line_402_23995c4b_native();
const NativeFunctionImplementation& ghostriggeripcserver_run_server_route_open_tool_line_416_ddf53e13_native();
const NativeFunctionImplementation& ghostriggeripcserver_run_server_route_viewport_command_line_430_432ef3ee_native();
const NativeFunctionImplementation& ghostriggeripcserver_run_server_route_appearance_line_447_2742b3e7_native();
const NativeFunctionImplementation& ghostriggeripcserver_run_server_route_animation_command_line_463_982eda49_native();
const NativeFunctionImplementation& ghostriggeripcserver_run_server_route_select_module_mesh_line_488_fa731d71_native();
const NativeFunctionImplementation& ghostriggeripcserver_run_server_route_set_renderer_backend_line_502_e952b54d_native();
const NativeFunctionImplementation& ghostriggeripcserver_run_server_route_set_dummy_helpers_line_517_1c1558f8_native();
const NativeFunctionImplementation& ghostriggeripcserver_run_server_route_set_light_helpers_line_529_ef738746_native();
const NativeFunctionImplementation& ghostriggeripcserver_run_server_route_select_helper_line_542_c880b0f5_native();
const NativeFunctionImplementation& ghostriggeripcserver_run_server_route_capture_viewport_line_554_fcdff117_native();
const NativeFunctionImplementation& ghostriggeripcserver_run_server_route_library_search_line_568_7f9a0098_native();
const NativeFunctionImplementation& ghostriggeripcserver_run_server_route_library_select_line_588_c8ddbb76_native();
const NativeFunctionImplementation& ghostriggeripcserver_run_server_route_resource_search_line_611_cf55da9f_native();
const NativeFunctionImplementation& ghostriggeripcserver_run_server_route_resource_select_line_631_084c730b_native();
const NativeFunctionImplementation& ghostriggeripcserver_run_server_route_state_line_653_5aef3d2d_native();
const NativeFunctionImplementation& ghostriggeripcserver_run_server_route_health_line_665_03fef148_native();
const NativeFunctionImplementation& ghostriggeripcserver_run_server_route_mcp_tools_list_line_675_401bdba0_native();
const NativeFunctionImplementation& ghostriggeripcserver_run_server_route_mcp_tools_call_line_684_ec6f07a5_native();
const NativeFunctionImplementation& ghostriggeripcserver_run_server_route_mcp_resources_list_line_706_aeb409a7_native();
const NativeFunctionImplementation& ghostriggeripcserver_run_server_route_mcp_resources_read_line_717_93514561_native();
const NativeFunctionImplementation& ghostriggeripcserver_run_server_route_catch_all_line_735_ac12cd3a_native();
const NativeFunctionImplementation& ghostriggeripcserver_run_server_not_found_line_741_e47c214f_native();
const NativeFunctionImplementation& ghostriggeripcserver_run_server_method_not_allowed_line_745_e464b868_native();

const NativeFunctionImplementation* nestedfunctions_native_functions(std::size_t& count);

} // namespace ghostrigger::core::ipc
