<?xml version="1.0" encoding="utf-8"?>
<Project>
  <PropertyGroup>
    <GhostRiggerNativeRoot>$(MSBuildThisFileDirectory)</GhostRiggerNativeRoot>
  </PropertyGroup>
  <ItemDefinitionGroup>
    <ClCompile>
      <AdditionalIncludeDirectories>$(GhostRiggerNativeRoot)GhostRigger.Native.Core.Foundation\Public;$(GhostRiggerNativeRoot)GhostRigger.Native.Core.Foundation;$(GhostRiggerNativeRoot)GhostRigger.Core.Rendering\Public;%(AdditionalIncludeDirectories)</AdditionalIncludeDirectories>
    </ClCompile>
  </ItemDefinitionGroup>
</Project>
