"""Screen-space gizmo hit testing."""

from __future__ import annotations

import math


class GizmoPicker:
    """Fast picker over handles generated by :class:`GizmoRenderer`."""

    def hit_test(self, mouse_pos: tuple[int, int], handles: list[dict], radius: int = 12) -> str | None:
        mx, my = float(mouse_pos[0]), float(mouse_pos[1])
        best = None
        best_dist = float(radius)
        best_priority = -1
        for handle in handles:
            kind = handle.get("kind", "point")
            name = str(handle.get("name", ""))
            if not name:
                continue
            priority = int(handle.get("priority", 0))
            if kind == "segment":
                dist = self._segment_distance(mx, my, handle["start"], handle["end"])
                tolerance = float(handle.get("radius", radius))
            elif kind == "polyline":
                points = handle.get("points", []) or []
                if len(points) < 2:
                    continue
                dist = min(
                    self._segment_distance(mx, my, start, end)
                    for start, end in zip(points, points[1:])
                )
                tolerance = float(handle.get("radius", radius))
            elif kind == "ring":
                cx, cy = handle["center"]
                dist_to_center = math.hypot(mx - cx, my - cy)
                dist = abs(dist_to_center - float(handle["radius"]))
                tolerance = float(handle.get("radius_px", radius))
            else:
                hx, hy = handle["pos"]
                dist = math.hypot(mx - float(hx), my - float(hy))
                tolerance = float(handle.get("radius", radius))
            if dist <= tolerance and (priority > best_priority or (priority == best_priority and dist < best_dist)):
                best = name
                best_dist = dist
                best_priority = priority
        return best

    @staticmethod
    def _segment_distance(px: float, py: float, start, end) -> float:
        ax, ay = float(start[0]), float(start[1])
        bx, by = float(end[0]), float(end[1])
        vx, vy = bx - ax, by - ay
        length2 = vx * vx + vy * vy
        if length2 <= 1e-9:
            return math.hypot(px - ax, py - ay)
        t = max(0.0, min(1.0, ((px - ax) * vx + (py - ay) * vy) / length2))
        cx = ax + vx * t
        cy = ay + vy * t
        return math.hypot(px - cx, py - cy)
