#pragma once

#include <cstddef>

namespace ghostrigger::phase15::ghostrigger_converters {

using PythonFunctionDescriptorJson = const char* (*)();

struct PythonFunctionDescriptorEntry {
    const char* python_file;
    const char* qualname;
    const char* function_type;
    PythonFunctionDescriptorJson descriptor_json;
};

const char* src_converters_mesh_converter_objimporter_import_obj_line_49_2a0b3397_descriptor_json();
const char* src_converters_mesh_converter_objimporter_import_file_line_57_65af3f3e_descriptor_json();
const char* src_converters_mesh_converter_objimporter_fv_line_129_b726d7b6_descriptor_json();
const char* src_converters_mesh_converter_objimporter_make_node_line_136_8c12fdf5_descriptor_json();
const char* src_converters_mesh_converter_objimporter_flat_normals_line_175_a8a92ef3_descriptor_json();
const char* src_converters_mesh_converter_objimporter_parse_mtl_line_193_b571b0d4_descriptor_json();
const char* src_converters_mesh_converter_fbximporter_import_file_line_219_aaf9dc8b_descriptor_json();
const char* src_converters_mesh_converter_fbximporter_load_assimp_line_276_8229498f_descriptor_json();
const char* src_converters_mesh_converter_fbximporter_load_assimp_py_line_294_cd182bb0_descriptor_json();
const char* src_converters_mesh_converter_fbximporter_walk_assimp_py_nodes_line_313_29bdf562_descriptor_json();
const char* src_converters_mesh_converter_fbximporter_assimp_py_mesh_line_339_7f6469b6_descriptor_json();
const char* src_converters_mesh_converter_fbximporter_walk_assimp_nodes_line_384_3ce3d08f_descriptor_json();
const char* src_converters_mesh_converter_fbximporter_assimp_mesh_line_407_a00d328e_descriptor_json();
const char* src_converters_mesh_converter_fbximporter_load_trimesh_line_451_270675e4_descriptor_json();
const char* src_converters_mesh_converter_objexporter_export_line_714_4bc38697_descriptor_json();
const char* src_converters_mesh_converter_fbxexporter_export_line_1167_add00c64_descriptor_json();
const char* src_converters_mesh_converter_fbxexporter_export_fbx_sdk_line_1247_d2d7a15c_descriptor_json();
const char* src_converters_mesh_converter_fbxexporter_add_fbx_mesh_line_1306_4cc38b38_descriptor_json();
const char* src_converters_mesh_converter_fbxexporter_export_assimp_line_1350_d43dd6c0_descriptor_json();
const char* src_converters_mesh_converter_fbxexporter_export_fbx_ascii_line_1364_438537dd_descriptor_json();
const char* src_converters_mesh_converter_gltfimporter_import_file_line_2927_a38b424d_descriptor_json();
const char* src_converters_mesh_converter_gltfimporter_load_pygltflib_line_2945_d2cfa7b7_descriptor_json();
const char* src_converters_mesh_converter_gltfimporter_load_trimesh_line_3179_1d1d39f4_descriptor_json();
const char* src_converters_mesh_converter_gltfexporter_export_line_3218_f2fcb98c_descriptor_json();
const char* src_converters_mesh_converter_gltfexporter_export_pygltflib_line_3280_ec58b6b7_descriptor_json();
const char* src_converters_mesh_converter_gltfexporter_export_manual_line_3632_9ef4eced_descriptor_json();
const char* src_converters_mesh_converter_gltfroundtripresult_init_line_3901_359c0534_descriptor_json();
const char* src_converters_mesh_converter_gltfroundtripresult_summary_line_3913_0d7e3e5d_descriptor_json();
const char* src_converters_normal_map_txibuilder_init_line_39_3c077d0e_descriptor_json();
const char* src_converters_normal_map_txibuilder_set_bumpmapped_line_43_988e81e0_descriptor_json();
const char* src_converters_normal_map_txibuilder_set_envmapped_line_51_7e02a03e_descriptor_json();
const char* src_converters_normal_map_txibuilder_set_bumpmap_scaling_line_59_e692ceb5_descriptor_json();
const char* src_converters_normal_map_txibuilder_set_specular_power_line_64_638cb06a_descriptor_json();
const char* src_converters_normal_map_txibuilder_set_alpha_blend_line_70_7275122b_descriptor_json();
const char* src_converters_normal_map_txibuilder_set_procedural_line_82_07c8868c_descriptor_json();
const char* src_converters_normal_map_txibuilder_set_clamp_line_88_bd5a86c5_descriptor_json();
const char* src_converters_normal_map_txibuilder_set_isbumpmap_line_96_4d57a0ae_descriptor_json();
const char* src_converters_normal_map_txibuilder_set_wateralpha_line_102_833b762c_descriptor_json();
const char* src_converters_normal_map_txibuilder_set_fps_line_106_234c7097_descriptor_json();
const char* src_converters_normal_map_txibuilder_set_numx_line_112_87c366fa_descriptor_json();
const char* src_converters_normal_map_txibuilder_set_numy_line_118_232d7402_descriptor_json();
const char* src_converters_normal_map_txibuilder_build_line_124_775c3b39_descriptor_json();
const char* src_converters_normal_map_txibuilder_save_txi_line_128_a4c6b53f_descriptor_json();
const char* src_converters_normal_map_softwarenormalbaker_init_line_173_c5e84a5f_descriptor_json();
const char* src_converters_normal_map_softwarenormalbaker_bake_line_177_02808e6b_descriptor_json();
const char* src_converters_normal_map_softwarenormalbaker_build_triangle_data_line_284_4d351538_descriptor_json();
const char* src_converters_normal_map_softwarenormalbaker_build_uv_lookup_line_309_ed64a14c_descriptor_json();
const char* src_converters_normal_map_softwarenormalbaker_ray_cast_normal_line_328_7b9ab29f_descriptor_json();

const PythonFunctionDescriptorEntry* instancemethods_descriptors(std::size_t& count);

} // namespace ghostrigger::phase15::ghostrigger_converters
