#pragma once

#include <cstddef>

namespace ghostrigger::phase15::ghostrigger_converters {

using PythonFunctionDescriptorJson = const char* (*)();

struct PythonFunctionDescriptorEntry {
    const char* python_file;
    const char* qualname;
    const char* function_type;
    PythonFunctionDescriptorJson descriptor_json;
};

const char* src_converters_blender_fbx_mesh_importer_import_fbx_mesh_with_blender_line_36_72cb2d44_descriptor_json();
const char* src_converters_blender_fbx_mesh_importer_model_from_blender_fbx_mesh_payload_line_106_2efe69b6_descriptor_json();
const char* src_converters_blender_fbx_mesh_importer_attach_imported_armature_guides_line_196_944dc899_descriptor_json();
const char* src_converters_blender_fbx_mesh_importer_optional_triple_line_302_ac85f0c9_descriptor_json();
const char* src_converters_blender_fbx_mesh_importer_output_json_path_line_314_7126c45c_descriptor_json();
const char* src_converters_blender_fbx_mesh_importer_triple_line_324_268acf83_descriptor_json();
const char* src_converters_blender_fbx_mesh_importer_pair_line_329_7bfb8a8e_descriptor_json();
const char* src_converters_blender_fbx_mesh_importer_face_line_334_a80e1f65_descriptor_json();
const char* src_converters_blender_fbx_mesh_importer_skin_vertex_line_339_7e47defb_descriptor_json();
const char* src_converters_mesh_converter_renderable_mesh_nodes_line_948_99f7f44a_descriptor_json();
const char* src_converters_mesh_converter_export_rigging_data_line_978_bbde667e_descriptor_json();
const char* src_converters_mesh_converter_tga_to_tpc_line_2649_0fa16c69_descriptor_json();
const char* src_converters_mesh_converter_tpc_to_tga_line_2728_cb425a79_descriptor_json();
const char* src_converters_mesh_converter_decompress_dxt1_line_2826_b5a4c5a2_descriptor_json();
const char* src_converters_mesh_converter_decompress_dxt5_line_2860_4d4bc427_descriptor_json();
const char* src_converters_mesh_converter_gen_mips_line_2892_b39293fc_descriptor_json();
const char* src_converters_mesh_converter_gltf_round_trip_verify_line_3933_7335d549_descriptor_json();
const char* src_converters_normal_map_normalize3_line_354_74c93553_descriptor_json();
const char* src_converters_normal_map_dot3_line_360_9b483c5d_descriptor_json();
const char* src_converters_normal_map_cross3_line_363_6ab633ea_descriptor_json();
const char* src_converters_normal_map_lerp3_line_368_018e7d43_descriptor_json();
const char* src_converters_normal_map_barycentric_uv_line_374_8e62e29e_descriptor_json();
const char* src_converters_normal_map_compute_tangent_line_394_af510af5_descriptor_json();
const char* src_converters_normal_map_world_to_tangent_line_412_48c8f8f4_descriptor_json();
const char* src_converters_normal_map_ray_triangle_intersect_line_419_373cf1f5_descriptor_json();

const PythonFunctionDescriptorEntry* modulefunctions_descriptors(std::size_t& count);

} // namespace ghostrigger::phase15::ghostrigger_converters
