#pragma once

#include <cstddef>

namespace ghostrigger::phase15::ghostrigger_converters {

using PythonFunctionDescriptorJson = const char* (*)();

struct PythonFunctionDescriptorEntry {
    const char* python_file;
    const char* qualname;
    const char* function_type;
    PythonFunctionDescriptorJson descriptor_json;
};

const char* src_converters_mesh_converter_objimporter_import_file_flush_line_87_1fb37067_descriptor_json();
const char* src_converters_mesh_converter_objimporter_import_file_new_group_line_92_b002e1cc_descriptor_json();
const char* src_converters_mesh_converter_objimporter_make_node_gi_line_155_23f6585c_descriptor_json();
const char* src_converters_mesh_converter_fbxexporter_export_fbx_ascii_new_id_line_1491_3c5a6030_descriptor_json();
const char* src_converters_mesh_converter_fbxexporter_export_fbx_ascii_quat_to_euler_deg_line_1843_dcb2a96b_descriptor_json();
const char* src_converters_mesh_converter_fbxexporter_export_fbx_ascii_world_matrix_col_major_line_1865_622a4fbc_descriptor_json();
const char* src_converters_mesh_converter_fbxexporter_export_fbx_ascii_qbone_matrix_col_major_line_2079_6bd3c6c9_descriptor_json();
const char* src_converters_mesh_converter_fbxexporter_export_fbx_ascii_write_anim_curve_line_2312_fcf8ef5f_descriptor_json();
const char* src_converters_mesh_converter_fbxexporter_export_fbx_ascii_write_grouped_curves_line_2347_ed965d64_descriptor_json();
const char* src_converters_mesh_converter_fbxexporter_export_fbx_ascii_quat_mul_line_2421_b242b201_descriptor_json();
const char* src_converters_mesh_converter_decompress_dxt1_e565_line_2839_e248a9b2_descriptor_json();
const char* src_converters_mesh_converter_decompress_dxt5_e565_line_2874_54635024_descriptor_json();
const char* src_converters_mesh_converter_gltfimporter_load_pygltflib_get_accessor_data_line_2955_abb66ade_descriptor_json();
const char* src_converters_mesh_converter_gltfexporter_export_pygltflib_add_accessor_line_3295_6516bad0_descriptor_json();
const char* src_converters_mesh_converter_gltfexporter_export_pygltflib_pack_v_line_3568_be1ebf70_descriptor_json();
const char* src_converters_mesh_converter_gltfexporter_export_pygltflib_pack_v_line_3575_9b5c23be_descriptor_json();
const char* src_converters_mesh_converter_gltfexporter_export_pygltflib_pack_v_line_3583_5193d6a4_descriptor_json();
const char* src_converters_mesh_converter_gltfexporter_export_manual_add_bv_line_3649_4f6d1cce_descriptor_json();
const char* src_converters_mesh_converter_gltfexporter_export_manual_add_acc_line_3659_4b98012c_descriptor_json();
const char* src_converters_mesh_converter_gltfexporter_export_manual_pv_line_3794_1bc29691_descriptor_json();
const char* src_converters_mesh_converter_gltfexporter_export_manual_pv_line_3797_dc62e16e_descriptor_json();
const char* src_converters_mesh_converter_gltfexporter_export_manual_pv_line_3801_cc34bf13_descriptor_json();

const PythonFunctionDescriptorEntry* nestedfunctions_descriptors(std::size_t& count);

} // namespace ghostrigger::phase15::ghostrigger_converters
