#pragma once

#include <cstddef>

namespace ghostrigger::phase15::ghostrigger_renderer_contracts {

using PythonFunctionDescriptorJson = const char* (*)();

struct PythonFunctionDescriptorEntry {
    const char* python_file;
    const char* qualname;
    const char* function_type;
    PythonFunctionDescriptorJson descriptor_json;
};

const char* src_adapters_rendering_renderer_factory_fallbackviewportrenderer_init_line_115_b27ff4d3_descriptor_json();
const char* src_adapters_rendering_renderer_factory_fallbackviewportrenderer_getattr_line_139_3525630d_descriptor_json();
const char* src_adapters_rendering_renderer_factory_fallbackviewportrenderer_setattr_line_148_00c480a2_descriptor_json();
const char* src_adapters_rendering_renderer_factory_fallbackviewportrenderer_apply_pending_line_158_3fbb5f53_descriptor_json();
const char* src_adapters_rendering_renderer_factory_fallbackviewportrenderer_activate_next_line_171_7e857c90_descriptor_json();
const char* src_adapters_rendering_renderer_factory_fallbackviewportrenderer_create_surface_widget_line_203_cc8f49e9_descriptor_json();
const char* src_adapters_rendering_renderer_factory_fallbackviewportrenderer_initialize_line_221_271835c7_descriptor_json();
const char* src_adapters_rendering_renderer_factory_fallbackviewportrenderer_render_line_227_0692d55f_descriptor_json();
const char* src_adapters_rendering_renderer_factory_fallbackviewportrenderer_set_settings_line_252_7f109032_descriptor_json();
const char* src_adapters_rendering_renderer_factory_fallbackviewportrenderer_shutdown_line_269_3b69a9fc_descriptor_json();
const char* src_adapters_rendering_renderer_factory_fallbackviewportrenderer_release_line_278_c21ad3d7_descriptor_json();
const char* src_adapters_rendering_renderer_factory_fallbackviewportrenderer_clear_caches_line_281_05d13aad_descriptor_json();
const char* src_adapters_rendering_renderer_factory_fallbackviewportrenderer_reset_framebuffers_line_286_636fd7cd_descriptor_json();
const char* src_adapters_rendering_renderer_factory_fallbackviewportrenderer_invalidate_node_line_291_417d0abc_descriptor_json();
const char* src_adapters_rendering_renderer_factory_fallbackviewportrenderer_invalidate_node_cache_line_296_0e4afc47_descriptor_json();
const char* src_adapters_rendering_renderer_factory_fallbackviewportrenderer_invalidate_transform_cache_line_301_4f760894_descriptor_json();
const char* src_adapters_rendering_renderer_factory_fallbackviewportrenderer_invalidate_all_line_311_a111cc0f_descriptor_json();
const char* src_adapters_rendering_renderer_factory_fallbackviewportrenderer_set_theme_colors_line_316_20198646_descriptor_json();
const char* src_adapters_rendering_renderer_factory_fallbackviewportrenderer_set_native_palette_colors_line_322_afefbe13_descriptor_json();
const char* src_adapters_rendering_renderer_factory_fallbackviewportrenderer_get_capabilities_line_332_e3cb3ced_descriptor_json();
const char* src_adapters_rendering_renderer_factory_fallbackviewportrenderer_is_available_line_343_cab40303_descriptor_json();
const char* src_adapters_rendering_renderer_factory_fallbackviewportrenderer_get_diagnostics_line_346_2a7934c6_descriptor_json();
const char* src_core_rendering_renderer_capabilities_renderercapabilities_to_dict_line_56_96c9be59_descriptor_json();
const char* src_core_rendering_renderer_capabilities_renderercapabilities_status_text_line_152_fec5213f_descriptor_json();
const char* src_core_rendering_renderer_capabilities_renderercapabilities_supports_display_mode_line_158_98c34e96_descriptor_json();
const char* src_core_rendering_renderer_interface_iviewportrenderer_is_available_line_16_d8d6e763_descriptor_json();
const char* src_core_rendering_renderer_interface_iviewportrenderer_get_capabilities_line_20_71760aee_descriptor_json();
const char* src_core_rendering_renderer_interface_iviewportrenderer_initialize_line_23_3c747f18_descriptor_json();
const char* src_core_rendering_renderer_interface_iviewportrenderer_create_surface_widget_line_26_1ab290cd_descriptor_json();
const char* src_core_rendering_renderer_interface_iviewportrenderer_resize_line_29_a241a354_descriptor_json();
const char* src_core_rendering_renderer_interface_iviewportrenderer_render_line_33_528a49c1_descriptor_json();
const char* src_core_rendering_renderer_interface_iviewportrenderer_render_overlay_line_36_0ea321a6_descriptor_json();
const char* src_core_rendering_renderer_interface_iviewportrenderer_pick_line_39_e82673ef_descriptor_json();
const char* src_core_rendering_renderer_interface_iviewportrenderer_shutdown_line_42_ff2b66e5_descriptor_json();
const char* src_core_rendering_renderer_interface_iviewportrenderer_get_diagnostics_line_47_5c5843ca_descriptor_json();
const char* src_core_rendering_renderer_interface_iviewportrenderer_upload_mesh_line_57_1fd39e44_descriptor_json();
const char* src_core_rendering_renderer_interface_iviewportrenderer_upload_texture_line_60_26f8032d_descriptor_json();
const char* src_core_rendering_renderer_interface_iviewportrenderer_release_resource_line_63_107b6898_descriptor_json();
const char* src_core_rendering_renderer_interface_iviewportrenderer_invalidate_all_line_66_8f695e92_descriptor_json();
const char* src_core_rendering_renderer_settings_renderersettings_to_settings_dict_line_115_56f97328_descriptor_json();

const PythonFunctionDescriptorEntry* instancemethods_descriptors(std::size_t& count);

} // namespace ghostrigger::phase15::ghostrigger_renderer_contracts
