#pragma once

#include <cstddef>

namespace ghostrigger::tools::spritematerials {

#ifndef GHOSTRIGGER_TOOLS_SPRITEMATERIALS_NATIVE_FUNCTION_IMPLEMENTATION_DEFINED
#define GHOSTRIGGER_TOOLS_SPRITEMATERIALS_NATIVE_FUNCTION_IMPLEMENTATION_DEFINED
struct NativeFunctionImplementation {
    const char* project;
    const char* native_namespace;
    const char* python_file;
    const char* qualname;
    const char* callable_type;
    const char* implementation_status;
    bool native_first;
    bool python_runtime_required;
    bool python_fallback_allowed;
    const char* contract_json;
};
#endif // GHOSTRIGGER_TOOLS_SPRITEMATERIALS_NATIVE_FUNCTION_IMPLEMENTATION_DEFINED

const NativeFunctionImplementation& texarraycache_construct_line_64_1c8a74d9_native();
const NativeFunctionImplementation& texarraycache_get_line_75_5ac63659_native();
const NativeFunctionImplementation& texarraycache_clear_line_105_bea9a5c0_native();
const NativeFunctionImplementation& texarraycache_len_line_109_543b7162_native();
const NativeFunctionImplementation& miparraycache_construct_line_143_312f6b9e_native();
const NativeFunctionImplementation& miparraycache_get_line_149_51bf3028_native();
const NativeFunctionImplementation& miparraycache_clear_line_169_a4460351_native();
const NativeFunctionImplementation& spritematerialdelegate_sizehint_line_14_c26c9848_native();
const NativeFunctionImplementation& qtspritematerialpanel_construct_line_46_387570c3_native();
const NativeFunctionImplementation& qtspritematerialpanel_build_line_53_ffd8682a_native();
const NativeFunctionImplementation& qtspritematerialpanel_apply_ghost_theme_line_189_5cb75459_native();
const NativeFunctionImplementation& qtspritematerialpanel_apply_ghost_layout_line_193_2100dd11_native();
const NativeFunctionImplementation& qtspritematerialpanel_set_model_line_203_00fdf9a9_native();
const NativeFunctionImplementation& qtspritematerialpanel_refresh_line_207_2e8a2a92_native();
const NativeFunctionImplementation& qtspritematerialpanel_selected_sprites_line_234_488b7536_native();
const NativeFunctionImplementation& qtspritematerialpanel_select_sprite_line_237_3977f512_native();
const NativeFunctionImplementation& qtspritematerialpanel_mesh_nodes_line_253_d2be05b2_native();
const NativeFunctionImplementation& qtspritematerialpanel_make_item_line_280_a9133b21_native();
const NativeFunctionImplementation& qtspritematerialpanel_on_selection_changed_line_300_a74e705f_native();
const NativeFunctionImplementation& qtspritematerialpanel_on_item_changed_line_308_a9e43a92_native();
const NativeFunctionImplementation& qtspritematerialpanel_sync_editor_from_selection_line_319_1dde6a81_native();
const NativeFunctionImplementation& qtspritematerialpanel_apply_editor_line_338_d13d48d5_native();
const NativeFunctionImplementation& qtspritematerialpanel_apply_render_mode_line_388_8010eb26_native();
const NativeFunctionImplementation& qtspritematerialpanel_set_selected_hidden_line_416_8556a7ce_native();
const NativeFunctionImplementation& qtspritematerialpanel_sync_editor_preset_line_428_7e8464aa_native();
const NativeFunctionImplementation& qtspritematerialpanel_isolate_selected_line_440_cad489d6_native();
const NativeFunctionImplementation& qtspritematerialpanel_reset_selected_line_455_464e909f_native();
const NativeFunctionImplementation& qtspritematerialpanel_reset_all_line_458_08da8153_native();
const NativeFunctionImplementation& qtspritematerialpanel_reset_nodes_line_461_c8f6f86e_native();
const NativeFunctionImplementation& qtspritematerialpanel_select_current_line_476_b41a75ef_native();
const NativeFunctionImplementation& qtspritematerialpanel_filter_rows_line_481_01f38a4a_native();
const NativeFunctionImplementation& qtspritematerialpanel_resize_columns_line_488_22dda067_native();
const NativeFunctionImplementation& qtspritematerialpanel_set_editor_enabled_line_492_f835b5d4_native();
const NativeFunctionImplementation& qtspritematerialpanel_set_combo_value_line_505_68cf5d6c_native();
const NativeFunctionImplementation& qtspritematerialpanel_emit_changed_line_509_17aa741a_native();
const NativeFunctionImplementation& qtspritematerialpanel_remember_original_line_512_f9f226d0_native();
const NativeFunctionImplementation& qtspritematerialpanel_restore_original_line_517_a6094d5e_native();
const NativeFunctionImplementation& qtspritematerialpanel_bump_revision_line_531_01b7f63a_native();
const NativeFunctionImplementation& qtspritematerialpanel_is_sprite_candidate_line_537_8643a866_native();
const NativeFunctionImplementation& qtspritematerialpanel_render_mode_line_582_528e32a4_native();
const NativeFunctionImplementation& qtspritematerialpanel_mode_label_line_607_70130ac8_native();
const NativeFunctionImplementation& qtspritematerialpanel_category_label_line_616_b8507ef0_native();
const NativeFunctionImplementation& qtspritematerialpanel_texture_name_line_643_629c9003_native();
const NativeFunctionImplementation& qtspritematerialpanel_has_valid_texture_line_650_3316ed94_native();
const NativeFunctionImplementation& qtspritematerialpanel_node_role_line_654_edc03e63_native();
const NativeFunctionImplementation& qtspritematerialpanel_alpha_cutoff_line_657_d1cb41cc_native();
const NativeFunctionImplementation& qtspritematerialpanel_opacity_line_661_5f48a67c_native();
const NativeFunctionImplementation& qtspritematerialpanel_flag_label_line_666_f899844f_native();
const NativeFunctionImplementation& qtspritematerialpanel_tooltip_line_689_55194fef_native();
const NativeFunctionImplementation& qtspritematerialpanel_uses_matte_key_line_701_84a3869c_native();
const NativeFunctionImplementation& qtspritematerialpanel_auto_uses_matte_key_line_707_73745050_native();
const NativeFunctionImplementation& qtspritematerialpanel_is_saber_hilt_line_713_2319907a_native();
const NativeFunctionImplementation& qtspritematerialpanel_glow_boost_line_720_35dd9a81_native();
const NativeFunctionImplementation& qtspritematerialpanel_sprite_icon_line_729_a4db81bd_native();
const NativeFunctionImplementation& materialtrack_post_construct_line_31_f8ed9602_native();
const NativeFunctionImplementation& materialtrack_default_interpolation_line_39_754e6ab4_native();
const NativeFunctionImplementation& materialtrack_serialize_line_44_e38a467e_native();

const NativeFunctionImplementation* instancemethods_native_functions(std::size_t& count);

} // namespace ghostrigger::tools::spritematerials
