#pragma once

#include <cstddef>

namespace ghostrigger::phase15::ghostrigger_tools_spritematerials {

using PythonFunctionDescriptorJson = const char* (*)();

struct PythonFunctionDescriptorEntry {
    const char* python_file;
    const char* qualname;
    const char* function_type;
    PythonFunctionDescriptorJson descriptor_json;
};

const char* src_core_graphics_tex_atlas_texarraycache_init_line_64_1c8a74d9_descriptor_json();
const char* src_core_graphics_tex_atlas_texarraycache_get_line_75_5ac63659_descriptor_json();
const char* src_core_graphics_tex_atlas_texarraycache_clear_line_105_bea9a5c0_descriptor_json();
const char* src_core_graphics_tex_atlas_texarraycache_len_line_109_543b7162_descriptor_json();
const char* src_core_graphics_tex_atlas_miparraycache_init_line_143_312f6b9e_descriptor_json();
const char* src_core_graphics_tex_atlas_miparraycache_get_line_149_51bf3028_descriptor_json();
const char* src_core_graphics_tex_atlas_miparraycache_clear_line_169_a4460351_descriptor_json();
const char* src_gui_panels_qt_sprite_material_panel_spritematerialdelegate_sizehint_line_14_c26c9848_descriptor_json();
const char* src_gui_panels_qt_sprite_material_panel_qtspritematerialpanel_init_line_46_387570c3_descriptor_json();
const char* src_gui_panels_qt_sprite_material_panel_qtspritematerialpanel_build_line_53_ffd8682a_descriptor_json();
const char* src_gui_panels_qt_sprite_material_panel_qtspritematerialpanel_apply_ghost_theme_line_189_5cb75459_descriptor_json();
const char* src_gui_panels_qt_sprite_material_panel_qtspritematerialpanel_apply_ghost_layout_line_193_2100dd11_descriptor_json();
const char* src_gui_panels_qt_sprite_material_panel_qtspritematerialpanel_set_model_line_203_00fdf9a9_descriptor_json();
const char* src_gui_panels_qt_sprite_material_panel_qtspritematerialpanel_refresh_line_207_2e8a2a92_descriptor_json();
const char* src_gui_panels_qt_sprite_material_panel_qtspritematerialpanel_selected_sprites_line_234_488b7536_descriptor_json();
const char* src_gui_panels_qt_sprite_material_panel_qtspritematerialpanel_select_sprite_line_237_3977f512_descriptor_json();
const char* src_gui_panels_qt_sprite_material_panel_qtspritematerialpanel_mesh_nodes_line_253_d2be05b2_descriptor_json();
const char* src_gui_panels_qt_sprite_material_panel_qtspritematerialpanel_make_item_line_280_a9133b21_descriptor_json();
const char* src_gui_panels_qt_sprite_material_panel_qtspritematerialpanel_on_selection_changed_line_300_a74e705f_descriptor_json();
const char* src_gui_panels_qt_sprite_material_panel_qtspritematerialpanel_on_item_changed_line_308_a9e43a92_descriptor_json();
const char* src_gui_panels_qt_sprite_material_panel_qtspritematerialpanel_sync_editor_from_selection_line_319_1dde6a81_descriptor_json();
const char* src_gui_panels_qt_sprite_material_panel_qtspritematerialpanel_apply_editor_line_338_d13d48d5_descriptor_json();
const char* src_gui_panels_qt_sprite_material_panel_qtspritematerialpanel_apply_render_mode_line_388_8010eb26_descriptor_json();
const char* src_gui_panels_qt_sprite_material_panel_qtspritematerialpanel_set_selected_hidden_line_416_8556a7ce_descriptor_json();
const char* src_gui_panels_qt_sprite_material_panel_qtspritematerialpanel_sync_editor_preset_line_428_7e8464aa_descriptor_json();
const char* src_gui_panels_qt_sprite_material_panel_qtspritematerialpanel_isolate_selected_line_440_cad489d6_descriptor_json();
const char* src_gui_panels_qt_sprite_material_panel_qtspritematerialpanel_reset_selected_line_455_464e909f_descriptor_json();
const char* src_gui_panels_qt_sprite_material_panel_qtspritematerialpanel_reset_all_line_458_08da8153_descriptor_json();
const char* src_gui_panels_qt_sprite_material_panel_qtspritematerialpanel_reset_nodes_line_461_c8f6f86e_descriptor_json();
const char* src_gui_panels_qt_sprite_material_panel_qtspritematerialpanel_select_current_line_476_b41a75ef_descriptor_json();
const char* src_gui_panels_qt_sprite_material_panel_qtspritematerialpanel_filter_rows_line_481_01f38a4a_descriptor_json();
const char* src_gui_panels_qt_sprite_material_panel_qtspritematerialpanel_resize_columns_line_488_22dda067_descriptor_json();
const char* src_gui_panels_qt_sprite_material_panel_qtspritematerialpanel_set_editor_enabled_line_492_f835b5d4_descriptor_json();
const char* src_gui_panels_qt_sprite_material_panel_qtspritematerialpanel_set_combo_value_line_505_68cf5d6c_descriptor_json();
const char* src_gui_panels_qt_sprite_material_panel_qtspritematerialpanel_emit_changed_line_509_17aa741a_descriptor_json();
const char* src_gui_panels_qt_sprite_material_panel_qtspritematerialpanel_remember_original_line_512_f9f226d0_descriptor_json();
const char* src_gui_panels_qt_sprite_material_panel_qtspritematerialpanel_restore_original_line_517_a6094d5e_descriptor_json();
const char* src_gui_panels_qt_sprite_material_panel_qtspritematerialpanel_bump_revision_line_531_01b7f63a_descriptor_json();
const char* src_gui_panels_qt_sprite_material_panel_qtspritematerialpanel_is_sprite_candidate_line_537_8643a866_descriptor_json();
const char* src_gui_panels_qt_sprite_material_panel_qtspritematerialpanel_render_mode_line_582_528e32a4_descriptor_json();
const char* src_gui_panels_qt_sprite_material_panel_qtspritematerialpanel_mode_label_line_607_70130ac8_descriptor_json();
const char* src_gui_panels_qt_sprite_material_panel_qtspritematerialpanel_category_label_line_616_b8507ef0_descriptor_json();
const char* src_gui_panels_qt_sprite_material_panel_qtspritematerialpanel_texture_name_line_643_629c9003_descriptor_json();
const char* src_gui_panels_qt_sprite_material_panel_qtspritematerialpanel_has_valid_texture_line_650_3316ed94_descriptor_json();
const char* src_gui_panels_qt_sprite_material_panel_qtspritematerialpanel_node_role_line_654_edc03e63_descriptor_json();
const char* src_gui_panels_qt_sprite_material_panel_qtspritematerialpanel_alpha_cutoff_line_657_d1cb41cc_descriptor_json();
const char* src_gui_panels_qt_sprite_material_panel_qtspritematerialpanel_opacity_line_661_5f48a67c_descriptor_json();
const char* src_gui_panels_qt_sprite_material_panel_qtspritematerialpanel_flag_label_line_666_f899844f_descriptor_json();
const char* src_gui_panels_qt_sprite_material_panel_qtspritematerialpanel_tooltip_line_689_55194fef_descriptor_json();
const char* src_gui_panels_qt_sprite_material_panel_qtspritematerialpanel_uses_matte_key_line_701_84a3869c_descriptor_json();
const char* src_gui_panels_qt_sprite_material_panel_qtspritematerialpanel_auto_uses_matte_key_line_707_73745050_descriptor_json();
const char* src_gui_panels_qt_sprite_material_panel_qtspritematerialpanel_is_saber_hilt_line_713_2319907a_descriptor_json();
const char* src_gui_panels_qt_sprite_material_panel_qtspritematerialpanel_glow_boost_line_720_35dd9a81_descriptor_json();
const char* src_gui_panels_qt_sprite_material_panel_qtspritematerialpanel_sprite_icon_line_729_a4db81bd_descriptor_json();
const char* src_sequence_tracks_material_track_materialtrack_post_init_line_31_f8ed9602_descriptor_json();
const char* src_sequence_tracks_material_track_materialtrack_default_interpolation_line_39_754e6ab4_descriptor_json();
const char* src_sequence_tracks_material_track_materialtrack_serialize_line_44_e38a467e_descriptor_json();

const PythonFunctionDescriptorEntry* instancemethods_descriptors(std::size_t& count);

} // namespace ghostrigger::phase15::ghostrigger_tools_spritematerials
