#pragma once

#include <cstddef>

namespace ghostrigger::phase15::ghostrigger_runtime_shared_contracts {

using PythonFunctionDescriptorJson = const char* (*)();

struct PythonFunctionDescriptorEntry {
    const char* python_file;
    const char* qualname;
    const char* function_type;
    PythonFunctionDescriptorJson descriptor_json;
};

const char* src_adapters_rendering_native_core_binding_repo_root_line_664_6b579e67_descriptor_json();
const char* src_adapters_rendering_native_core_binding_candidate_paths_line_668_f7698985_descriptor_json();
const char* src_adapters_rendering_native_core_binding_decode_json_line_681_c57c56f2_descriptor_json();
const char* src_adapters_rendering_native_core_binding_cpu_skinning_fallback_batch_item_to_dict_line_2301_c912dd2d_descriptor_json();
const char* src_adapters_rendering_native_core_binding_gpu_skinning_dispatch_item_to_dict_line_2317_1641aa65_descriptor_json();
const char* src_adapters_rendering_native_core_binding_resource_upload_item_to_dict_line_2330_e0df7076_descriptor_json();
const char* src_adapters_rendering_native_core_binding_device_resource_item_to_dict_line_2343_e563a16f_descriptor_json();
const char* src_adapters_rendering_native_core_binding_device_resource_upload_commit_item_to_dict_line_2357_3561c33e_descriptor_json();
const char* src_adapters_rendering_native_core_binding_device_resource_transition_item_to_dict_line_2367_2441bd93_descriptor_json();
const char* src_adapters_rendering_native_core_binding_draw_item_to_dict_line_2379_c431326f_descriptor_json();
const char* src_adapters_rendering_native_core_binding_draw_batch_to_dict_line_2391_5c57f3e4_descriptor_json();
const char* src_adapters_rendering_native_core_binding_vec3_line_2402_56084119_descriptor_json();
const char* src_adapters_rendering_native_core_binding_vec4_line_2409_62260cb6_descriptor_json();
const char* src_adapters_rendering_native_core_binding_flatten_matrices_line_2416_35af63bb_descriptor_json();
const char* src_adapters_rendering_native_core_binding_flatten_transform_matrix_line_2438_9cea9dfc_descriptor_json();
const char* src_adapters_rendering_native_core_binding_flatten_positions_line_2457_0bcbec57_descriptor_json();
const char* src_adapters_rendering_native_core_binding_flatten_indices_line_2480_ecd95aee_descriptor_json();
const char* src_adapters_rendering_native_core_binding_flatten_skin_indices_line_2493_911ca48c_descriptor_json();
const char* src_adapters_rendering_native_core_binding_flatten_skin_weights_line_2498_78ccf10b_descriptor_json();
const char* src_adapters_rendering_native_core_binding_flatten_matrix_like_line_2503_f898edc6_descriptor_json();
const char* src_adapters_rendering_native_core_binding_flatten_numeric_line_2526_8e5122e0_descriptor_json();
const char* src_adapters_rendering_native_core_binding_texture_bytes_line_2539_6cf97f46_descriptor_json();
const char* src_adapters_rendering_native_core_renderer_safe_len_line_875_2b260a11_descriptor_json();
const char* src_adapters_rendering_native_core_renderer_material_slot_line_886_8b4e8754_descriptor_json();
const char* src_adapters_rendering_native_core_renderer_mesh_flags_line_894_b4ae071b_descriptor_json();
const char* src_adapters_rendering_native_core_renderer_material_color_line_906_28e11dac_descriptor_json();
const char* src_adapters_rendering_native_core_renderer_mesh_bounds_line_923_45af63f7_descriptor_json();
const char* src_adapters_rendering_native_core_renderer_frame_flags_line_960_3d801e42_descriptor_json();
const char* src_adapters_rendering_native_core_renderer_pick_ray_from_request_line_973_841d79ad_descriptor_json();
const char* src_adapters_rendering_native_core_renderer_vec3_line_986_da54c03f_descriptor_json();
const char* src_adapters_rendering_native_core_renderer_texture_key_line_993_1fc5daf0_descriptor_json();
const char* src_adapters_rendering_native_core_renderer_texture_size_line_1001_0591e482_descriptor_json();
const char* src_adapters_rendering_native_core_renderer_texture_byte_size_line_1015_f6e27853_descriptor_json();
const char* src_adapters_rendering_native_core_renderer_texture_format_line_1032_b2b58131_descriptor_json();
const char* src_adapters_rendering_native_core_renderer_texture_flags_line_1040_8f25e810_descriptor_json();
const char* src_adapters_rendering_native_core_renderer_texture_payload_line_1049_e8478aed_descriptor_json();
const char* src_adapters_rendering_native_core_renderer_texture_row_pitch_line_1068_087037f2_descriptor_json();
const char* src_adapters_rendering_native_core_renderer_stable_clip_hash_line_1078_2e4c8ef1_descriptor_json();
const char* src_core_rendering_renderer_backend_normalize_renderer_backend_line_66_6420bbbf_descriptor_json();
const char* src_core_rendering_renderer_backend_supported_renderer_backend_line_73_e099ca56_descriptor_json();
const char* src_core_rendering_renderer_backend_renderer_backend_label_line_80_7ea56790_descriptor_json();

const PythonFunctionDescriptorEntry* modulefunctions_descriptors(std::size_t& count);

} // namespace ghostrigger::phase15::ghostrigger_runtime_shared_contracts
