#pragma once

#include <cstddef>

namespace ghostrigger::phase15::ghostrigger_mdl {

using PythonFunctionDescriptorJson = const char* (*)();

struct PythonFunctionDescriptorEntry {
    const char* python_file;
    const char* qualname;
    const char* function_type;
    PythonFunctionDescriptorJson descriptor_json;
};

const char* src_core_mdl_ghostrigger_mdl_reader_ghostriggertrimeshheader_read_line_47_a77cf33c_descriptor_json();
const char* src_core_mdl_ghostrigger_mdl_reader_ghostriggertrimeshheader_read_extra_line_150_78d7d39b_descriptor_json();
const char* src_core_mdl_ghostrigger_mdl_reader_ghostriggertrimeshheader_sanitize_faces_line_229_e672cde8_descriptor_json();
const char* src_core_mdl_ghostrigger_mdl_reader_ghostriggernode_read_line_245_5cf2f559_descriptor_json();
const char* src_core_mdl_ghostrigger_mdl_reader_ghostriggernode_record_for_active_reader_line_316_b970b062_descriptor_json();
const char* src_core_mdl_ghostrigger_mdl_reader_ghostriggernode_sanitize_light_header_line_321_1ba5b3e7_descriptor_json();
const char* src_core_mdl_ghostrigger_mdl_reader_ghostriggermdlbinaryreader_init_line_352_2bfa9c9b_descriptor_json();
const char* src_core_mdl_ghostrigger_mdl_reader_ghostriggermdlbinaryreader_get_node_order_line_357_70cb6717_descriptor_json();
const char* src_core_mdl_ghostrigger_mdl_reader_ghostriggermdlbinaryreader_load_node_line_405_17f9a8b3_descriptor_json();
const char* src_core_mdl_ghostrigger_mdl_reader_ghostriggermdlbinaryreader_preserve_raw_node_flags_line_422_81e15ea3_descriptor_json();
const char* src_core_mdl_ghostrigger_mdl_reader_ghostriggermdlbinaryreader_fill_mdx_offset_zero_vertices_line_428_3a1d4ae1_descriptor_json();
const char* src_core_mdl_mdl_parser_mdlbinaryparser_init_line_65_9d80c482_descriptor_json();
const char* src_core_mdl_mdl_parser_mdlbinaryparser_parse_line_89_6b152104_descriptor_json();
const char* src_core_mdl_mdl_parser_mdlbinaryparser_parse_mesh_line_136_6872c356_descriptor_json();
const char* src_core_mdl_mdl_parser_mdlbinaryparser_parse_controllers_line_158_ce00725e_descriptor_json();
const char* src_core_mdl_mdl_parser_mdlbinaryparser_parse_one_animation_line_240_62882005_descriptor_json();
const char* src_core_mdl_mdl_parser_mdlbinaryparser_parse_skin_line_253_84130beb_descriptor_json();
const char* src_core_mdl_mdl_parser_mdlbinaryparser_parse_dangly_line_265_e9fb578f_descriptor_json();
const char* src_core_mdl_mdl_parser_mdlbinaryparser_parse_emitter_line_275_c69bbfe5_descriptor_json();
const char* src_core_mdl_mdl_parser_mdlbinaryparser_parse_node_line_293_4ccc5538_descriptor_json();
const char* src_core_mdl_mdl_parser_mdlbinaryparser_parse_animations_line_301_754bbbf7_descriptor_json();
const char* src_core_mdl_mdl_parser_mdlasciiparser_parse_file_line_339_5a0029c0_descriptor_json();
const char* src_core_mdl_mdl_parser_mdlasciiparser_parse_string_line_343_36c463aa_descriptor_json();
const char* src_core_mdl_mdl_parser_mdlasciiparser_parse_line_347_09eddbf6_descriptor_json();
const char* src_core_mdl_mdl_parser_mdlasciiparser_parse_anim_block_line_413_175d6862_descriptor_json();
const char* src_core_mdl_mdl_parser_mdlasciiparser_tok_line_439_1c64c94d_descriptor_json();
const char* src_core_mdl_mdl_parser_mdlasciiparser_parse_node_block_line_442_12998b7b_descriptor_json();
const char* src_core_mdl_mdl_parser_mdlasciiwriter_build_lines_line_728_daf16bcc_descriptor_json();
const char* src_core_mdl_mdl_parser_mdlasciiwriter_to_string_line_750_1659264b_descriptor_json();
const char* src_core_mdl_mdl_parser_mdlasciiwriter_write_line_754_18516610_descriptor_json();
const char* src_core_mdl_mdl_parser_mdlasciiwriter_write_node_line_760_153d7497_descriptor_json();
const char* src_core_mdl_mdl_parser_mdlasciiwriter_write_mesh_line_804_7f9dabef_descriptor_json();
const char* src_core_mdl_mdl_parser_mdlasciiwriter_write_light_line_865_cbc65042_descriptor_json();
const char* src_core_mdl_mdl_parser_mdlasciiwriter_write_dangly_line_875_23d582d3_descriptor_json();
const char* src_core_mdl_mdl_parser_mdlasciiwriter_write_emitter_line_890_8a36b9f8_descriptor_json();
const char* src_core_mdl_mdl_parser_mdlasciiwriter_write_anim_line_894_3b3e3bf3_descriptor_json();
const char* src_core_mdl_mdl_parser_mdlasciiwriter_write_anim_node_line_919_91795237_descriptor_json();
const char* src_core_mdl_mdl_porter_crossgameporter_init_line_113_29740206_descriptor_json();
const char* src_core_mdl_mdl_porter_crossgameporter_port_line_121_0e95d97a_descriptor_json();
const char* src_core_mdl_mdl_porter_crossgameporter_build_texture_report_line_158_e3a05e08_descriptor_json();
const char* src_core_mdl_mdl_porter_crossgameporter_iter_nodes_line_177_d01d25a1_descriptor_json();
const char* src_core_mdl_mdl_porter_crossgameporter_walk_nodes_line_184_3f340422_descriptor_json();
const char* src_core_mdl_mdl_porter_mdlbinarywriter_write_line_237_e269f4d0_descriptor_json();
const char* src_core_mdl_mdl_porter_mdlbinarywriter_build_line_257_ab7da392_descriptor_json();
const char* src_core_mdl_mdl_porter_mdlbinarywriter_build_line_268_00d3b9e5_descriptor_json();
const char* src_core_mdl_mdl_porter_mdlbinarywriter_serialize_controllers_line_578_72549bba_descriptor_json();
const char* src_core_mdl_mdl_porter_mdlbinarywriter_build_mdx_segment_line_643_1175cd5e_descriptor_json();
const char* src_core_mdl_mdl_porter_mdlbinarywriter_build_face_block_line_689_e5ea7fec_descriptor_json();
const char* src_core_mdl_mdl_porter_mdlbinarywriter_build_mesh_header_line_724_015da340_descriptor_json();
const char* src_core_mdl_mdl_porter_mdlbinarywriter_build_animations_line_1092_435ba98f_descriptor_json();
const char* src_core_mdl_mdl_porter_mdlbinarywriter_build_one_anim_line_1106_2c95a7aa_descriptor_json();
const char* src_core_mdl_mdl_porter_mdlbinarywriter_animation_nodes_with_hierarchy_line_1208_4813b8cd_descriptor_json();
const char* src_core_mdl_mdl_porter_mdlbinarywriter_build_anim_node_line_1355_3a6829ba_descriptor_json();
const char* src_core_mdl_mdl_writer_mdlbinarywriter_write_files_line_273_c838287d_descriptor_json();
const char* src_core_mdl_mdl_writer_mdlbinarywriter_write_animation_override_files_line_282_72e371fc_descriptor_json();
const char* src_core_mdl_mdl_writer_mdlbinarywriter_inject_animation_override_bytes_line_312_947d6a66_descriptor_json();
const char* src_core_mdl_mdl_writer_mdlbinarywriter_prepare_animation_only_state_line_363_cee83c7c_descriptor_json();
const char* src_core_mdl_mdl_writer_mdlbinarywriter_write_line_444_7cddad1e_descriptor_json();
const char* src_core_mdl_mdl_writer_mdlbinarywriter_build_line_634_05ed5ed0_descriptor_json();
const char* src_core_mdl_mdl_writer_mdlbinarywriter_register_name_line_641_0fa70b99_descriptor_json();
const char* src_core_mdl_mdl_writer_mdlbinarywriter_name_index_for_line_651_6e96a13f_descriptor_json();
const char* src_core_mdl_mdl_writer_mdlbinarywriter_mdx_stride_for_line_661_57182612_descriptor_json();
const char* src_core_mdl_mdl_writer_mdlbinarywriter_write_mdx_node_line_709_47301beb_descriptor_json();
const char* src_core_mdl_mdl_writer_mdlbinarywriter_write_node_tree_line_756_e2afae78_descriptor_json();
const char* src_core_mdl_mdl_writer_mdlbinarywriter_write_one_node_pass1_line_835_a07b886b_descriptor_json();
const char* src_core_mdl_mdl_writer_mdlbinarywriter_count_ctrl_data_line_927_6b5ad89d_descriptor_json();
const char* src_core_mdl_mdl_writer_mdlbinarywriter_write_controllers_line_937_347f50cf_descriptor_json();
const char* src_core_mdl_mdl_writer_mdlbinarywriter_write_mesh_header_line_1011_e82de1c8_descriptor_json();
const char* src_core_mdl_mdl_writer_mdlbinarywriter_write_skin_header_line_1264_332fa180_descriptor_json();
const char* src_core_mdl_mdl_writer_mdlbinarywriter_skin_bone_node_index_line_1391_ead03c95_descriptor_json();
const char* src_core_mdl_mdl_writer_mdlbinarywriter_write_dangly_header_line_1398_a892c0ff_descriptor_json();
const char* src_core_mdl_mdl_writer_mdlbinarywriter_write_aabb_section_line_1435_ccc32c27_descriptor_json();
const char* src_core_mdl_mdl_writer_mdlbinarywriter_write_emitter_header_line_1484_97a21059_descriptor_json();
const char* src_core_mdl_mdl_writer_mdlbinarywriter_write_reference_header_line_1521_8cf1c21c_descriptor_json();
const char* src_core_mdl_mdl_writer_mdlbinarywriter_write_animation_line_1531_44c87801_descriptor_json();
const char* src_core_mdl_mdl_writer_mdlbinarywriter_animation_nodes_with_hierarchy_line_1598_de9fdbaa_descriptor_json();
const char* src_core_mdl_mdl_writer_mdlbinarywriter_write_anim_node_tree_line_1805_fa2352a7_descriptor_json();
const char* src_core_mdl_mdl_writer_mdlbinarywriter_write_one_anim_node_header_and_child_array_line_1878_8ad4dbab_descriptor_json();

const PythonFunctionDescriptorEntry* instancemethods_descriptors(std::size_t& count);

} // namespace ghostrigger::phase15::ghostrigger_mdl
