#pragma once

#include <cstddef>

namespace ghostrigger::mdl {

#ifndef GHOSTRIGGER_MDL_NATIVE_FUNCTION_IMPLEMENTATION_DEFINED
#define GHOSTRIGGER_MDL_NATIVE_FUNCTION_IMPLEMENTATION_DEFINED
struct NativeFunctionImplementation {
    const char* project;
    const char* native_namespace;
    const char* python_file;
    const char* qualname;
    const char* callable_type;
    const char* implementation_status;
    bool native_first;
    bool python_runtime_required;
    bool python_fallback_allowed;
    const char* contract_json;
};
#endif // GHOSTRIGGER_MDL_NATIVE_FUNCTION_IMPLEMENTATION_DEFINED

const NativeFunctionImplementation& ghostriggertrimeshheader_read_line_47_a77cf33c_native();
const NativeFunctionImplementation& ghostriggertrimeshheader_read_extra_line_150_78d7d39b_native();
const NativeFunctionImplementation& ghostriggertrimeshheader_sanitize_faces_line_229_e672cde8_native();
const NativeFunctionImplementation& ghostriggernode_read_line_245_5cf2f559_native();
const NativeFunctionImplementation& ghostriggernode_record_for_active_reader_line_316_b970b062_native();
const NativeFunctionImplementation& ghostriggernode_sanitize_light_header_line_321_1ba5b3e7_native();
const NativeFunctionImplementation& ghostriggermdlbinaryreader_construct_line_352_2bfa9c9b_native();
const NativeFunctionImplementation& ghostriggermdlbinaryreader_get_node_order_line_357_70cb6717_native();
const NativeFunctionImplementation& ghostriggermdlbinaryreader_load_node_line_405_17f9a8b3_native();
const NativeFunctionImplementation& ghostriggermdlbinaryreader_preserve_raw_node_flags_line_422_81e15ea3_native();
const NativeFunctionImplementation& ghostriggermdlbinaryreader_fill_mdx_offset_zero_vertices_line_428_3a1d4ae1_native();
const NativeFunctionImplementation& mdlbinaryparser_construct_line_65_9d80c482_native();
const NativeFunctionImplementation& mdlbinaryparser_parse_line_89_6b152104_native();
const NativeFunctionImplementation& mdlbinaryparser_parse_mesh_line_136_6872c356_native();
const NativeFunctionImplementation& mdlbinaryparser_parse_controllers_line_158_ce00725e_native();
const NativeFunctionImplementation& mdlbinaryparser_parse_one_animation_line_240_62882005_native();
const NativeFunctionImplementation& mdlbinaryparser_parse_skin_line_253_84130beb_native();
const NativeFunctionImplementation& mdlbinaryparser_parse_dangly_line_265_e9fb578f_native();
const NativeFunctionImplementation& mdlbinaryparser_parse_emitter_line_275_c69bbfe5_native();
const NativeFunctionImplementation& mdlbinaryparser_parse_node_line_293_4ccc5538_native();
const NativeFunctionImplementation& mdlbinaryparser_parse_animations_line_301_754bbbf7_native();
const NativeFunctionImplementation& mdlasciiparser_parse_file_line_339_5a0029c0_native();
const NativeFunctionImplementation& mdlasciiparser_parse_string_line_343_36c463aa_native();
const NativeFunctionImplementation& mdlasciiparser_parse_line_347_09eddbf6_native();
const NativeFunctionImplementation& mdlasciiparser_parse_anim_block_line_413_175d6862_native();
const NativeFunctionImplementation& mdlasciiparser_tok_line_439_1c64c94d_native();
const NativeFunctionImplementation& mdlasciiparser_parse_node_block_line_442_12998b7b_native();
const NativeFunctionImplementation& mdlasciiwriter_build_lines_line_728_daf16bcc_native();
const NativeFunctionImplementation& mdlasciiwriter_to_string_line_750_1659264b_native();
const NativeFunctionImplementation& mdlasciiwriter_write_line_754_18516610_native();
const NativeFunctionImplementation& mdlasciiwriter_write_node_line_760_153d7497_native();
const NativeFunctionImplementation& mdlasciiwriter_write_mesh_line_804_7f9dabef_native();
const NativeFunctionImplementation& mdlasciiwriter_write_light_line_865_cbc65042_native();
const NativeFunctionImplementation& mdlasciiwriter_write_dangly_line_875_23d582d3_native();
const NativeFunctionImplementation& mdlasciiwriter_write_emitter_line_890_8a36b9f8_native();
const NativeFunctionImplementation& mdlasciiwriter_write_anim_line_894_3b3e3bf3_native();
const NativeFunctionImplementation& mdlasciiwriter_write_anim_node_line_919_91795237_native();
const NativeFunctionImplementation& crossgameporter_construct_line_113_29740206_native();
const NativeFunctionImplementation& crossgameporter_port_line_121_0e95d97a_native();
const NativeFunctionImplementation& crossgameporter_build_texture_report_line_158_e3a05e08_native();
const NativeFunctionImplementation& crossgameporter_iter_nodes_line_177_d01d25a1_native();
const NativeFunctionImplementation& crossgameporter_walk_nodes_line_184_3f340422_native();
const NativeFunctionImplementation& mdlbinarywriter_write_line_237_e269f4d0_native();
const NativeFunctionImplementation& mdlbinarywriter_build_line_257_ab7da392_native();
const NativeFunctionImplementation& mdlbinarywriter_build_line_268_00d3b9e5_native();
const NativeFunctionImplementation& mdlbinarywriter_serialize_controllers_line_578_72549bba_native();
const NativeFunctionImplementation& mdlbinarywriter_build_mdx_segment_line_643_1175cd5e_native();
const NativeFunctionImplementation& mdlbinarywriter_build_face_block_line_689_e5ea7fec_native();
const NativeFunctionImplementation& mdlbinarywriter_build_mesh_header_line_724_015da340_native();
const NativeFunctionImplementation& mdlbinarywriter_build_animations_line_1092_435ba98f_native();
const NativeFunctionImplementation& mdlbinarywriter_build_one_anim_line_1106_2c95a7aa_native();
const NativeFunctionImplementation& mdlbinarywriter_animation_nodes_with_hierarchy_line_1208_4813b8cd_native();
const NativeFunctionImplementation& mdlbinarywriter_build_anim_node_line_1355_3a6829ba_native();
const NativeFunctionImplementation& mdlbinarywriter_write_files_line_273_c838287d_native();
const NativeFunctionImplementation& mdlbinarywriter_write_animation_override_files_line_282_72e371fc_native();
const NativeFunctionImplementation& mdlbinarywriter_inject_animation_override_bytes_line_312_947d6a66_native();
const NativeFunctionImplementation& mdlbinarywriter_prepare_animation_only_state_line_363_cee83c7c_native();
const NativeFunctionImplementation& mdlbinarywriter_write_line_444_7cddad1e_native();
const NativeFunctionImplementation& mdlbinarywriter_build_line_634_05ed5ed0_native();
const NativeFunctionImplementation& mdlbinarywriter_register_name_line_641_0fa70b99_native();
const NativeFunctionImplementation& mdlbinarywriter_name_index_for_line_651_6e96a13f_native();
const NativeFunctionImplementation& mdlbinarywriter_mdx_stride_for_line_661_57182612_native();
const NativeFunctionImplementation& mdlbinarywriter_write_mdx_node_line_709_47301beb_native();
const NativeFunctionImplementation& mdlbinarywriter_write_node_tree_line_756_e2afae78_native();
const NativeFunctionImplementation& mdlbinarywriter_write_one_node_pass1_line_835_a07b886b_native();
const NativeFunctionImplementation& mdlbinarywriter_count_ctrl_data_line_927_6b5ad89d_native();
const NativeFunctionImplementation& mdlbinarywriter_write_controllers_line_937_347f50cf_native();
const NativeFunctionImplementation& mdlbinarywriter_write_mesh_header_line_1011_e82de1c8_native();
const NativeFunctionImplementation& mdlbinarywriter_write_skin_header_line_1264_332fa180_native();
const NativeFunctionImplementation& mdlbinarywriter_skin_bone_node_index_line_1391_ead03c95_native();
const NativeFunctionImplementation& mdlbinarywriter_write_dangly_header_line_1398_a892c0ff_native();
const NativeFunctionImplementation& mdlbinarywriter_write_aabb_section_line_1435_ccc32c27_native();
const NativeFunctionImplementation& mdlbinarywriter_write_emitter_header_line_1484_97a21059_native();
const NativeFunctionImplementation& mdlbinarywriter_write_reference_header_line_1521_8cf1c21c_native();
const NativeFunctionImplementation& mdlbinarywriter_write_animation_line_1531_44c87801_native();
const NativeFunctionImplementation& mdlbinarywriter_animation_nodes_with_hierarchy_line_1598_de9fdbaa_native();
const NativeFunctionImplementation& mdlbinarywriter_write_anim_node_tree_line_1805_fa2352a7_native();
const NativeFunctionImplementation& mdlbinarywriter_write_one_anim_node_header_and_child_array_line_1878_8ad4dbab_native();

const NativeFunctionImplementation* instancemethods_native_functions(std::size_t& count);

} // namespace ghostrigger::mdl
