#pragma once

#include <cstddef>

namespace ghostrigger::tools::workflow::bodyattachmentsystem {

#ifndef GHOSTRIGGER_TOOLS_BODYATTACHMENTSYSTEM_NATIVE_FUNCTION_IMPLEMENTATION_DEFINED
#define GHOSTRIGGER_TOOLS_BODYATTACHMENTSYSTEM_NATIVE_FUNCTION_IMPLEMENTATION_DEFINED
struct NativeFunctionImplementation {
    const char* project;
    const char* native_namespace;
    const char* python_file;
    const char* qualname;
    const char* callable_type;
    const char* implementation_status;
    bool native_first;
    bool python_runtime_required;
    bool python_fallback_allowed;
    const char* contract_json;
};
#endif // GHOSTRIGGER_TOOLS_BODYATTACHMENTSYSTEM_NATIVE_FUNCTION_IMPLEMENTATION_DEFINED

const NativeFunctionImplementation& qtbodyattachmentpanel_construct_line_83_f681e428_native();
const NativeFunctionImplementation& qtbodyattachmentpanel_build_line_93_2522e5c1_native();
const NativeFunctionImplementation& qtbodyattachmentpanel_selected_slot_line_162_7f212de1_native();
const NativeFunctionImplementation& qtbodyattachmentpanel_selected_mode_line_165_7e7800b2_native();
const NativeFunctionImplementation& qtbodyattachmentpanel_set_mode_line_168_0c3ee976_native();
const NativeFunctionImplementation& qtbodyattachmentpanel_selected_model_resref_line_185_dd042b5d_native();
const NativeFunctionImplementation& qtbodyattachmentpanel_set_selected_slot_line_191_f2c2de62_native();
const NativeFunctionImplementation& qtbodyattachmentpanel_set_body_model_line_205_ceeed903_native();
const NativeFunctionImplementation& qtbodyattachmentpanel_set_slot_model_line_210_c8d64d69_native();
const NativeFunctionImplementation& qtbodyattachmentpanel_clear_slot_model_line_215_9d62b336_native();
const NativeFunctionImplementation& qtbodyattachmentpanel_set_status_line_219_5dd31913_native();
const NativeFunctionImplementation& qtbodyattachmentpanel_populate_model_combo_line_222_2186666a_native();
const NativeFunctionImplementation& qtbodyattachmentpanel_emit_attach_line_231_cddba835_native();
const NativeFunctionImplementation& qtbodyattachmentpanel_set_slot_text_line_238_da26a40d_native();
const NativeFunctionImplementation& qtbodyattachmentpanel_refresh_layers_line_247_ae6a7c13_native();
const NativeFunctionImplementation& qtbodyattachmentpanel_sync_selected_layer_line_273_b273ddea_native();
const NativeFunctionImplementation& qtbodyattachmentpanel_handle_layer_selection_changed_line_287_932184ba_native();
const NativeFunctionImplementation& qtbodyattachmentpanel_handle_mode_changed_line_295_c1f7e0ae_native();
const NativeFunctionImplementation& qtbodyattachmentpanel_layer_rows_line_298_45a17258_native();
const NativeFunctionImplementation& basworkflowmixin_handle_bas_mode_changed_line_30_463782ec_native();
const NativeFunctionImplementation& basworkflowmixin_bas_mode_for_model_line_45_637e5673_native();
const NativeFunctionImplementation& basworkflowmixin_handle_bas_attach_requested_line_52_b913d353_native();
const NativeFunctionImplementation& basworkflowmixin_handle_bas_clear_requested_line_113_d2c28306_native();
const NativeFunctionImplementation& basworkflowmixin_refresh_bas_animation_panel_after_layer_change_line_128_4f5f1e4b_native();
const NativeFunctionImplementation& basworkflowmixin_load_bas_attachment_model_line_143_816e89a5_native();
const NativeFunctionImplementation& basworkflowmixin_rebuild_bas_preview_line_156_0cf1b9d1_native();
const NativeFunctionImplementation& basworkflowmixin_handle_bas_save_build_requested_line_189_eb9b7858_native();
const NativeFunctionImplementation& basworkflowmixin_save_bas_model_recipe_line_216_1bfdd376_native();
const NativeFunctionImplementation& basworkflowmixin_reset_bas_model_node_traversal_line_236_e55ba05c_native();
const NativeFunctionImplementation& basworkflowmixin_attach_bas_item_to_preview_line_251_3842565e_native();
const NativeFunctionImplementation& basworkflowmixin_bas_layer_transform_from_model_line_281_d639e093_native();
const NativeFunctionImplementation& basworkflowmixin_apply_bas_layer_transform_line_295_c1f51d6a_native();
const NativeFunctionImplementation& basworkflowmixin_prepare_bas_layer_root_line_314_fa1500b9_native();
const NativeFunctionImplementation& basworkflowmixin_tag_bas_attachment_subtree_line_328_e5c46d12_native();
const NativeFunctionImplementation& basworkflowmixin_find_model_node_line_344_a8e7b853_native();
const NativeFunctionImplementation& basworkflowmixin_bas_socket_for_slot_line_355_b5dcdf49_native();
const NativeFunctionImplementation& basworkflowmixin_bas_target_scene_object_line_358_4eeb7693_native();
const NativeFunctionImplementation& basworkflowmixin_apply_bas_preview_to_viewport_line_384_50d3d7fb_native();
const NativeFunctionImplementation& basworkflowmixin_sync_bas_body_animation_engine_line_427_2a6ea634_native();
const NativeFunctionImplementation& basworkflowmixin_restore_bas_animation_pose_after_viewport_refresh_line_465_ee920908_native();
const NativeFunctionImplementation& basworkflowmixin_request_bas_viewport_refresh_line_485_7bbd9071_native();

const NativeFunctionImplementation* instancemethods_native_functions(std::size_t& count);

} // namespace ghostrigger::tools::workflow::bodyattachmentsystem
