#pragma once

#include <cstddef>

namespace ghostrigger::native_host {

struct NativeDependencySpec {
    const wchar_t* name;
    const wchar_t* dll_name;
    const char* version_export;
    const char* capabilities_export;
};

inline constexpr NativeDependencySpec kNativeDependencySpecs[] = {
    {L"GhostRigger.Adapters.Files", L"GhostRigger.Adapters.Files.dll", "gr_adapters_files_version", "gr_adapters_files_capabilities_json"},
    {L"GhostRigger.Adapters.GPU", L"GhostRigger.Adapters.GPU.dll", "gr_adapters_gpu_version", "gr_adapters_gpu_capabilities_json"},
    {L"GhostRigger.Adapters.QtAutorig", L"GhostRigger.Adapters.QtAutorig.dll", "gr_adapters_qt_autorig_version", "gr_adapters_qt_autorig_capabilities_json"},
    {L"GhostRigger.Adapters.QtIPC", L"GhostRigger.Adapters.QtIPC.dll", "gr_adapters_qt_ipc_version", "gr_adapters_qt_ipc_capabilities_json"},
    {L"GhostRigger.Adapters.QtViewport", L"GhostRigger.Adapters.QtViewport.dll", "gr_adapters_qt_viewport_version", "gr_adapters_qt_viewport_capabilities_json"},
    {L"GhostRigger.Adapters.Rendering", L"GhostRigger.Adapters.Rendering.dll", "gr_adapters_rendering_version", "gr_adapters_rendering_capabilities_json"},
    {L"GhostRigger.Adapters.Scripts", L"GhostRigger.Adapters.Scripts.dll", "gr_adapters_scripts_version", "gr_adapters_scripts_capabilities_json"},
    {L"GhostRigger.Animation", L"GhostRigger.Animation.dll", "gr_animation_version", "gr_animation_capabilities_json"},
    {L"GhostRigger.AnimationRetargeting", L"GhostRigger.AnimationRetargeting.dll", "gr_animation_retargeting_version", "gr_animation_retargeting_capabilities_json"},
    {L"GhostRigger.Assets", L"GhostRigger.Assets.dll", "gr_assets_version", "gr_assets_capabilities_json"},
    {L"GhostRigger.Autorig", L"GhostRigger.Autorig.dll", "gr_autorig_version", "gr_autorig_capabilities_json"},
    {L"GhostRigger.Camera", L"GhostRigger.Camera.dll", "gr_camera_version", "gr_camera_capabilities_json"},
    {L"GhostRigger.Characters", L"GhostRigger.Characters.dll", "gr_characters_version", "gr_characters_capabilities_json"},
    {L"GhostRigger.Converters", L"GhostRigger.Converters.dll", "gr_converters_version", "gr_converters_capabilities_json"},
    {L"GhostRigger.Diagnostics", L"GhostRigger.Diagnostics.dll", "gr_diagnostics_version", "gr_diagnostics_capabilities_json"},
    {L"GhostRigger.Export", L"GhostRigger.Export.dll", "gr_export_version", "gr_export_capabilities_json"},
    {L"GhostRigger.Formats", L"GhostRigger.Formats.dll", "gr_formats_version", "gr_formats_capabilities_json"},
    {L"GhostRigger.GUI.Camera", L"GhostRigger.GUI.Camera.dll", "gr_gui_camera_version", "gr_gui_camera_capabilities_json"},
    {L"GhostRigger.GUI.Dialogs", L"GhostRigger.GUI.Dialogs.dll", "gr_gui_dialogs_version", "gr_gui_dialogs_capabilities_json"},
    {L"GhostRigger.GUI.Gizmo", L"GhostRigger.GUI.Gizmo.dll", "gr_gui_gizmo_version", "gr_gui_gizmo_capabilities_json"},
    {L"GhostRigger.GUI.Integration", L"GhostRigger.GUI.Integration.dll", "gr_gui_integration_version", "gr_gui_integration_capabilities_json"},
    {L"GhostRigger.GUI.Lighting", L"GhostRigger.GUI.Lighting.dll", "gr_gui_lighting_version", "gr_gui_lighting_capabilities_json"},
    {L"GhostRigger.GUI.Panels", L"GhostRigger.GUI.Panels.dll", "gr_gui_panels_version", "gr_gui_panels_capabilities_json"},
    {L"GhostRigger.GUI.Rendering", L"GhostRigger.GUI.Rendering.dll", "gr_gui_rendering_version", "gr_gui_rendering_capabilities_json"},
    {L"GhostRigger.GUI.SequenceEditor", L"GhostRigger.GUI.SequenceEditor.dll", "gr_gui_sequence_editor_version", "gr_gui_sequence_editor_capabilities_json"},
    {L"GhostRigger.GUI.Textures", L"GhostRigger.GUI.Textures.dll", "gr_gui_textures_version", "gr_gui_textures_capabilities_json"},
    {L"GhostRigger.GUI.Theme", L"GhostRigger.GUI.Theme.dll", "gr_gui_theme_version", "gr_gui_theme_capabilities_json"},
    {L"GhostRigger.GUI.Viewports", L"GhostRigger.GUI.Viewports.dll", "gr_gui_viewports_version", "gr_gui_viewports_capabilities_json"},
    {L"GhostRigger.Game", L"GhostRigger.Game.dll", "gr_game_version", "gr_game_capabilities_json"},
    {L"GhostRigger.GameLibrary", L"GhostRigger.GameLibrary.dll", "gr_game_library_version", "gr_game_library_capabilities_json"},
    {L"GhostRigger.Geometry", L"GhostRigger.Geometry.dll", "gr_geometry_version", "gr_geometry_capabilities_json"},
    {L"GhostRigger.Gizmo", L"GhostRigger.Gizmo.dll", "gr_gizmo_version", "gr_gizmo_capabilities_json"},
    {L"GhostRigger.Graphics", L"GhostRigger.Graphics.dll", "gr_graphics_version", "gr_graphics_capabilities_json"},
    {L"GhostRigger.IO", L"GhostRigger.IO.dll", "gr_io_version", "gr_io_capabilities_json"},
    {L"GhostRigger.IPC", L"GhostRigger.IPC.dll", "gr_ipc_version", "gr_ipc_capabilities_json"},
    {L"GhostRigger.Infra", L"GhostRigger.Infra.dll", "gr_infra_version", "gr_infra_capabilities_json"},
    {L"GhostRigger.KotorMCP", L"GhostRigger.KotorMCP.dll", "gr_kotor_mcp_version", "gr_kotor_mcp_capabilities_json"},
    {L"GhostRigger.Level", L"GhostRigger.Level.dll", "gr_level_version", "gr_level_capabilities_json"},
    {L"GhostRigger.Lighting", L"GhostRigger.Lighting.dll", "gr_lighting_version", "gr_lighting_capabilities_json"},
    {L"GhostRigger.MDL", L"GhostRigger.MDL.dll", "gr_mdl_version", "gr_mdl_capabilities_json"},
    {L"GhostRigger.Math", L"GhostRigger.Math.dll", "gr_math_version", "gr_math_capabilities_json"},
    {L"GhostRigger.Measurement", L"GhostRigger.Measurement.dll", "gr_measurement_version", "gr_measurement_capabilities_json"},
    {L"GhostRigger.MeshTools", L"GhostRigger.MeshTools.dll", "gr_mesh_tools_version", "gr_mesh_tools_capabilities_json"},
    {L"GhostRigger.Modules", L"GhostRigger.Modules.dll", "gr_modules_version", "gr_modules_capabilities_json"},
    {L"GhostRigger.Native.NativeCore", L"GhostRigger.Native.NativeCore.dll", "gr_native_core_version", "gr_native_core_capabilities_json"},
    {L"GhostRigger.Native.NativeCore.Diagnostics", L"GhostRigger.Native.NativeCore.Diagnostics.dll", "gr_native_core_diagnostics_version", "gr_native_core_diagnostics_capabilities_json"},
    {L"GhostRigger.Native.NativeCore.Math", L"GhostRigger.Native.NativeCore.Math.dll", "gr_native_core_math_version", "gr_native_core_math_capabilities_json"},
    {L"GhostRigger.Ports", L"GhostRigger.Ports.dll", "gr_ports_version", "gr_ports_capabilities_json"},
    {L"GhostRigger.Project", L"GhostRigger.Project.dll", "gr_project_version", "gr_project_capabilities_json"},
    {L"GhostRigger.Renderer.Contracts", L"GhostRigger.Renderer.Contracts.dll", "gr_renderer_contracts_version", "gr_renderer_contracts_capabilities_json"},
    {L"GhostRigger.Renderer.D3D12", L"GhostRigger.Renderer.D3D12.dll", "gr_renderer_d3d12_version", "gr_renderer_d3d12_capabilities_json"},
    {L"GhostRigger.Renderer.ModernGL", L"GhostRigger.Renderer.ModernGL.dll", "gr_renderer_moderngl_version", "gr_renderer_moderngl_capabilities_json"},
    {L"GhostRigger.Renderer.Null", L"GhostRigger.Renderer.Null.dll", "gr_renderer_null_version", "gr_renderer_null_capabilities_json"},
    {L"GhostRigger.Renderer.PyGFX", L"GhostRigger.Renderer.PyGFX.dll", "gr_renderer_pygfx_version", "gr_renderer_pygfx_capabilities_json"},
    {L"GhostRigger.Rendering", L"GhostRigger.Rendering.dll", "gr_rendering_version", "gr_rendering_capabilities_json"},
    {L"GhostRigger.Resources", L"GhostRigger.Resources.dll", "gr_resources_version", "gr_resources_capabilities_json"},
    {L"GhostRigger.Retargeting", L"GhostRigger.Retargeting.dll", "gr_retargeting_version", "gr_retargeting_capabilities_json"},
    {L"GhostRigger.Runtime", L"GhostRigger.Runtime.dll", "gr_runtime_version", ""},
    {L"GhostRigger.Runtime.Shared.Contracts", L"GhostRigger.Runtime.Shared.Contracts.dll", "gr_runtime_shared_contracts_version", "gr_runtime_shared_contracts_capabilities_json"},
    {L"GhostRigger.Runtime.Shared.Descriptors", L"GhostRigger.Runtime.Shared.Descriptors.dll", "gr_runtime_shared_descriptors_version", "gr_runtime_shared_descriptors_capabilities_json"},
    {L"GhostRigger.Runtime.Shared.Resources", L"GhostRigger.Runtime.Shared.Resources.dll", "gr_runtime_shared_resources_version", "gr_runtime_shared_resources_capabilities_json"},
    {L"GhostRigger.Scene", L"GhostRigger.Scene.dll", "gr_scene_version", "gr_scene_capabilities_json"},
    {L"GhostRigger.Sequence", L"GhostRigger.Sequence.dll", "gr_sequence_version", "gr_sequence_capabilities_json"},
    {L"GhostRigger.Skeleton", L"GhostRigger.Skeleton.dll", "gr_skeleton_version", "gr_skeleton_capabilities_json"},
    {L"GhostRigger.Special", L"GhostRigger.Special.dll", "gr_special_version", "gr_special_capabilities_json"},
    {L"GhostRigger.Systems.BAS", L"GhostRigger.Systems.BAS.dll", "gr_systems_bas_version", "gr_systems_bas_capabilities_json"},
    {L"GhostRigger.Templates", L"GhostRigger.Templates.dll", "gr_templates_version", "gr_templates_capabilities_json"},
    {L"GhostRigger.Tools.BodyAttachmentSystem", L"GhostRigger.Tools.BodyAttachmentSystem.dll", "gr_tools_body_attachment_system_version", "gr_tools_body_attachment_system_capabilities_json"},
    {L"GhostRigger.Tools.Camera", L"GhostRigger.Tools.Camera.dll", "gr_tools_camera_version", "gr_tools_camera_capabilities_json"},
    {L"GhostRigger.Tools.CharacterBuilder", L"GhostRigger.Tools.CharacterBuilder.dll", "gr_tools_character_builder_version", "gr_tools_character_builder_capabilities_json"},
    {L"GhostRigger.Tools.ContentBrowser", L"GhostRigger.Tools.ContentBrowser.dll", "gr_tools_content_browser_version", "gr_tools_content_browser_capabilities_json"},
    {L"GhostRigger.Tools.Export", L"GhostRigger.Tools.Export.dll", "gr_tools_export_version", "gr_tools_export_capabilities_json"},
    {L"GhostRigger.Tools.Lighting", L"GhostRigger.Tools.Lighting.dll", "gr_tools_lighting_version", "gr_tools_lighting_capabilities_json"},
    {L"GhostRigger.Tools.ModuleMeshes", L"GhostRigger.Tools.ModuleMeshes.dll", "gr_tools_module_meshes_version", "gr_tools_module_meshes_capabilities_json"},
    {L"GhostRigger.Tools.NodesSkeletonBrowser", L"GhostRigger.Tools.NodesSkeletonBrowser.dll", "gr_tools_nodes_skeleton_browser_version", "gr_tools_nodes_skeleton_browser_capabilities_json"},
    {L"GhostRigger.Tools.PivotControls", L"GhostRigger.Tools.PivotControls.dll", "gr_tools_pivot_controls_version", "gr_tools_pivot_controls_capabilities_json"},
    {L"GhostRigger.Tools.Properties", L"GhostRigger.Tools.Properties.dll", "gr_tools_properties_version", "gr_tools_properties_capabilities_json"},
    {L"GhostRigger.Tools.ResourceBrowser", L"GhostRigger.Tools.ResourceBrowser.dll", "gr_tools_resource_browser_version", "gr_tools_resource_browser_capabilities_json"},
    {L"GhostRigger.Tools.Retargeting", L"GhostRigger.Tools.Retargeting.dll", "gr_tools_retargeting_version", "gr_tools_retargeting_capabilities_json"},
    {L"GhostRigger.Tools.SceneInformation", L"GhostRigger.Tools.SceneInformation.dll", "gr_tools_scene_information_version", "gr_tools_scene_information_capabilities_json"},
    {L"GhostRigger.Tools.SequenceEditor", L"GhostRigger.Tools.SequenceEditor.dll", "gr_tools_sequence_editor_version", "gr_tools_sequence_editor_capabilities_json"},
    {L"GhostRigger.Tools.SpriteMaterials", L"GhostRigger.Tools.SpriteMaterials.dll", "gr_tools_sprite_materials_version", "gr_tools_sprite_materials_capabilities_json"},
    {L"GhostRigger.Tools.TwoDABrowser", L"GhostRigger.Tools.TwoDABrowser.dll", "gr_tools_two_da_browser_version", "gr_tools_two_da_browser_capabilities_json"},
    {L"GhostRigger.Unreal", L"GhostRigger.Unreal.dll", "gr_unreal_version", "gr_unreal_capabilities_json"},
    {L"GhostRigger.Validation", L"GhostRigger.Validation.dll", "gr_validation_version", "gr_validation_capabilities_json"},
    {L"GhostRigger.Walkmesh", L"GhostRigger.Walkmesh.dll", "gr_walkmesh_version", "gr_walkmesh_capabilities_json"},
    {L"GhostRigger.Windows.AnimationRetargetWorkbench", L"GhostRigger.Windows.AnimationRetargetWorkbench.dll", "gr_windows_animation_retarget_workbench_version", "gr_windows_animation_retarget_workbench_capabilities_json"},
    {L"GhostRigger.Windows.LegacyRiggingWindow", L"GhostRigger.Windows.LegacyRiggingWindow.dll", "gr_windows_legacy_rigging_window_version", "gr_windows_legacy_rigging_window_capabilities_json"},
    {L"GhostRigger.Windows.LevelEditor", L"GhostRigger.Windows.LevelEditor.dll", "gr_windows_level_editor_version", "gr_windows_level_editor_capabilities_json"},
    {L"GhostRigger.Windows.MainWindow", L"GhostRigger.Windows.MainWindow.dll", "gr_windows_main_window_version", "gr_windows_main_window_capabilities_json"},
    {L"GhostRigger.Windows.UnrealAnimatorWindow", L"GhostRigger.Windows.UnrealAnimatorWindow.dll", "gr_windows_unreal_animator_window_version", "gr_windows_unreal_animator_window_capabilities_json"},
    {L"GhostRigger.Workbench", L"GhostRigger.Workbench.dll", "gr_workbench_version", "gr_workbench_capabilities_json"},
    {L"GhostRigger.Workflow", L"GhostRigger.Workflow.dll", "gr_workflow_version", "gr_workflow_capabilities_json"},
};

inline constexpr std::size_t kNativeDependencySpecCount = sizeof(kNativeDependencySpecs) / sizeof(kNativeDependencySpecs[0]);

} // namespace ghostrigger::native_host
