#pragma once

#include <cstddef>

namespace ghostrigger::domain::core::scene {

#ifndef GHOSTRIGGER_SCENE_NATIVE_FUNCTION_IMPLEMENTATION_DEFINED
#define GHOSTRIGGER_SCENE_NATIVE_FUNCTION_IMPLEMENTATION_DEFINED
struct NativeFunctionImplementation {
    const char* project;
    const char* native_namespace;
    const char* python_file;
    const char* qualname;
    const char* callable_type;
    const char* implementation_status;
    bool native_first;
    bool python_runtime_required;
    bool python_fallback_allowed;
    const char* contract_json;
};
#endif // GHOSTRIGGER_SCENE_NATIVE_FUNCTION_IMPLEMENTATION_DEFINED

const NativeFunctionImplementation& transformreferencecontroller_construct_line_98_fb543c88_native();
const NativeFunctionImplementation& transformreferencecontroller_set_axis_mode_line_103_2955bef9_native();
const NativeFunctionImplementation& transformreferencecontroller_get_axis_mode_line_109_3e8b0906_native();
const NativeFunctionImplementation& transformreferencecontroller_get_transform_basis_line_112_787c9f27_native();
const NativeFunctionImplementation& transformreferencecontroller_get_gizmo_orientation_line_132_f1e2319a_native();
const NativeFunctionImplementation& transformreferencecontroller_resolve_pick_reference_line_135_9bf0d575_native();
const NativeFunctionImplementation& transformreferencecontroller_clear_pick_reference_line_139_515a9c4c_native();
const NativeFunctionImplementation& transformreferencecontroller_picked_reference_line_142_ad668aad_native();
const NativeFunctionImplementation& transformreferencecontroller_set_working_basis_line_145_a5b720a0_native();
const NativeFunctionImplementation& transformreferencecontroller_object_basis_line_148_d7d6708d_native();
const NativeFunctionImplementation& transformreferencecontroller_reference_is_deleted_line_159_633805a7_native();
const NativeFunctionImplementation& kmaxscene_all_objects_line_48_c34d0250_native();
const NativeFunctionImplementation& kmaxscene_sync_collections_line_55_1228fe53_native();
const NativeFunctionImplementation& kmaxscene_mark_dirty_line_80_2ccc144f_native();
const NativeFunctionImplementation& kmaxscene_mark_clean_line_84_2cccded8_native();
const NativeFunctionImplementation& kmaxscenemanager_construct_line_23_72059f48_native();
const NativeFunctionImplementation& kmaxscenemanager_create_new_scene_line_26_9dc7bd88_native();
const NativeFunctionImplementation& kmaxscenemanager_clear_scene_line_30_05d78b52_native();
const NativeFunctionImplementation& kmaxscenemanager_load_kmax_line_36_67d70b56_native();
const NativeFunctionImplementation& kmaxscenemanager_save_kmax_line_40_f90d97d8_native();
const NativeFunctionImplementation& kmaxscenemanager_save_kmax_as_line_46_cbccae78_native();
const NativeFunctionImplementation& kmaxscenemanager_mark_dirty_line_49_b2022f95_native();
const NativeFunctionImplementation& kmaxscenemanager_is_dirty_line_52_0e4ba05a_native();
const NativeFunctionImplementation& kmaxscenemanager_add_model_instance_line_55_ad20d879_native();
const NativeFunctionImplementation& kmaxscenemanager_add_camera_object_line_86_f83ac88c_native();
const NativeFunctionImplementation& kmaxscenemanager_add_light_object_line_131_ecf7b70b_native();
const NativeFunctionImplementation& kmaxscenemanager_remove_object_line_179_e57500f4_native();
const NativeFunctionImplementation& kmaxscenemanager_remove_camera_object_line_188_b2f683e2_native();
const NativeFunctionImplementation& kmaxscenemanager_remove_light_object_line_192_2c8dc840_native();
const NativeFunctionImplementation& kmaxscenemanager_duplicate_object_line_196_53201c6e_native();
const NativeFunctionImplementation& kmaxscenemanager_duplicate_camera_object_line_213_cbdd7334_native();
const NativeFunctionImplementation& kmaxscenemanager_duplicate_light_object_line_217_289c0e7b_native();
const NativeFunctionImplementation& kmaxscenemanager_select_object_line_221_4ea2ef9c_native();
const NativeFunctionImplementation& kmaxscenemanager_clear_selection_line_228_9aa42c89_native();
const NativeFunctionImplementation& kmaxscenemanager_get_selected_objects_line_238_94640ea7_native();
const NativeFunctionImplementation& kmaxscenemanager_get_scene_objects_line_241_79efcdf6_native();
const NativeFunctionImplementation& kmaxscenemanager_serialize_scene_line_244_1bca1563_native();
const NativeFunctionImplementation& kmaxscenemanager_deserialize_scene_line_247_66b5c940_native();
const NativeFunctionImplementation& kmaxscenemanager_rename_object_line_252_53745c59_native();
const NativeFunctionImplementation& kmaxscenemanager_set_object_visibility_line_263_51a5ca42_native();
const NativeFunctionImplementation& kmaxscenemanager_set_object_locked_line_273_3cedde68_native();
const NativeFunctionImplementation& kmaxscenemanager_update_camera_properties_line_283_5ff93207_native();
const NativeFunctionImplementation& kmaxscenemanager_update_light_properties_line_302_51d6c48a_native();
const NativeFunctionImplementation& kmaxscenemanager_update_object_transform_line_327_fcd5fb99_native();
const NativeFunctionImplementation& kmaxscenemanager_update_object_pivot_line_349_5b198df4_native();
const NativeFunctionImplementation& kmaxscenemanager_find_object_line_372_b5ecdbde_native();
const NativeFunctionImplementation& kmaxscenemanager_unique_object_name_line_375_b0fa066c_native();
const NativeFunctionImplementation& kmaxscenemanager_next_asset_name_line_385_e24cff49_native();
const NativeFunctionImplementation& kmaxscenemanager_sync_asset_metadata_from_object_line_437_237a5221_native();
const NativeFunctionImplementation& kmaxscenemanager_retarget_asset_metadata_line_470_a46e93bf_native();
const NativeFunctionImplementation& kmaxvalidationresult_add_error_line_18_837c265b_native();
const NativeFunctionImplementation& kmaxvalidationresult_add_warning_line_22_34a7df14_native();
const NativeFunctionImplementation& moduleroomplacement_to_metadata_line_29_7258d94f_native();
const NativeFunctionImplementation& plane_normalize_line_89_f39e33da_native();
const NativeFunctionImplementation& plane_distance_to_point_line_96_a2461415_native();
const NativeFunctionImplementation& frustum_construct_line_127_01bff540_native();
const NativeFunctionImplementation& frustum_update_from_matrix_line_130_28e625a5_native();
const NativeFunctionImplementation& frustum_update_from_camera_line_154_2d8582b9_native();
const NativeFunctionImplementation& frustum_test_sphere_line_232_b1ad6096_native();
const NativeFunctionImplementation& frustum_test_aabb_line_243_7b6a60be_native();
const NativeFunctionImplementation& frustum_is_trivially_disabled_line_260_9d3b4e19_native();
const NativeFunctionImplementation& areproperties_ambient_float_line_376_048edaa3_native();
const NativeFunctionImplementation& areproperties_fog_color_float_line_381_08eb70a7_native();
const NativeFunctionImplementation& areproperties_has_grass_line_385_b70ccdfb_native();
const NativeFunctionImplementation& scenegraph_construct_line_417_ec5ce4b3_native();
const NativeFunctionImplementation& scenegraph_add_room_line_430_1c375049_native();
const NativeFunctionImplementation& scenegraph_room_by_name_line_433_cf1cce0f_native();
const NativeFunctionImplementation& scenegraph_set_vis_data_line_440_b288dd35_native();
const NativeFunctionImplementation& scenegraph_set_current_room_line_448_9c3cf495_native();
const NativeFunctionImplementation& scenegraph_detect_current_room_line_456_b841f6a7_native();
const NativeFunctionImplementation& scenegraph_visible_rooms_line_491_86b13421_native();
const NativeFunctionImplementation& scenegraph_rooms_all_visible_line_535_b0f35489_native();
const NativeFunctionImplementation& scenegraph_set_all_rooms_visible_line_539_4c62b259_native();
const NativeFunctionImplementation& scenegraph_toggle_room_line_543_193d3124_native();
const NativeFunctionImplementation& scenegraph_objects_of_type_line_551_e91e5111_native();
const NativeFunctionImplementation& scenegraph_objects_in_room_line_554_991bef38_native();
const NativeFunctionImplementation& scenegraph_objects_near_line_558_856af220_native();
const NativeFunctionImplementation& scenegraph_assign_objects_to_rooms_line_570_843da9cb_native();
const NativeFunctionImplementation& scenegraph_summary_line_591_e2b447fe_native();
const NativeFunctionImplementation& scenemanager_build_scene_line_622_bc1d586d_native();
const NativeFunctionImplementation& scenemanager_load_git_objects_line_702_76cdbd68_native();
const NativeFunctionImplementation& scenemanager_load_room_models_line_762_c18f93ff_native();
const NativeFunctionImplementation& scenemanager_update_room_bounds_line_790_7cee2ced_native();
const NativeFunctionImplementation& modellookup_construct_line_840_136abe19_native();
const NativeFunctionImplementation& modellookup_creature_model_line_844_ff5682c7_native();
const NativeFunctionImplementation& modellookup_placeable_model_line_855_24d7ef00_native();
const NativeFunctionImplementation& modellookup_door_model_line_860_af639bf6_native();
const NativeFunctionImplementation& charactersceneregistry_construct_line_898_a8a3dd03_native();
const NativeFunctionImplementation& charactersceneregistry_register_line_906_0a037122_native();
const NativeFunctionImplementation& charactersceneregistry_unregister_line_928_c5418159_native();
const NativeFunctionImplementation& charactersceneregistry_get_line_940_bdb926a6_native();
const NativeFunctionImplementation& charactersceneregistry_get_by_alias_line_945_23809c94_native();
const NativeFunctionImplementation& charactersceneregistry_set_alias_line_951_a7aa5a48_native();
const NativeFunctionImplementation& charactersceneregistry_list_scenes_line_960_7fff0942_native();
const NativeFunctionImplementation& charactersceneregistry_list_aliases_line_965_df934c03_native();
const NativeFunctionImplementation& charactersceneregistry_len_line_970_1444c8a8_native();
const NativeFunctionImplementation& charactersceneregistry_clear_line_974_b2d1f352_native();
const NativeFunctionImplementation& sceneframerenderer_construct_line_1069_a6717535_native();
const NativeFunctionImplementation& sceneframerenderer_set_scene_line_1081_9a646288_native();
const NativeFunctionImplementation& sceneframerenderer_set_room_visible_line_1088_52b5a66b_native();
const NativeFunctionImplementation& sceneframerenderer_clear_visibility_overrides_line_1092_cc2a39fd_native();
const NativeFunctionImplementation& sceneframerenderer_build_draw_list_line_1098_f46bf922_native();
const NativeFunctionImplementation& sceneframerenderer_all_room_names_line_1189_3a3d2bfd_native();
const NativeFunctionImplementation& sceneframerenderer_room_count_line_1198_7d73145c_native();
const NativeFunctionImplementation& sceneframerenderer_object_count_line_1202_ccf667d5_native();
const NativeFunctionImplementation& sceneframerenderer_are_properties_line_1213_a69944dd_native();
const NativeFunctionImplementation& scenemanifest_to_dict_line_19_264bedf5_native();
const NativeFunctionImplementation& transform_to_dict_line_27_0e4c5c8d_native();
const NativeFunctionImplementation& pivotdata_position_line_58_a41b1041_native();
const NativeFunctionImplementation& pivotdata_rotation_line_66_052837bd_native();
const NativeFunctionImplementation& pivotdata_is_valid_line_69_52cd01cc_native();
const NativeFunctionImplementation& pivotdata_sanitized_line_73_9bbd75d0_native();
const NativeFunctionImplementation& pivotdata_to_dict_line_78_3048ea00_native();
const NativeFunctionImplementation& sceneobjectinstance_to_dict_line_27_564c9705_native();
const NativeFunctionImplementation& sceneresourceref_to_dict_line_25_2c240522_native();

const NativeFunctionImplementation* instancemethods_native_functions(std::size_t& count);

} // namespace ghostrigger::domain::core::scene
