#pragma once

#include <cstddef>

namespace ghostrigger::phase15::ghostrigger_geometry {

using PythonFunctionDescriptorJson = const char* (*)();

struct PythonFunctionDescriptorEntry {
    const char* python_file;
    const char* qualname;
    const char* function_type;
    PythonFunctionDescriptorJson descriptor_json;
};

const char* src_core_geometry_model_data_vertexskindata_normalize_line_655_adabe2a1_descriptor_json();
const char* src_core_geometry_model_data_vertexskindata_to_packed_line_661_f2afdae3_descriptor_json();
const char* src_core_geometry_model_data_modelnode_compute_bounds_line_906_b54f13bd_descriptor_json();
const char* src_core_geometry_model_data_modelnode_world_position_line_920_3212a140_descriptor_json();
const char* src_core_geometry_model_data_modelnode_bone_world_position_line_985_2e0a3ca1_descriptor_json();
const char* src_core_geometry_model_data_modelnode_world_transform_line_1034_ff665d1c_descriptor_json();
const char* src_core_geometry_model_data_modelnode_compute_tangents_line_1083_3ddc0c29_descriptor_json();
const char* src_core_geometry_model_data_modelnode_compute_tangents_line_1179_9c622130_descriptor_json();
const char* src_core_geometry_model_data_modelnode_clone_shallow_line_1276_eea38d74_descriptor_json();
const char* src_core_geometry_model_data_supermodelchain_loaded_models_line_1357_c862f246_descriptor_json();
const char* src_core_geometry_model_data_kotormodel_all_nodes_line_1427_dd483f08_descriptor_json();
const char* src_core_geometry_model_data_kotormodel_mesh_nodes_line_1456_9a385185_descriptor_json();
const char* src_core_geometry_model_data_kotormodel_bone_nodes_line_1459_92284c78_descriptor_json();
const char* src_core_geometry_model_data_kotormodel_find_node_line_1471_a4f9dc4c_descriptor_json();
const char* src_core_geometry_model_data_kotormodel_compute_all_tangents_line_1477_50105b62_descriptor_json();
const char* src_core_geometry_model_data_kotormodel_compute_bounds_line_1502_03f3f4b2_descriptor_json();
const char* src_core_geometry_model_data_kotormodel_render_bounds_line_1550_96e90d04_descriptor_json();
const char* src_core_geometry_model_data_kotormodel_node_count_line_1690_5ba7ecd1_descriptor_json();
const char* src_core_geometry_model_data_kotormodel_texture_list_line_1693_818b2b0c_descriptor_json();
const char* src_core_geometry_model_data_kotormodel_compute_all_tangents_legacy_line_1702_065c0bf0_descriptor_json();
const char* src_core_geometry_model_data_sceneslot_post_init_line_1792_5550caed_descriptor_json();
const char* src_core_geometry_model_data_characterscene_post_init_line_1853_0ced5b3c_descriptor_json();
const char* src_core_geometry_model_data_characterscene_recompute_mode_line_1864_a56b9830_descriptor_json();
const char* src_core_geometry_model_data_characterscene_set_mode_line_1924_c8431a53_descriptor_json();
const char* src_core_geometry_model_data_characterscene_unlock_mode_line_1940_f348b0d5_descriptor_json();
const char* src_core_geometry_model_data_characterscene_assign_line_1947_e1004bec_descriptor_json();
const char* src_core_geometry_model_data_characterscene_clear_slot_line_1979_a0caa73f_descriptor_json();
const char* src_core_geometry_model_data_characterscene_get_line_1986_f188529f_descriptor_json();
const char* src_core_geometry_model_data_characterscene_get_model_line_1990_804798c8_descriptor_json();
const char* src_core_geometry_model_data_characterscene_mark_clean_line_2019_4fa7fd2a_descriptor_json();
const char* src_core_geometry_model_data_characterscene_asset_id_for_line_2025_7db1e454_descriptor_json();
const char* src_core_geometry_model_data_characterscene_summary_line_2030_6cff1d6c_descriptor_json();
const char* src_core_geometry_model_data_characterscene_to_dict_line_2083_38492785_descriptor_json();
const char* src_core_geometry_model_data_characterscene_to_json_line_2308_675ed452_descriptor_json();

const PythonFunctionDescriptorEntry* instancemethods_descriptors(std::size_t& count);

} // namespace ghostrigger::phase15::ghostrigger_geometry
