#pragma once

#include <cstddef>

namespace ghostrigger::phase15::ghostrigger_geometry {

using PythonFunctionDescriptorJson = const char* (*)();

struct PythonFunctionDescriptorEntry {
    const char* python_file;
    const char* qualname;
    const char* function_type;
    PythonFunctionDescriptorJson descriptor_json;
};

const char* src_core_geometry_lightsaber_clean_line_76_f321d73c_descriptor_json();
const char* src_core_geometry_lightsaber_finite_vertex3_line_80_03c6de23_descriptor_json();
const char* src_core_geometry_lightsaber_context_text_line_90_d00ccc79_descriptor_json();
const char* src_core_geometry_lightsaber_lightsaber_blade_color_choices_line_104_5528abd2_descriptor_json();
const char* src_core_geometry_lightsaber_normalize_color_id_line_110_4e936914_descriptor_json();
const char* src_core_geometry_lightsaber_iter_model_nodes_line_124_a7b9943e_descriptor_json();
const char* src_core_geometry_lightsaber_is_lightsaber_model_line_149_18b9cc63_descriptor_json();
const char* src_core_geometry_lightsaber_lightsaber_blade_color_override_line_160_6643984f_descriptor_json();
const char* src_core_geometry_lightsaber_set_lightsaber_blade_color_override_line_177_e97c18d0_descriptor_json();
const char* src_core_geometry_lightsaber_is_lightsaber_blade_node_line_200_9393d26d_descriptor_json();
const char* src_core_geometry_lightsaber_lightsaber_blade_emissive_rgb_line_217_dc1263cd_descriptor_json();
const char* src_core_geometry_lightsaber_lightsaber_blade_diffuse_rgb_line_235_4c91e4e2_descriptor_json();
const char* src_core_geometry_lightsaber_lightsaber_blade_texture_cache_key_line_242_cd61c4d8_descriptor_json();
const char* src_core_geometry_lightsaber_should_use_procedural_lightsaber_blade_texture_line_249_dc275bb1_descriptor_json();
const char* src_core_geometry_lightsaber_lightsaber_blade_procedural_rgba8_line_264_1fd5beb6_descriptor_json();
const char* src_core_geometry_lightsaber_synthetic_lightsaber_blade_uvs_line_326_8da84fa2_descriptor_json();
const char* src_core_geometry_lightsaber_lightsaber_blade_preview_quad_line_368_d623df31_descriptor_json();
const char* src_core_geometry_map_snap_tools_import_lyt_room_graph_line_84_4b8a864f_descriptor_json();
const char* src_core_geometry_map_snap_tools_normalise_resref_line_91_4cad19d1_descriptor_json();
const char* src_core_geometry_map_snap_tools_module_from_input_line_95_d90f927c_descriptor_json();
const char* src_core_geometry_map_snap_tools_distance_line_99_74569af9_descriptor_json();
const char* src_core_geometry_map_snap_tools_sub_line_106_38fcd35b_descriptor_json();
const char* src_core_geometry_map_snap_tools_add_line_110_163b327d_descriptor_json();
const char* src_core_geometry_map_snap_tools_round_to_grid_line_114_641a32df_descriptor_json();
const char* src_core_geometry_map_snap_tools_snap_position_to_grid_line_120_a3575454_descriptor_json();
const char* src_core_geometry_map_snap_tools_build_graph_line_134_66aba17d_descriptor_json();
const char* src_core_geometry_map_snap_tools_room_by_id_line_138_2b64950c_descriptor_json();
const char* src_core_geometry_map_snap_tools_set_room_position_line_146_548aa17f_descriptor_json();
const char* src_core_geometry_map_snap_tools_build_snap_anchors_line_154_0cb5005c_descriptor_json();
const char* src_core_geometry_map_snap_tools_find_snap_candidates_line_198_8b7a6173_descriptor_json();
const char* src_core_geometry_map_snap_tools_snap_room_to_anchor_line_230_750c31c8_descriptor_json();
const char* src_core_geometry_map_snap_tools_snap_room_to_nearest_anchor_line_272_6d03b028_descriptor_json();
const char* src_core_geometry_map_snap_tools_snap_room_to_grid_line_292_56e76528_descriptor_json();
const char* src_core_geometry_map_snap_tools_git_raw_line_315_e4107e5d_descriptor_json();
const char* src_core_geometry_map_snap_tools_raw_list_line_322_43dfd95d_descriptor_json();
const char* src_core_geometry_map_snap_tools_object_row_line_330_0f5464e1_descriptor_json();
const char* src_core_geometry_map_snap_tools_object_position_line_340_1b26a8a5_descriptor_json();
const char* src_core_geometry_map_snap_tools_set_object_position_line_349_05d4547c_descriptor_json();
const char* src_core_geometry_map_snap_tools_nearest_room_id_line_356_18fefe90_descriptor_json();
const char* src_core_geometry_map_snap_tools_align_object_to_room_line_363_d7ad92b7_descriptor_json();
const char* src_core_geometry_map_snap_tools_snap_object_to_grid_line_401_6a4d2586_descriptor_json();
const char* src_core_geometry_model_data_is_animation_supermodel_line_35_fc362fb6_descriptor_json();
const char* src_core_geometry_model_data_classify_kotor_model_line_337_83251b23_descriptor_json();
const char* src_core_geometry_model_data_detect_character_mode_line_494_a6e0eadd_descriptor_json();
const char* src_core_geometry_model_data_quat_mul_line_528_786b5f7e_descriptor_json();
const char* src_core_geometry_model_data_quat_conjugate_line_549_046e1a0a_descriptor_json();
const char* src_core_geometry_model_data_quat_rotate_line_559_6fd74838_descriptor_json();
const char* src_core_geometry_model_data_quat_normalize_line_587_e360c2d9_descriptor_json();
const char* src_core_geometry_model_data_quat_normalize_bind_line_597_e3c28ffe_descriptor_json();
const char* src_core_geometry_model_data_make_asset_id_line_1745_d18b3908_descriptor_json();
const char* src_core_geometry_vertex_space_compute_vertex_space_line_51_d74e1ec7_descriptor_json();

const PythonFunctionDescriptorEntry* modulefunctions_descriptors(std::size_t& count);

} // namespace ghostrigger::phase15::ghostrigger_geometry
