#pragma once

#include <cstddef>

namespace ghostrigger::phase15::ghostrigger_animation {

using PythonFunctionDescriptorJson = const char* (*)();

struct PythonFunctionDescriptorEntry {
    const char* python_file;
    const char* qualname;
    const char* function_type;
    PythonFunctionDescriptorJson descriptor_json;
};

const char* src_core_animation_animation_engine_lerp_line_326_ccd49f0b_descriptor_json();
const char* src_core_animation_animation_engine_lerp3_line_330_d78b4641_descriptor_json();
const char* src_core_animation_animation_engine_slerp_line_338_888e1d94_descriptor_json();
const char* src_core_animation_animation_engine_is_finite_vec_line_371_80e75373_descriptor_json();
const char* src_core_animation_animation_engine_ensure_quat_sign_consistency_line_376_245dd9e4_descriptor_json();
const char* src_core_animation_animation_engine_interp_channel_line_416_30ecba82_descriptor_json();
const char* src_core_animation_animation_engine_normalize_quat_xyzw_line_532_5ac44082_descriptor_json();
const char* src_core_animation_animation_engine_controller_matches_line_541_deb22beb_descriptor_json();
const char* src_core_animation_animation_engine_sample_controller_absolute_line_548_8c8f34d5_descriptor_json();
const char* src_core_animation_animation_engine_compose_transform_line_575_69723e71_descriptor_json();
const char* src_core_animation_animation_engine_evaluate_aurora_animation_pose_line_593_25410bcc_descriptor_json();
const char* src_core_animation_animation_engine_merge_usecomp_animations_line_1737_0f5aa4af_descriptor_json();
const char* src_core_animation_animation_engine_build_bone_remap_line_1756_49c68eb2_descriptor_json();
const char* src_core_animation_animation_engine_retarget_usecomp_line_1860_e8730c26_descriptor_json();
const char* src_core_animation_animation_engine_get_ctrl_line_1916_97e63288_descriptor_json();
const char* src_core_animation_animation_library_batch_export_animations_line_1331_05a3fc02_descriptor_json();
const char* src_core_animation_animation_library_mat4_identity_line_1415_1a0231a6_descriptor_json();
const char* src_core_animation_animation_library_mat4_mul_line_1420_39fc4bfb_descriptor_json();
const char* src_core_animation_animation_library_mat4_from_sqt_line_1432_7eefb660_descriptor_json();
const char* src_core_animation_animation_library_mat4_inverse_trs_line_1481_6714de78_descriptor_json();
const char* src_core_animation_animation_library_build_world_transforms_line_1514_82257b22_descriptor_json();
const char* src_core_animation_animation_library_slerp_quat_line_1548_644ef13a_descriptor_json();
const char* src_core_animation_animation_library_quat_to_euler_xyz_line_1583_d602106e_descriptor_json();
const char* src_core_animation_animation_library_safe_filename_line_1606_7580dfda_descriptor_json();
const char* src_core_animation_gpu_skinning_classify_skinning_species_line_141_a7a903d5_descriptor_json();
const char* src_core_animation_gpu_skinning_explicit_skin_formula_override_line_196_6b278fbf_descriptor_json();
const char* src_core_animation_gpu_skinning_active_skin_formula_line_201_14d466e5_descriptor_json();
const char* src_core_animation_gpu_skinning_quat_to_mat4_line_245_1b945e78_descriptor_json();
const char* src_core_animation_gpu_skinning_mat4_mul_py_line_269_bf3579a4_descriptor_json();
const char* src_core_animation_gpu_skinning_mat4_identity_py_line_281_5178349d_descriptor_json();
const char* src_core_animation_gpu_skinning_mat4_translate_py_line_285_7994369d_descriptor_json();
const char* src_core_animation_gpu_skinning_mat4_to_flat_col_line_289_49386053_descriptor_json();
const char* src_core_animation_gpu_skinning_mat4_rotation_only_py_line_298_2fb6568c_descriptor_json();
const char* src_core_animation_gpu_skinning_mat4_invert_py_line_1323_37f6c614_descriptor_json();
const char* src_core_animation_gpu_skinning_validate_tbn_line_1751_77cb7c15_descriptor_json();
const char* src_core_animation_skinning_profiles_init_load_profiles_line_79_e95213b9_descriptor_json();
const char* src_core_animation_skinning_profiles_init_contains_any_line_110_6435d954_descriptor_json();
const char* src_core_animation_skinning_profiles_init_enum_value_line_114_25301b80_descriptor_json();
const char* src_core_animation_skinning_profiles_init_node_names_from_model_line_119_6f20dc36_descriptor_json();
const char* src_core_animation_skinning_profiles_init_has_skin_from_nodes_line_126_58133f04_descriptor_json();
const char* src_core_animation_skinning_profiles_init_taxonomy_from_model_line_140_dc777ddc_descriptor_json();
const char* src_core_animation_skinning_profiles_init_context_from_args_line_150_7419fa6f_descriptor_json();
const char* src_core_animation_skinning_profiles_init_specific_profile_for_context_line_191_c9346b62_descriptor_json();
const char* src_core_animation_skinning_profiles_init_species_for_context_line_269_9e9e7859_descriptor_json();
const char* src_core_animation_skinning_profiles_init_profile_matches_line_294_1074b75f_descriptor_json();
const char* src_core_animation_skinning_profiles_init_resolve_skinning_profile_line_327_fb033e86_descriptor_json();
const char* src_core_animation_skinning_profiles_init_classify_skinning_species_line_393_21cf51aa_descriptor_json();

const PythonFunctionDescriptorEntry* modulefunctions_descriptors(std::size_t& count);

} // namespace ghostrigger::phase15::ghostrigger_animation
