#pragma once

#include <cstddef>

namespace ghostrigger::phase15::ghostrigger_animation {

using PythonFunctionDescriptorJson = const char* (*)();

struct PythonFunctionDescriptorEntry {
    const char* python_file;
    const char* qualname;
    const char* function_type;
    PythonFunctionDescriptorJson descriptor_json;
};

const char* src_core_animation_animation_engine_interp_channel_safe_val_line_443_ac242877_descriptor_json();
const char* src_core_animation_animation_engine_animationengine_export_animation_bvh_collect_bones_line_1474_36617db8_descriptor_json();
const char* src_core_animation_animation_engine_animationengine_export_animation_bvh_bvh_bone_line_1497_76c5d7d0_descriptor_json();
const char* src_core_animation_animation_engine_animationengine_export_animation_bvh_quat_to_euler_zxy_line_1548_6dc3b074_descriptor_json();
const char* src_core_animation_animation_engine_animationengine_export_animation_bvh_collect_frame_line_1579_cc3f4033_descriptor_json();
const char* src_core_animation_animation_library_animationlibrary_scan_run_line_135_6499ffb5_descriptor_json();
const char* src_core_animation_animation_library_fbxanimationexporter_write_fbx_new_id_line_603_0f438edb_descriptor_json();
const char* src_core_animation_animation_library_fbxanimationexporter_write_fbx_collect_line_610_8b35a11f_descriptor_json();
const char* src_core_animation_animation_library_fbxanimationexporter_write_fbx_write_single_curve_line_795_21c30c63_descriptor_json();
const char* src_core_animation_animation_library_fbxanimationexporter_write_fbx_write_curve_line_824_bdc39bcf_descriptor_json();
const char* src_core_animation_animation_library_fbxanimationexporter_write_fbx_baked_new_id_line_979_78c0530b_descriptor_json();
const char* src_core_animation_animation_library_fbxanimationexporter_write_fbx_baked_collect_line_986_10b572bb_descriptor_json();
const char* src_core_animation_animation_library_fbxanimationexporter_write_fbx_baked_write_single_baked_curve_line_1171_4500447a_descriptor_json();
const char* src_core_animation_animation_library_fbxanimationexporter_write_fbx_baked_write_baked_curve_line_1199_37b407c6_descriptor_json();
const char* src_core_animation_animation_library_build_world_transforms_visit_line_1530_b7e8a71d_descriptor_json();
const char* src_core_animation_gpu_skinning_matrixpaletteuploader_build_inverse_bind_pose_get_world_bind_line_501_b2c62f64_descriptor_json();
const char* src_core_animation_gpu_skinning_matrixpaletteuploader_set_bind_pose_from_anim_get_world_base_line_619_9eefd8e4_descriptor_json();
const char* src_core_animation_gpu_skinning_matrixpaletteuploader_compute_palette_get_world_anim_line_1152_89fa6368_descriptor_json();

const PythonFunctionDescriptorEntry* nestedfunctions_descriptors(std::size_t& count);

} // namespace ghostrigger::phase15::ghostrigger_animation
