#pragma once

#include <cstddef>

namespace ghostrigger::phase15::ghostrigger_workflow {

using PythonFunctionDescriptorJson = const char* (*)();

struct PythonFunctionDescriptorEntry {
    const char* python_file;
    const char* qualname;
    const char* function_type;
    PythonFunctionDescriptorJson descriptor_json;
};

const char* src_core_workflow_workflow_base_import_model_data_line_82_3c6c0659_descriptor_json();
const char* src_core_workflow_workflow_base_import_validation_service_line_96_7fff170e_descriptor_json();
const char* src_core_workflow_workflow_base_import_accurig_line_105_b9ea3e7c_descriptor_json();
const char* src_core_workflow_workflow_base_import_scene_io_line_118_2de54ed5_descriptor_json();
const char* src_core_workflow_workflow_base_summarize_issues_line_153_7ba076da_descriptor_json();
const char* src_core_workflow_workflow_base_blocking_codes_from_issues_line_208_6ada9ff5_descriptor_json();
const char* src_core_workflow_workflow_base_ext_of_line_339_896772f2_descriptor_json();
const char* src_core_workflow_workflow_base_resref_from_path_line_345_c25e7d68_descriptor_json();
const char* src_core_workflow_workflow_base_safe_resref_line_355_4741b6fb_descriptor_json();
const char* src_core_workflow_composite_workflow_import_model_data_line_53_bd1d3466_descriptor_json();
const char* src_core_workflow_composite_workflow_import_body_workflow_line_61_26f6848f_descriptor_json();
const char* src_core_workflow_composite_workflow_import_head_workflow_line_69_194f4fc3_descriptor_json();
const char* src_core_workflow_composite_workflow_import_character_builder_line_77_f52d5677_descriptor_json();
const char* src_core_workflow_composite_workflow_import_validation_service_line_85_e7f5da99_descriptor_json();
const char* src_core_workflow_composite_workflow_import_workflow_base_line_93_506cb17a_descriptor_json();
const char* src_core_workflow_composite_workflow_import_creature_appearance_line_101_7c2a6fe6_descriptor_json();
const char* src_core_workflow_composite_workflow_import_scene_io_line_109_1a650e6c_descriptor_json();
const char* src_core_workflow_composite_workflow_import_mesh_exporters_line_117_2600da03_descriptor_json();
const char* src_core_workflow_composite_workflow_slot_models_line_210_ca8fcfa9_descriptor_json();
const char* src_core_workflow_composite_workflow_make_issue_line_217_44ee55cf_descriptor_json();
const char* src_core_workflow_composite_workflow_normalise_quat_line_233_e158161d_descriptor_json();
const char* src_core_workflow_composite_workflow_matrix_from_transform_line_241_6ec8e7a8_descriptor_json();
const char* src_core_workflow_composite_workflow_first_root_name_line_260_cd65a3ed_descriptor_json();
const char* src_core_workflow_composite_workflow_write_snap_metadata_line_273_afb48ac3_descriptor_json();
const char* src_core_workflow_composite_workflow_supermodel_value_line_297_b1347312_descriptor_json();
const char* src_core_workflow_composite_workflow_bounds_line_301_3d513d35_descriptor_json();
const char* src_core_workflow_composite_workflow_append_supermodel_issues_line_323_8a3a2e3d_descriptor_json();
const char* src_core_workflow_composite_workflow_append_seam_issue_line_363_e5fc4668_descriptor_json();
const char* src_core_workflow_composite_workflow_snap_head_to_body_line_399_f26a7c73_descriptor_json();
const char* src_core_workflow_composite_workflow_load_composite_line_490_12045c43_descriptor_json();
const char* src_core_workflow_composite_workflow_check_composite_line_559_2a2767b8_descriptor_json();
const char* src_core_workflow_composite_workflow_update_snap_after_scene_mutation_line_621_3a421500_descriptor_json();
const char* src_core_workflow_composite_workflow_scene_resref_line_635_8368a739_descriptor_json();
const char* src_core_workflow_composite_workflow_composite_export_model_line_653_20db1318_descriptor_json();
const char* src_core_workflow_composite_workflow_export_composite_single_format_line_679_1eee98f5_descriptor_json();
const char* src_core_workflow_composite_workflow_export_composite_scene_line_734_cd23b5b0_descriptor_json();

const PythonFunctionDescriptorEntry* modulefunctions_descriptors(std::size_t& count);

} // namespace ghostrigger::phase15::ghostrigger_workflow
