"""Native package discovery helpers for the embedded C++ host."""

from .package_registry import (
    NATIVE_CORE_DIAGNOSTICS_PACKAGE,
    NATIVE_CORE_MATH_PACKAGE,
    NATIVE_CORE_PACKAGE,
    RENDERER_CONTRACTS_PACKAGE,
    RENDERER_NULL_PACKAGE,
    RUNTIME_SHARED_CONTRACTS_PACKAGE,
    RUNTIME_SHARED_DESCRIPTORS_PACKAGE,
    RUNTIME_SHARED_RESOURCES_PACKAGE,
    NativePackageSpec,
    NativePackageStatus,
    query_native_core_diagnostics_status,
    query_native_core_math_status,
    query_native_core_status,
    query_native_package_status,
    query_renderer_contracts_status,
    query_renderer_null_status,
    query_runtime_shared_contracts_status,
    query_runtime_shared_descriptors_status,
    query_runtime_shared_resources_status,
)

__all__ = [
    "NATIVE_CORE_DIAGNOSTICS_PACKAGE",
    "NATIVE_CORE_MATH_PACKAGE",
    "NATIVE_CORE_PACKAGE",
    "RENDERER_CONTRACTS_PACKAGE",
    "RENDERER_NULL_PACKAGE",
    "RUNTIME_SHARED_CONTRACTS_PACKAGE",
    "RUNTIME_SHARED_DESCRIPTORS_PACKAGE",
    "RUNTIME_SHARED_RESOURCES_PACKAGE",
    "NativePackageSpec",
    "NativePackageStatus",
    "query_native_core_diagnostics_status",
    "query_native_core_math_status",
    "query_native_core_status",
    "query_native_package_status",
    "query_renderer_contracts_status",
    "query_renderer_null_status",
    "query_runtime_shared_contracts_status",
    "query_runtime_shared_descriptors_status",
    "query_runtime_shared_resources_status",
]
