"""Fallback tokens for GhostRigger themes and layouts."""

from __future__ import annotations

LEGACY_MATRIX_COLORS: dict[str, str] = {
    "bg": "#0B0F0D",
    "bg2": "#07100C",
    "panel": "#111916",
    "panel2": "#151D1A",
    "border": "#1B2A22",
    "hover": "#183428",
    "selected": "#00FF7A",
    "accent": "#00FF7A",
    "accent2": "#00D7B5",
    "text": "#E8F0EC",
    "text2": "#7A9A88",
    "success": "#00FF7A",
    "warning": "#FFAA00",
    "error": "#FF4444",
    "gold": "#D8C66A",
}

TOKEN_ALIASES: dict[str, str] = {
    "bg": "window.background",
    "bg2": "viewport.background",
    "panel": "panel.background",
    "panel2": "panel.backgroundAlt",
    "border": "panel.border",
    "hover": "button.hover",
    "selected": "selection.background",
    "accent": "accent.primary",
    "accent2": "accent.secondary",
    "text": "text.primary",
    "text2": "text.secondary",
    "gold": "text.gold",
}

FALLBACK_COLORS: dict[str, str] = {
    "window.background": LEGACY_MATRIX_COLORS["bg"],
    "window.text": LEGACY_MATRIX_COLORS["text"],
    "panel.background": LEGACY_MATRIX_COLORS["panel"],
    "panel.backgroundAlt": LEGACY_MATRIX_COLORS["panel2"],
    "panel.altBackground": LEGACY_MATRIX_COLORS["panel2"],
    "panel.border": LEGACY_MATRIX_COLORS["border"],
    "panel.headerBackground": LEGACY_MATRIX_COLORS["panel2"],
    "panel.headerText": LEGACY_MATRIX_COLORS["text"],
    "groupbox.border": LEGACY_MATRIX_COLORS["border"],
    "groupbox.title": LEGACY_MATRIX_COLORS["gold"],
    "viewport.background": LEGACY_MATRIX_COLORS["bg2"],
    "viewport.border": "#34383F",
    "viewport.text": "#8F9AAA",
    "viewport.gridMajor": "#1D3A2B",
    "viewport.gridMinor": "#102019",
    "toolbar.background": LEGACY_MATRIX_COLORS["panel"],
    "toolbar.border": LEGACY_MATRIX_COLORS["border"],
    "button.background": LEGACY_MATRIX_COLORS["panel2"],
    "button.hover": LEGACY_MATRIX_COLORS["hover"],
    "button.pressed": "#102019",
    "button.checked": LEGACY_MATRIX_COLORS["accent"],
    "button.checkedText": "#001A0E",
    "button.text": LEGACY_MATRIX_COLORS["text"],
    "button.accentText": "#001A0E",
    "button.disabledBackground": LEGACY_MATRIX_COLORS["panel"],
    "button.disabledText": "#55665B",
    "input.background": LEGACY_MATRIX_COLORS["panel2"],
    "input.text": LEGACY_MATRIX_COLORS["text"],
    "input.border": LEGACY_MATRIX_COLORS["border"],
    "input.focusBorder": LEGACY_MATRIX_COLORS["accent2"],
    "tab.background": LEGACY_MATRIX_COLORS["panel"],
    "tab.selectedBackground": LEGACY_MATRIX_COLORS["bg2"],
    "tab.inactiveBackground": LEGACY_MATRIX_COLORS["panel"],
    "tab.text": LEGACY_MATRIX_COLORS["text2"],
    "tab.selectedText": LEGACY_MATRIX_COLORS["accent"],
    "table.background": LEGACY_MATRIX_COLORS["bg2"],
    "table.text": LEGACY_MATRIX_COLORS["text"],
    "table.headerBackground": LEGACY_MATRIX_COLORS["panel2"],
    "table.headerText": LEGACY_MATRIX_COLORS["text"],
    "table.grid": LEGACY_MATRIX_COLORS["border"],
    "tree.background": LEGACY_MATRIX_COLORS["bg2"],
    "tree.text": LEGACY_MATRIX_COLORS["text"],
    "scrollbar.background": LEGACY_MATRIX_COLORS["panel"],
    "scrollbar.handle": LEGACY_MATRIX_COLORS["border"],
    "selection.background": LEGACY_MATRIX_COLORS["selected"],
    "selection.text": "#FFFFFF",
    "text.primary": LEGACY_MATRIX_COLORS["text"],
    "text.secondary": LEGACY_MATRIX_COLORS["text2"],
    "text.disabled": "#55665B",
    "text.gold": LEGACY_MATRIX_COLORS["gold"],
    "accent.primary": LEGACY_MATRIX_COLORS["accent"],
    "accent.secondary": LEGACY_MATRIX_COLORS["accent2"],
    "transformBar.background": LEGACY_MATRIX_COLORS["panel"],
    "transformBar.border": LEGACY_MATRIX_COLORS["border"],
    "matrixBar.background": LEGACY_MATRIX_COLORS["bg"],
    "matrixBar.glyph": LEGACY_MATRIX_COLORS["accent"],
    "matrixBar.text": LEGACY_MATRIX_COLORS["accent"],
    "matrixBar.subtext": LEGACY_MATRIX_COLORS["text2"],
    "matrixBar.metaText": LEGACY_MATRIX_COLORS["text2"],
    "matrixBar.ipcText": LEGACY_MATRIX_COLORS["accent"],
    "info": LEGACY_MATRIX_COLORS["accent2"],
    "warning": LEGACY_MATRIX_COLORS["warning"],
    "error": LEGACY_MATRIX_COLORS["error"],
    "success": LEGACY_MATRIX_COLORS["success"],
}

FALLBACK_FONTS: dict[str, dict[str, str | int]] = {
    "default": {"family": "Consolas", "size": 9, "weight": "normal"},
    "monospace": {"family": "Consolas", "size": 9, "weight": "normal"},
    "heading": {"family": "Segoe UI", "size": 10, "weight": "bold"},
    "small": {"family": "Segoe UI", "size": 8, "weight": "normal"},
    "viewport": {"family": "Consolas", "size": 9, "weight": "normal"},
    "terminal": {"family": "Consolas", "size": 9, "weight": "normal"},
    "matrix": {"family": "Aurebesh AF", "size": 9, "weight": "normal"},
}

FALLBACK_METRICS: dict[str, int] = {
    "window.defaultWidth": 1650,
    "window.defaultHeight": 920,
    "toolbar.height": 34,
    "toolbar.iconSize": 18,
    "toolbar.buttonHeight": 16,
    "toolbar.buttonMinWidth": 64,
    "toolbar.spacing": 4,
    "button.height": 16,
    "button.minWidth": 64,
    "button.paddingX": 6,
    "button.paddingY": 1,
    "button.paddingH": 6,
    "button.paddingV": 1,
    "input.height": 24,
    "input.minWidth": 90,
    "combo.height": 24,
    "spinbox.height": 24,
    "checkbox.spacing": 4,
    "tab.height": 26,
    "panel.margin": 4,
    "panel.spacing": 4,
    "panel.headerHeight": 28,
    "panel.minWidth": 260,
    "panel.preferredWidth": 360,
    "leftPanel.preferredWidth": 390,
    "rightPanel.preferredWidth": 390,
    "farRightPanel.preferredWidth": 380,
    "splitter.handleWidth": 6,
    "groupbox.margin": 8,
    "groupbox.spacing": 4,
    "table.rowHeight": 22,
    "tree.rowHeight": 22,
    "statusbar.height": 24,
    "transformBar.height": 30,
    "viewportToolbar.height": 34,
    "bottom.preferredHeight": 220,
    "bottomPanel.preferredHeight": 220,
    "bottom.minHeight": 120,
    "viewport.minWidth": 500,
    "border.radius": 3,
}

VALID_BUTTON_MODES = {
    "iconOnly",
    "textOnly",
    "iconText",
    "textBesideIcon",
    "textUnderIcon",
}


def color_alias_view(colors: dict[str, str]) -> dict[str, str]:
    """Return the legacy ``C`` dictionary view for older GUI modules."""

    view: dict[str, str] = {}
    for legacy_key, token in TOKEN_ALIASES.items():
        view[legacy_key] = colors.get(token, FALLBACK_COLORS[token])
    for key in ("success", "warning", "error"):
        view[key] = colors.get(key, FALLBACK_COLORS[key])
    return view
