#pragma once

#include <cstddef>

namespace ghostrigger::phase15::ghostrigger_gui_panels {

using PythonFunctionDescriptorJson = const char* (*)();

struct PythonFunctionDescriptorEntry {
    const char* python_file;
    const char* qualname;
    const char* function_type;
    PythonFunctionDescriptorJson descriptor_json;
};

const char* src_gui_panels_module_editor_module_editor_outliner_pathtext_line_118_bc674f7e_descriptor_json();
const char* src_gui_panels_qt_animation_panel_animation_display_name_line_114_1b1dca2a_descriptor_json();
const char* src_gui_panels_qt_animation_panel_animation_row_label_line_127_2e7e3436_descriptor_json();
const char* src_gui_panels_qt_animation_panel_animation_base_display_name_line_138_03aa7c07_descriptor_json();
const char* src_gui_panels_qt_animation_panel_animation_set_context_line_167_1f7046f6_descriptor_json();
const char* src_gui_panels_qt_animation_panel_animation_action_label_line_175_bd63af3f_descriptor_json();
const char* src_gui_panels_qt_animation_panel_humanize_animation_slot_line_182_a124c22c_descriptor_json();
const char* src_gui_panels_qt_animation_panel_animation_game_label_line_191_9ffeda17_descriptor_json();
const char* src_gui_panels_qt_animation_panel_game_from_model_line_202_88085dc4_descriptor_json();
const char* src_gui_panels_qt_bottom_strip_severity_to_key_line_74_43c6d655_descriptor_json();
const char* src_gui_panels_qt_character_builder_panel_issue_field_line_51_2ed2931c_descriptor_json();
const char* src_gui_panels_qt_character_builder_panel_issue_slot_text_line_64_aea04b23_descriptor_json();
const char* src_gui_panels_qt_character_builder_panel_attachment_type_from_resref_line_74_fb54eef9_descriptor_json();
const char* src_gui_panels_qt_character_builder_panel_import_model_data_line_239_381469b8_descriptor_json();
const char* src_gui_panels_qt_character_builder_panel_import_scene_io_line_247_5de8af8c_descriptor_json();
const char* src_gui_panels_qt_common_panels_tab_icon_line_52_a54d8dc6_descriptor_json();
const char* src_gui_panels_qt_content_browser_panel_display_name_from_library_row_line_118_5539bae8_descriptor_json();
const char* src_gui_panels_qt_content_browser_panel_encoded_display_name_line_140_1ee739f0_descriptor_json();
const char* src_gui_panels_qt_content_browser_panel_player_display_name_line_199_41174031_descriptor_json();
const char* src_gui_panels_qt_content_browser_panel_party_display_name_line_219_ceed43bb_descriptor_json();
const char* src_gui_panels_qt_content_browser_panel_npc_display_name_line_240_75e1c40f_descriptor_json();
const char* src_gui_panels_qt_content_browser_panel_droid_display_name_line_273_d3645255_descriptor_json();
const char* src_gui_panels_qt_content_browser_panel_species_gender_display_name_line_284_37d95e21_descriptor_json();
const char* src_gui_panels_qt_content_browser_panel_party_variant_line_313_b078fc58_descriptor_json();
const char* src_gui_panels_qt_content_browser_panel_letter_or_number_variant_line_325_a22744e6_descriptor_json();
const char* src_gui_panels_qt_content_browser_panel_npc_variant_line_340_d2228373_descriptor_json();
const char* src_gui_panels_qt_content_browser_panel_with_variant_line_354_ccb0f27d_descriptor_json();
const char* src_gui_panels_qt_content_browser_panel_humanize_asset_name_line_364_1bad8caf_descriptor_json();
const char* src_gui_panels_qt_content_browser_panel_descriptor_from_library_row_line_417_7b1074c1_descriptor_json();
const char* src_gui_panels_qt_content_browser_panel_descriptor_from_animation_entry_line_473_6a4ce035_descriptor_json();
const char* src_gui_panels_qt_library_panel_looks_like_minigame_line_706_52da16d2_descriptor_json();
const char* src_gui_panels_qt_library_panel_category_sort_key_line_710_cf24a25a_descriptor_json();
const char* src_gui_panels_qt_library_panel_looks_like_party_member_line_717_ca92f23e_descriptor_json();
const char* src_gui_panels_qt_library_panel_looks_like_droid_line_721_3657b726_descriptor_json();
const char* src_gui_panels_qt_library_panel_looks_like_gui_or_menu_model_line_725_412b3e69_descriptor_json();
const char* src_gui_panels_qt_library_panel_looks_like_module_geometry_line_735_13bfdb98_descriptor_json();
const char* src_gui_panels_qt_library_panel_looks_like_module_minigame_piece_line_741_1acc9e03_descriptor_json();
const char* src_gui_panels_qt_library_panel_infer_model_category_line_745_cd03150d_descriptor_json();
const char* src_gui_panels_qt_library_panel_stripped_resource_token_line_885_e5cdb09e_descriptor_json();
const char* src_gui_panels_qt_library_panel_metadata_int_line_893_e73882a8_descriptor_json();
const char* src_gui_panels_qt_library_panel_subcategory_from_item_metadata_line_901_d8c23b50_descriptor_json();
const char* src_gui_panels_qt_library_panel_category_from_item_metadata_line_934_5068412a_descriptor_json();
const char* src_gui_panels_qt_library_panel_subcategory_from_door_metadata_line_941_d6219d40_descriptor_json();
const char* src_gui_panels_qt_library_panel_player_character_metadata_line_958_9d32c1ff_descriptor_json();
const char* src_gui_panels_qt_library_panel_party_member_metadata_line_997_c1c247a8_descriptor_json();
const char* src_gui_panels_qt_library_panel_commoner_metadata_line_1027_339c9395_descriptor_json();
const char* src_gui_panels_qt_library_panel_npc_metadata_line_1040_f6daba89_descriptor_json();
const char* src_gui_panels_qt_library_panel_droid_metadata_line_1138_6da28921_descriptor_json();
const char* src_gui_panels_qt_library_panel_creature_metadata_line_1155_2d01bbbd_descriptor_json();
const char* src_gui_panels_qt_library_panel_supermodel_metadata_line_1204_dd432d41_descriptor_json();
const char* src_gui_panels_qt_library_panel_turret_metadata_line_1217_e34f11de_descriptor_json();
const char* src_gui_panels_qt_library_panel_engine_item_metadata_line_1230_e7999c9e_descriptor_json();
const char* src_gui_panels_qt_library_panel_environment_metadata_line_1247_6cdb985e_descriptor_json();
const char* src_gui_panels_qt_library_panel_gui_metadata_line_1264_b7c2e2dc_descriptor_json();
const char* src_gui_panels_qt_library_panel_hologram_metadata_line_1289_221875cb_descriptor_json();
const char* src_gui_panels_qt_library_panel_level_asset_metadata_line_1304_9da927bf_descriptor_json();
const char* src_gui_panels_qt_library_panel_minigame_metadata_line_1327_d5293595_descriptor_json();
const char* src_gui_panels_qt_library_panel_menu_metadata_line_1342_fee6079d_descriptor_json();
const char* src_gui_panels_qt_library_panel_visual_fx_metadata_line_1351_eb94436c_descriptor_json();
const char* src_gui_panels_qt_library_panel_visual_metadata_line_1374_70b5a553_descriptor_json();
const char* src_gui_panels_qt_library_panel_planet_metadata_line_1397_319cabb3_descriptor_json();
const char* src_gui_panels_qt_library_panel_misc_model_metadata_line_1404_2cde7b2b_descriptor_json();
const char* src_gui_panels_qt_library_panel_stunt_metadata_line_1419_f3ad83c5_descriptor_json();
const char* src_gui_panels_qt_library_panel_infer_model_subcategory_line_1434_335a1205_descriptor_json();
const char* src_gui_panels_qt_library_panel_subcategory_sort_key_line_1645_e1868f2d_descriptor_json();
const char* src_gui_panels_qt_library_panel_content_browser_metadata_for_resref_line_1653_82928a38_descriptor_json();
const char* src_gui_panels_qt_library_panel_module_info_for_row_line_1729_04499754_descriptor_json();
const char* src_gui_panels_qt_library_panel_as_gff_dict_line_1738_67b9acc7_descriptor_json();
const char* src_gui_panels_qt_library_panel_template_field_text_line_1750_9ffe08e3_descriptor_json();
const char* src_gui_panels_qt_library_panel_template_model_candidates_line_1755_f89306d9_descriptor_json();
const char* src_gui_panels_qt_library_panel_door_model_candidates_line_1786_1b78da41_descriptor_json();
const char* src_gui_panels_qt_library_panel_template_metadata_index_for_game_line_1810_9ecd4628_descriptor_json();
const char* src_gui_panels_qt_library_panel_enrich_library_rows_with_resource_metadata_line_1893_d76cdcd1_descriptor_json();
const char* src_gui_panels_qt_library_panel_enrich_library_rows_line_1910_e1a3e5ac_descriptor_json();
const char* src_gui_panels_qt_log_panel_normalise_log_level_line_26_c676b4ca_descriptor_json();
const char* src_gui_panels_qt_log_panel_detect_log_level_line_45_0e6b106a_descriptor_json();
const char* src_gui_panels_qt_log_panel_make_log_tool_button_line_152_aaed0568_descriptor_json();
const char* src_gui_panels_qt_resource_browser_model_role_text_line_273_f07acd64_descriptor_json();
const char* src_gui_panels_qt_resource_browser_model_as_iter_line_282_aeff2e47_descriptor_json();
const char* src_gui_panels_qt_skeleton_panel_node_browser_role_line_12_c8466915_descriptor_json();
const char* src_gui_panels_qt_ue5_rig_export_panel_fmt_ratio_line_192_464fc7b2_descriptor_json();
const char* src_gui_panels_qt_workflow_rail_steps_for_mode_line_93_1e189d9f_descriptor_json();

const PythonFunctionDescriptorEntry* modulefunctions_descriptors(std::size_t& count);

} // namespace ghostrigger::phase15::ghostrigger_gui_panels
