#pragma once

#include <cstddef>

namespace ghostrigger::phase15::ghostrigger_gui_panels {

using PythonFunctionDescriptorJson = const char* (*)();

struct PythonFunctionDescriptorEntry {
    const char* python_file;
    const char* qualname;
    const char* function_type;
    PythonFunctionDescriptorJson descriptor_json;
};

const char* src_gui_panels_module_editor_module_editor_properties_moduleeditorpropertiespanel_set_vector_line_85_4910d35b_descriptor_json();
const char* src_gui_panels_qt_character_builder_panel_qtcharacterbuilderwindow_character_builder_theme_stylesheet_line_551_081c8327_descriptor_json();
const char* src_gui_panels_qt_character_builder_panel_qtcharacterbuilderwindow_option_field_line_1975_4be3154b_descriptor_json();
const char* src_gui_panels_qt_character_builder_panel_qtcharacterbuilderwindow_settings_line_4222_ff8074da_descriptor_json();
const char* src_gui_panels_qt_diagnostics_panel_qtdiagnosticspanel_safe_list_line_112_2f271222_descriptor_json();
const char* src_gui_panels_qt_diagnostics_panel_qtdiagnosticspanel_performance_report_lines_line_206_254a0745_descriptor_json();
const char* src_gui_panels_qt_diagnostics_panel_qtdiagnosticspanel_bytes_with_mb_line_245_51acfcc8_descriptor_json();
const char* src_gui_panels_qt_mesh_operation_options_qtmeshoperationoptionswidget_double_spin_line_63_b81f3fe3_descriptor_json();
const char* src_gui_panels_qt_mesh_operation_options_qtmeshoperationoptionswidget_int_spin_line_72_60c5d659_descriptor_json();
const char* src_gui_panels_qt_mesh_operation_options_qtmeshoperationoptionswidget_checked_box_line_79_cbfce570_descriptor_json();
const char* src_gui_panels_qt_ue5_rig_export_panel_qtue5rigexportpanel_artifact_summary_line_175_ab052981_descriptor_json();

const PythonFunctionDescriptorEntry* staticmethods_descriptors(std::size_t& count);

} // namespace ghostrigger::phase15::ghostrigger_gui_panels
