#pragma once

#include <cstddef>

namespace ghostrigger::core::assets {

#ifndef GHOSTRIGGER_ASSETS_NATIVE_FUNCTION_IMPLEMENTATION_DEFINED
#define GHOSTRIGGER_ASSETS_NATIVE_FUNCTION_IMPLEMENTATION_DEFINED
struct NativeFunctionImplementation {
    const char* project;
    const char* native_namespace;
    const char* python_file;
    const char* qualname;
    const char* callable_type;
    const char* implementation_status;
    bool native_first;
    bool python_runtime_required;
    bool python_fallback_allowed;
    const char* contract_json;
};
#endif // GHOSTRIGGER_ASSETS_NATIVE_FUNCTION_IMPLEMENTATION_DEFINED

const NativeFunctionImplementation& import_model_data_line_38_b1b403fc_native();
const NativeFunctionImplementation& import_composite_workflow_line_46_a02ef67b_native();
const NativeFunctionImplementation& import_kotor_loader_line_54_88966d41_native();
const NativeFunctionImplementation& scene_metadata_line_246_ae317da8_native();
const NativeFunctionImplementation& slot_model_line_254_a6e52b2d_native();
const NativeFunctionImplementation& all_nodes_line_261_078f027a_native();
const NativeFunctionImplementation& node_name_line_271_0710a1bd_native();
const NativeFunctionImplementation& node_world_transform_line_275_086fd89c_native();
const NativeFunctionImplementation& normalise_quat_line_286_b849af25_native();
const NativeFunctionImplementation& matrix_from_transform_line_294_05e20b71_native();
const NativeFunctionImplementation& socket_names_line_308_def6bb54_native();
const NativeFunctionImplementation& resolve_socket_line_318_6da45f08_native();
const NativeFunctionImplementation& model_identity_line_332_1a2b3ba9_native();
const NativeFunctionImplementation& animation_name_line_340_07db619d_native();
const NativeFunctionImplementation& animation_length_line_356_c4dd0a42_native();
const NativeFunctionImplementation& model_animations_line_375_2bdfe77f_native();
const NativeFunctionImplementation& mesh_nodes_line_387_547c049d_native();
const NativeFunctionImplementation& clean_token_line_400_62e1ef0f_native();
const NativeFunctionImplementation& node_textures_line_404_b8a5324e_native();
const NativeFunctionImplementation& preview_source_model_line_421_17140c05_native();
const NativeFunctionImplementation& slot_entry_line_429_4f9ec898_native();
const NativeFunctionImplementation& slot_game_version_line_436_798eb400_native();
const NativeFunctionImplementation& slot_resref_line_441_902097a4_native();
const NativeFunctionImplementation& animation_group_line_446_cf9511a9_native();
const NativeFunctionImplementation& clip_loop_default_line_477_cda199cc_native();
const NativeFunctionImplementation& motion_assignment_line_481_05169476_native();
const NativeFunctionImplementation& add_clip_line_488_ff2fed7e_native();
const NativeFunctionImplementation& group_clips_line_520_800ab937_native();
const NativeFunctionImplementation& default_clip_line_531_cd41f185_native();
const NativeFunctionImplementation& write_preview_metadata_line_540_b8b8502d_native();
const NativeFunctionImplementation& load_character_preview_line_573_376e8ff1_native();
const NativeFunctionImplementation& refresh_character_preview_line_649_401ca870_native();
const NativeFunctionImplementation& available_attachment_sockets_line_680_dac81bf1_native();
const NativeFunctionImplementation& attach_item_to_preview_line_687_569c75cf_native();
const NativeFunctionImplementation& issue_payload_line_777_4a676c71_native();
const NativeFunctionImplementation& attachment_issue_line_789_35f34bff_native();
const NativeFunctionImplementation& socket_side_line_810_40de0dbf_native();
const NativeFunctionImplementation& expected_attachment_side_line_814_f7a7be4b_native();
const NativeFunctionImplementation& is_lightsaber_attachment_line_826_ea01152d_native();
const NativeFunctionImplementation& requires_bullet_hook_line_837_8d41d196_native();
const NativeFunctionImplementation& matrix_close_line_848_06e4d55b_native();
const NativeFunctionImplementation& validate_attachment_overlay_line_859_d2eddd05_native();
const NativeFunctionImplementation& load_exported_preview_model_line_1013_17de13b5_native();
const NativeFunctionImplementation& model_parity_summary_line_1021_7e9fe15e_native();
const NativeFunctionImplementation& delta_line_1053_ddb38c77_native();
const NativeFunctionImplementation& delta_payload_line_1074_08c3bd71_native();
const NativeFunctionImplementation& compare_export_preview_parity_line_1086_9bf4bd2c_native();
const NativeFunctionImplementation& build_animation_workbench_line_1286_eca1719b_native();
const NativeFunctionImplementation& find_workbench_clip_line_1404_e438c57b_native();
const NativeFunctionImplementation& play_preview_animation_line_1423_8f33236c_native();
const NativeFunctionImplementation& scrub_preview_animation_line_1483_1d637b1d_native();
const NativeFunctionImplementation& key_line_98_0520e2cf_native();
const NativeFunctionImplementation& texture_name_candidates_line_110_f1e75d5f_native();
const NativeFunctionImplementation& decode_texture_line_748_23e8416a_native();
const NativeFunctionImplementation& tpc_uncompressed_txi_line_877_211ae331_native();
const NativeFunctionImplementation& tpc_info_line_912_ce2f9944_native();
const NativeFunctionImplementation& is_tpc_line_943_3763289e_native();
const NativeFunctionImplementation& get_manager_line_1014_7b60640d_native();
const NativeFunctionImplementation& reset_manager_line_1024_a1b1addf_native();
const NativeFunctionImplementation& resolve_model_textures_line_1034_771e23a2_native();
const NativeFunctionImplementation& audit_model_textures_line_1149_37515999_native();
const NativeFunctionImplementation& identify_texture_source_line_1240_5185a261_native();
const NativeFunctionImplementation& parse_txi_for_alpha_line_1278_ef05cf3e_native();
const NativeFunctionImplementation& apply_alpha_fix_line_1313_55e1139e_native();

const NativeFunctionImplementation* modulefunctions_native_functions(std::size_t& count);

} // namespace ghostrigger::core::assets
