#pragma once

#include <cstddef>

namespace ghostrigger::phase15::ghostrigger_animationretargeting {

using PythonFunctionDescriptorJson = const char* (*)();

struct PythonFunctionDescriptorEntry {
    const char* python_file;
    const char* qualname;
    const char* function_type;
    PythonFunctionDescriptorJson descriptor_json;
};

const char* src_core_animation_retargeting_retargeter_nodes_by_name_line_65_e3de5782_descriptor_json();
const char* src_core_animation_retargeting_retargeter_candidate_names_line_76_b6eddd65_descriptor_json();
const char* src_core_animation_retargeting_retargeter_clean_manual_mapping_line_88_8f23256c_descriptor_json();
const char* src_core_animation_retargeting_retargeter_build_bone_map_line_100_8e82d5c4_descriptor_json();
const char* src_core_animation_retargeting_retargeter_sub3_line_149_03d6213f_descriptor_json();
const char* src_core_animation_retargeting_retargeter_add3_line_157_c4cbd1f2_descriptor_json();
const char* src_core_animation_retargeting_retargeter_mul3_line_165_14d84c21_descriptor_json();
const char* src_core_animation_retargeting_retargeter_normal_quat_line_169_98a854c7_descriptor_json();
const char* src_core_animation_retargeting_retargeter_quat_conjugate_line_177_0afd563e_descriptor_json();
const char* src_core_animation_retargeting_retargeter_quat_mul_line_182_481c2862_descriptor_json();
const char* src_core_animation_retargeting_retargeter_retarget_rotation_line_193_550164d3_descriptor_json();
const char* src_core_animation_retargeting_retargeter_world_positions_by_key_line_198_09fd658e_descriptor_json();
const char* src_core_animation_retargeting_retargeter_height_from_positions_line_221_e0f49b0c_descriptor_json();
const char* src_core_animation_retargeting_retargeter_position_delta_scale_line_226_35d691fe_descriptor_json();
const char* src_core_animation_retargeting_retargeter_retarget_pose_line_244_c1c102c3_descriptor_json();
const char* src_core_animation_retargeting_retargeter_scaled_position_values_line_296_75cae199_descriptor_json();
const char* src_core_animation_retargeting_retargeter_retarget_animation_line_308_238ad410_descriptor_json();
const char* src_core_animation_retargeting_skeleton_template_picker_import_character_builder_line_190_09eda0fb_descriptor_json();
const char* src_core_animation_retargeting_skeleton_template_picker_norm_game_line_198_84abe7d0_descriptor_json();
const char* src_core_animation_retargeting_skeleton_template_picker_norm_part_line_209_623f1163_descriptor_json();
const char* src_core_animation_retargeting_skeleton_template_picker_read_json_line_222_670073be_descriptor_json();
const char* src_core_animation_retargeting_skeleton_template_picker_manifest_path_for_template_line_231_dbebd530_descriptor_json();
const char* src_core_animation_retargeting_skeleton_template_picker_infer_part_line_236_93e262d0_descriptor_json();
const char* src_core_animation_retargeting_skeleton_template_picker_npc_numbered_variant_base_resref_line_253_faf35258_descriptor_json();
const char* src_core_animation_retargeting_skeleton_template_picker_resolve_model_variant_source_resref_line_279_d9b2c09f_descriptor_json();
const char* src_core_animation_retargeting_skeleton_template_picker_matches_query_line_307_2c5a3371_descriptor_json();
const char* src_core_animation_retargeting_skeleton_template_picker_dedupe_options_line_326_cbb29e1f_descriptor_json();
const char* src_core_animation_retargeting_skeleton_template_picker_list_bundled_templates_line_338_067a378e_descriptor_json();
const char* src_core_animation_retargeting_skeleton_template_picker_list_canonical_skeleton_sources_line_398_34b733d8_descriptor_json();
const char* src_core_animation_retargeting_skeleton_template_picker_build_game_template_options_line_442_cf0ea35f_descriptor_json();
const char* src_core_animation_retargeting_skeleton_template_picker_list_skeleton_templates_line_512_254d6d6a_descriptor_json();
const char* src_core_animation_retargeting_skeleton_template_picker_option_summary_line_591_42834424_descriptor_json();

const PythonFunctionDescriptorEntry* modulefunctions_descriptors(std::size_t& count);

} // namespace ghostrigger::phase15::ghostrigger_animationretargeting
