#pragma once

#include <cstddef>

namespace ghostrigger::domain::core::assets {

#ifndef GHOSTRIGGER_ASSETS_NATIVE_FUNCTION_IMPLEMENTATION_DEFINED
#define GHOSTRIGGER_ASSETS_NATIVE_FUNCTION_IMPLEMENTATION_DEFINED
struct NativeFunctionImplementation {
    const char* project;
    const char* native_namespace;
    const char* python_file;
    const char* qualname;
    const char* callable_type;
    const char* implementation_status;
    bool native_first;
    bool python_runtime_required;
    bool python_fallback_allowed;
    const char* contract_json;
};
#endif // GHOSTRIGGER_ASSETS_NATIVE_FUNCTION_IMPLEMENTATION_DEFINED

const NativeFunctionImplementation& overrideentry_construct_line_78_d0248e73_native();
const NativeFunctionImplementation& overridelayer_construct_line_92_9a4beb57_native();
const NativeFunctionImplementation& overridelayer_scan_line_129_98c9efb9_native();
const NativeFunctionImplementation& overridelayer_has_line_165_b86069d5_native();
const NativeFunctionImplementation& overridelayer_get_line_169_5add8090_native();
const NativeFunctionImplementation& overridelayer_get_path_line_185_c262cb88_native();
const NativeFunctionImplementation& overridelayer_list_by_ext_line_190_557b8098_native();
const NativeFunctionImplementation& overridelayer_list_all_line_195_6f822cf2_native();
const NativeFunctionImplementation& overridelayer_badge_line_199_113b22d1_native();
const NativeFunctionImplementation& overridelayer_summary_line_203_64178277_native();
const NativeFunctionImplementation& overridelayer_get_model_line_219_d4fef934_native();
const NativeFunctionImplementation& overridelayer_get_model_mdx_line_226_8f1870db_native();
const NativeFunctionImplementation& overridelayer_get_texture_line_230_13b13e91_native();
const NativeFunctionImplementation& overridelayer_send_to_override_line_240_93c46add_native();
const NativeFunctionImplementation& overridelayer_delete_override_line_257_e4330164_native();
const NativeFunctionImplementation& overridelayer_get_or_fallback_line_276_1beaa118_native();
const NativeFunctionImplementation& bifindex_construct_line_134_43bf71f9_native();
const NativeFunctionImplementation& bifindex_read_line_150_3f1c64f4_native();
const NativeFunctionImplementation& erfindex_construct_line_180_fe2d145b_native();
const NativeFunctionImplementation& erfindex_read_line_208_299ccda5_native();
const NativeFunctionImplementation& erfindex_list_type_line_221_cb623c1f_native();
const NativeFunctionImplementation& erfindex_has_line_225_abaf94e1_native();
const NativeFunctionImplementation& resourcemanager_construct_line_251_4264fa12_native();
const NativeFunctionImplementation& resourcemanager_set_k1_dir_line_258_b686e51c_native();
const NativeFunctionImplementation& resourcemanager_set_k2_dir_line_276_d65c3d5d_native();
const NativeFunctionImplementation& resourcemanager_get_k1_line_294_80cd1115_native();
const NativeFunctionImplementation& resourcemanager_get_k2_line_297_aaeabce7_native();
const NativeFunctionImplementation& resourcemanager_is_ready_line_300_9449e3fd_native();
const NativeFunctionImplementation& resourcemanager_get_line_306_4982196b_native();
const NativeFunctionImplementation& resourcemanager_get_mdl_line_326_182100bd_native();
const NativeFunctionImplementation& resourcemanager_get_mdx_line_329_4915e0d9_native();
const NativeFunctionImplementation& resourcemanager_get_texture_line_332_b30518be_native();
const NativeFunctionImplementation& resourcemanager_get_txi_line_343_2fc841d3_native();
const NativeFunctionImplementation& resourcemanager_list_models_line_356_0e391e12_native();
const NativeFunctionImplementation& resourcemanager_list_textures_line_370_98c3bec0_native();
const NativeFunctionImplementation& resourcemanager_has_textures_line_381_7f8f22c0_native();
const NativeFunctionImplementation& resourcemanager_load_model_line_408_ef643ebf_native();
const NativeFunctionImplementation& resourcemanager_load_texture_image_line_432_dda8e4c2_native();
const NativeFunctionImplementation& resourcemanager_game_dir_line_453_5dd3ce5c_native();
const NativeFunctionImplementation& resourcemanager_stats_line_458_9896ccfe_native();
const NativeFunctionImplementation& gameinstall_construct_line_488_92370a38_native();
const NativeFunctionImplementation& gameinstall_index_chitin_line_509_0a35adde_native();
const NativeFunctionImplementation& gameinstall_index_texture_packs_line_560_05e39cb9_native();
const NativeFunctionImplementation& gameinstall_index_modules_line_583_6fe3848d_native();
const NativeFunctionImplementation& gameinstall_load_override_line_600_75822fc1_native();
const NativeFunctionImplementation& gameinstall_get_line_624_969575a1_native();
const NativeFunctionImplementation& gameinstall_has_line_664_c6e0101b_native();
const NativeFunctionImplementation& gameinstall_list_resrefs_line_677_863540d1_native();
const NativeFunctionImplementation& gameinstall_find_file_line_697_7f712412_native();
const NativeFunctionImplementation& gameinstall_find_dir_line_711_d26a04be_native();
const NativeFunctionImplementation& gameinstall_find_file_ci_line_727_ef094f05_native();

const NativeFunctionImplementation* instancemethods_native_functions(std::size_t& count);

} // namespace ghostrigger::domain::core::assets
