#pragma once

#include <cstddef>

namespace ghostrigger::runtime::core::host::shared::contracts {

#ifndef GHOSTRIGGER_RUNTIME_SHARED_CONTRACTS_NATIVE_FUNCTION_IMPLEMENTATION_DEFINED
#define GHOSTRIGGER_RUNTIME_SHARED_CONTRACTS_NATIVE_FUNCTION_IMPLEMENTATION_DEFINED
struct NativeFunctionImplementation {
    const char* project;
    const char* native_namespace;
    const char* python_file;
    const char* qualname;
    const char* callable_type;
    const char* implementation_status;
    bool native_first;
    bool python_runtime_required;
    bool python_fallback_allowed;
    const char* contract_json;
};
#endif // GHOSTRIGGER_RUNTIME_SHARED_CONTRACTS_NATIVE_FUNCTION_IMPLEMENTATION_DEFINED

const NativeFunctionImplementation& nativeruntimebinding_configure_abi_line_721_0249aa88_native();
const NativeFunctionImplementation& nativeruntimebinding_bind_optional_line_930_7f8fcbff_native();
const NativeFunctionImplementation& nativeruntimebinding_version_line_939_a492fa7c_native();
const NativeFunctionImplementation& nativeruntimebinding_capabilities_line_943_20a2fc8e_native();
const NativeFunctionImplementation& nativeruntimebinding_create_line_949_07e50360_native();
const NativeFunctionImplementation& nativeruntimebinding_destroy_line_953_d2f9c7f6_native();
const NativeFunctionImplementation& nativeruntimebinding_diagnostics_line_957_2ec4e54f_native();
const NativeFunctionImplementation& nativeruntimebinding_scene_create_line_960_c5625ffe_native();
const NativeFunctionImplementation& nativeruntimebinding_scene_destroy_line_966_4f86610a_native();
const NativeFunctionImplementation& nativeruntimebinding_scene_clear_line_970_b75288fd_native();
const NativeFunctionImplementation& nativeruntimebinding_scene_diagnostics_line_975_64ac946a_native();
const NativeFunctionImplementation& nativeruntimebinding_scene_add_mesh_line_980_31776fa2_native();
const NativeFunctionImplementation& nativeruntimebinding_scene_remove_mesh_line_1009_dc99df50_native();
const NativeFunctionImplementation& nativeruntimebinding_scene_update_mesh_buffers_line_1016_46d53c78_native();
const NativeFunctionImplementation& nativeruntimebinding_scene_update_mesh_vertex_range_line_1053_3faa7107_native();
const NativeFunctionImplementation& nativeruntimebinding_scene_update_mesh_index_range_line_1086_271a9fd1_native();
const NativeFunctionImplementation& nativeruntimebinding_scene_update_mesh_material_line_1118_80b3b5b8_native();
const NativeFunctionImplementation& nativeruntimebinding_scene_update_mesh_material_state_line_1148_fc147978_native();
const NativeFunctionImplementation& nativeruntimebinding_scene_update_mesh_transform_line_1172_960db4ba_native();
const NativeFunctionImplementation& nativeruntimebinding_scene_update_mesh_skinning_line_1199_955d7934_native();
const NativeFunctionImplementation& nativeruntimebinding_scene_bind_mesh_skin_palette_line_1241_c23c1725_native();
const NativeFunctionImplementation& nativeruntimebinding_scene_add_texture_line_1266_883f9cb8_native();
const NativeFunctionImplementation& nativeruntimebinding_scene_remove_texture_line_1293_e5499d12_native();
const NativeFunctionImplementation& nativeruntimebinding_scene_update_texture_data_line_1304_d7dee4b0_native();
const NativeFunctionImplementation& nativeruntimebinding_scene_update_texture_region_line_1336_d83c0eba_native();
const NativeFunctionImplementation& nativeruntimebinding_scene_add_skin_palette_line_1375_ebbd4670_native();
const NativeFunctionImplementation& nativeruntimebinding_scene_update_skin_palette_line_1396_dd27fedb_native();
const NativeFunctionImplementation& nativeruntimebinding_scene_update_skin_palette_matrices_line_1420_e5cff1e4_native();
const NativeFunctionImplementation& nativeruntimebinding_scene_update_skin_palette_matrix_range_line_1451_f6376150_native();
const NativeFunctionImplementation& nativeruntimebinding_scene_remove_skin_palette_line_1484_b408be41_native();
const NativeFunctionImplementation& nativeruntimebinding_scene_update_animation_sample_line_1495_b38b4e3f_native();
const NativeFunctionImplementation& nativeruntimebinding_cpu_skin_vertices_line_1530_1581f9d3_native();
const NativeFunctionImplementation& nativeruntimebinding_sample_animation_palette_line_1612_e7a71dd2_native();
const NativeFunctionImplementation& nativeruntimebinding_scene_render_frame_line_1659_8dd82d26_native();
const NativeFunctionImplementation& nativeruntimebinding_scene_pick_bounds_line_1709_b491aabe_native();
const NativeFunctionImplementation& nativeruntimebinding_scene_query_bounds_line_1746_aac6f19a_native();
const NativeFunctionImplementation& nativeruntimebinding_scene_assemble_draw_list_line_1782_e9dcf63c_native();
const NativeFunctionImplementation& nativeruntimebinding_scene_record_commands_line_1843_0a9c9d33_native();
const NativeFunctionImplementation& nativeruntimebinding_scene_get_resource_residency_line_1882_a33e5b65_native();
const NativeFunctionImplementation& nativeruntimebinding_scene_get_resource_upload_plan_line_1929_809323c6_native();
const NativeFunctionImplementation& nativeruntimebinding_scene_allocate_device_resources_line_1973_0a92942f_native();
const NativeFunctionImplementation& nativeruntimebinding_scene_commit_device_resource_uploads_line_2020_a224b7bc_native();
const NativeFunctionImplementation& nativeruntimebinding_scene_transition_device_resources_line_2064_9bfb045f_native();
const NativeFunctionImplementation& nativeruntimebinding_scene_get_gpu_skinning_dispatch_line_2108_2cb7a72a_native();
const NativeFunctionImplementation& nativeruntimebinding_scene_get_cpu_skinning_fallback_batch_line_2163_4253bf89_native();
const NativeFunctionImplementation& nativeruntimebinding_scene_execute_cpu_skinning_fallback_line_2219_18c56fab_native();
const NativeFunctionImplementation& nativeruntimebinding_scene_read_cpu_skinned_positions_line_2259_98cc62c8_native();
const NativeFunctionImplementation& nativeviewportrenderer_construct_line_26_0093d29a_native();
const NativeFunctionImplementation& nativeviewportrenderer_del_line_57_76461ea5_native();
const NativeFunctionImplementation& nativeviewportrenderer_is_available_line_63_bdd60308_native();
const NativeFunctionImplementation& nativeviewportrenderer_get_capabilities_line_66_813b9d4c_native();
const NativeFunctionImplementation& nativeviewportrenderer_get_diagnostics_line_86_4739532e_native();
const NativeFunctionImplementation& nativeviewportrenderer_render_line_108_31ebc7bd_native();
const NativeFunctionImplementation& nativeviewportrenderer_clear_caches_line_130_36cfa52b_native();
const NativeFunctionImplementation& nativeviewportrenderer_upload_mesh_line_143_da2064ce_native();
const NativeFunctionImplementation& nativeviewportrenderer_update_mesh_vertex_range_line_213_0e92e7dc_native();
const NativeFunctionImplementation& nativeviewportrenderer_update_mesh_index_range_line_234_f4249aa2_native();
const NativeFunctionImplementation& nativeviewportrenderer_update_mesh_material_state_line_255_3b94d6f9_native();
const NativeFunctionImplementation& nativeviewportrenderer_upload_material_texture_line_281_cc6c38fd_native();
const NativeFunctionImplementation& nativeviewportrenderer_query_bounds_line_290_b6078e3b_native();
const NativeFunctionImplementation& nativeviewportrenderer_assemble_draw_list_line_310_20c75023_native();
const NativeFunctionImplementation& nativeviewportrenderer_record_commands_line_334_0eacd2b5_native();
const NativeFunctionImplementation& nativeviewportrenderer_get_resource_residency_line_358_b8306c1d_native();
const NativeFunctionImplementation& nativeviewportrenderer_get_resource_upload_plan_line_380_9a2bfc71_native();
const NativeFunctionImplementation& nativeviewportrenderer_allocate_device_resources_line_393_73d8b565_native();
const NativeFunctionImplementation& nativeviewportrenderer_commit_device_resource_uploads_line_406_7f9b8deb_native();
const NativeFunctionImplementation& nativeviewportrenderer_transition_device_resources_line_419_555882d8_native();
const NativeFunctionImplementation& nativeviewportrenderer_get_gpu_skinning_dispatch_line_432_9090b722_native();
const NativeFunctionImplementation& nativeviewportrenderer_get_cpu_skinning_fallback_batch_line_454_d2caac3f_native();
const NativeFunctionImplementation& nativeviewportrenderer_execute_cpu_skinning_fallback_line_476_b4eb9fcb_native();
const NativeFunctionImplementation& nativeviewportrenderer_read_cpu_skinned_positions_line_498_14435927_native();
const NativeFunctionImplementation& nativeviewportrenderer_pick_line_521_d575d1c3_native();
const NativeFunctionImplementation& nativeviewportrenderer_upload_texture_line_570_0dd4ae86_native();
const NativeFunctionImplementation& nativeviewportrenderer_update_texture_region_line_607_425250e5_native();
const NativeFunctionImplementation& nativeviewportrenderer_release_resource_line_643_0e091bba_native();
const NativeFunctionImplementation& nativeviewportrenderer_upload_skin_palette_line_679_7f87673c_native();
const NativeFunctionImplementation& nativeviewportrenderer_update_skin_palette_line_696_4deba837_native();
const NativeFunctionImplementation& nativeviewportrenderer_update_skin_palette_matrices_line_726_60e99b28_native();
const NativeFunctionImplementation& nativeviewportrenderer_update_skin_palette_matrix_range_line_746_5ea7b116_native();
const NativeFunctionImplementation& nativeviewportrenderer_bind_mesh_skin_palette_line_774_efd8d949_native();
const NativeFunctionImplementation& nativeviewportrenderer_update_animation_sample_line_796_e0960bf2_native();
const NativeFunctionImplementation& nativeviewportrenderer_cpu_skin_vertices_line_821_e9cf1b4a_native();
const NativeFunctionImplementation& nativeviewportrenderer_sample_animation_palette_line_843_a0212566_native();
const NativeFunctionImplementation& nativeviewportrenderer_shutdown_line_861_421b7b5d_native();
const NativeFunctionImplementation& filewriterport_write_bytes_line_13_386e4596_native();
const NativeFunctionImplementation& filewriterport_write_text_line_16_f4a4863f_native();
const NativeFunctionImplementation& scriptcompilerport_compile_script_line_27_6df94b86_native();
const NativeFunctionImplementation& texturedecoder_decode_texture_line_27_e83bd02c_native();
const NativeFunctionImplementation& renderercapabilities_to_dict_line_56_96c9be59_native();
const NativeFunctionImplementation& renderercapabilities_status_text_line_152_fec5213f_native();
const NativeFunctionImplementation& renderercapabilities_supports_display_mode_line_158_98c34e96_native();
const NativeFunctionImplementation& iviewportrenderer_is_available_line_16_d8d6e763_native();
const NativeFunctionImplementation& iviewportrenderer_get_capabilities_line_20_71760aee_native();
const NativeFunctionImplementation& iviewportrenderer_constructialize_line_23_3c747f18_native();
const NativeFunctionImplementation& iviewportrenderer_create_surface_widget_line_26_1ab290cd_native();
const NativeFunctionImplementation& iviewportrenderer_resize_line_29_a241a354_native();
const NativeFunctionImplementation& iviewportrenderer_render_line_33_528a49c1_native();
const NativeFunctionImplementation& iviewportrenderer_render_overlay_line_36_0ea321a6_native();
const NativeFunctionImplementation& iviewportrenderer_pick_line_39_e82673ef_native();
const NativeFunctionImplementation& iviewportrenderer_shutdown_line_42_ff2b66e5_native();
const NativeFunctionImplementation& iviewportrenderer_get_diagnostics_line_47_5c5843ca_native();
const NativeFunctionImplementation& iviewportrenderer_upload_mesh_line_57_1fd39e44_native();
const NativeFunctionImplementation& iviewportrenderer_upload_texture_line_60_26f8032d_native();
const NativeFunctionImplementation& iviewportrenderer_release_resource_line_63_107b6898_native();
const NativeFunctionImplementation& iviewportrenderer_invalidate_all_line_66_8f695e92_native();

const NativeFunctionImplementation* instancemethods_native_functions(std::size_t& count);

} // namespace ghostrigger::runtime::core::host::shared::contracts
