#pragma once

#include <cstddef>

namespace ghostrigger::phase15::ghostrigger_meshtools {

using PythonFunctionDescriptorJson = const char* (*)();

struct PythonFunctionDescriptorEntry {
    const char* python_file;
    const char* qualname;
    const char* function_type;
    PythonFunctionDescriptorJson descriptor_json;
};

const char* src_mesh_tools_mesh_attach_attach_selected_meshes_line_10_282c2932_descriptor_json();
const char* src_mesh_tools_mesh_attach_is_mesh_line_86_a952fc27_descriptor_json();
const char* src_mesh_tools_mesh_attach_world_vertices_line_90_54e74ea7_descriptor_json();
const char* src_mesh_tools_mesh_attach_extend_vertex_channel_line_101_6724dfba_descriptor_json();
const char* src_mesh_tools_mesh_attach_compatible_channels_line_109_22108ab8_descriptor_json();
const char* src_mesh_tools_mesh_attach_combined_name_line_116_4a578f66_descriptor_json();
const char* src_mesh_tools_mesh_border_cap_selected_borders_line_10_6a74d032_descriptor_json();
const char* src_mesh_tools_mesh_border_default_material_for_cap_line_49_b1a74bea_descriptor_json();
const char* src_mesh_tools_mesh_border_refresh_mesh_line_61_8b693d30_descriptor_json();
const char* src_mesh_tools_mesh_border_mesh_id_line_66_0f33d3c3_descriptor_json();
const char* src_mesh_tools_mesh_bridge_bridge_selected_line_10_a47a2001_descriptor_json();
const char* src_mesh_tools_mesh_bridge_strip_closing_vertex_line_66_79d80aad_descriptor_json();
const char* src_mesh_tools_mesh_connect_connect_selected_line_10_0e1eb981_descriptor_json();
const char* src_mesh_tools_mesh_connect_connect_vertices_line_19_ecbd1e9b_descriptor_json();
const char* src_mesh_tools_mesh_connect_connect_edges_line_40_19ec004e_descriptor_json();
const char* src_mesh_tools_mesh_connect_midpoint_vertex_line_61_303e08da_descriptor_json();
const char* src_mesh_tools_mesh_connect_mesh_id_line_83_28c2e0ed_descriptor_json();
const char* src_mesh_tools_mesh_element_select_element_for_face_line_8_d155980b_descriptor_json();
const char* src_mesh_tools_mesh_history_snapshot_mesh_line_78_b7387527_descriptor_json();
const char* src_mesh_tools_mesh_history_restore_snapshot_line_85_845dec61_descriptor_json();
const char* src_mesh_tools_mesh_operations_delete_selected_line_16_26a07979_descriptor_json();
const char* src_mesh_tools_mesh_operations_remove_isolated_vertices_line_52_01d0d331_descriptor_json();
const char* src_mesh_tools_mesh_operations_flip_normals_line_69_feb11d98_descriptor_json();
const char* src_mesh_tools_mesh_operations_recalculate_normals_line_84_7a5932ab_descriptor_json();
const char* src_mesh_tools_mesh_operations_detach_selection_line_90_fbaffdc2_descriptor_json();
const char* src_mesh_tools_mesh_operations_selected_face_indices_line_121_5aeb8bf8_descriptor_json();
const char* src_mesh_tools_mesh_operations_mesh_id_line_138_1770cbc9_descriptor_json();
const char* src_mesh_tools_mesh_preservation_remap_vertex_attributes_line_10_32df41d5_descriptor_json();
const char* src_mesh_tools_mesh_preservation_filter_face_attributes_line_42_de0b48af_descriptor_json();
const char* src_mesh_tools_mesh_preservation_append_face_attributes_line_52_2db65328_descriptor_json();
const char* src_mesh_tools_mesh_selection_convert_convert_selection_line_10_c761e266_descriptor_json();
const char* src_mesh_tools_mesh_selection_convert_loop_has_selected_edge_line_85_49f1deff_descriptor_json();
const char* src_mesh_tools_mesh_topology_normalize_edge_line_13_80180e3b_descriptor_json();
const char* src_mesh_tools_mesh_topology_vec_sub_line_20_e6d5b01d_descriptor_json();
const char* src_mesh_tools_mesh_topology_cross_line_24_ddd174d9_descriptor_json();
const char* src_mesh_tools_mesh_topology_length_line_32_9c936e17_descriptor_json();
const char* src_mesh_tools_mesh_topology_normal_line_36_3a49f3b4_descriptor_json();
const char* src_mesh_tools_mesh_topology_face_edges_line_272_c9079cd7_descriptor_json();
const char* src_mesh_tools_mesh_validation_validate_mesh_line_9_6f28607f_descriptor_json();
const char* src_mesh_tools_mesh_weld_weld_selected_vertices_line_14_124c1c61_descriptor_json();
const char* src_mesh_tools_mesh_weld_target_weld_vertex_line_31_2877ab55_descriptor_json();
const char* src_mesh_tools_mesh_weld_target_weld_edge_line_45_aef313df_descriptor_json();
const char* src_mesh_tools_mesh_weld_cluster_vertices_line_57_392a6c07_descriptor_json();
const char* src_mesh_tools_mesh_weld_collapse_groups_line_81_809ae7f0_descriptor_json();
const char* src_mesh_tools_mesh_weld_compact_vertex_attributes_line_132_579b86ca_descriptor_json();
const char* src_mesh_tools_mesh_weld_distance_line_139_1cbd57cc_descriptor_json();

const PythonFunctionDescriptorEntry* modulefunctions_descriptors(std::size_t& count);

} // namespace ghostrigger::phase15::ghostrigger_meshtools
