#pragma once

#include <cstddef>

namespace ghostrigger::phase15::ghostrigger_assets {

using PythonFunctionDescriptorJson = const char* (*)();

struct PythonFunctionDescriptorEntry {
    const char* python_file;
    const char* qualname;
    const char* function_type;
    PythonFunctionDescriptorJson descriptor_json;
};

const char* src_core_assets_override_layer_overrideentry_init_line_78_d0248e73_descriptor_json();
const char* src_core_assets_override_layer_overridelayer_init_line_92_9a4beb57_descriptor_json();
const char* src_core_assets_override_layer_overridelayer_scan_line_129_98c9efb9_descriptor_json();
const char* src_core_assets_override_layer_overridelayer_has_line_165_b86069d5_descriptor_json();
const char* src_core_assets_override_layer_overridelayer_get_line_169_5add8090_descriptor_json();
const char* src_core_assets_override_layer_overridelayer_get_path_line_185_c262cb88_descriptor_json();
const char* src_core_assets_override_layer_overridelayer_list_by_ext_line_190_557b8098_descriptor_json();
const char* src_core_assets_override_layer_overridelayer_list_all_line_195_6f822cf2_descriptor_json();
const char* src_core_assets_override_layer_overridelayer_badge_line_199_113b22d1_descriptor_json();
const char* src_core_assets_override_layer_overridelayer_summary_line_203_64178277_descriptor_json();
const char* src_core_assets_override_layer_overridelayer_get_model_line_219_d4fef934_descriptor_json();
const char* src_core_assets_override_layer_overridelayer_get_model_mdx_line_226_8f1870db_descriptor_json();
const char* src_core_assets_override_layer_overridelayer_get_texture_line_230_13b13e91_descriptor_json();
const char* src_core_assets_override_layer_overridelayer_send_to_override_line_240_93c46add_descriptor_json();
const char* src_core_assets_override_layer_overridelayer_delete_override_line_257_e4330164_descriptor_json();
const char* src_core_assets_override_layer_overridelayer_get_or_fallback_line_276_1beaa118_descriptor_json();
const char* src_core_assets_resource_manager_bifindex_init_line_134_43bf71f9_descriptor_json();
const char* src_core_assets_resource_manager_bifindex_read_line_150_3f1c64f4_descriptor_json();
const char* src_core_assets_resource_manager_erfindex_init_line_180_fe2d145b_descriptor_json();
const char* src_core_assets_resource_manager_erfindex_read_line_208_299ccda5_descriptor_json();
const char* src_core_assets_resource_manager_erfindex_list_type_line_221_cb623c1f_descriptor_json();
const char* src_core_assets_resource_manager_erfindex_has_line_225_abaf94e1_descriptor_json();
const char* src_core_assets_resource_manager_resourcemanager_init_line_251_4264fa12_descriptor_json();
const char* src_core_assets_resource_manager_resourcemanager_set_k1_dir_line_258_b686e51c_descriptor_json();
const char* src_core_assets_resource_manager_resourcemanager_set_k2_dir_line_276_d65c3d5d_descriptor_json();
const char* src_core_assets_resource_manager_resourcemanager_get_k1_line_294_80cd1115_descriptor_json();
const char* src_core_assets_resource_manager_resourcemanager_get_k2_line_297_aaeabce7_descriptor_json();
const char* src_core_assets_resource_manager_resourcemanager_is_ready_line_300_9449e3fd_descriptor_json();
const char* src_core_assets_resource_manager_resourcemanager_get_line_306_4982196b_descriptor_json();
const char* src_core_assets_resource_manager_resourcemanager_get_mdl_line_326_182100bd_descriptor_json();
const char* src_core_assets_resource_manager_resourcemanager_get_mdx_line_329_4915e0d9_descriptor_json();
const char* src_core_assets_resource_manager_resourcemanager_get_texture_line_332_b30518be_descriptor_json();
const char* src_core_assets_resource_manager_resourcemanager_get_txi_line_343_2fc841d3_descriptor_json();
const char* src_core_assets_resource_manager_resourcemanager_list_models_line_356_0e391e12_descriptor_json();
const char* src_core_assets_resource_manager_resourcemanager_list_textures_line_370_98c3bec0_descriptor_json();
const char* src_core_assets_resource_manager_resourcemanager_has_textures_line_381_7f8f22c0_descriptor_json();
const char* src_core_assets_resource_manager_resourcemanager_load_model_line_408_ef643ebf_descriptor_json();
const char* src_core_assets_resource_manager_resourcemanager_load_texture_image_line_432_dda8e4c2_descriptor_json();
const char* src_core_assets_resource_manager_resourcemanager_game_dir_line_453_5dd3ce5c_descriptor_json();
const char* src_core_assets_resource_manager_resourcemanager_stats_line_458_9896ccfe_descriptor_json();
const char* src_core_assets_resource_manager_gameinstall_init_line_488_92370a38_descriptor_json();
const char* src_core_assets_resource_manager_gameinstall_index_chitin_line_509_0a35adde_descriptor_json();
const char* src_core_assets_resource_manager_gameinstall_index_texture_packs_line_560_05e39cb9_descriptor_json();
const char* src_core_assets_resource_manager_gameinstall_index_modules_line_583_6fe3848d_descriptor_json();
const char* src_core_assets_resource_manager_gameinstall_load_override_line_600_75822fc1_descriptor_json();
const char* src_core_assets_resource_manager_gameinstall_get_line_624_969575a1_descriptor_json();
const char* src_core_assets_resource_manager_gameinstall_has_line_664_c6e0101b_descriptor_json();
const char* src_core_assets_resource_manager_gameinstall_list_resrefs_line_677_863540d1_descriptor_json();
const char* src_core_assets_resource_manager_gameinstall_find_file_line_697_7f712412_descriptor_json();
const char* src_core_assets_resource_manager_gameinstall_find_dir_line_711_d26a04be_descriptor_json();
const char* src_core_assets_resource_manager_gameinstall_find_file_ci_line_727_ef094f05_descriptor_json();

const PythonFunctionDescriptorEntry* instancemethods_descriptors(std::size_t& count);

} // namespace ghostrigger::phase15::ghostrigger_assets
