#pragma once

#include <cstddef>

namespace ghostrigger::phase15::ghostrigger_assets {

using PythonFunctionDescriptorJson = const char* (*)();

struct PythonFunctionDescriptorEntry {
    const char* python_file;
    const char* qualname;
    const char* function_type;
    PythonFunctionDescriptorJson descriptor_json;
};

const char* src_core_assets_asset_preview_import_model_data_line_38_b1b403fc_descriptor_json();
const char* src_core_assets_asset_preview_import_composite_workflow_line_46_a02ef67b_descriptor_json();
const char* src_core_assets_asset_preview_import_kotor_loader_line_54_88966d41_descriptor_json();
const char* src_core_assets_asset_preview_scene_metadata_line_246_ae317da8_descriptor_json();
const char* src_core_assets_asset_preview_slot_model_line_254_a6e52b2d_descriptor_json();
const char* src_core_assets_asset_preview_all_nodes_line_261_078f027a_descriptor_json();
const char* src_core_assets_asset_preview_node_name_line_271_0710a1bd_descriptor_json();
const char* src_core_assets_asset_preview_node_world_transform_line_275_086fd89c_descriptor_json();
const char* src_core_assets_asset_preview_normalise_quat_line_286_b849af25_descriptor_json();
const char* src_core_assets_asset_preview_matrix_from_transform_line_294_05e20b71_descriptor_json();
const char* src_core_assets_asset_preview_socket_names_line_308_def6bb54_descriptor_json();
const char* src_core_assets_asset_preview_resolve_socket_line_318_6da45f08_descriptor_json();
const char* src_core_assets_asset_preview_model_identity_line_332_1a2b3ba9_descriptor_json();
const char* src_core_assets_asset_preview_animation_name_line_340_07db619d_descriptor_json();
const char* src_core_assets_asset_preview_animation_length_line_356_c4dd0a42_descriptor_json();
const char* src_core_assets_asset_preview_model_animations_line_375_2bdfe77f_descriptor_json();
const char* src_core_assets_asset_preview_mesh_nodes_line_387_547c049d_descriptor_json();
const char* src_core_assets_asset_preview_clean_token_line_400_62e1ef0f_descriptor_json();
const char* src_core_assets_asset_preview_node_textures_line_404_b8a5324e_descriptor_json();
const char* src_core_assets_asset_preview_preview_source_model_line_421_17140c05_descriptor_json();
const char* src_core_assets_asset_preview_slot_entry_line_429_4f9ec898_descriptor_json();
const char* src_core_assets_asset_preview_slot_game_version_line_436_798eb400_descriptor_json();
const char* src_core_assets_asset_preview_slot_resref_line_441_902097a4_descriptor_json();
const char* src_core_assets_asset_preview_animation_group_line_446_cf9511a9_descriptor_json();
const char* src_core_assets_asset_preview_clip_loop_default_line_477_cda199cc_descriptor_json();
const char* src_core_assets_asset_preview_motion_assignment_line_481_05169476_descriptor_json();
const char* src_core_assets_asset_preview_add_clip_line_488_ff2fed7e_descriptor_json();
const char* src_core_assets_asset_preview_group_clips_line_520_800ab937_descriptor_json();
const char* src_core_assets_asset_preview_default_clip_line_531_cd41f185_descriptor_json();
const char* src_core_assets_asset_preview_write_preview_metadata_line_540_b8b8502d_descriptor_json();
const char* src_core_assets_asset_preview_load_character_preview_line_573_376e8ff1_descriptor_json();
const char* src_core_assets_asset_preview_refresh_character_preview_line_649_401ca870_descriptor_json();
const char* src_core_assets_asset_preview_available_attachment_sockets_line_680_dac81bf1_descriptor_json();
const char* src_core_assets_asset_preview_attach_item_to_preview_line_687_569c75cf_descriptor_json();
const char* src_core_assets_asset_preview_issue_payload_line_777_4a676c71_descriptor_json();
const char* src_core_assets_asset_preview_attachment_issue_line_789_35f34bff_descriptor_json();
const char* src_core_assets_asset_preview_socket_side_line_810_40de0dbf_descriptor_json();
const char* src_core_assets_asset_preview_expected_attachment_side_line_814_f7a7be4b_descriptor_json();
const char* src_core_assets_asset_preview_is_lightsaber_attachment_line_826_ea01152d_descriptor_json();
const char* src_core_assets_asset_preview_requires_bullet_hook_line_837_8d41d196_descriptor_json();
const char* src_core_assets_asset_preview_matrix_close_line_848_06e4d55b_descriptor_json();
const char* src_core_assets_asset_preview_validate_attachment_overlay_line_859_d2eddd05_descriptor_json();
const char* src_core_assets_asset_preview_load_exported_preview_model_line_1013_17de13b5_descriptor_json();
const char* src_core_assets_asset_preview_model_parity_summary_line_1021_7e9fe15e_descriptor_json();
const char* src_core_assets_asset_preview_delta_line_1053_ddb38c77_descriptor_json();
const char* src_core_assets_asset_preview_delta_payload_line_1074_08c3bd71_descriptor_json();
const char* src_core_assets_asset_preview_compare_export_preview_parity_line_1086_9bf4bd2c_descriptor_json();
const char* src_core_assets_asset_preview_build_animation_workbench_line_1286_eca1719b_descriptor_json();
const char* src_core_assets_asset_preview_find_workbench_clip_line_1404_e438c57b_descriptor_json();
const char* src_core_assets_asset_preview_play_preview_animation_line_1423_8f33236c_descriptor_json();
const char* src_core_assets_asset_preview_scrub_preview_animation_line_1483_1d637b1d_descriptor_json();
const char* src_core_assets_resource_manager_key_line_98_0520e2cf_descriptor_json();
const char* src_core_assets_resource_manager_texture_name_candidates_line_110_f1e75d5f_descriptor_json();
const char* src_core_assets_resource_manager_decode_texture_line_748_23e8416a_descriptor_json();
const char* src_core_assets_resource_manager_tpc_uncompressed_txi_line_877_211ae331_descriptor_json();
const char* src_core_assets_resource_manager_tpc_info_line_912_ce2f9944_descriptor_json();
const char* src_core_assets_resource_manager_is_tpc_line_943_3763289e_descriptor_json();
const char* src_core_assets_resource_manager_get_manager_line_1014_7b60640d_descriptor_json();
const char* src_core_assets_resource_manager_reset_manager_line_1024_a1b1addf_descriptor_json();
const char* src_core_assets_resource_manager_resolve_model_textures_line_1034_771e23a2_descriptor_json();
const char* src_core_assets_resource_manager_audit_model_textures_line_1149_37515999_descriptor_json();
const char* src_core_assets_resource_manager_identify_texture_source_line_1240_5185a261_descriptor_json();
const char* src_core_assets_resource_manager_parse_txi_for_alpha_line_1278_ef05cf3e_descriptor_json();
const char* src_core_assets_resource_manager_apply_alpha_fix_line_1313_55e1139e_descriptor_json();

const PythonFunctionDescriptorEntry* modulefunctions_descriptors(std::size_t& count);

} // namespace ghostrigger::phase15::ghostrigger_assets
