"""Unreal-target animation retargeting helpers.

The viewport can already display a pose generated by one model on another
model when node names happen to line up. This module makes that explicit and
safe: rotations and motion deltas are transferred, target bind-pose bone
offsets are preserved, and scale controllers are ignored by default so the
target model does not change height, width, or bone length.
"""

from __future__ import annotations

import copy
from dataclasses import dataclass, field
import math
from typing import Dict, Iterable, Optional

from src.core.qt_core.animation.animation_engine import AnimPose, NodePose
from src.core.qt_core.geometry.model_data import Animation


_ALIASES: Dict[str, tuple[str, ...]] = {
    "rootdummy": ("root", "root_g", "dummyroot"),
    "pelvis_g": ("pelvis", "hips", "hip_g"),
    "spine_g": ("spine_01", "spine", "spine_g"),
    "torso_g": ("spine_02", "spine_01", "spine_g", "chest_g"),
    "torsoupr_g": ("spine1", "spine_03", "spine_04", "spine_01", "chest"),
    "neck_g": ("neck", "neck_01", "necklwr_g"),
    "necklwr_g": ("neck", "neck_01"),
    "headhook": ("head", "head_g", "headhook_g"),
    "head_g": ("head",),
    "rcollar_g": ("clavicle_r", "shoulder_r", "r_shoulder"),
    "rbicep_g": ("upperarm_r", "r_upperarm"),
    "rbicepl_g": ("lowerarm_r", "r_forearm"),
    "rshoulder": ("upperarm_r", "r_upperarm"),
    "lbicep_g": ("upperarm_l", "l_upperarm"),
    "lcollar_g": ("clavicle_l", "shoulder_l", "l_shoulder"),
    "lbicepl_g": ("lowerarm_l", "l_forearm"),
    "lshoulder": ("upperarm_l", "l_upperarm"),
    "rforearm_g": ("lowerarm_r", "r_forearm"),
    "rforearm": ("lowerarm_r", "r_forearm"),
    "lforearm_g": ("lowerarm_l", "l_forearm"),
    "lforearm": ("lowerarm_l", "l_forearm"),
    "rhand": ("r_hand", "rhand_g", "hand_r"),
    "lhand": ("l_hand", "lhand_g", "hand_l"),
    "rhand_g": ("hand_r", "r_hand"),
    "lhand_g": ("hand_l", "l_hand"),
    "rthigh_g": ("thigh_r", "r_thigh"),
    "rthigh": ("thigh_r", "r_thigh"),
    "lthigh_g": ("thigh_l", "l_thigh"),
    "lthigh": ("thigh_l", "l_thigh"),
    "rshin_g": ("calf_r", "lowerleg_r", "r_calf"),
    "rshin": ("calf_r", "lowerleg_r", "r_calf"),
    "lshin_g": ("calf_l", "lowerleg_l", "l_calf"),
    "lshin": ("calf_l", "lowerleg_l", "l_calf"),
    "rfoot_g": ("rfoot", "foot_r", "r_foot"),
    "rfoot": ("foot_r", "r_foot"),
    "lfoot_g": ("lfoot", "foot_l", "l_foot"),
    "lfoot": ("foot_l", "l_foot"),
    "rfoott_g": ("ball_r", "toe_r", "r_toe"),
    "rfoott": ("ball_r", "toe_r", "r_toe"),
    "lfoott_g": ("ball_l", "toe_l", "l_toe"),
    "lfoott": ("ball_l", "toe_l", "l_toe"),
}

def _is_null_helper_name(name: str) -> bool:
    key = str(name or "").strip().lower()
    return "dummy" in key or "hook" in key


@dataclass(frozen=True)
class RetargetConfig:
    """Controls how poses are transferred between skeletons."""

    preserve_model_scale: bool = True
    ignore_scale_keys: bool = True
    copy_material_animation: bool = True
    allow_unmapped_nodes: bool = False
    root_motion_scale: float = 1.0
    interpolate_unmapped_target_bones: bool = True
    bake_sample_rate: float = 30.0
    twist_bone_rotation_weight: float = 0.35


@dataclass(frozen=True)
class BoneMappingReport:
    source_model: str = ""
    target_model: str = ""
    mapping: Dict[str, str] = field(default_factory=dict)
    exact_matches: int = 0
    alias_matches: int = 0
    manual_matches: int = 0
    missing_source: tuple[str, ...] = ()
    missing_target: tuple[str, ...] = ()
    derived_target: tuple[str, ...] = ()

    @property
    def matched_count(self) -> int:
        return len(self.mapping)

    @property
    def derived_count(self) -> int:
        return len(self.derived_target)


@dataclass(frozen=True)
class RetargetResult:
    pose: AnimPose
    report: BoneMappingReport


def _nodes_by_name(model) -> Dict[str, object]:
    nodes = list(model.all_nodes()) if hasattr(model, "all_nodes") else []
    return {
        str(getattr(n, "name", "") or "").lower(): n
        for n in nodes
        if getattr(n, "name", "")
    }


def _target_nodes(model) -> list[object]:
    return list(model.all_nodes()) if hasattr(model, "all_nodes") else []


def _node_key(node: object) -> str:
    return str(getattr(node, "name", "") or "").lower()


def _is_skeletal_node(node: object) -> bool:
    if bool(getattr(node, "is_mesh", False)):
        return False
    key = _node_key(node)
    if _is_null_helper_name(key):
        return False
    if key.startswith("ik_") or key in {"interaction", "center_of_mass"}:
        return False
    if getattr(node, "_hide_skeleton_overlay", False):
        return False
    return True


def _candidate_names(source_name: str) -> Iterable[str]:
    key = source_name.lower()
    yield key
    for alias in _ALIASES.get(key, ()):
        yield alias.lower()
    for src, aliases in _ALIASES.items():
        if key in aliases:
            yield src
            for alias in aliases:
                yield alias.lower()


def _clean_manual_mapping(manual_mapping: Optional[dict[str, str]]) -> Dict[str, str]:
    if not manual_mapping:
        return {}
    out: Dict[str, str] = {}
    for src, dst in manual_mapping.items():
        src_key = str(src or "").strip().lower()
        dst_key = str(dst or "").strip().lower()
        if src_key and dst_key:
            out[src_key] = dst_key
    return out


def build_bone_map(
    source_model,
    target_model,
    manual_mapping: Optional[dict[str, str]] = None,
) -> BoneMappingReport:
    """Build a conservative source-node-name to target-node-name map."""
    source_root = getattr(source_model, "root_node", None)
    target_root = getattr(target_model, "root_node", None)
    src_nodes = {
        key: node
        for key, node in _nodes_by_name(source_model).items()
        if node is not source_root and _is_skeletal_node(node)
    }
    dst_nodes = {
        key: node
        for key, node in _nodes_by_name(target_model).items()
        if node is not target_root and _is_skeletal_node(node)
    }
    manual = _clean_manual_mapping(manual_mapping)
    mapping: Dict[str, str] = {}
    exact = 0
    alias = 0
    manual_count = 0

    for src_name in src_nodes:
        manual_target = manual.get(src_name, "")
        if manual_target and manual_target in dst_nodes:
            mapping[src_name] = manual_target
            manual_count += 1
            continue

        target_name = ""
        for candidate in _candidate_names(src_name):
            if candidate in dst_nodes:
                target_name = candidate
                break
        if not target_name:
            continue
        mapping[src_name] = target_name
        if target_name == src_name:
            exact += 1
        else:
            alias += 1

    missing_source = tuple(sorted(src for src in src_nodes if src not in mapping))
    mapped_targets = set(mapping.values())
    derived_target = _derived_target_bone_keys(target_model, mapped_targets)
    missing_target = tuple(sorted(dst for dst in dst_nodes if dst not in mapped_targets and dst not in derived_target))
    return BoneMappingReport(
        source_model=str(getattr(source_model, "name", "") or ""),
        target_model=str(getattr(target_model, "name", "") or ""),
        mapping=mapping,
        exact_matches=exact,
        alias_matches=alias,
        manual_matches=manual_count,
        missing_source=missing_source,
        missing_target=missing_target,
        derived_target=derived_target,
    )


def _sub3(a, b) -> tuple[float, float, float]:
    return (
        float(a[0]) - float(b[0]),
        float(a[1]) - float(b[1]),
        float(a[2]) - float(b[2]),
    )


def _add3(a, b, scale: float = 1.0) -> tuple[float, float, float]:
    return (
        float(a[0]) + float(b[0]) * scale,
        float(a[1]) + float(b[1]) * scale,
        float(a[2]) + float(b[2]) * scale,
    )


def _mul3(a, scale: float) -> tuple[float, float, float]:
    return (float(a[0]) * scale, float(a[1]) * scale, float(a[2]) * scale)


def _sub_quat(a, b) -> float:
    return max(abs(float(x) - float(y)) for x, y in zip(a, b))


def _normal_quat(q) -> tuple[float, float, float, float]:
    x, y, z, w = (float(q[0]), float(q[1]), float(q[2]), float(q[3]))
    length = math.sqrt(x * x + y * y + z * z + w * w)
    if length <= 1e-8:
        return (0.0, 0.0, 0.0, 1.0)
    return (x / length, y / length, z / length, w / length)


def _quat_conjugate(q) -> tuple[float, float, float, float]:
    x, y, z, w = _normal_quat(q)
    return (-x, -y, -z, w)


def _quat_mul(a, b) -> tuple[float, float, float, float]:
    ax, ay, az, aw = _normal_quat(a)
    bx, by, bz, bw = _normal_quat(b)
    return _normal_quat((
        aw * bx + ax * bw + ay * bz - az * by,
        aw * by - ax * bz + ay * bw + az * bx,
        aw * bz + ax * by - ay * bx + az * bw,
        aw * bw - ax * bx - ay * by - az * bz,
    ))


def _retarget_rotation(src_pose_rot, src_bind_rot, dst_bind_rot) -> tuple[float, float, float, float]:
    """Apply source bind-relative rotation to the target bind orientation."""
    src_delta = _quat_mul(src_pose_rot, _quat_conjugate(src_bind_rot))
    return _quat_mul(src_delta, dst_bind_rot)


def _slerp_quat(a, b, t: float) -> tuple[float, float, float, float]:
    ax, ay, az, aw = _normal_quat(a)
    bx, by, bz, bw = _normal_quat(b)
    t = max(0.0, min(1.0, float(t)))
    dot = ax * bx + ay * by + az * bz + aw * bw
    if dot < 0.0:
        bx, by, bz, bw = -bx, -by, -bz, -bw
        dot = -dot
    if dot > 0.9995:
        out = (
            ax + t * (bx - ax),
            ay + t * (by - ay),
            az + t * (bz - az),
            aw + t * (bw - aw),
        )
        return _normal_quat(out)
    theta_0 = math.acos(max(-1.0, min(1.0, dot)))
    theta = theta_0 * t
    sin_theta = math.sin(theta)
    sin_theta_0 = math.sin(theta_0)
    s0 = math.cos(theta) - dot * sin_theta / sin_theta_0
    s1 = sin_theta / sin_theta_0
    return _normal_quat((
        s0 * ax + s1 * bx,
        s0 * ay + s1 * by,
        s0 * az + s1 * bz,
        s0 * aw + s1 * bw,
    ))


def _bind_pose(node: object) -> NodePose:
    name = str(getattr(node, "name", "") or "")
    return NodePose(
        name=name,
        position=tuple(getattr(node, "position", (0.0, 0.0, 0.0))),
        rotation=tuple(getattr(node, "rotation", (0.0, 0.0, 0.0, 1.0))),
        scale=1.0,
    )


def _world_positions_by_key(model) -> dict[str, tuple[float, float, float]]:
    out: dict[str, tuple[float, float, float]] = {}

    def visit(node: object, parent_pos: tuple[float, float, float]) -> None:
        local = tuple(getattr(node, "position", (0.0, 0.0, 0.0)))
        world = _add3(parent_pos, local)
        key = _node_key(node)
        if key:
            out[key] = world
        for child in getattr(node, "children", []) or []:
            visit(child, world)

    root = getattr(model, "root_node", None)
    if root is not None:
        visit(root, (0.0, 0.0, 0.0))
    else:
        for node in _target_nodes(model):
            key = _node_key(node)
            if key:
                out[key] = tuple(getattr(node, "position", (0.0, 0.0, 0.0)))
    return out


def _height_from_positions(positions: Iterable[tuple[float, float, float]]) -> float:
    zs = [float(pos[2]) for pos in positions]
    if not zs:
        return 0.0
    return max(zs) - min(zs)


def _position_delta_scale(
    cfg: RetargetConfig,
    source_model,
    target_model,
    report: BoneMappingReport,
) -> float:
    if not cfg.preserve_model_scale:
        return 1.0
    src_world = _world_positions_by_key(source_model)
    dst_world = _world_positions_by_key(target_model)
    src_points = []
    dst_points = []
    for src_key, dst_key in report.mapping.items():
        if src_key in src_world and dst_key in dst_world:
            src_points.append(src_world[src_key])
            dst_points.append(dst_world[dst_key])
    src_height = _height_from_positions(src_points)
    dst_height = _height_from_positions(dst_points)
    if src_height <= 1e-6 or dst_height <= 1e-6:
        return 1.0
    return max(0.01, min(100.0, dst_height / src_height))


def _nearest_direct_ancestor(node: object, direct_keys: set[str]) -> object | None:
    parent = getattr(node, "parent", None)
    while parent is not None:
        if _node_key(parent) in direct_keys:
            return parent
        parent = getattr(parent, "parent", None)
    return None


def _path_from_ancestor_to_node(ancestor: object, node: object) -> list[object]:
    path: list[object] = []
    cur = node
    while cur is not None and cur is not ancestor:
        path.append(cur)
        cur = getattr(cur, "parent", None)
    if cur is not ancestor:
        return []
    path.reverse()
    return path


def _apply_bridge_poses(out: AnimPose, target_model, cfg: RetargetConfig) -> tuple[str, ...]:
    if not cfg.interpolate_unmapped_target_bones:
        return ()

    direct_keys = set(out.nodes)
    derived: set[str] = set()
    target_nodes = [node for node in _target_nodes(target_model) if _is_skeletal_node(node)]

    for node in target_nodes:
        key = _node_key(node)
        if key not in direct_keys:
            continue
        ancestor = _nearest_direct_ancestor(node, direct_keys)
        if ancestor is None:
            continue
        chain = _path_from_ancestor_to_node(ancestor, node)
        bridge = [item for item in chain[:-1] if _node_key(item) not in direct_keys and _is_skeletal_node(item)]
        if not bridge:
            continue
        target_pose = out.nodes[key]
        chain_len = len(bridge) + 1
        for item in bridge:
            item_key = _node_key(item)
            bind = _bind_pose(item)
            out.nodes[item_key] = NodePose(
                name=bind.name,
                position=bind.position,
                rotation=_slerp_quat(bind.rotation, target_pose.rotation, 1.0 / chain_len),
                scale=1.0,
            )
            derived.add(item_key)
        bind_target = _bind_pose(node)
        out.nodes[key] = NodePose(
            name=target_pose.name,
            position=target_pose.position,
            rotation=_slerp_quat(bind_target.rotation, target_pose.rotation, 1.0 / chain_len),
            scale=target_pose.scale,
            alpha=target_pose.alpha,
            selfillum=target_pose.selfillum,
        )

    if cfg.twist_bone_rotation_weight > 0.0:
        for node in target_nodes:
            key = _node_key(node)
            if key in out.nodes or "twist" not in key:
                continue
            ancestor = _nearest_direct_ancestor(node, direct_keys)
            if ancestor is None:
                continue
            ancestor_pose = out.nodes.get(_node_key(ancestor))
            if ancestor_pose is None:
                continue
            bind = _bind_pose(node)
            out.nodes[key] = NodePose(
                name=bind.name,
                position=bind.position,
                rotation=_slerp_quat(bind.rotation, ancestor_pose.rotation, cfg.twist_bone_rotation_weight),
                scale=1.0,
            )
            derived.add(key)

    return tuple(sorted(derived))


def _derived_target_bone_keys(target_model, direct_keys: set[str]) -> tuple[str, ...]:
    derived: set[str] = set()
    target_nodes = [node for node in _target_nodes(target_model) if _is_skeletal_node(node)]

    for node in target_nodes:
        key = _node_key(node)
        if key not in direct_keys:
            continue
        ancestor = _nearest_direct_ancestor(node, direct_keys)
        if ancestor is None:
            continue
        chain = _path_from_ancestor_to_node(ancestor, node)
        for item in chain[:-1]:
            item_key = _node_key(item)
            if item_key not in direct_keys and _is_skeletal_node(item):
                derived.add(item_key)

    for node in target_nodes:
        key = _node_key(node)
        if key in direct_keys or "twist" not in key:
            continue
        if _nearest_direct_ancestor(node, direct_keys) is not None:
            derived.add(key)

    return tuple(sorted(derived))


def retarget_pose(
    source_pose: AnimPose,
    source_model,
    target_model,
    config: Optional[RetargetConfig] = None,
    mapping_report: Optional[BoneMappingReport] = None,
) -> RetargetResult:
    """Retarget one evaluated source pose onto ``target_model``.

    Source positions are converted back to animation deltas relative to the
    source bind pose, then re-applied to the target bind pose. This is the key
    guard that prevents source bone lengths from resizing the target model.
    """
    cfg = config or RetargetConfig()
    report = mapping_report or build_bone_map(source_model, target_model)
    src_nodes = _nodes_by_name(source_model)
    dst_nodes = _nodes_by_name(target_model)
    position_delta_scale = _position_delta_scale(cfg, source_model, target_model, report)
    out = AnimPose(time=float(getattr(source_pose, "time", 0.0) or 0.0))

    for src_name, src_np in (getattr(source_pose, "nodes", {}) or {}).items():
        src_key = str(src_name or "").lower()
        dst_key = report.mapping.get(src_key)
        if not dst_key and cfg.allow_unmapped_nodes:
            dst_key = src_key
        if not dst_key or dst_key not in dst_nodes:
            continue

        src_node = src_nodes.get(src_key)
        dst_node = dst_nodes[dst_key]
        src_bind_pos = getattr(src_node, "position", (0.0, 0.0, 0.0)) if src_node else (0.0, 0.0, 0.0)
        src_bind_rot = getattr(src_node, "rotation", (0.0, 0.0, 0.0, 1.0)) if src_node else (0.0, 0.0, 0.0, 1.0)
        dst_bind_pos = getattr(dst_node, "position", (0.0, 0.0, 0.0))
        dst_bind_rot = getattr(dst_node, "rotation", (0.0, 0.0, 0.0, 1.0))
        delta = _sub3(getattr(src_np, "position", (0.0, 0.0, 0.0)), src_bind_pos)
        motion_scale = position_delta_scale
        if src_key in {"rootdummy", "root"}:
            motion_scale *= cfg.root_motion_scale
        position = _add3(dst_bind_pos, delta, motion_scale)
        rotation = _retarget_rotation(
            getattr(src_np, "rotation", (0.0, 0.0, 0.0, 1.0)),
            src_bind_rot,
            dst_bind_rot,
        )

        out.nodes[dst_key] = NodePose(
            name=str(getattr(dst_node, "name", dst_key) or dst_key),
            position=position,
            rotation=rotation,
            scale=1.0 if cfg.ignore_scale_keys else float(getattr(src_np, "scale", 1.0) or 1.0),
            alpha=getattr(src_np, "alpha", None) if cfg.copy_material_animation else None,
            selfillum=getattr(src_np, "selfillum", None) if cfg.copy_material_animation else None,
        )

    for dst_key in report.mapping.values():
        if dst_key in out.nodes:
            continue
        dst_node = dst_nodes.get(dst_key)
        if dst_node is not None and _is_skeletal_node(dst_node):
            out.nodes[dst_key] = _bind_pose(dst_node)

    derived = _apply_bridge_poses(out, target_model, cfg)
    if derived:
        derived_target = tuple(sorted(set(report.derived_target).union(derived)))
        report = BoneMappingReport(
            source_model=report.source_model,
            target_model=report.target_model,
            mapping=report.mapping,
            exact_matches=report.exact_matches,
            alias_matches=report.alias_matches,
            manual_matches=report.manual_matches,
            missing_source=report.missing_source,
            missing_target=tuple(item for item in report.missing_target if item not in set(derived)),
            derived_target=derived_target,
        )

    return RetargetResult(pose=out, report=report)


def _sample_retargeted_animation(
    source_animation: Animation,
    source_model,
    target_model,
    cfg: RetargetConfig,
    report: BoneMappingReport,
    name_suffix: str,
) -> tuple[Animation, BoneMappingReport]:
    from src.core.qt_core.animation.animation_engine import AnimationEngine

    length = float(getattr(source_animation, "length", 0.0) or 0.0)
    sample_rate = max(1.0, float(cfg.bake_sample_rate or 30.0))
    frame_count = max(1, int(math.ceil(length * sample_rate)))
    times = [0.0] if length <= 0.0 else [min(length, i / sample_rate) for i in range(frame_count + 1)]
    if length > 0.0 and times[-1] < length:
        times.append(length)

    try:
        engine = AnimationEngine(source_model)
    except Exception:
        return _copy_retargeted_animation(source_animation, source_model, target_model, cfg, report, name_suffix)
    if not engine.play(str(getattr(source_animation, "name", "") or ""), loop=False, blend=False):
        return _copy_retargeted_animation(source_animation, source_model, target_model, cfg, report, name_suffix)

    target_nodes_by_name = _nodes_by_name(target_model)
    sampled: dict[str, list[NodePose]] = {}
    derived_seen: set[str] = set(report.derived_target)
    for t in times:
        source_pose = engine.evaluate(t)
        result = retarget_pose(source_pose, source_model, target_model, cfg, report)
        derived_seen.update(result.report.derived_target)
        for key, pose in result.pose.nodes.items():
            if key in target_nodes_by_name:
                sampled.setdefault(key, []).append(pose)

    new_anim = Animation(
        name=f"{getattr(source_animation, 'name', 'animation')}{name_suffix}",
        length=length,
        transition_time=float(getattr(source_animation, "transition_time", 0.25) or 0.25),
        anim_root=report.mapping.get(str(getattr(source_animation, "anim_root", "") or "").lower(), ""),
        events=copy.deepcopy(getattr(source_animation, "events", []) or []),
        nodes=[],
    )

    for key, poses in sorted(sampled.items()):
        node = target_nodes_by_name.get(key)
        if node is None or not _is_skeletal_node(node):
            continue
        anim_node = node.clone_shallow() if hasattr(node, "clone_shallow") else copy.copy(node)
        anim_node.name = str(getattr(node, "name", key) or key)
        anim_node.children = []
        anim_node.parent = None
        anim_node.controllers = []
        bind_pos = tuple(getattr(node, "position", (0.0, 0.0, 0.0)))
        bind_rot = tuple(getattr(node, "rotation", (0.0, 0.0, 0.0, 1.0)))
        pos_values = [_sub3(getattr(pose, "position", bind_pos), bind_pos) for pose in poses]
        rot_values = [tuple(getattr(pose, "rotation", bind_rot)) for pose in poses]
        if any(max(abs(part) for part in value) > 1e-6 for value in pos_values):
            anim_node.controllers.append({"type": 8, "times": list(times), "values": pos_values})
        if any(_sub_quat(value, bind_rot) > 1e-6 for value in rot_values):
            anim_node.controllers.append({"type": 20, "times": list(times), "values": rot_values})
        if anim_node.controllers:
            new_anim.nodes.append(anim_node)

    final_report = BoneMappingReport(
        source_model=report.source_model,
        target_model=report.target_model,
        mapping=report.mapping,
        exact_matches=report.exact_matches,
        alias_matches=report.alias_matches,
        manual_matches=report.manual_matches,
        missing_source=report.missing_source,
        missing_target=tuple(item for item in report.missing_target if item not in derived_seen),
        derived_target=tuple(sorted(derived_seen)),
    )
    return new_anim, final_report


def _scaled_position_values(values, scale: float):
    if abs(scale - 1.0) <= 1e-8:
        return values
    out = []
    for val in values or []:
        if len(val) >= 3:
            out.append(_mul3(val, scale))
        else:
            out.append(val)
    return out


def _copy_retargeted_animation(
    source_animation: Animation,
    source_model,
    target_model,
    cfg: RetargetConfig,
    report: BoneMappingReport,
    name_suffix: str,
) -> tuple[Animation, BoneMappingReport]:
    dst_nodes = _nodes_by_name(target_model)
    position_delta_scale = _position_delta_scale(cfg, source_model, target_model, report)
    new_anim = Animation(
        name=f"{getattr(source_animation, 'name', 'animation')}{name_suffix}",
        length=float(getattr(source_animation, "length", 0.0) or 0.0),
        transition_time=float(getattr(source_animation, "transition_time", 0.25) or 0.25),
        anim_root=report.mapping.get(str(getattr(source_animation, "anim_root", "") or "").lower(), ""),
        events=copy.deepcopy(getattr(source_animation, "events", []) or []),
        nodes=[],
    )

    for src_anim_node in getattr(source_animation, "nodes", []) or []:
        src_key = str(getattr(src_anim_node, "name", "") or "").lower()
        dst_key = report.mapping.get(src_key)
        if not dst_key or dst_key not in dst_nodes:
            continue
        dst_node = dst_nodes[dst_key]
        anim_node = dst_node.clone_shallow() if hasattr(dst_node, "clone_shallow") else copy.copy(dst_node)
        anim_node.name = str(getattr(dst_node, "name", dst_key) or dst_key)
        anim_node.children = []
        anim_node.parent = None
        anim_node.controllers = []
        for ctrl in getattr(src_anim_node, "controllers", []) or []:
            ctype = int(ctrl.get("type", -1)) if isinstance(ctrl, dict) else -1
            if cfg.ignore_scale_keys and ctype == 36:
                continue
            new_ctrl = copy.deepcopy(ctrl)
            if ctype == 8:
                scale = position_delta_scale
                if src_key in {"rootdummy", "root"}:
                    scale *= cfg.root_motion_scale
                new_ctrl["values"] = _scaled_position_values(new_ctrl.get("values", []) or [], scale)
            anim_node.controllers.append(new_ctrl)
        if anim_node.controllers:
            new_anim.nodes.append(anim_node)

    return new_anim, report


def retarget_animation(
    source_animation: Animation,
    source_model,
    target_model,
    config: Optional[RetargetConfig] = None,
    mapping_report: Optional[BoneMappingReport] = None,
    name_suffix: str = "_retarget",
) -> tuple[Animation, BoneMappingReport]:
    """Create a target-model animation clip from ``source_animation``.

    KotOR position controllers are relative deltas, so they can be copied
    directly onto a target node without importing source bind offsets. Scale
    controllers are dropped by default.
    """
    cfg = config or RetargetConfig()
    report = mapping_report or build_bone_map(source_model, target_model)
    if cfg.interpolate_unmapped_target_bones:
        return _sample_retargeted_animation(source_animation, source_model, target_model, cfg, report, name_suffix)
    return _copy_retargeted_animation(source_animation, source_model, target_model, cfg, report, name_suffix)
