#pragma once

#include <cstddef>

namespace ghostrigger::domain::core::animation {

#ifndef GHOSTRIGGER_ANIMATION_NATIVE_FUNCTION_IMPLEMENTATION_DEFINED
#define GHOSTRIGGER_ANIMATION_NATIVE_FUNCTION_IMPLEMENTATION_DEFINED
struct NativeFunctionImplementation {
    const char* project;
    const char* native_namespace;
    const char* python_file;
    const char* qualname;
    const char* callable_type;
    const char* implementation_status;
    bool native_first;
    bool python_runtime_required;
    bool python_fallback_allowed;
    const char* contract_json;
};
#endif // GHOSTRIGGER_ANIMATION_NATIVE_FUNCTION_IMPLEMENTATION_DEFINED

const NativeFunctionImplementation& interp_channel_safe_val_line_443_ac242877_native();
const NativeFunctionImplementation& animationengine_export_animation_bvh_collect_bones_line_1474_36617db8_native();
const NativeFunctionImplementation& animationengine_export_animation_bvh_bvh_bone_line_1497_76c5d7d0_native();
const NativeFunctionImplementation& animationengine_export_animation_bvh_quat_to_euler_zxy_line_1548_6dc3b074_native();
const NativeFunctionImplementation& animationengine_export_animation_bvh_collect_frame_line_1579_cc3f4033_native();
const NativeFunctionImplementation& animationlibrary_scan_run_line_135_6499ffb5_native();
const NativeFunctionImplementation& fbxanimationexporter_write_fbx_new_id_line_603_0f438edb_native();
const NativeFunctionImplementation& fbxanimationexporter_write_fbx_collect_line_610_8b35a11f_native();
const NativeFunctionImplementation& fbxanimationexporter_write_fbx_write_single_curve_line_795_21c30c63_native();
const NativeFunctionImplementation& fbxanimationexporter_write_fbx_write_curve_line_824_bdc39bcf_native();
const NativeFunctionImplementation& fbxanimationexporter_write_fbx_baked_new_id_line_979_78c0530b_native();
const NativeFunctionImplementation& fbxanimationexporter_write_fbx_baked_collect_line_986_10b572bb_native();
const NativeFunctionImplementation& fbxanimationexporter_write_fbx_baked_write_single_baked_curve_line_1171_4500447a_native();
const NativeFunctionImplementation& fbxanimationexporter_write_fbx_baked_write_baked_curve_line_1199_37b407c6_native();
const NativeFunctionImplementation& build_world_transforms_visit_line_1530_b7e8a71d_native();
const NativeFunctionImplementation& matrixpaletteuploader_build_inverse_bind_pose_get_world_bind_line_501_b2c62f64_native();
const NativeFunctionImplementation& matrixpaletteuploader_set_bind_pose_from_anim_get_world_base_line_619_9eefd8e4_native();
const NativeFunctionImplementation& matrixpaletteuploader_compute_palette_get_world_anim_line_1152_89fa6368_native();

const NativeFunctionImplementation* nestedfunctions_native_functions(std::size_t& count);

} // namespace ghostrigger::domain::core::animation
