#pragma once

#include <cstddef>

namespace ghostrigger::native::nativecore {

#ifndef GHOSTRIGGER_NATIVE_NATIVECORE_NATIVE_FUNCTION_IMPLEMENTATION_DEFINED
#define GHOSTRIGGER_NATIVE_NATIVECORE_NATIVE_FUNCTION_IMPLEMENTATION_DEFINED
struct NativeFunctionImplementation {
    const char* project;
    const char* native_namespace;
    const char* python_file;
    const char* qualname;
    const char* callable_type;
    const char* implementation_status;
    bool native_first;
    bool python_runtime_required;
    bool python_fallback_allowed;
    const char* contract_json;
};
#endif // GHOSTRIGGER_NATIVE_NATIVECORE_NATIVE_FUNCTION_IMPLEMENTATION_DEFINED

const NativeFunctionImplementation& candidate_output_dirs_line_687_ceffe8c0_native();
const NativeFunctionImplementation& candidate_paths_line_694_bc29a84b_native();
const NativeFunctionImplementation& load_library_line_709_dd015af0_native();
const NativeFunctionImplementation& query_native_package_status_line_713_b2f17f81_native();
const NativeFunctionImplementation& query_native_core_status_line_767_be63bc2d_native();
const NativeFunctionImplementation& query_native_core_diagnostics_status_line_771_5cef6a4b_native();
const NativeFunctionImplementation& query_native_core_math_status_line_777_05b2640c_native();
const NativeFunctionImplementation& query_runtime_shared_contracts_status_line_783_3352097f_native();
const NativeFunctionImplementation& query_runtime_shared_descriptors_status_line_789_61484c46_native();
const NativeFunctionImplementation& query_runtime_shared_resources_status_line_795_d08a2477_native();
const NativeFunctionImplementation& query_renderer_contracts_status_line_801_c501756a_native();
const NativeFunctionImplementation& query_renderer_null_status_line_807_1a10251c_native();
const NativeFunctionImplementation& query_renderer_d3d12_status_line_813_c1b9a834_native();
const NativeFunctionImplementation& query_renderer_moderngl_status_line_819_61632f7b_native();
const NativeFunctionImplementation& query_renderer_pygfx_status_line_825_5ac4b26e_native();
const NativeFunctionImplementation& query_tools_retargeting_status_line_831_701640de_native();
const NativeFunctionImplementation& query_tools_export_status_line_837_1685a354_native();
const NativeFunctionImplementation& query_tools_character_builder_status_line_843_373b2c6a_native();
const NativeFunctionImplementation& query_tools_content_browser_status_line_849_f9132765_native();
const NativeFunctionImplementation& query_tools_resource_browser_status_line_855_34822832_native();
const NativeFunctionImplementation& query_tools_two_da_browser_status_line_861_7baebfd1_native();
const NativeFunctionImplementation& query_tools_scene_information_status_line_867_2af23030_native();
const NativeFunctionImplementation& query_tools_properties_status_line_873_1f8ad1ad_native();
const NativeFunctionImplementation& query_tools_lighting_status_line_879_34b10206_native();
const NativeFunctionImplementation& query_tools_camera_status_line_885_80a719dd_native();
const NativeFunctionImplementation& query_tools_module_meshes_status_line_891_89342fe1_native();
const NativeFunctionImplementation& query_tools_body_attachment_system_status_line_897_fb05f314_native();
const NativeFunctionImplementation& query_tools_nodes_skeleton_browser_status_line_903_5062154d_native();
const NativeFunctionImplementation& query_tools_sprite_materials_status_line_909_92a98a3a_native();
const NativeFunctionImplementation& query_tools_pivot_controls_status_line_915_d842d853_native();
const NativeFunctionImplementation& query_tools_sequence_editor_status_line_921_df318c8e_native();
const NativeFunctionImplementation& query_windows_main_window_status_line_927_e5443c00_native();
const NativeFunctionImplementation& query_windows_level_editor_status_line_933_2f18d158_native();
const NativeFunctionImplementation& query_windows_animation_retarget_workbench_status_line_939_368bd5a8_native();
const NativeFunctionImplementation& query_windows_legacy_rigging_window_status_line_945_0d70c4ef_native();
const NativeFunctionImplementation& query_windows_unreal_animator_window_status_line_951_dd925acb_native();
const NativeFunctionImplementation& query_python_module_package_statuses_line_957_806b3cab_native();
const NativeFunctionImplementation& python_module_package_specs_line_966_6d06a7bd_native();
const NativeFunctionImplementation& renderer_d3d12_guarded_metadata_capabilities_line_969_4fae5818_native();

const NativeFunctionImplementation* modulefunctions_native_functions(std::size_t& count);

} // namespace ghostrigger::native::nativecore
