#pragma once

#include <cstddef>

namespace ghostrigger::phase15::ghostrigger_tools_retargeting {

using PythonFunctionDescriptorJson = const char* (*)();

struct PythonFunctionDescriptorEntry {
    const char* python_file;
    const char* qualname;
    const char* function_type;
    PythonFunctionDescriptorJson descriptor_json;
};

const char* src_core_retargeting_animation_injector_animationinjector_sha256_line_131_7e1dc125_descriptor_json();
const char* src_core_retargeting_animation_injector_animationinjector_game_version_line_139_fec0e21e_descriptor_json();
const char* src_core_retargeting_aurora_animation_writer_auroraanimationwriter_sha256_line_456_c6a70532_descriptor_json();
const char* src_core_retargeting_aurora_animation_writer_auroraanimationwriter_game_version_line_464_9564893d_descriptor_json();
const char* src_core_retargeting_aurora_animation_writer_auroraanimationwriter_discard_outputs_line_589_db2226a0_descriptor_json();
const char* src_core_retargeting_aurora_animation_writer_auroraanimationwriter_animation_frame_count_line_739_4a6ad467_descriptor_json();
const char* src_core_retargeting_aurora_animation_writer_auroraanimationwriter_is_motion_gate_node_line_779_8cc47c80_descriptor_json();
const char* src_core_retargeting_aurora_animation_writer_auroraanimationwriter_normalize_quat_wxyz_line_819_95a5aeda_descriptor_json();
const char* src_core_retargeting_aurora_animation_writer_auroraanimationwriter_rotation_amplitude_wxyz_line_829_4624e937_descriptor_json();
const char* src_core_retargeting_aurora_animation_writer_auroraanimationwriter_normalized_times_line_1059_4886e8e5_descriptor_json();
const char* src_core_retargeting_aurora_animation_writer_auroraanimationwriter_merge_controller_times_line_1072_e9fbed77_descriptor_json();
const char* src_core_retargeting_aurora_animation_writer_auroraanimationwriter_fallback_animation_times_line_1079_3435b31a_descriptor_json();
const char* src_core_retargeting_aurora_animation_writer_auroraanimationwriter_normalize_quat_xyzw_line_1089_6b726730_descriptor_json();
const char* src_core_retargeting_aurora_animation_writer_auroraanimationwriter_three_floats_line_1120_735e824e_descriptor_json();
const char* src_core_retargeting_aurora_animation_writer_auroraanimationwriter_position_values_have_motion_line_1150_71694b90_descriptor_json();
const char* src_core_retargeting_aurora_animation_writer_auroraanimationwriter_is_root_or_pelvis_node_line_1161_0ea878bb_descriptor_json();
const char* src_core_retargeting_aurora_animation_writer_auroraanimationwriter_four_floats_line_1371_a7f0019a_descriptor_json();
const char* src_core_retargeting_aurora_animation_writer_auroraanimationwriter_validate_controller_rows_line_1377_ba7a6429_descriptor_json();
const char* src_core_retargeting_aurora_animation_writer_auroraanimationwriter_find_local_animation_index_line_1390_5605003a_descriptor_json();
const char* src_core_retargeting_fbx_backend_fbxbackendfactory_backend_type_from_string_line_205_2c02004a_descriptor_json();
const char* src_core_retargeting_fbx_backend_fbxbackendfactory_get_importer_line_212_5fc6f7dd_descriptor_json();
const char* src_core_retargeting_fbx_backend_fbxbackendfactory_get_importer_from_environment_line_245_13512b07_descriptor_json();
const char* src_core_retargeting_fbx_backend_fbxbackendfactory_list_available_backends_line_254_3acfe2e2_descriptor_json();

const PythonFunctionDescriptorEntry* staticmethods_descriptors(std::size_t& count);

} // namespace ghostrigger::phase15::ghostrigger_tools_retargeting
