#pragma once

#include <cstddef>

namespace ghostrigger::phase15::ghostrigger_game {

using PythonFunctionDescriptorJson = const char* (*)();

struct PythonFunctionDescriptorEntry {
    const char* python_file;
    const char* qualname;
    const char* function_type;
    PythonFunctionDescriptorJson descriptor_json;
};

const char* src_core_game_game_library_ext_res_type_name_line_147_01728658_descriptor_json();
const char* src_core_game_game_library_ext_res_type_ext_line_152_be86c927_descriptor_json();
const char* src_core_game_game_library_ext_read_2da_from_library_line_409_66611753_descriptor_json();
const char* src_core_game_game_library_ext_read_gff_from_library_line_426_a81c1965_descriptor_json();
const char* src_core_game_game_library_ext_list_all_resources_line_443_a95d6a3e_descriptor_json();
const char* src_core_game_import_normalisation_model_root_name_line_14_b3f36a68_descriptor_json();
const char* src_core_game_import_normalisation_apply_known_skin_bone_map_normalisations_line_26_e7cbd46f_descriptor_json();
const char* src_core_game_import_normalisation_normalise_bastila_headless_body_torso_line_36_71f88dd3_descriptor_json();
const char* src_core_game_kotor_install_res_key_line_81_d89d1922_descriptor_json();
const char* src_core_game_kotor_loader_load_model_from_bytes_line_101_39077bf8_descriptor_json();
const char* src_core_game_kotor_loader_load_model_from_file_line_159_bcd175fa_descriptor_json();
const char* src_core_game_kotor_loader_game_name_line_213_ffd92671_descriptor_json();
const char* src_core_game_kotor_loader_is_null_supermodel_line_228_ebcc9ea4_descriptor_json();
const char* src_core_game_kotor_loader_configure_supermodel_resource_manager_line_232_e7c74104_descriptor_json();
const char* src_core_game_kotor_loader_load_supermodel_chain_line_240_1efde3d8_descriptor_json();
const char* src_core_game_kotor_loader_get_valid_animation_slots_line_290_da9e4e42_descriptor_json();
const char* src_core_game_kotor_loader_resolve_animation_slot_line_310_a4fd9bc2_descriptor_json();
const char* src_core_game_kotor_loader_patch_tpc_header_line_362_39366810_descriptor_json();
const char* src_core_game_kotor_loader_load_tpc_as_pil_line_407_d07caf95_descriptor_json();
const char* src_core_game_kotor_loader_mdl_to_kotormodel_line_511_6e446fd7_descriptor_json();
const char* src_core_game_kotor_loader_detect_version_from_bytes_line_576_3d33ba69_descriptor_json();
const char* src_core_game_kotor_loader_is_xbox_from_bytes_line_602_879408d0_descriptor_json();
const char* src_core_game_kotor_loader_detect_version_line_613_21d121b9_descriptor_json();
const char* src_core_game_kotor_loader_convert_node_line_626_ac727525_descriptor_json();
const char* src_core_game_kotor_loader_read_mesh_line_698_f14c7b47_descriptor_json();
const char* src_core_game_kotor_loader_read_skin_textures_line_956_3888f767_descriptor_json();
const char* src_core_game_kotor_loader_read_skin_weights_line_985_8c4cf503_descriptor_json();
const char* src_core_game_kotor_loader_read_dangly_line_1173_9f6cab8d_descriptor_json();
const char* src_core_game_kotor_loader_read_light_line_1225_3bbbde20_descriptor_json();
const char* src_core_game_kotor_loader_read_controllers_line_1258_36619c08_descriptor_json();
const char* src_core_game_kotor_loader_convert_anim_line_1306_c5549544_descriptor_json();
const char* src_core_game_kotor_loader_walk_nodes_line_1335_df6bf8b4_descriptor_json();
const char* src_core_game_kotor_loader_fill_missing_normals_line_1355_7ef28257_descriptor_json();
const char* src_core_game_kotor_loader_apply_bind_pose_line_1401_71383db6_descriptor_json();
const char* src_core_game_kotor_loader_iter_nodes_dfs_line_1487_12824831_descriptor_json();
const char* src_core_game_kotor_loader_find_node_exact_line_1504_bc652d17_descriptor_json();
const char* src_core_game_kotor_loader_reparent_head_nodes_line_1521_d4207389_descriptor_json();
const char* src_core_game_pykotor_bridge_is_pykotor_available_line_29_90071d4f_descriptor_json();
const char* src_core_game_pykotor_bridge_fill_mesh_data_line_34_2da510e0_descriptor_json();
const char* src_core_game_pykotor_bridge_list_animations_via_pykotor_line_40_982d6f81_descriptor_json();
const char* src_core_game_pykotor_bridge_compare_model_animations_line_56_eade3dac_descriptor_json();
const char* src_core_game_pykotor_bridge_validate_animations_via_pykotor_line_92_78ef2a24_descriptor_json();
const char* src_core_game_pykotor_mdl_io_fix_ensure_pykotor_mdl_binary_fixes_line_120_91ced2ac_descriptor_json();
const char* src_core_game_pykotor_mdl_io_fix_raise_or_bypass_line_172_ebe23a5b_descriptor_json();
const char* src_core_game_pykotor_mdl_io_fix_check_pykotor_compat_line_188_e8e4995c_descriptor_json();
const char* src_core_game_pykotor_mdl_io_fix_ghostrigger_trimesh_read_line_295_f8a97a2a_descriptor_json();
const char* src_core_game_pykotor_mdl_io_fix_patch_load_node_mdx_zero_line_416_82445f13_descriptor_json();

const PythonFunctionDescriptorEntry* modulefunctions_descriptors(std::size_t& count);

} // namespace ghostrigger::phase15::ghostrigger_game
