#pragma once

#include <cstddef>

namespace ghostrigger::phase15::ghostrigger_walkmesh {

using PythonFunctionDescriptorJson = const char* (*)();

struct PythonFunctionDescriptorEntry {
    const char* python_file;
    const char* qualname;
    const char* function_type;
    PythonFunctionDescriptorJson descriptor_json;
};

const char* src_core_walkmesh_walkmesh_renderer_walkmeshoverlay_init_line_187_29d6a454_descriptor_json();
const char* src_core_walkmesh_walkmesh_renderer_walkmeshoverlay_load_from_wok_line_195_a0d500bd_descriptor_json();
const char* src_core_walkmesh_walkmesh_renderer_walkmeshoverlay_load_from_ascii_wok_line_235_745fcb2c_descriptor_json();
const char* src_core_walkmesh_walkmesh_renderer_walkmeshoverlay_walkable_faces_line_289_b33a2e47_descriptor_json();
const char* src_core_walkmesh_walkmesh_renderer_walkmeshoverlay_non_walkable_faces_line_292_4c0ce679_descriptor_json();
const char* src_core_walkmesh_walkmesh_renderer_walkmeshoverlay_faces_by_material_line_295_e834cd8f_descriptor_json();
const char* src_core_walkmesh_walkmesh_renderer_walkmeshoverlay_faces_for_render_line_298_3728a6b1_descriptor_json();
const char* src_core_walkmesh_walkmesh_renderer_walkmeshoverlay_aabb_line_314_82c0207c_descriptor_json();
const char* src_core_walkmesh_walkmesh_renderer_walkmeshoverlay_summary_line_331_2ae230ef_descriptor_json();
const char* src_core_walkmesh_walkmesh_renderer_walkmeshoverlay_boundary_edges_line_340_1a989b1a_descriptor_json();
const char* src_core_walkmesh_walkmesh_renderer_walkmeshloader_from_wok_data_line_395_af5b94d6_descriptor_json();
const char* src_core_walkmesh_walkmesh_renderer_walkmeshloader_from_file_line_402_9cc0fc61_descriptor_json();
const char* src_core_walkmesh_walkmesh_renderer_walkmeshloader_from_scene_room_line_416_cadddf33_descriptor_json();
const char* src_core_walkmesh_walkmesh_renderer_walkmeshloader_load_all_room_overlays_line_426_7a60ecf0_descriptor_json();
const char* src_core_walkmesh_walkmesh_renderer_walkmeshwriter_to_bytes_line_523_6069c2fb_descriptor_json();
const char* src_core_walkmesh_walkmesh_renderer_walkmeshwriter_to_bytes_from_wok_line_535_90912352_descriptor_json();
const char* src_core_walkmesh_walkmesh_renderer_walkmeshwriter_write_file_line_545_14bbad56_descriptor_json();
const char* src_core_walkmesh_walkmesh_renderer_walkmeshwriter_write_wok_file_line_557_a80a0a68_descriptor_json();
const char* src_core_walkmesh_walkmesh_renderer_walkmeshwriter_extract_geometry_line_586_38a9d751_descriptor_json();
const char* src_core_walkmesh_walkmesh_renderer_walkmeshtogglecontroller_init_line_743_55186ffc_descriptor_json();
const char* src_core_walkmesh_walkmesh_renderer_walkmeshtogglecontroller_visible_line_758_2d38d64c_descriptor_json();
const char* src_core_walkmesh_walkmesh_renderer_walkmeshtogglecontroller_toggle_line_762_3c2bbce5_descriptor_json();
const char* src_core_walkmesh_walkmesh_renderer_walkmeshtogglecontroller_on_key_line_773_f67fe1bf_descriptor_json();
const char* src_core_walkmesh_walkmesh_renderer_walkmeshtogglecontroller_toggle_room_line_786_5eecdb22_descriptor_json();
const char* src_core_walkmesh_walkmesh_renderer_walkmeshtogglecontroller_set_all_line_799_9b83b04b_descriptor_json();
const char* src_core_walkmesh_walkmesh_renderer_walkmeshtogglecontroller_set_overlays_line_804_de6a3441_descriptor_json();
const char* src_core_walkmesh_walkmesh_renderer_walkmeshtogglecontroller_set_key_line_809_2771a18a_descriptor_json();
const char* src_core_walkmesh_walkmesh_renderer_walkmeshtogglecontroller_sync_overlays_line_825_72803aef_descriptor_json();

const PythonFunctionDescriptorEntry* instancemethods_descriptors(std::size_t& count);

} // namespace ghostrigger::phase15::ghostrigger_walkmesh
