#pragma once

#include <cstddef>

namespace ghostrigger::phase15::ghostrigger_walkmesh {

using PythonFunctionDescriptorJson = const char* (*)();

struct PythonFunctionDescriptorEntry {
    const char* python_file;
    const char* qualname;
    const char* function_type;
    PythonFunctionDescriptorJson descriptor_json;
};

const char* src_core_walkmesh_walkmesh_editor_import_module_format_line_128_b17b2aa2_descriptor_json();
const char* src_core_walkmesh_walkmesh_editor_import_walkmesh_renderer_line_137_88470d36_descriptor_json();
const char* src_core_walkmesh_walkmesh_editor_module_from_input_line_147_c2b5ea5e_descriptor_json();
const char* src_core_walkmesh_walkmesh_editor_looks_like_wok_line_153_ea56805e_descriptor_json();
const char* src_core_walkmesh_walkmesh_editor_room_woks_line_157_3c189e0c_descriptor_json();
const char* src_core_walkmesh_walkmesh_editor_select_wok_line_165_95814c82_descriptor_json();
const char* src_core_walkmesh_walkmesh_editor_surface_names_line_187_0e0b3e30_descriptor_json();
const char* src_core_walkmesh_walkmesh_editor_walkable_ids_line_192_de93cc15_descriptor_json();
const char* src_core_walkmesh_walkmesh_editor_surface_name_line_197_62f14ef3_descriptor_json();
const char* src_core_walkmesh_walkmesh_editor_surface_color_line_202_576794ea_descriptor_json();
const char* src_core_walkmesh_walkmesh_editor_is_walkable_line_209_d58bfb9c_descriptor_json();
const char* src_core_walkmesh_walkmesh_editor_face_indices_line_213_deb3c831_descriptor_json();
const char* src_core_walkmesh_walkmesh_editor_face_adjacency_line_217_7c19b1ff_descriptor_json();
const char* src_core_walkmesh_walkmesh_editor_centroid_line_221_ee9ca26c_descriptor_json();
const char* src_core_walkmesh_walkmesh_editor_face_info_line_234_0b837fd0_descriptor_json();
const char* src_core_walkmesh_walkmesh_editor_surface_distribution_line_252_8f9f4efb_descriptor_json();
const char* src_core_walkmesh_walkmesh_editor_walkable_face_count_line_262_89163905_descriptor_json();
const char* src_core_walkmesh_walkmesh_editor_non_walk_face_count_line_268_99b04b19_descriptor_json();
const char* src_core_walkmesh_walkmesh_editor_boundary_edges_line_274_3d7fa03b_descriptor_json();
const char* src_core_walkmesh_walkmesh_editor_walkmesh_surface_palette_line_280_4a8498ac_descriptor_json();
const char* src_core_walkmesh_walkmesh_editor_build_walkmesh_workbench_line_294_c66ae8cf_descriptor_json();
const char* src_core_walkmesh_walkmesh_editor_select_walkmesh_face_line_331_12dab30c_descriptor_json();
const char* src_core_walkmesh_walkmesh_editor_set_walkmesh_face_surface_line_380_c294b580_descriptor_json();
const char* src_core_walkmesh_walkmesh_editor_paint_walkmesh_point_line_449_e2aaa4bf_descriptor_json();
const char* src_core_walkmesh_walkmesh_editor_validate_walkmesh_line_470_a514510b_descriptor_json();
const char* src_core_walkmesh_walkmesh_editor_roundtrip_walkmesh_line_584_8753b6a5_descriptor_json();
const char* src_core_walkmesh_walkmesh_renderer_surface_color_line_117_64d9d09b_descriptor_json();
const char* src_core_walkmesh_walkmesh_renderer_surface_name_line_122_416678cb_descriptor_json();
const char* src_core_walkmesh_walkmesh_renderer_build_draw_list_line_457_d887c5f1_descriptor_json();
const char* src_core_walkmesh_walkmesh_renderer_get_walkmesh_fbx_material_line_867_0fb07cd7_descriptor_json();
const char* src_core_walkmesh_walkmesh_renderer_walkmesh_to_fbx_materials_line_887_e5348752_descriptor_json();

const PythonFunctionDescriptorEntry* modulefunctions_descriptors(std::size_t& count);

} // namespace ghostrigger::phase15::ghostrigger_walkmesh
