#pragma once

#include <cstddef>

namespace ghostrigger::phase15::ghostrigger_resources {

using PythonFunctionDescriptorJson = const char* (*)();

struct PythonFunctionDescriptorEntry {
    const char* python_file;
    const char* qualname;
    const char* function_type;
    PythonFunctionDescriptorJson descriptor_json;
};

const char* src_core_resources_game_resource_provider_gameresourcequery_post_init_line_76_8060f04c_descriptor_json();
const char* src_core_resources_game_resource_provider_gameresourcequery_to_address_line_84_27269e94_descriptor_json();
const char* src_core_resources_game_resource_provider_gameresourcerecord_post_init_line_107_9a620728_descriptor_json();
const char* src_core_resources_game_resource_provider_gameresourceprovider_list_resources_line_154_13eb721d_descriptor_json();
const char* src_core_resources_game_resource_provider_gameresourceprovider_resolve_line_157_db6153cc_descriptor_json();
const char* src_core_resources_game_resource_provider_gameresourceprovider_read_bytes_line_160_7e0b3a1b_descriptor_json();
const char* src_core_resources_game_resource_provider_gameresourceprovider_exists_line_163_eda4619b_descriptor_json();
const char* src_core_resources_game_resource_provider_inmemorygameresourceprovider_init_line_188_d08dcb62_descriptor_json();
const char* src_core_resources_game_resource_provider_inmemorygameresourceprovider_add_line_197_49d40e02_descriptor_json();
const char* src_core_resources_game_resource_provider_inmemorygameresourceprovider_list_resources_line_200_2ca86bab_descriptor_json();
const char* src_core_resources_game_resource_provider_inmemorygameresourceprovider_list_module_resources_line_205_a022d9b4_descriptor_json();
const char* src_core_resources_game_resource_provider_inmemorygameresourceprovider_resolve_line_208_c2b6a07f_descriptor_json();
const char* src_core_resources_game_resource_provider_inmemorygameresourceprovider_read_bytes_line_224_2e9321d1_descriptor_json();
const char* src_core_resources_game_resource_provider_inmemorygameresourceprovider_read_resource_line_227_8e539aeb_descriptor_json();
const char* src_core_resources_game_resource_provider_inmemorygameresourceprovider_exists_line_238_28740a54_descriptor_json();
const char* src_core_resources_game_resource_provider_localfileresourceprovider_list_resources_line_249_577bbf95_descriptor_json();
const char* src_core_resources_game_resource_provider_localfileresourceprovider_resolve_line_260_dfe7c954_descriptor_json();
const char* src_core_resources_game_resource_provider_localfileresourceprovider_read_bytes_line_270_15ed95e3_descriptor_json();
const char* src_core_resources_game_resource_provider_localfileresourceprovider_exists_line_273_262362a1_descriptor_json();
const char* src_core_resources_game_resource_provider_localfileresourceprovider_record_for_path_line_280_1e0a7666_descriptor_json();
const char* src_core_resources_game_resource_provider_compositegameresourceprovider_init_line_302_f4c139f6_descriptor_json();
const char* src_core_resources_game_resource_provider_compositegameresourceprovider_list_resources_line_305_158702ab_descriptor_json();
const char* src_core_resources_game_resource_provider_compositegameresourceprovider_list_module_resources_line_311_b9fdbc05_descriptor_json();
const char* src_core_resources_game_resource_provider_compositegameresourceprovider_resolve_line_314_8dbf0540_descriptor_json();
const char* src_core_resources_game_resource_provider_compositegameresourceprovider_read_bytes_line_334_31527e38_descriptor_json();
const char* src_core_resources_game_resource_provider_compositegameresourceprovider_read_resource_line_337_b248788c_descriptor_json();
const char* src_core_resources_game_resource_provider_compositegameresourceprovider_exists_line_348_dd7a3867_descriptor_json();
const char* src_core_resources_game_resource_provider_resourcemanagergameresourceprovider_init_line_360_145e2601_descriptor_json();
const char* src_core_resources_game_resource_provider_resourcemanagergameresourceprovider_list_resources_line_363_1abeed1b_descriptor_json();
const char* src_core_resources_game_resource_provider_resourcemanagergameresourceprovider_list_module_resources_line_374_3e04a171_descriptor_json();
const char* src_core_resources_game_resource_provider_resourcemanagergameresourceprovider_resolve_line_377_10f73bb5_descriptor_json();
const char* src_core_resources_game_resource_provider_resourcemanagergameresourceprovider_read_bytes_line_413_bd99e881_descriptor_json();
const char* src_core_resources_game_resource_provider_resourcemanagergameresourceprovider_read_resource_line_416_6be8f0b0_descriptor_json();
const char* src_core_resources_game_resource_provider_resourcemanagergameresourceprovider_exists_line_427_5ef4e963_descriptor_json();

const PythonFunctionDescriptorEntry* instancemethods_descriptors(std::size_t& count);

} // namespace ghostrigger::phase15::ghostrigger_resources
