#pragma once

#include <cstddef>

namespace ghostrigger::phase15::ghostrigger_resources {

using PythonFunctionDescriptorJson = const char* (*)();

struct PythonFunctionDescriptorEntry {
    const char* python_file;
    const char* qualname;
    const char* function_type;
    PythonFunctionDescriptorJson descriptor_json;
};

const char* src_core_resources_game_resource_provider_coerce_resource_query_line_167_aa2b5698_descriptor_json();
const char* src_core_resources_game_resource_provider_restype_to_extension_line_435_d168dbf6_descriptor_json();
const char* src_core_resources_game_resource_provider_records_from_install_line_442_29a1399c_descriptor_json();
const char* src_core_resources_game_resource_provider_override_records_line_460_fa1405f7_descriptor_json();
const char* src_core_resources_game_resource_provider_erf_records_line_484_f262248d_descriptor_json();
const char* src_core_resources_game_resource_provider_bif_records_line_522_923b63b9_descriptor_json();
const char* src_core_resources_game_resource_provider_record_line_553_2745da10_descriptor_json();
const char* src_core_resources_game_resource_provider_record_matches_line_585_f4a92796_descriptor_json();
const char* src_core_resources_game_resource_provider_sort_records_line_602_cf3d7f84_descriptor_json();
const char* src_core_resources_game_resource_provider_dedupe_records_line_616_788f2d14_descriptor_json();
const char* src_core_resources_game_resource_provider_shadow_warnings_line_628_0fd0c506_descriptor_json();
const char* src_core_resources_game_resource_provider_missing_message_line_639_8fea0f4d_descriptor_json();
const char* src_core_resources_game_resource_provider_safe_path_size_line_645_ca4cce06_descriptor_json();
const char* src_core_resources_game_resource_provider_clean_text_line_654_ba113744_descriptor_json();
const char* src_core_resources_game_resource_provider_clean_restype_line_663_96e19284_descriptor_json();
const char* src_core_resources_game_resource_provider_clean_game_line_672_dc0cf339_descriptor_json();
const char* src_core_resources_game_resource_provider_manager_game_name_line_684_d824b250_descriptor_json();
const char* src_core_resources_game_resource_provider_manager_install_line_688_f11c7825_descriptor_json();
const char* src_core_resources_game_resource_provider_resource_manager_type_id_line_696_88dd7962_descriptor_json();
const char* src_core_resources_game_resource_provider_resource_manager_restype_line_706_feb4e7a7_descriptor_json();
const char* src_core_resources_game_resource_provider_known_resource_type_ids_line_715_dd065008_descriptor_json();

const PythonFunctionDescriptorEntry* modulefunctions_descriptors(std::size_t& count);

} // namespace ghostrigger::phase15::ghostrigger_resources
