#pragma once

#include <cstddef>

namespace ghostrigger::phase15::ghostrigger_characters {

using PythonFunctionDescriptorJson = const char* (*)();

struct PythonFunctionDescriptorEntry {
    const char* python_file;
    const char* qualname;
    const char* function_type;
    PythonFunctionDescriptorJson descriptor_json;
};

const char* src_core_characters_character_autofit_report_autofitreport_to_dict_line_33_ee841977_descriptor_json();
const char* src_core_characters_character_autofit_report_autofitoverride_is_active_line_59_9e6cf1ad_descriptor_json();
const char* src_core_characters_character_builder_kotorinstallsupermodelresourcemanager_init_line_226_39b49e73_descriptor_json();
const char* src_core_characters_character_builder_kotorinstallsupermodelresourcemanager_load_model_line_230_b4f199f1_descriptor_json();
const char* src_core_characters_character_builder_lipplayback_init_line_447_59f98da0_descriptor_json();
const char* src_core_characters_character_builder_lipplayback_load_lip_line_453_dc7169fc_descriptor_json();
const char* src_core_characters_character_builder_lipplayback_load_talk_animation_line_471_8a8e9b0f_descriptor_json();
const char* src_core_characters_character_builder_lipplayback_update_line_499_1fea2b3a_descriptor_json();
const char* src_core_characters_character_builder_lipplayback_play_line_556_6ab85370_descriptor_json();
const char* src_core_characters_character_builder_lipplayback_stop_line_561_e35fd591_descriptor_json();
const char* src_core_characters_character_builder_lipplayback_pause_line_566_0feaed5d_descriptor_json();
const char* src_core_characters_character_builder_lipplayback_resume_line_570_4b644eb0_descriptor_json();
const char* src_core_characters_character_builder_skeletonselector_init_line_716_abb16a59_descriptor_json();
const char* src_core_characters_character_builder_skeletonselector_set_model_line_723_c20a00bd_descriptor_json();
const char* src_core_characters_character_builder_skeletonselector_build_node_map_line_730_dceba0e0_descriptor_json();
const char* src_core_characters_character_builder_skeletonselector_select_all_line_739_4a92a273_descriptor_json();
const char* src_core_characters_character_builder_skeletonselector_select_skeleton_only_line_745_3b91aa94_descriptor_json();
const char* src_core_characters_character_builder_skeletonselector_select_group_line_767_61782937_descriptor_json();
const char* src_core_characters_character_builder_skeletonselector_select_by_names_line_784_0174d57c_descriptor_json();
const char* src_core_characters_character_builder_skeletonselector_deselect_line_793_fa669a6c_descriptor_json();
const char* src_core_characters_character_builder_skeletonselector_clear_line_801_dcdb4351_descriptor_json();
const char* src_core_characters_character_builder_skeletonselector_toggle_line_805_395ce025_descriptor_json();
const char* src_core_characters_character_builder_skeletonselector_is_selected_line_831_fe1a2033_descriptor_json();
const char* src_core_characters_character_builder_skeletonselector_available_groups_line_834_585dfd94_descriptor_json();
const char* src_core_characters_character_export_transaction_characterbuilderexporttransactionrequest_post_init_line_67_ccaeb70b_descriptor_json();
const char* src_core_characters_character_override_package_characterbuilderoverridepackagerequest_post_init_line_83_2d712e87_descriptor_json();
const char* src_core_characters_character_rig_state_characterrigstate_to_dict_line_41_2be13f9c_descriptor_json();
const char* src_core_characters_character_validation_report_characterbuildervalidationreport_to_dict_line_1021_f662db65_descriptor_json();
const char* src_core_characters_character_validation_report_characterbuildervalidationreport_to_json_line_1101_1a171c49_descriptor_json();
const char* src_core_characters_character_validation_report_characterbuildervalidationreport_to_text_line_1104_d5a86722_descriptor_json();
const char* src_core_characters_creature_appearance_gffparser_init_line_86_60a41e81_descriptor_json();
const char* src_core_characters_creature_appearance_gffparser_parse_line_91_6e71a31e_descriptor_json();
const char* src_core_characters_creature_appearance_creatureappearance_repr_line_216_e5c6d4f0_descriptor_json();
const char* src_core_characters_creature_appearance_creaturemodelset_all_models_line_719_9678b50d_descriptor_json();
const char* src_core_characters_creature_appearance_creatureassembly_init_line_1181_92987777_descriptor_json();
const char* src_core_characters_creature_appearance_creatureassembly_export_separate_line_1314_ae15d588_descriptor_json();
const char* src_core_characters_creature_appearance_creatureassembly_get_viewport_preview_model_line_1422_553fadfc_descriptor_json();
const char* src_core_characters_native_skeleton_nativenodesnapshot_to_dict_line_73_2504d10c_descriptor_json();
const char* src_core_characters_native_skeleton_nativeskeletonsnapshot_to_dict_line_101_abe4546e_descriptor_json();
const char* src_core_characters_native_skeleton_nativeskeletonsnapshot_node_names_line_116_21d14856_descriptor_json();

const PythonFunctionDescriptorEntry* instancemethods_descriptors(std::size_t& count);

} // namespace ghostrigger::phase15::ghostrigger_characters
