#pragma once

#include <cstddef>

namespace ghostrigger::phase15::ghostrigger_characters {

using PythonFunctionDescriptorJson = const char* (*)();

struct PythonFunctionDescriptorEntry {
    const char* python_file;
    const char* qualname;
    const char* function_type;
    PythonFunctionDescriptorJson descriptor_json;
};

const char* src_core_characters_character_builder_rebuild_templates_strip_line_631_7ecc14ab_descriptor_json();
const char* src_core_characters_character_export_transaction_export_character_mdl_mdx_transaction_writer_line_148_6e96dd53_descriptor_json();
const char* src_core_characters_character_export_transaction_export_character_mdl_mdx_transaction_verifier_line_161_538f2514_descriptor_json();
const char* src_core_characters_character_override_package_package_character_override_candidate_writer_line_167_3a137123_descriptor_json();
const char* src_core_characters_character_override_package_package_character_override_candidate_verifier_line_186_fe0af2f4_descriptor_json();
const char* src_core_characters_creature_appearance_merge_supermodel_is_bone_or_dummy_line_518_e06daae3_descriptor_json();
const char* src_core_characters_creature_appearance_merge_supermodel_deep_copy_subtree_line_525_77665d97_descriptor_json();
const char* src_core_characters_creature_appearance_creatureassembly_from_resrefs_load_line_1284_29e801d6_descriptor_json();
const char* src_core_characters_creature_appearance_snap_head_onto_body_scale_verts_line_1593_21984514_descriptor_json();
const char* src_core_characters_headless_body_workflow_ground_snapped_target_origin_mapped_line_2011_8a0fe80f_descriptor_json();
const char* src_core_characters_headless_body_workflow_apply_external_model_fit_adjustment_transform_point_line_2309_3b6f063d_descriptor_json();
const char* src_core_characters_headless_body_workflow_normalize_external_model_for_kotor_transform_point_line_2575_98ab7fce_descriptor_json();
const char* src_core_characters_headless_body_workflow_normalize_external_model_for_kotor_transform_direction_line_2579_9f227abd_descriptor_json();
const char* src_core_characters_headless_body_workflow_normalize_external_model_for_kotor_transform_node_position_line_2583_bf5207e2_descriptor_json();
const char* src_core_characters_headless_body_workflow_normalize_external_model_for_kotor_transform_point_line_2692_be866f18_descriptor_json();
const char* src_core_characters_headless_body_workflow_normalize_external_model_for_kotor_transform_direction_line_2700_d3af9a5d_descriptor_json();
const char* src_core_characters_headless_body_workflow_normalize_external_model_for_kotor_transform_node_position_line_2706_3aa6f982_descriptor_json();
const char* src_core_characters_headless_body_workflow_with_supermodel_resource_manager_resolvercontext_init_line_5113_fc886da7_descriptor_json();
const char* src_core_characters_headless_body_workflow_with_supermodel_resource_manager_resolvercontext_enter_line_5118_e5652f36_descriptor_json();
const char* src_core_characters_headless_body_workflow_with_supermodel_resource_manager_resolvercontext_exit_line_5131_fed9154f_descriptor_json();
const char* src_core_characters_headless_body_workflow_model_nodes_walk_line_5184_c22f7bba_descriptor_json();
const char* src_core_characters_headless_body_workflow_export_single_format_reload_exported_line_5841_aa70b842_descriptor_json();

const PythonFunctionDescriptorEntry* nestedfunctions_descriptors(std::size_t& count);

} // namespace ghostrigger::phase15::ghostrigger_characters
