#pragma once

#include <cstddef>

namespace ghostrigger::phase15::ghostrigger_characters {

using PythonFunctionDescriptorJson = const char* (*)();

struct PythonFunctionDescriptorEntry {
    const char* python_file;
    const char* qualname;
    const char* function_type;
    PythonFunctionDescriptorJson descriptor_json;
};

const char* src_core_characters_character_builder_lipplayback_is_playing_line_575_81977988_descriptor_json();
const char* src_core_characters_character_builder_lipplayback_elapsed_line_579_29f5bf16_descriptor_json();
const char* src_core_characters_character_builder_lipplayback_duration_line_583_9c4d1b72_descriptor_json();
const char* src_core_characters_character_builder_skeletonselector_selected_nodes_line_814_a8d99566_descriptor_json();
const char* src_core_characters_character_builder_skeletonselector_selected_names_line_824_fbedefbf_descriptor_json();
const char* src_core_characters_character_builder_skeletonselector_count_line_828_06c4a08b_descriptor_json();
const char* src_core_characters_character_export_preflight_characterexportpreflightresult_export_allowed_line_112_99f50905_descriptor_json();
const char* src_core_characters_character_export_transaction_characterbuilderexporttransactionresult_succeeded_line_82_551814e9_descriptor_json();
const char* src_core_characters_character_export_transaction_characterbuilderexporttransactionresult_mdl_path_line_86_18384d89_descriptor_json();
const char* src_core_characters_character_export_transaction_characterbuilderexporttransactionresult_mdx_path_line_90_f2c3ffcd_descriptor_json();
const char* src_core_characters_character_export_transaction_characterbuilderexporttransactionresult_validation_report_json_path_line_94_9bb14de4_descriptor_json();
const char* src_core_characters_character_export_transaction_characterbuilderexporttransactionresult_validation_report_txt_path_line_98_940918be_descriptor_json();
const char* src_core_characters_character_override_package_characterbuilderoverridepackageresult_succeeded_line_105_e0460de1_descriptor_json();
const char* src_core_characters_character_override_package_characterbuilderoverridepackageresult_mdl_path_line_109_8f6cd8bf_descriptor_json();
const char* src_core_characters_character_override_package_characterbuilderoverridepackageresult_mdx_path_line_116_ab37777c_descriptor_json();
const char* src_core_characters_character_override_package_characterbuilderoverridepackageresult_manifest_path_line_120_ac2a447e_descriptor_json();
const char* src_core_characters_character_override_package_characterbuilderoverridepackageresult_readme_path_line_124_fe040bc7_descriptor_json();
const char* src_core_characters_character_validation_report_characterbuildervalidationreport_merged_report_line_1001_f4e1d21c_descriptor_json();
const char* src_core_characters_character_validation_report_characterbuildervalidationreport_capability_stage_line_1008_3013e082_descriptor_json();
const char* src_core_characters_creature_appearance_creatureappearance_primary_model_line_210_b53bb619_descriptor_json();
const char* src_core_characters_creature_appearance_creaturemodelset_primary_line_715_12a3fc44_descriptor_json();
const char* src_core_characters_headless_body_workflow_bodyguideedithistory_can_undo_line_3233_965ab5fb_descriptor_json();
const char* src_core_characters_headless_body_workflow_bodyguideedithistory_can_redo_line_3237_68214687_descriptor_json();

const PythonFunctionDescriptorEntry* properties_descriptors(std::size_t& count);

} // namespace ghostrigger::phase15::ghostrigger_characters
