#pragma once

#include <cstddef>

namespace ghostrigger::gizmo {

#ifndef GHOSTRIGGER_GIZMO_NATIVE_FUNCTION_IMPLEMENTATION_DEFINED
#define GHOSTRIGGER_GIZMO_NATIVE_FUNCTION_IMPLEMENTATION_DEFINED
struct NativeFunctionImplementation {
    const char* project;
    const char* native_namespace;
    const char* python_file;
    const char* qualname;
    const char* callable_type;
    const char* implementation_status;
    bool native_first;
    bool python_runtime_required;
    bool python_fallback_allowed;
    const char* contract_json;
};
#endif // GHOSTRIGGER_GIZMO_NATIVE_FUNCTION_IMPLEMENTATION_DEFINED

const NativeFunctionImplementation& gizmopicker_hit_test_line_11_7b73adf8_native();
const NativeFunctionImplementation& nulldraw_line_line_14_07ab314f_native();
const NativeFunctionImplementation& nulldraw_ellipse_line_17_1917bf4f_native();
const NativeFunctionImplementation& nulldraw_rectangle_line_20_5baf48da_native();
const NativeFunctionImplementation& nulldraw_polygon_line_23_88049024_native();
const NativeFunctionImplementation& gizmorenderer_construct_line_37_a38a82c3_native();
const NativeFunctionImplementation& gizmorenderer_draw_line_40_f6e63b63_native();
const NativeFunctionImplementation& gizmorenderer_build_render_data_line_72_80d20e57_native();
const NativeFunctionImplementation& gizmorenderer_color_line_144_eee988d5_native();
const NativeFunctionImplementation& gizmorenderer_draw_translate_line_147_2f322aa3_native();
const NativeFunctionImplementation& gizmorenderer_pivot_marker_line_184_c875bc82_native();
const NativeFunctionImplementation& gizmorenderer_thick_line_commands_line_194_7b4e297c_native();
const NativeFunctionImplementation& gizmorenderer_arrowhead_commands_line_223_8a2c1a11_native();
const NativeFunctionImplementation& gizmorenderer_square_commands_line_242_cfaf90f8_native();
const NativeFunctionImplementation& gizmorenderer_disk_commands_line_252_7031c35a_native();
const NativeFunctionImplementation& gizmorenderer_draw_scale_line_294_7570f64a_native();
const NativeFunctionImplementation& gizmorenderer_draw_rotate_line_312_668ab592_native();
const NativeFunctionImplementation& transformcontroller_construct_line_39_50939a96_native();
const NativeFunctionImplementation& transformcontroller_snapshot_line_60_9f1c704a_native();
const NativeFunctionImplementation& transformcontroller_set_position_snap_line_86_cf91bb6b_native();
const NativeFunctionImplementation& transformcontroller_begin_drag_line_93_d91f3ce1_native();
const NativeFunctionImplementation& transformcontroller_drag_line_115_b61c076a_native();
const NativeFunctionImplementation& transformcontroller_apply_translate_line_127_0fbf0075_native();
const NativeFunctionImplementation& transformcontroller_apply_view_translate_line_181_aa686c4b_native();
const NativeFunctionImplementation& transformcontroller_apply_rotate_line_225_fb3c1c0d_native();
const NativeFunctionImplementation& transformcontroller_apply_scale_line_253_d0840c2f_native();
const NativeFunctionImplementation& transformcontroller_cancel_line_329_299df350_native();
const NativeFunctionImplementation& transformcontroller_end_drag_line_335_6d85d24f_native();
const NativeFunctionImplementation& transformcontroller_restore_line_342_1b53854f_native();
const NativeFunctionImplementation& transformcontroller_invalidate_line_364_e38981a7_native();
const NativeFunctionImplementation& transformcontroller_apply_light_scale_line_368_4d83d6d5_native();
const NativeFunctionImplementation& transformcontroller_apply_camera_scale_line_392_81775637_native();
const NativeFunctionImplementation& transformgizmo_construct_line_14_a9df9afb_native();
const NativeFunctionImplementation& transformgizmo_set_selected_object_line_35_2fe16a2b_native();
const NativeFunctionImplementation& transformgizmo_set_selected_objects_line_39_5056a6e3_native();
const NativeFunctionImplementation& transformgizmo_clear_selection_line_44_709ea6a0_native();
const NativeFunctionImplementation& transformgizmo_cycle_mode_line_52_647d8f31_native();
const NativeFunctionImplementation& transformgizmo_set_mode_line_58_6aa46899_native();
const NativeFunctionImplementation& transformgizmo_update_from_selection_line_62_608ad04e_native();
const NativeFunctionImplementation& transformgizmo_update_from_object_transform_line_98_58d66d54_native();
const NativeFunctionImplementation& transformgizmo_get_gizmo_origin_world_line_101_b1909cb5_native();
const NativeFunctionImplementation& transformgizmo_get_gizmo_orientation_matrix_line_105_0820e329_native();
const NativeFunctionImplementation& transformgizmo_get_gizmo_scale_for_camera_line_112_7e491cf8_native();
const NativeFunctionImplementation& transformgizmo_begin_drag_line_115_f58a8495_native();
const NativeFunctionImplementation& transformgizmo_drag_line_130_26d16200_native();
const NativeFunctionImplementation& transformgizmo_end_drag_line_134_8582966a_native();
const NativeFunctionImplementation& transformgizmo_cancel_drag_line_140_ae2279af_native();
const NativeFunctionImplementation& transformgizmo_draw_line_145_df47d660_native();
const NativeFunctionImplementation& transformgizmo_build_render_data_line_153_8ddf70d2_native();
const NativeFunctionImplementation& transformgizmo_hit_test_line_161_fcd24e7d_native();

const NativeFunctionImplementation* instancemethods_native_functions(std::size_t& count);

} // namespace ghostrigger::gizmo
