#pragma once

#include <cstddef>

namespace ghostrigger::phase15::ghostrigger_gizmo {

using PythonFunctionDescriptorJson = const char* (*)();

struct PythonFunctionDescriptorEntry {
    const char* python_file;
    const char* qualname;
    const char* function_type;
    PythonFunctionDescriptorJson descriptor_json;
};

const char* src_core_gizmo_gizmo_picker_gizmopicker_hit_test_line_11_7b73adf8_descriptor_json();
const char* src_core_gizmo_gizmo_renderer_nulldraw_line_line_14_07ab314f_descriptor_json();
const char* src_core_gizmo_gizmo_renderer_nulldraw_ellipse_line_17_1917bf4f_descriptor_json();
const char* src_core_gizmo_gizmo_renderer_nulldraw_rectangle_line_20_5baf48da_descriptor_json();
const char* src_core_gizmo_gizmo_renderer_nulldraw_polygon_line_23_88049024_descriptor_json();
const char* src_core_gizmo_gizmo_renderer_gizmorenderer_init_line_37_a38a82c3_descriptor_json();
const char* src_core_gizmo_gizmo_renderer_gizmorenderer_draw_line_40_f6e63b63_descriptor_json();
const char* src_core_gizmo_gizmo_renderer_gizmorenderer_build_render_data_line_72_80d20e57_descriptor_json();
const char* src_core_gizmo_gizmo_renderer_gizmorenderer_color_line_144_eee988d5_descriptor_json();
const char* src_core_gizmo_gizmo_renderer_gizmorenderer_draw_translate_line_147_2f322aa3_descriptor_json();
const char* src_core_gizmo_gizmo_renderer_gizmorenderer_pivot_marker_line_184_c875bc82_descriptor_json();
const char* src_core_gizmo_gizmo_renderer_gizmorenderer_thick_line_commands_line_194_7b4e297c_descriptor_json();
const char* src_core_gizmo_gizmo_renderer_gizmorenderer_arrowhead_commands_line_223_8a2c1a11_descriptor_json();
const char* src_core_gizmo_gizmo_renderer_gizmorenderer_square_commands_line_242_cfaf90f8_descriptor_json();
const char* src_core_gizmo_gizmo_renderer_gizmorenderer_disk_commands_line_252_7031c35a_descriptor_json();
const char* src_core_gizmo_gizmo_renderer_gizmorenderer_draw_scale_line_294_7570f64a_descriptor_json();
const char* src_core_gizmo_gizmo_renderer_gizmorenderer_draw_rotate_line_312_668ab592_descriptor_json();
const char* src_core_gizmo_transform_controller_transformcontroller_init_line_39_50939a96_descriptor_json();
const char* src_core_gizmo_transform_controller_transformcontroller_snapshot_line_60_9f1c704a_descriptor_json();
const char* src_core_gizmo_transform_controller_transformcontroller_set_position_snap_line_86_cf91bb6b_descriptor_json();
const char* src_core_gizmo_transform_controller_transformcontroller_begin_drag_line_93_d91f3ce1_descriptor_json();
const char* src_core_gizmo_transform_controller_transformcontroller_drag_line_115_b61c076a_descriptor_json();
const char* src_core_gizmo_transform_controller_transformcontroller_apply_translate_line_127_0fbf0075_descriptor_json();
const char* src_core_gizmo_transform_controller_transformcontroller_apply_view_translate_line_181_aa686c4b_descriptor_json();
const char* src_core_gizmo_transform_controller_transformcontroller_apply_rotate_line_225_fb3c1c0d_descriptor_json();
const char* src_core_gizmo_transform_controller_transformcontroller_apply_scale_line_253_d0840c2f_descriptor_json();
const char* src_core_gizmo_transform_controller_transformcontroller_cancel_line_329_299df350_descriptor_json();
const char* src_core_gizmo_transform_controller_transformcontroller_end_drag_line_335_6d85d24f_descriptor_json();
const char* src_core_gizmo_transform_controller_transformcontroller_restore_line_342_1b53854f_descriptor_json();
const char* src_core_gizmo_transform_controller_transformcontroller_invalidate_line_364_e38981a7_descriptor_json();
const char* src_core_gizmo_transform_controller_transformcontroller_apply_light_scale_line_368_4d83d6d5_descriptor_json();
const char* src_core_gizmo_transform_controller_transformcontroller_apply_camera_scale_line_392_81775637_descriptor_json();
const char* src_core_gizmo_transform_gizmo_transformgizmo_init_line_14_a9df9afb_descriptor_json();
const char* src_core_gizmo_transform_gizmo_transformgizmo_set_selected_object_line_35_2fe16a2b_descriptor_json();
const char* src_core_gizmo_transform_gizmo_transformgizmo_set_selected_objects_line_39_5056a6e3_descriptor_json();
const char* src_core_gizmo_transform_gizmo_transformgizmo_clear_selection_line_44_709ea6a0_descriptor_json();
const char* src_core_gizmo_transform_gizmo_transformgizmo_cycle_mode_line_52_647d8f31_descriptor_json();
const char* src_core_gizmo_transform_gizmo_transformgizmo_set_mode_line_58_6aa46899_descriptor_json();
const char* src_core_gizmo_transform_gizmo_transformgizmo_update_from_selection_line_62_608ad04e_descriptor_json();
const char* src_core_gizmo_transform_gizmo_transformgizmo_update_from_object_transform_line_98_58d66d54_descriptor_json();
const char* src_core_gizmo_transform_gizmo_transformgizmo_get_gizmo_origin_world_line_101_b1909cb5_descriptor_json();
const char* src_core_gizmo_transform_gizmo_transformgizmo_get_gizmo_orientation_matrix_line_105_0820e329_descriptor_json();
const char* src_core_gizmo_transform_gizmo_transformgizmo_get_gizmo_scale_for_camera_line_112_7e491cf8_descriptor_json();
const char* src_core_gizmo_transform_gizmo_transformgizmo_begin_drag_line_115_f58a8495_descriptor_json();
const char* src_core_gizmo_transform_gizmo_transformgizmo_drag_line_130_26d16200_descriptor_json();
const char* src_core_gizmo_transform_gizmo_transformgizmo_end_drag_line_134_8582966a_descriptor_json();
const char* src_core_gizmo_transform_gizmo_transformgizmo_cancel_drag_line_140_ae2279af_descriptor_json();
const char* src_core_gizmo_transform_gizmo_transformgizmo_draw_line_145_df47d660_descriptor_json();
const char* src_core_gizmo_transform_gizmo_transformgizmo_build_render_data_line_153_8ddf70d2_descriptor_json();
const char* src_core_gizmo_transform_gizmo_transformgizmo_hit_test_line_161_fcd24e7d_descriptor_json();

const PythonFunctionDescriptorEntry* instancemethods_descriptors(std::size_t& count);

} // namespace ghostrigger::phase15::ghostrigger_gizmo
