#pragma once

#include <cstddef>

namespace ghostrigger::core::gui::integration {

#ifndef GHOSTRIGGER_GUI_INTEGRATION_NATIVE_FUNCTION_IMPLEMENTATION_DEFINED
#define GHOSTRIGGER_GUI_INTEGRATION_NATIVE_FUNCTION_IMPLEMENTATION_DEFINED
struct NativeFunctionImplementation {
    const char* project;
    const char* native_namespace;
    const char* python_file;
    const char* qualname;
    const char* callable_type;
    const char* implementation_status;
    bool native_first;
    bool python_runtime_required;
    bool python_fallback_allowed;
    const char* contract_json;
};
#endif // GHOSTRIGGER_GUI_INTEGRATION_NATIVE_FUNCTION_IMPLEMENTATION_DEFINED

const NativeFunctionImplementation& qtmatrixengine_construct_line_60_0dc28f9c_native();
const NativeFunctionImplementation& qtmatrixengine_start_line_66_25622b25_native();
const NativeFunctionImplementation& qtmatrixengine_stop_line_70_e3c2b852_native();
const NativeFunctionImplementation& qtmatrixpanel_construct_line_77_e400e60c_native();
const NativeFunctionImplementation& qtmatrixpanel_apply_ghost_theme_line_105_45c2f152_native();
const NativeFunctionImplementation& qtmatrixpanel_set_matrix_config_line_119_63d4965d_native();
const NativeFunctionImplementation& qtmatrixpanel_crop_rect_line_160_263c6742_native();
const NativeFunctionImplementation& qtmatrixpanel_resizeevent_line_170_ff69dedc_native();
const NativeFunctionImplementation& qtmatrixpanel_paintevent_line_182_4e44a4b6_native();
const NativeFunctionImplementation& qtmatrixpanel_advance_line_217_33000fa3_native();
const NativeFunctionImplementation& qtmatrixlabel_construct_line_234_987d214d_native();
const NativeFunctionImplementation& qtmatrixlabel_apply_ghost_theme_line_238_e467f9fe_native();
const NativeFunctionImplementation& qtoverflowscrollarea_construct_line_23_83c656a7_native();
const NativeFunctionImplementation& qtoverflowscrollarea_setwidget_line_32_3c3140ee_native();
const NativeFunctionImplementation& qtoverflowscrollarea_resizeevent_line_36_05cd02c4_native();
const NativeFunctionImplementation& qtoverflowscrollarea_sync_content_width_line_40_9fbec4af_native();
const NativeFunctionImplementation& qtflowlayout_construct_line_54_8627f45a_native();
const NativeFunctionImplementation& qtflowlayout_additem_line_70_a817afc1_native();
const NativeFunctionImplementation& qtflowlayout_setspacing_line_73_5e14d2e5_native();
const NativeFunctionImplementation& qtflowlayout_count_line_78_39dbd8ed_native();
const NativeFunctionImplementation& qtflowlayout_itemat_line_81_e6cd0652_native();
const NativeFunctionImplementation& qtflowlayout_takeat_line_84_ec994623_native();
const NativeFunctionImplementation& qtflowlayout_expandingdirections_line_89_a124d406_native();
const NativeFunctionImplementation& qtflowlayout_hasheightforwidth_line_92_63efc361_native();
const NativeFunctionImplementation& qtflowlayout_heightforwidth_line_95_326d1524_native();
const NativeFunctionImplementation& qtflowlayout_setgeometry_line_98_8a7e840d_native();
const NativeFunctionImplementation& qtflowlayout_sizehint_line_102_9f166a20_native();
const NativeFunctionImplementation& qtflowlayout_minimumsize_line_105_e27816b7_native();
const NativeFunctionImplementation& qtflowlayout_do_layout_line_113_5ce904ee_native();
const NativeFunctionImplementation& editorintegrationeventbus_construct_line_56_39b5d149_native();
const NativeFunctionImplementation& editorintegrationeventbus_record_tool_action_line_65_23d5b024_native();
const NativeFunctionImplementation& editorintegrationeventbus_record_scene_update_line_70_f7ecd415_native();
const NativeFunctionImplementation& editorintegrationeventbus_record_cache_invalidation_line_81_8a0007eb_native();
const NativeFunctionImplementation& editorintegrationeventbus_record_redraw_line_85_43c35f9d_native();
const NativeFunctionImplementation& editorintegrationeventbus_warn_unsupported_line_89_9083e319_native();
const NativeFunctionImplementation& activeviewportservice_construct_line_96_b750c90a_native();
const NativeFunctionImplementation& activeviewportservice_get_active_viewport_line_109_dbb2cda8_native();
const NativeFunctionImplementation& activeviewportservice_get_active_renderer_line_114_6962af86_native();
const NativeFunctionImplementation& activeviewportservice_get_active_renderer_backend_line_120_0d438fbb_native();
const NativeFunctionImplementation& activeviewportservice_get_display_options_line_134_3bebbb5f_native();
const NativeFunctionImplementation& activeviewportservice_request_redraw_line_138_9c331d19_native();
const NativeFunctionImplementation& activeviewportservice_get_camera_line_148_f59bb637_native();
const NativeFunctionImplementation& activeviewportservice_get_scene_line_152_84771390_native();
const NativeFunctionImplementation& activeviewportservice_get_selection_line_161_a717c3b0_native();
const NativeFunctionImplementation& rendererservice_construct_line_175_dac1ed29_native();
const NativeFunctionImplementation& rendererservice_get_capabilities_line_185_0cbcccfa_native();
const NativeFunctionImplementation& rendererservice_get_diagnostics_line_200_311e9e22_native();
const NativeFunctionImplementation& rendererservice_supports_line_218_321f224f_native();
const NativeFunctionImplementation& rendererservice_request_mode_line_225_b11fb619_native();
const NativeFunctionImplementation& rendererservice_request_surface_refresh_line_236_4ed18016_native();
const NativeFunctionImplementation& rendererservice_request_resource_invalidation_line_242_5e844a58_native();
const NativeFunctionImplementation& rendererservice_fallback_capabilities_line_263_574398db_native();
const NativeFunctionImplementation& selectionservice_construct_line_330_af4d5f8d_native();
const NativeFunctionImplementation& selectionservice_current_line_335_92376805_native();
const NativeFunctionImplementation& selectionservice_select_node_line_338_6fc945c9_native();
const NativeFunctionImplementation& selectionservice_select_meshes_line_345_8b8613bd_native();
const NativeFunctionImplementation& sceneservice_construct_line_354_7545edb7_native();
const NativeFunctionImplementation& sceneservice_get_scene_line_359_fc34c885_native();
const NativeFunctionImplementation& diagnosticsservice_construct_line_380_3a6fb0c8_native();
const NativeFunctionImplementation& diagnosticsservice_snapshot_line_396_dd0427ea_native();
const NativeFunctionImplementation& toolintegrationregistry_register_line_36_e6dad00e_native();
const NativeFunctionImplementation& toolintegrationregistry_get_line_39_afc5f053_native();
const NativeFunctionImplementation& toolintegrationregistry_all_tools_line_42_99154aac_native();
const NativeFunctionImplementation& toolintegrationregistry_compatibility_rows_line_45_ed790c26_native();
const NativeFunctionImplementation& aliasloader_construct_line_224_ab29ba54_native();
const NativeFunctionImplementation& aliasloader_create_module_line_227_f2e967e8_native();
const NativeFunctionImplementation& aliasloader_exec_module_line_230_98e3e840_native();
const NativeFunctionImplementation& aliasfinder_find_spec_line_242_05e98a6c_native();
const NativeFunctionImplementation& lazymodule_construct_line_257_c7722d35_native();
const NativeFunctionImplementation& lazymodule_load_line_262_9d56a695_native();
const NativeFunctionImplementation& lazymodule_getattr_line_272_406585d8_native();
const NativeFunctionImplementation& lazymodule_dir_line_275_23687304_native();

const NativeFunctionImplementation* instancemethods_native_functions(std::size_t& count);

} // namespace ghostrigger::core::gui::integration
