#pragma once

#include <cstddef>

namespace ghostrigger::phase15::ghostrigger_gui_viewports {

using PythonFunctionDescriptorJson = const char* (*)();

struct PythonFunctionDescriptorEntry {
    const char* python_file;
    const char* qualname;
    const char* function_type;
    PythonFunctionDescriptorJson descriptor_json;
};

const char* src_gui_viewports_viewport_core_widgets_drag_interactions_viewportdraginteractionsmixin_apply_gimbal_drag_axis_delta_line_756_94b2cdad_descriptor_json();
const char* src_gui_viewports_viewport_core_widgets_drag_interactions_viewportdraginteractionsmixin_draw_mesh_subobject_selection_point_line_1114_5dd0970e_descriptor_json();
const char* src_gui_viewports_viewport_core_widgets_drag_interactions_viewportdraginteractionsmixin_draw_mesh_subobject_selection_draw_edge_line_1122_3690c91e_descriptor_json();
const char* src_gui_viewports_viewport_core_widgets_picking_hover_viewportpickinghovermixin_apply_mesh_subobject_hit_update_set_line_305_68f1ed55_descriptor_json();
const char* src_gui_viewports_viewport_core_widgets_picking_hover_viewportpickinghovermixin_update_mesh_hover_clear_hover_line_1050_777a470e_descriptor_json();
const char* src_gui_viewports_viewport_core_widgets_picking_hover_viewportpickinghovermixin_update_mesh_hover_set_hover_line_1068_33a26edb_descriptor_json();
const char* src_gui_viewports_viewport_core_widgets_rendering_pipeline_viewportrenderingpipelinemixin_start_deferred_txi_metadata_load_line_66_183ebc96_descriptor_json();
const char* src_gui_viewports_viewport_core_widgets_rendering_pipeline_viewportrenderingpipelinemixin_render_gpu_frame_continue_uploads_line_464_823a5599_descriptor_json();
const char* src_gui_viewports_viewport_core_widgets_rendering_pipeline_viewportrenderingpipelinemixin_renderer_statistics_lines_number_line_619_e7062561_descriptor_json();
const char* src_gui_viewports_viewport_core_widgets_resource_cache_viewportresourcecachemixin_prewarm_textures_load_line_100_10beff55_descriptor_json();
const char* src_gui_viewports_viewport_core_widgets_transform_camera_viewporttransformcameramixin_euler_degrees_to_quat_axis_quat_line_61_0ee9c5d6_descriptor_json();

const PythonFunctionDescriptorEntry* nestedfunctions_descriptors(std::size_t& count);

} // namespace ghostrigger::phase15::ghostrigger_gui_viewports
