#pragma once

#include <cstddef>

namespace ghostrigger::phase15::ghostrigger_gui_viewports {

using PythonFunctionDescriptorJson = const char* (*)();

struct PythonFunctionDescriptorEntry {
    const char* python_file;
    const char* qualname;
    const char* function_type;
    PythonFunctionDescriptorJson descriptor_json;
};

const char* src_gui_viewports_viewport_core_widgets_construction_viewportconstructionmixin_active_renderer_line_388_169a686d_descriptor_json();
const char* src_gui_viewports_viewport_core_widgets_construction_viewportconstructionmixin_active_renderer_backend_line_398_dd4723ef_descriptor_json();
const char* src_gui_viewports_viewport_core_widgets_construction_viewportconstructionmixin_viewport_toolbar_chrome_visible_line_510_6ca847b5_descriptor_json();
const char* src_gui_viewports_viewport_core_widgets_construction_viewportconstructionmixin_viewcube_chrome_visible_line_514_1fe6d360_descriptor_json();
const char* src_gui_viewports_viewport_core_widgets_construction_viewportconstructionmixin_transform_typein_chrome_visible_line_518_c2ace669_descriptor_json();
const char* src_gui_viewports_viewport_core_widgets_event_navigation_viewporteventnavigationmixin_character_mode_line_396_8989c930_descriptor_json();
const char* src_gui_viewports_viewport_core_widgets_event_navigation_viewporteventnavigationmixin_ortho_mode_line_714_543586a3_descriptor_json();
const char* src_gui_viewports_viewport_core_widgets_measurement_controls_viewportmeasurementcontrolsmixin_mesh_hover_enabled_line_34_0c8fc93e_descriptor_json();
const char* src_gui_viewports_viewport_core_widgets_overlay_layers_viewportoverlaylayersmixin_weight_heatmap_enabled_line_268_87e036af_descriptor_json();
const char* src_gui_viewports_viewport_core_widgets_overlay_layers_viewportoverlaylayersmixin_weight_heatmap_dot_size_line_272_49846575_descriptor_json();
const char* src_gui_viewports_viewport_core_widgets_overlay_layers_viewportoverlaylayersmixin_joint_symmetry_enabled_line_436_a3c7510a_descriptor_json();
const char* src_gui_viewports_viewport_core_widgets_overlay_layers_viewportoverlaylayersmixin_joint_dot_enabled_line_473_58b0e228_descriptor_json();
const char* src_gui_viewports_viewport_core_widgets_overlay_layers_viewportoverlaylayersmixin_joint_dot_size_line_477_dfdb9a1f_descriptor_json();
const char* src_gui_viewports_viewport_core_widgets_overlay_layers_viewportoverlaylayersmixin_joint_dot_opacity_line_481_d5c3937c_descriptor_json();
const char* src_gui_viewports_viewport_core_widgets_scene_models_viewportscenemodelmixin_tex_cache_line_722_2d7365ee_descriptor_json();
const char* src_gui_viewports_viewport_core_widgets_snap_view_bar_floatingsnapviewwidget_ortho_button_line_138_7f8f61d2_descriptor_json();
const char* src_gui_viewports_viewport_core_widgets_state_helpers_viewportstatemixin_navigation_profile_line_353_d50c9674_descriptor_json();
const char* src_gui_viewports_viewport_core_widgets_transform_camera_viewporttransformcameramixin_thumbnail_widget_line_259_48c6e8ee_descriptor_json();

const PythonFunctionDescriptorEntry* properties_descriptors(std::size_t& count);

} // namespace ghostrigger::phase15::ghostrigger_gui_viewports
