#pragma once

#include <cstddef>

namespace ghostrigger::phase15::ghostrigger_gui_viewports {

using PythonFunctionDescriptorJson = const char* (*)();

struct PythonFunctionDescriptorEntry {
    const char* python_file;
    const char* qualname;
    const char* function_type;
    PythonFunctionDescriptorJson descriptor_json;
};

const char* src_gui_viewports_viewport_core_widgets_construction_viewportconstructionmixin_palette_rgb_line_643_9dd90d51_descriptor_json();
const char* src_gui_viewports_viewport_core_widgets_display_controls_viewportdisplaycontrolsmixin_display_mode_label_line_34_20f24441_descriptor_json();
const char* src_gui_viewports_viewport_core_widgets_display_controls_viewportdisplaycontrolsmixin_renderer_label_for_backend_line_49_26a73c6e_descriptor_json();
const char* src_gui_viewports_viewport_core_widgets_display_controls_viewportdisplaycontrolsmixin_normalized_renderer_backend_line_56_98c86a60_descriptor_json();
const char* src_gui_viewports_viewport_core_widgets_history_animation_viewporthistoryanimationmixin_state_changed_line_12_65e06347_descriptor_json();
const char* src_gui_viewports_viewport_core_widgets_picking_hover_viewportpickinghovermixin_point_in_triangle_line_16_210d4fb1_descriptor_json();
const char* src_gui_viewports_viewport_core_widgets_picking_hover_viewportpickinghovermixin_point_segment_dist2_line_361_268c86bb_descriptor_json();
const char* src_gui_viewports_viewport_core_widgets_picking_hover_viewportpickinghovermixin_ray_triangle_intersection_line_391_34123a84_descriptor_json();
const char* src_gui_viewports_viewport_core_widgets_resource_cache_viewportresourcecachemixin_texture_names_for_prewarm_line_123_9c1770ad_descriptor_json();
const char* src_gui_viewports_viewport_core_widgets_scene_models_viewportscenemodelmixin_apply_scene_instance_scale_line_394_70781400_descriptor_json();
const char* src_gui_viewports_viewport_core_widgets_scene_models_viewportscenemodelmixin_euler_degrees_to_quat_line_461_f16cb803_descriptor_json();
const char* src_gui_viewports_viewport_core_widgets_selection_mesh_viewportselectionmeshmixin_is_selectable_mesh_node_line_456_c3e66b2a_descriptor_json();
const char* src_gui_viewports_viewport_core_widgets_selection_mesh_viewportselectionmeshmixin_bounds_from_points_line_605_befd9daa_descriptor_json();
const char* src_gui_viewports_viewport_core_widgets_selection_mesh_viewportselectionmeshmixin_bounds_center_line_628_ea6a8670_descriptor_json();
const char* src_gui_viewports_viewport_core_widgets_selection_mesh_viewportselectionmeshmixin_gimbal_world_axis_line_936_d2905c16_descriptor_json();
const char* src_gui_viewports_viewport_core_widgets_state_helpers_viewportstatemixin_quat_conjugate_line_131_1213f9e1_descriptor_json();
const char* src_gui_viewports_viewport_core_widgets_transform_camera_viewporttransformcameramixin_snapshot_vertices_line_12_e2a666d4_descriptor_json();
const char* src_gui_viewports_viewport_core_widgets_transform_camera_viewporttransformcameramixin_optional_tuple_attr_line_19_469c6b21_descriptor_json();
const char* src_gui_viewports_viewport_core_widgets_transform_camera_viewporttransformcameramixin_node_scale_line_29_14c8be97_descriptor_json();
const char* src_gui_viewports_viewport_core_widgets_transform_camera_viewporttransformcameramixin_quat_to_euler_degrees_line_38_762ca686_descriptor_json();
const char* src_gui_viewports_viewport_core_widgets_transform_camera_viewporttransformcameramixin_euler_degrees_to_quat_line_58_9594df6e_descriptor_json();

const PythonFunctionDescriptorEntry* staticmethods_descriptors(std::size_t& count);

} // namespace ghostrigger::phase15::ghostrigger_gui_viewports
