#pragma once

#include <cstddef>

namespace ghostrigger::gui::viewports {

#ifndef GHOSTRIGGER_GUI_VIEWPORTS_NATIVE_FUNCTION_IMPLEMENTATION_DEFINED
#define GHOSTRIGGER_GUI_VIEWPORTS_NATIVE_FUNCTION_IMPLEMENTATION_DEFINED
struct NativeFunctionImplementation {
    const char* project;
    const char* native_namespace;
    const char* python_file;
    const char* qualname;
    const char* callable_type;
    const char* implementation_status;
    bool native_first;
    bool python_runtime_required;
    bool python_fallback_allowed;
    const char* contract_json;
};
#endif // GHOSTRIGGER_GUI_VIEWPORTS_NATIVE_FUNCTION_IMPLEMENTATION_DEFINED

const NativeFunctionImplementation& viewportconstructionmixin_palette_rgb_line_643_9dd90d51_native();
const NativeFunctionImplementation& viewportdisplaycontrolsmixin_display_mode_label_line_34_20f24441_native();
const NativeFunctionImplementation& viewportdisplaycontrolsmixin_renderer_label_for_backend_line_49_26a73c6e_native();
const NativeFunctionImplementation& viewportdisplaycontrolsmixin_normalized_renderer_backend_line_56_98c86a60_native();
const NativeFunctionImplementation& viewporthistoryanimationmixin_state_changed_line_12_65e06347_native();
const NativeFunctionImplementation& viewportpickinghovermixin_point_in_triangle_line_16_210d4fb1_native();
const NativeFunctionImplementation& viewportpickinghovermixin_point_segment_dist2_line_361_268c86bb_native();
const NativeFunctionImplementation& viewportpickinghovermixin_ray_triangle_intersection_line_391_34123a84_native();
const NativeFunctionImplementation& viewportresourcecachemixin_texture_names_for_prewarm_line_123_9c1770ad_native();
const NativeFunctionImplementation& viewportscenemodelmixin_apply_scene_instance_scale_line_394_70781400_native();
const NativeFunctionImplementation& viewportscenemodelmixin_euler_degrees_to_quat_line_461_f16cb803_native();
const NativeFunctionImplementation& viewportselectionmeshmixin_is_selectable_mesh_node_line_456_c3e66b2a_native();
const NativeFunctionImplementation& viewportselectionmeshmixin_bounds_from_points_line_605_befd9daa_native();
const NativeFunctionImplementation& viewportselectionmeshmixin_bounds_center_line_628_ea6a8670_native();
const NativeFunctionImplementation& viewportselectionmeshmixin_gimbal_world_axis_line_936_d2905c16_native();
const NativeFunctionImplementation& viewportstatemixin_quat_conjugate_line_131_1213f9e1_native();
const NativeFunctionImplementation& viewporttransformcameramixin_snapshot_vertices_line_12_e2a666d4_native();
const NativeFunctionImplementation& viewporttransformcameramixin_optional_tuple_attr_line_19_469c6b21_native();
const NativeFunctionImplementation& viewporttransformcameramixin_node_scale_line_29_14c8be97_native();
const NativeFunctionImplementation& viewporttransformcameramixin_quat_to_euler_degrees_line_38_762ca686_native();
const NativeFunctionImplementation& viewporttransformcameramixin_euler_degrees_to_quat_line_58_9594df6e_native();

const NativeFunctionImplementation* staticmethods_native_functions(std::size_t& count);

} // namespace ghostrigger::gui::viewports
