#pragma once

#include <cstddef>

namespace ghostrigger::phase15::ghostrigger_measurement {

using PythonFunctionDescriptorJson = const char* (*)();

struct PythonFunctionDescriptorEntry {
    const char* python_file;
    const char* qualname;
    const char* function_type;
    PythonFunctionDescriptorJson descriptor_json;
};

const char* src_measurement_angle_snap_anglesnap_init_line_10_d32771ad_descriptor_json();
const char* src_measurement_angle_snap_anglesnap_set_enabled_line_15_f4dd860e_descriptor_json();
const char* src_measurement_angle_snap_anglesnap_toggle_line_18_418e58ac_descriptor_json();
const char* src_measurement_angle_snap_anglesnap_set_increment_degrees_line_22_dd56794d_descriptor_json();
const char* src_measurement_angle_snap_anglesnap_snap_degrees_line_25_5c6cf86d_descriptor_json();
const char* src_measurement_angle_snap_anglesnap_snap_radians_line_32_4d8afb99_descriptor_json();
const char* src_measurement_angle_snap_anglesnap_apply_to_euler_line_37_6dc489f4_descriptor_json();
const char* src_measurement_angle_snap_anglesnap_apply_delta_line_40_99081e10_descriptor_json();
const char* src_measurement_dimension_calculator_dimensioncalculator_calculate_line_46_6073e550_descriptor_json();
const char* src_measurement_dimension_calculator_dimensioncalculator_bounds_line_73_60c5fb14_descriptor_json();
const char* src_measurement_dimension_calculator_dimensioncalculator_position_line_102_0da1b6a7_descriptor_json();
const char* src_measurement_grid_measurement_gridmeasurement_init_line_12_1d7adb30_descriptor_json();
const char* src_measurement_grid_measurement_gridmeasurement_update_line_31_773c6a0f_descriptor_json();
const char* src_measurement_grid_measurement_gridmeasurement_format_label_line_51_e8907977_descriptor_json();
const char* src_measurement_grid_measurement_gridmeasurement_label_stride_line_54_db2cc245_descriptor_json();
const char* src_measurement_grid_measurement_gridmeasurement_extent_for_bounds_line_62_dc2527b2_descriptor_json();
const char* src_measurement_measurement_controller_measurementcontroller_init_line_15_498716e6_descriptor_json();
const char* src_measurement_measurement_controller_measurementcontroller_configure_line_23_9d657060_descriptor_json();
const char* src_measurement_measurement_controller_measurementcontroller_begin_measurement_line_27_ba0d6b4b_descriptor_json();
const char* src_measurement_measurement_controller_measurementcontroller_update_preview_line_33_59cc5677_descriptor_json();
const char* src_measurement_measurement_controller_measurementcontroller_finish_measurement_line_37_5984a976_descriptor_json();
const char* src_measurement_measurement_controller_measurementcontroller_clear_measurement_line_45_eb4cdc6d_descriptor_json();
const char* src_measurement_measurement_controller_measurementcontroller_get_delta_line_51_5accbef6_descriptor_json();
const char* src_measurement_measurement_controller_measurementcontroller_get_distance_line_57_bb0a03cc_descriptor_json();
const char* src_measurement_measurement_controller_measurementcontroller_formatted_distance_line_63_bc986bcc_descriptor_json();
const char* src_measurement_measurement_controller_measurementcontroller_draw_overlay_line_69_3849db42_descriptor_json();
const char* src_measurement_measurement_controller_measurementcontroller_active_segment_line_91_48418274_descriptor_json();
const char* src_measurement_measurement_formatter_measurementformatter_init_line_11_d5e8c44b_descriptor_json();
const char* src_measurement_measurement_formatter_measurementformatter_distance_line_15_58e1ef9f_descriptor_json();
const char* src_measurement_measurement_formatter_measurementformatter_angle_degrees_line_18_aef0df60_descriptor_json();
const char* src_measurement_measurement_formatter_measurementformatter_scale_line_26_6218ca83_descriptor_json();
const char* src_measurement_percent_snap_percentsnap_init_line_9_85db9d3f_descriptor_json();
const char* src_measurement_percent_snap_percentsnap_set_enabled_line_14_b1733eee_descriptor_json();
const char* src_measurement_percent_snap_percentsnap_toggle_line_17_c32a5886_descriptor_json();
const char* src_measurement_percent_snap_percentsnap_set_increment_percent_line_21_f5aa9c1c_descriptor_json();
const char* src_measurement_percent_snap_percentsnap_snap_percent_line_28_223b9932_descriptor_json();
const char* src_measurement_percent_snap_percentsnap_snap_scale_factor_line_34_cdc24c95_descriptor_json();
const char* src_measurement_percent_snap_percentsnap_apply_to_scale_line_40_00f2f4d6_descriptor_json();
const char* src_measurement_unit_settings_measurementsettings_to_dict_line_56_4b4eb962_descriptor_json();
const char* src_measurement_unit_system_unitsystem_init_line_108_e33bdd36_descriptor_json();
const char* src_measurement_unit_system_unitsystem_set_system_unit_line_112_9b13b0a4_descriptor_json();
const char* src_measurement_unit_system_unitsystem_set_display_unit_line_122_0f8f235b_descriptor_json();
const char* src_measurement_unit_system_unitsystem_to_display_units_line_125_5418cfb9_descriptor_json();
const char* src_measurement_unit_system_unitsystem_to_system_units_line_128_c46e494d_descriptor_json();
const char* src_measurement_unit_system_unitsystem_convert_line_131_ce73130c_descriptor_json();
const char* src_measurement_unit_system_unitsystem_format_distance_line_137_42f4e6db_descriptor_json();
const char* src_measurement_unit_system_unitsystem_parse_distance_line_149_6cb943ce_descriptor_json();

const PythonFunctionDescriptorEntry* instancemethods_descriptors(std::size_t& count);

} // namespace ghostrigger::phase15::ghostrigger_measurement
