#pragma once

#include <cstddef>

namespace ghostrigger::phase15::ghostrigger_export {

using PythonFunctionDescriptorJson = const char* (*)();

struct PythonFunctionDescriptorEntry {
    const char* python_file;
    const char* qualname;
    const char* function_type;
    PythonFunctionDescriptorJson descriptor_json;
};

const char* src_core_export_export_job_run_export_job_line_108_e68b41e9_descriptor_json();
const char* src_core_export_export_job_preflight_export_request_line_263_01b4bba5_descriptor_json();
const char* src_core_export_export_job_validate_staged_outputs_line_319_8e66a640_descriptor_json();
const char* src_core_export_export_job_result_line_334_e9ef6bd5_descriptor_json();
const char* src_core_export_export_job_single_issue_report_line_362_5757b4ff_descriptor_json();
const char* src_core_export_export_job_issue_line_385_4db8c74f_descriptor_json();
const char* src_core_export_export_job_publish_line_401_a53a92e7_descriptor_json();
const char* src_core_export_export_job_shared_output_parent_line_413_001c658b_descriptor_json();
const char* src_core_export_export_job_rollback_promoted_outputs_line_422_6cf28be4_descriptor_json();
const char* src_core_export_export_job_final_manifest_path_line_439_188f8463_descriptor_json();
const char* src_core_export_export_job_normalized_path_key_line_446_7fbdeaec_descriptor_json();
const char* src_core_export_export_job_safe_job_id_line_450_e73ab220_descriptor_json();
const char* src_core_export_export_job_ensure_json_serializable_line_455_dc882db9_descriptor_json();
const char* src_core_export_gltf_importer_decode_accessor_line_152_6f438c5e_descriptor_json();
const char* src_core_export_gltf_importer_resolve_buffers_line_231_3b6565af_descriptor_json();
const char* src_core_export_gltf_importer_matrix_to_trs_line_265_79964a2c_descriptor_json();
const char* src_core_export_gltf_importer_node_trs_from_mapping_line_318_b07a17f5_descriptor_json();
const char* src_core_export_gltf_importer_node_scale_from_mapping_line_333_5454ffdb_descriptor_json();
const char* src_core_export_gltf_importer_node_trs_from_object_line_346_bdd95aaa_descriptor_json();
const char* src_core_export_gltf_importer_node_scale_from_object_line_361_ddbf387c_descriptor_json();
const char* src_core_export_gltf_importer_mul_scale_line_369_72dca566_descriptor_json();
const char* src_core_export_gltf_importer_apply_scale_to_pos_line_376_1219d937_descriptor_json();
const char* src_core_export_gltf_importer_compose_gltf_world_line_383_c0f9e7e1_descriptor_json();
const char* src_core_export_gltf_importer_gltf_root_indices_line_400_1b3f99ac_descriptor_json();
const char* src_core_export_gltf_importer_candidate_blender_executables_line_1082_aaa33477_descriptor_json();
const char* src_core_export_gltf_importer_blender_sort_key_line_1125_18a02b8a_descriptor_json();
const char* src_core_export_gltf_importer_convert_fbx_to_glb_with_blender_line_1136_428ff1fd_descriptor_json();
const char* src_core_export_gltf_importer_auto_import_line_1184_b404afc0_descriptor_json();
const char* src_core_export_gltf_importer_build_skin_data_line_1215_fcd8f9f0_descriptor_json();
const char* src_core_export_gltf_importer_channel_to_controller_line_1238_6e25f4a7_descriptor_json();
const char* src_core_export_gltf_importer_fill_material_pygltflib_line_1258_6367fccf_descriptor_json();
const char* src_core_export_unity_export_bridge_asset_relative_line_18_5ce50433_descriptor_json();
const char* src_core_export_unity_export_bridge_build_output_paths_line_27_18384c92_descriptor_json();
const char* src_core_export_unity_export_bridge_summarize_model_line_41_3b22d89c_descriptor_json();
const char* src_core_export_unity_export_bridge_inspect_fbx_skin_objects_line_85_bdc78f34_descriptor_json();
const char* src_core_export_unity_export_bridge_export_model_for_unity_line_159_63d8706b_descriptor_json();
const char* src_core_export_unity_import_validator_as_list_line_10_902fc7b4_descriptor_json();
const char* src_core_export_unity_import_validator_clip_name_line_20_8f3b8c4f_descriptor_json();
const char* src_core_export_unity_import_validator_renderer_type_line_28_e82cbec7_descriptor_json();
const char* src_core_export_unity_import_validator_renderer_int_line_36_b33aab39_descriptor_json();
const char* src_core_export_unity_import_validator_material_count_line_48_9d6865dc_descriptor_json();
const char* src_core_export_unity_import_validator_build_unity_import_manifest_line_61_0bc29d4a_descriptor_json();
const char* src_core_export_unity_import_validator_validate_unity_import_file_line_180_e7e3ce03_descriptor_json();

const PythonFunctionDescriptorEntry* modulefunctions_descriptors(std::size_t& count);

} // namespace ghostrigger::phase15::ghostrigger_export
