#pragma once

#include <cstddef>

namespace ghostrigger::phase15::ghostrigger_rendering {

using PythonFunctionDescriptorJson = const char* (*)();

struct PythonFunctionDescriptorEntry {
    const char* python_file;
    const char* qualname;
    const char* function_type;
    PythonFunctionDescriptorJson descriptor_json;
};

const char* src_core_rendering_frame_core_colors_paste_textured_triangle_tint_line_587_5193742e_descriptor_json();
const char* src_core_rendering_frame_core_renderer_geometry_renderergeometrymixin_lbs_vertex_bind_fallback_line_527_d2878eec_descriptor_json();
const char* src_core_rendering_frame_core_renderer_overlays_rendereroverlaymixin_draw_bones_is_bone_node_line_147_aa7a9b54_descriptor_json();
const char* src_core_rendering_frame_core_renderer_overlays_rendereroverlaymixin_draw_bones_nearest_bone_ancestor_line_172_934eb3bd_descriptor_json();
const char* src_core_rendering_frame_core_renderer_overlays_rendereroverlaymixin_draw_bones_draw_bone_segment_line_186_898ea37e_descriptor_json();
const char* src_core_rendering_frame_core_renderer_overlays_rendereroverlaymixin_draw_bones_bone_world_pos_line_220_e47613ba_descriptor_json();
const char* src_core_rendering_frame_core_renderer_overlays_rendereroverlaymixin_draw_bones_process_bone_node_line_234_6b881f0b_descriptor_json();
const char* src_core_rendering_frame_core_renderer_overlays_rendereroverlaymixin_draw_gimbal_rotated_ellipse_points_line_600_f373ac21_descriptor_json();
const char* src_core_rendering_frame_core_renderer_overlays_rendereroverlaymixin_draw_gimbal_draw_polyline_line_615_72d7a6a0_descriptor_json();
const char* src_core_rendering_frame_core_renderer_overlays_rendereroverlaymixin_draw_gimbal_draw_hatch_line_621_07987ada_descriptor_json();
const char* src_core_rendering_frame_core_renderer_overlays_rendereroverlaymixin_draw_character_fit_overlay_point_line_744_81c8a916_descriptor_json();
const char* src_core_rendering_frame_core_renderer_overlays_rendereroverlaymixin_draw_character_fit_overlay_axis_color_line_752_2684be83_descriptor_json();
const char* src_core_rendering_frame_core_renderer_overlays_rendereroverlaymixin_draw_character_fit_overlay_draw_group_line_762_2cdb9232_descriptor_json();
const char* src_core_rendering_frame_core_renderer_overlays_rendereroverlaymixin_draw_ext_skeleton_bp_line_828_91e1d42b_descriptor_json();
const char* src_core_rendering_frame_core_renderer_overlays_rendereroverlaymixin_draw_ext_skeleton_draw_ext_bone_line_832_a2494a89_descriptor_json();
const char* src_core_rendering_frame_core_renderer_overlays_rendereroverlaymixin_draw_axes_axis_end_line_988_7ac64d99_descriptor_json();
const char* src_core_rendering_frame_core_renderer_render_loop_rendererrenderloopmixin_project_clipped_line_to_camera_line_333_51e07c49_descriptor_json();
const char* src_core_rendering_frame_core_renderer_render_loop_rendererrenderloopmixin_project_clipped_line_to_screen_line_363_bc00ed77_descriptor_json();
const char* src_core_rendering_frame_core_texture_cache_texturecache_sample_bilinear_rgba_line_798_2d60ae01_descriptor_json();
const char* src_core_rendering_gpu_diagnostics_records_texture_content_stats_sample_line_180_6862de25_descriptor_json();
const char* src_core_rendering_gpu_diagnostics_records_skin_3g_candidate_records_norm_pos_line_1096_04f54701_descriptor_json();
const char* src_core_rendering_gpu_diagnostics_records_skin_3g_candidate_records_delta_to_production_line_1109_482a84f4_descriptor_json();
const char* src_core_rendering_gpu_scene_helpers_compositemodel_init_bb_line_204_ce6728e6_descriptor_json();
const char* src_core_rendering_skeleton_render_data_cached_world_position_resolver_world_transform_line_189_c0b42698_descriptor_json();
const char* src_core_rendering_skeleton_render_data_cached_world_position_resolver_world_position_line_217_44c528c3_descriptor_json();

const PythonFunctionDescriptorEntry* nestedfunctions_descriptors(std::size_t& count);

} // namespace ghostrigger::phase15::ghostrigger_rendering
