#pragma once

#include <cstddef>

namespace ghostrigger::phase15::ghostrigger_rendering {

using PythonFunctionDescriptorJson = const char* (*)();

struct PythonFunctionDescriptorEntry {
    const char* python_file;
    const char* qualname;
    const char* function_type;
    PythonFunctionDescriptorJson descriptor_json;
};

const char* src_core_rendering_frame_core_renderer_geometry_renderergeometrymixin_compute_area_weighted_normals_line_34_34b1d19f_descriptor_json();
const char* src_core_rendering_frame_core_renderer_geometry_renderergeometrymixin_bas_attachment_root_for_node_line_240_91df42e7_descriptor_json();
const char* src_core_rendering_frame_core_renderer_geometry_renderergeometrymixin_apply_vertex_transform_line_354_5892625e_descriptor_json();
const char* src_core_rendering_frame_core_renderer_overlays_rendereroverlaymixin_hud_text_width_line_1012_45510b60_descriptor_json();
const char* src_core_rendering_frame_core_renderer_setup_renderersetupmixin_blend_rgb_line_232_2fef0bfa_descriptor_json();
const char* src_core_rendering_frame_core_renderer_setup_renderersetupmixin_relative_luma_line_237_44f84aac_descriptor_json();
const char* src_core_rendering_frame_core_renderer_setup_renderersetupmixin_compute_skin_proxy_ids_line_433_5a02960f_descriptor_json();
const char* src_core_rendering_frame_core_texture_cache_texturecache_copy_texture_attrs_line_459_0700afca_descriptor_json();
const char* src_core_rendering_frame_core_texture_cache_texturecache_apply_kotor_alpha_line_469_b587da27_descriptor_json();
const char* src_core_rendering_renderer_settings_renderersettings_apply_defaults_line_152_cad434f7_descriptor_json();

const PythonFunctionDescriptorEntry* staticmethods_descriptors(std::size_t& count);

} // namespace ghostrigger::phase15::ghostrigger_rendering
