"""Core model data structures and geometry utilities."""

from .component_editing import (
    ComponentEditAudit,
    ComponentEditResult,
    ComponentBounds,
    ComponentMesh,
    ComponentTransformControl,
    audit_component_edit_result,
    bridge_edges,
    cleanup_degenerate_faces,
    cleanup_face_normals,
    component_bounds,
    component_mesh,
    component_universal_transform_control,
    extrude_face,
    fill_face,
    flatten_vertices,
    mirror_vertices,
    split_face_with_edge,
    snap_vertex_to_vertex,
    snap_vertices_to_vertex,
    snap_vertices_to_grid,
    transform_snap_vertices_to_level,
    triangulate_faces,
    weld_vertices,
)

__all__ = [
    "ComponentEditAudit",
    "ComponentEditResult",
    "ComponentBounds",
    "ComponentMesh",
    "ComponentTransformControl",
    "audit_component_edit_result",
    "bridge_edges",
    "cleanup_degenerate_faces",
    "cleanup_face_normals",
    "component_bounds",
    "component_mesh",
    "component_universal_transform_control",
    "extrude_face",
    "fill_face",
    "flatten_vertices",
    "mirror_vertices",
    "split_face_with_edge",
    "snap_vertex_to_vertex",
    "snap_vertices_to_vertex",
    "snap_vertices_to_grid",
    "transform_snap_vertices_to_level",
    "triangulate_faces",
    "weld_vertices",
]
