#pragma once

#include <cstddef>

namespace ghostrigger::phase15::ghostrigger_adapters_qtviewport {

using PythonFunctionDescriptorJson = const char* (*)();

struct PythonFunctionDescriptorEntry {
    const char* python_file;
    const char* qualname;
    const char* function_type;
    PythonFunctionDescriptorJson descriptor_json;
};

const char* src_adapters_qt_viewport_camera_gizmo_renderer_cameragizmorenderer_init_line_11_a6578952_descriptor_json();
const char* src_adapters_qt_viewport_camera_gizmo_renderer_cameragizmorenderer_set_theme_colors_line_36_55ae0baf_descriptor_json();
const char* src_adapters_qt_viewport_camera_gizmo_renderer_cameragizmorenderer_reset_theme_colors_line_51_de2741c1_descriptor_json();
const char* src_adapters_qt_viewport_camera_gizmo_renderer_cameragizmorenderer_set_native_palette_colors_line_62_7ccd7ee0_descriptor_json();
const char* src_adapters_qt_viewport_camera_gizmo_renderer_cameragizmorenderer_draw_line_82_e26fcd58_descriptor_json();
const char* src_adapters_qt_viewport_camera_gizmo_renderer_cameragizmorenderer_draw_camera_line_90_75e34c3c_descriptor_json();
const char* src_adapters_qt_viewport_camera_gizmo_renderer_cameragizmorenderer_draw_target_line_108_7d4550f0_descriptor_json();
const char* src_adapters_qt_viewport_camera_gizmo_renderer_cameragizmorenderer_draw_frustum_line_122_346970ea_descriptor_json();
const char* src_adapters_qt_viewport_camera_gizmo_renderer_cameragizmorenderer_camera_position_line_155_d3d21be1_descriptor_json();
const char* src_adapters_qt_viewport_camera_gizmo_renderer_cameragizmorenderer_camera_rotation_line_165_9cd361be_descriptor_json();
const char* src_adapters_qt_viewport_camera_overlays_cameraoverlays_draw_line_7_0710b789_descriptor_json();
const char* src_adapters_qt_viewport_camera_overlays_cameraoverlays_active_frame_rect_line_16_6a2efa6c_descriptor_json();
const char* src_adapters_qt_viewport_camera_overlays_cameraoverlays_draw_letterbox_line_32_f67fab12_descriptor_json();
const char* src_adapters_qt_viewport_camera_overlays_cameraoverlays_draw_safe_frame_line_52_ca817b68_descriptor_json();
const char* src_adapters_qt_viewport_camera_overlays_cameraoverlays_draw_guides_line_62_4fe6b929_descriptor_json();
const char* src_adapters_qt_viewport_lighting_viewport_controller_lightingviewportcontroller_init_line_10_008aef57_descriptor_json();
const char* src_adapters_qt_viewport_lighting_viewport_controller_lightingviewportcontroller_apply_to_renderer_line_17_99889bc9_descriptor_json();
const char* src_adapters_qt_viewport_still_frame_renderer_framerenderer_init_line_14_4f72f7ff_descriptor_json();
const char* src_adapters_qt_viewport_still_frame_renderer_framerenderer_render_current_frame_line_20_b27a926e_descriptor_json();
const char* src_adapters_qt_viewport_still_frame_renderer_framerenderer_render_to_file_line_68_94da0a3b_descriptor_json();
const char* src_adapters_qt_viewport_still_frame_renderer_framerenderer_resolution_line_91_313ea057_descriptor_json();
const char* src_adapters_qt_viewport_still_frame_renderer_framerenderer_snapshot_helpers_line_100_1f072412_descriptor_json();
const char* src_adapters_qt_viewport_still_frame_renderer_framerenderer_set_helpers_line_116_c7b75807_descriptor_json();
const char* src_adapters_qt_viewport_still_frame_renderer_framerenderer_restore_helpers_line_128_618b0eac_descriptor_json();

const PythonFunctionDescriptorEntry* instancemethods_descriptors(std::size_t& count);

} // namespace ghostrigger::phase15::ghostrigger_adapters_qtviewport
